### DISCUSSION TITLE
type: area just showing line

### DISCUSSION THREAD

**Discussion by ehendrix23** [RomRider/apexcharts-card#116] [Q&A] [answered]
First off, this component is exactly what I was looking for! Thank you.

Now based on examples shown this should work, but for some reason I am unable to find the issue in my configuration. I'm trying to display 2 series as an area but they keep on showing as line instead. 
Per my understanding, I need to set chart_type to ```line``` and then type for the series to ```area``` by putting in each series or in ```all_series_config```. 
Here is what I have, I also tried just having it within each entity under ```series``` but that did not change the result.

```
  - type: 'custom:apexcharts-card'
    graph_span: 24h
    span:
      start: hour
      offset: '-19h'
    chart_type: line
    all_series_config:
      unit: GB
      type: area
      group_by:
        func: max
        duration: 1h
    apex_config:
      yaxis:
        show: true
        showAlways: true
        labels:
          show: true
          align: center
      chart:
        height: 400px
      tooltip:
        x:
          format: 'MM/dd/yyyy hh:mm TT'
    series:
      - entity: sensor.asuswrt_upload_hourly
        name: Upload
      - entity: sensor.asuswrt_download_hourly
        name: Download
```

What am I missing? :-)
