### DISCUSSION TITLE
Minimum and Maximum on Y-Axis

### DISCUSSION THREAD

**Discussion by Stefan-OJ** [RomRider/apexcharts-card#151] [Q&A]
Is there a way to set a fixed minimum and maximum on the Y-Axis? Use Case: Plotting phone battery percentage on chart.

**Comment by RomRider** [comment]
Yes, using `apex_config` and using parameters from apexcharts.js [documentation](https://apexcharts.com/docs/options/#):
```
apex_config:
  yaxis:
    min: 0
    max: 100
```
