### DISCUSSION TITLE
How to combine area gradient with solid line

### DISCUSSION THREAD

**Discussion by ArdJonker** [RomRider/apexcharts-card#256] [Q&A]
I'd like to combine a area gradient fill with a solid line:
![ChartNeed](https://user-images.githubusercontent.com/6270792/145577502-641b8f26-4ead-4e37-a51c-164a3c0565bb.png)

But what is get is:
![ChartIs](https://user-images.githubusercontent.com/6270792/145577577-707d932d-d6dd-4581-adb9-e0343afd042e.png)

How do i make the solid line solid and not also gradient?

My code:
```yaml
type: custom:apexcharts-card
graph_span: 24h
span:
  start: hour
  offset: '-4h'
now:
  show: true
  label: Now
header:
  show: true
  title: Car State of Charge (%)
apex_config:
  fill:
     {
       type: "gradient",
       gradient:
         {
           shadeIntensity: 1,
           inverseColors: false,
           opacityFrom: 0.45,
           opacityTo: 0.05,
           stops: [20, 100, 100, 100],
         },
     }
  legend:
    show: false
  chart:
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: true
        pan: true
        reset: true
series:
  - entity: input_number.car_state_of_charge
    color: '#009be5'
    stroke_width: 2
    type: line
    extend_to_end: false
    yaxis_id: SoC
  - entity: input_text.soc_prognose
    type: line
    color: '#fea602'
    stroke_width: 2
    extend_to_end: false
    yaxis_id: SoC
    data_generator: |
      return entity.attributes.records.map((record, index) => {
        return [new Date(record.time).getTime(), record.soc];
      });
  - entity: input_text.apex_prices
    color: '#ccc'
    extend_to_end: false
    stroke_width: 1
    curve: stepline
    yaxis_id: EPEXprice
    data_generator: |
      return entity.attributes.records.map((record, index) => {
        return [new Date(record.time).getTime(), record.price];
      });
    type: line
yaxis:
  - id: SoC
    min: 0
    max: 100
    decimals: 0
    apex_config:
      tickAmount: 5
  - id: EPEXprice
    decimals: 0
    opposite: true
    min: '|-2|'
    max: '|+2|'
```
