### DISCUSSION TITLE
1 year history graph grouped by month

### DISCUSSION THREAD

**Discussion by miguelfreitaspt** [RomRider/apexcharts-card#272] [Q&A]
Hello.

I wanted to create a consumption graph that had the monthly consumptions, i.e. grouped by month, over a year.
Is this possible? Thanks.

**Comment by altserg** [comment]
Try my config sample. I do not like the X axis formatting (prefer that all 12 months are listed there), but I do not know how to do that.

type: custom:apexcharts-card
locale: en
hours_12: false
apex_config:
  tooltip:
    x:
      format: MMM yyyy
header:
  show: true
  title: Yearly Water Consumption
  show_states: true
  colorize_states: true
graph_span: 1year
span:
  start: year
series:
  - entity: sensor.montly_water_consumption
    type: column
    color: cyan
    show:
      in_header: false
    statistics:
      type: state
      period: month
      align: start
  - entity: sensor.yearly_water_consumption
    type: column
    show:
      in_chart: false

![image](https://user-images.githubusercontent.com/79573763/168144457-820ed6bb-7bab-4d5d-a3c0-767a08eeb710.png)

**Comment by pLeXwithFleX** [comment]
Hey guys,

im trying the same with a custom state measurement entity wthich count our laundry. My problem is when I set "type to state" under the statistics series no value is available and wont show. If I remove this setting, it shows me correctly the last value of the month, but not the current value during the month:

![image](https://user-images.githubusercontent.com/34384097/218306842-613e019d-aa8d-4e78-9e95-1757bce7fb13.png)

here is my code:

```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 300px
experimental:
  color_threshold: true
graph_span: 1year
locale: de
span:
  start: year
show:
  last_updated: false
header:
  show: true
  show_states: true
  colorize_states: true
  title: Statistik
  floating: false
now:
  show: true
  label: heute
  color: red
yaxis:
  - min: 0
    max: ~15
    decimals: 0
    apex_config:
      tickAmount: 5
series:
  - entity: sensor.custom_wasche_counter
    show:
      header_color_threshold: true
      extremas: true
    type: column
    name: Wäsche
    statistics:
      period: month
      align: start
      type: state
  - entity: sensor.custom_trockner_counter
    show:
      header_color_threshold: true
      extremas: true
    type: column
    name: Trockner
    statistics:
      period: month
      align: start
      type: state
```

The entity looks good to me:

![image](https://user-images.githubusercontent.com/34384097/218306907-78f0f7c2-baca-4443-a7b3-7af5aa4e4422.png)

I want to display the sum of the previous months and also the current value of the current month until the end.
Can anyone assist?

thx alot

Alex
