### DISCUSSION TITLE
How do make a good Wind Diagram - e.g. how to replace the y-tick labels :)

### DISCUSSION THREAD

**Discussion by upwindanderl** [RomRider/apexcharts-card#295] [Q&A]
_first of all! WOW how cool is this apexcharts-card
i started with mini-graph cards months before and i was only searching for some grid and now there is this super-powerful master graph tool -> so good! Thanks a lot @RomRider_   
--

The first thing i tried with this apexcharts card is some sort of windy diagram using my rooftop sensors
10mins later i got this beatiful first draft:
![grafik](https://user-images.githubusercontent.com/51791206/154994724-86c95cce-c394-48bf-8543-3690a6d33bb7.png)

Atm i got stock how to replace the y-ticks of the 2nd axis, maybe i'm to stupid to read the https://apexcharts.com/docs/options/yaxis/ 
Any idea how to replace
0 -> Nord
180 -> South
270 -> West
90 -> East
?
My wooden workaround would be a new sensor in the home assistant, mapping this ticks but maybe there is some better idea?!

2nd question
is there any chance to replace the red direction line with points instead of a line? I'm also to stupid to find this option, the only things i got is type: columns and lines

Here is my code:
`
```
type: custom:apexcharts-card
graph_span: 24h
header:
  show: true
  title: Wind
  standard_format: true
yaxis:
  - id: first
    decimals: 0
    apex_config:
      tickAmount: 10
      title:
        text: Speed
        style:
          fontSize: 10
  - id: second
    decimals: 0
    apex_config:
      tickAmount: 4
      title:
        text: Dir.
        rotate: 90
        style:
          fontSize: 10
    opposite: true
    min: 0
    max: 360
series:
  - entity: sensor.wind_speed
    yaxis_id: first
    type: area
    stroke_width: 1
    group_by:
      func: max
      fill: last
  - entity: sensor.wind_gust
    yaxis_id: first
    stroke_width: 3
    opacity: 0.5
    type: line
    show:
      extremas: true
  - entity: sensor.wind_direction
    type: line
    yaxis_id: second
    stroke_width: 4
    opacity: 1
    curve: stepline
    group_by:
      func: avg
```
`
