### DISCUSSION TITLE
Sum in show_states

### DISCUSSION THREAD

**Discussion by mdzmdz** [RomRider/apexcharts-card#297] [Q&A]
I have a chart like this.

<img width="344" alt="chart" src="https://user-images.githubusercontent.com/94713948/155110013-8536bd95-b178-4a66-9035-5f2acf05cfa3.png">

The show-states field contains the last value of the entity. Is there a way to show sum of the values in the chart instead?

**Comment by slyoldfox** [comment]
I was looking to ask the same thing, but for the average.

```
type: custom:apexcharts-card
graph_span: 24h
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.shellyplus1pm_083af201d164_switch_0_power
    group_by:
      duration: 5m
      func: avg
```

I was expecting the header to be showing the `average` value for the `graph_span` period but that seems not to be the case.

It is even debatable if this example is correct:
https://github.com/RomRider/apexcharts-card#aggregating-data

For me personally all aggregated values should show the aggregated values for the graph_span period, instead of the last value from that sensor.

@RomRider what do you think, do we need to create an issue for this or is this possible in some way I don't see. (I did read all options 3 times now)
