### DISCUSSION TITLE
Remove horizontal guidelines

### DISCUSSION THREAD

**Discussion by stobra** [RomRider/apexcharts-card#372] [Q&A]
Hello,

Is anyone able to provide an examples of how to remove horizontal guidelines? I'm unable to figure it out.

**Comment by EvisHome** [comment]
Hey, you can do this by using apex_config

```
type: custom:apexcharts-card
apex_config:
  grid:
    show: false
```

**Reply by EvisHome** [reply]
you can also change the color and opacity, to make it less visible.

```
type: custom:apexcharts-card
apex_config:
  grid:
    show: true
    borderColor: rgba(255,255,255,0.2)
```
