### DISCUSSION TITLE
Showing tomorrow's extremas for Nordpool

### DISCUSSION THREAD

**Discussion by tfriberg** [RomRider/apexcharts-card#385] [Q&A]
Is there a way I can show tomorrow's extremas in the header?
I've only been able to show today's values in the header for the tomorrow's chart.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/867763/185792245-f723f26d-0fb4-44c9-abaa-d2fa815085f3.png">

The chart can render tomorrow's values as bars, and even show the extremas as bar values (min/max)
<img width="497" alt="image" src="https://user-images.githubusercontent.com/867763/185792284-7f5a303b-d2c5-46cb-ad8e-e58a70045b29.png">

How do I go about showing these values in the header from tomorrow's values?

```
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
  offset: +1d
apex_config:
  legend:
    showForSingleSeries: false
  plotOptions:
    bar:
      borderRadius: 2
  yaxis:
    decimalsInFloat: 2
    tickAmount: 10
    forceNiceScale: true
all_series_config:
  show:
    offset_in_name: false
header:
  title: NordPool SE3 - Tomorrow
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.nordpool_se3
    type: column
    color: orange
    float_precision: 2
    stroke_width: 2
    name: Tomorrow
    show:
      in_header: false
      legend_value: false
      extremas: true
    data_generator: |
      return entity.attributes.raw_tomorrow.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];
      });
    extend_to: end
  - entity: sensor.nordpool_se3
    offset: '-24h'
    attribute: average
    type: column
    color: '#cccccc'
    float_precision: 2
    stroke_width: 2
    name: Average tomorrow
    group_by:
      duration: 1d
    show:
      in_header: true
      in_chart: false
      legend_value: true
    extend_to: end
  - entity: sensor.nordpool_se3
    offset: '-24h'
    attribute: max
    type: column
    color: '#B63330'
    float_precision: 2
    stroke_width: 2
    name: Max tomorrow
    group_by:
      duration: 1d
    show:
      in_header: true
      in_chart: false
      legend_value: true
    extend_to: end
  - entity: sensor.nordpool_se3
    attribute: min
    offset: '-24h'
    type: column
    color: '#489989'
    float_precision: 2
    stroke_width: 2
    name: Min tomorrow
    group_by:
      duration: '-1d'
    show:
      in_header: true
      in_chart: false
      legend_value: true
    extend_to: end
```
```
Raw data:
Current price
0.4
Average
0.5
Off peak 1
0.43
Off peak 2
0.29
Peak
0.64
Min
0.08
Max
1
Unit
kWh
Currency
SEK
Country
Sweden
Region
SE3
Low price
true
Tomorrow valid
true
Today
0.93, 0.49, 0.41, 0.4, 0.35, 0.32, 0.08, 0.46, 0.99, 1, 0.92, 0.95, 0.65, 0.41, 0.38, 0.4, 0.43, 0.33, 0.56, 0.42, 0.29, 0.65, 0.13, 0.09
Tomorrow
0.06, 0.04, 0.03, 0.03, 0.04, 0.65, 4.57, 5.39, 7.2, 7.42, 7.58, 7.37, 6.45, 5.86, 5.86, 7.06, 7.42, 7.53, 8.32, 7.53, 7.42, 5.86, 5.32, 3.73
Raw today
- start: '2022-08-21T00:00:00+02:00'
end: '2022-08-21T01:00:00+02:00'
value: 0.93
- start: '2022-08-21T01:00:00+02:00'
end: '2022-08-21T02:00:00+02:00'
value: 0.49
- start: '2022-08-21T02:00:00+02:00'
end: '2022-08-21T03:00:00+02:00'
value: 0.41
- start: '2022-08-21T03:00:00+02:00'
end: '2022-08-21T04:00:00+02:00'
value: 0.4
- start: '2022-08-21T04:00:00+02:00'
end: '2022-08-21T05:00:00+02:00'
value: 0.35
- start: '2022-08-21T05:00:00+02:00'
end: '2022-08-21T06:00:00+02:00'
value: 0.32
- start: '2022-08-21T06:00:00+02:00'
end: '2022-08-21T07:00:00+02:00'
value: 0.08
- start: '2022-08-21T07:00:00+02:00'
end: '2022-08-21T08:00:00+02:00'
value: 0.46
- start: '2022-08-21T08:00:00+02:00'
end: '2022-08-21T09:00:00+02:00'
value: 0.99
- start: '2022-08-21T09:00:00+02:00'
end: '2022-08-21T10:00:00+02:00'
value: 1
- start: '2022-08-21T10:00:00+02:00'
end: '2022-08-21T11:00:00+02:00'
value: 0.92
- start: '2022-08-21T11:00:00+02:00'
end: '2022-08-21T12:00:00+02:00'
value: 0.95
- start: '2022-08-21T12:00:00+02:00'
end: '2022-08-21T13:00:00+02:00'
value: 0.65
- start: '2022-08-21T13:00:00+02:00'
end: '2022-08-21T14:00:00+02:00'
value: 0.41
- start: '2022-08-21T14:00:00+02:00'
end: '2022-08-21T15:00:00+02:00'
value: 0.38
- start: '2022-08-21T15:00:00+02:00'
end: '2022-08-21T16:00:00+02:00'
value: 0.4
- start: '2022-08-21T16:00:00+02:00'
end: '2022-08-21T17:00:00+02:00'
value: 0.43
- start: '2022-08-21T17:00:00+02:00'
end: '2022-08-21T18:00:00+02:00'
value: 0.33
- start: '2022-08-21T18:00:00+02:00'
end: '2022-08-21T19:00:00+02:00'
value: 0.56
- start: '2022-08-21T19:00:00+02:00'
end: '2022-08-21T20:00:00+02:00'
value: 0.42
- start: '2022-08-21T20:00:00+02:00'
end: '2022-08-21T21:00:00+02:00'
value: 0.29
- start: '2022-08-21T21:00:00+02:00'
end: '2022-08-21T22:00:00+02:00'
value: 0.65
- start: '2022-08-21T22:00:00+02:00'
end: '2022-08-21T23:00:00+02:00'
value: 0.13
- start: '2022-08-21T23:00:00+02:00'
end: '2022-08-22T00:00:00+02:00'
value: 0.09
Raw tomorrow
- start: '2022-08-22T00:00:00+02:00'
end: '2022-08-22T01:00:00+02:00'
value: 0.06
- start: '2022-08-22T01:00:00+02:00'
end: '2022-08-22T02:00:00+02:00'
value: 0.04
- start: '2022-08-22T02:00:00+02:00'
end: '2022-08-22T03:00:00+02:00'
value: 0.03
- start: '2022-08-22T03:00:00+02:00'
end: '2022-08-22T04:00:00+02:00'
value: 0.03
- start: '2022-08-22T04:00:00+02:00'
end: '2022-08-22T05:00:00+02:00'
value: 0.04
- start: '2022-08-22T05:00:00+02:00'
end: '2022-08-22T06:00:00+02:00'
value: 0.65
- start: '2022-08-22T06:00:00+02:00'
end: '2022-08-22T07:00:00+02:00'
value: 4.57
- start: '2022-08-22T07:00:00+02:00'
end: '2022-08-22T08:00:00+02:00'
value: 5.39
- start: '2022-08-22T08:00:00+02:00'
end: '2022-08-22T09:00:00+02:00'
value: 7.2
- start: '2022-08-22T09:00:00+02:00'
end: '2022-08-22T10:00:00+02:00'
value: 7.42
- start: '2022-08-22T10:00:00+02:00'
end: '2022-08-22T11:00:00+02:00'
value: 7.58
- start: '2022-08-22T11:00:00+02:00'
end: '2022-08-22T12:00:00+02:00'
value: 7.37
- start: '2022-08-22T12:00:00+02:00'
end: '2022-08-22T13:00:00+02:00'
value: 6.45
- start: '2022-08-22T13:00:00+02:00'
end: '2022-08-22T14:00:00+02:00'
value: 5.86
- start: '2022-08-22T14:00:00+02:00'
end: '2022-08-22T15:00:00+02:00'
value: 5.86
- start: '2022-08-22T15:00:00+02:00'
end: '2022-08-22T16:00:00+02:00'
value: 7.06
- start: '2022-08-22T16:00:00+02:00'
end: '2022-08-22T17:00:00+02:00'
value: 7.42
- start: '2022-08-22T17:00:00+02:00'
end: '2022-08-22T18:00:00+02:00'
value: 7.53
- start: '2022-08-22T18:00:00+02:00'
end: '2022-08-22T19:00:00+02:00'
value: 8.32
- start: '2022-08-22T19:00:00+02:00'
end: '2022-08-22T20:00:00+02:00'
value: 7.53
- start: '2022-08-22T20:00:00+02:00'
end: '2022-08-22T21:00:00+02:00'
value: 7.42
- start: '2022-08-22T21:00:00+02:00'
end: '2022-08-22T22:00:00+02:00'
value: 5.86
- start: '2022-08-22T22:00:00+02:00'
end: '2022-08-22T23:00:00+02:00'
value: 5.32
- start: '2022-08-22T23:00:00+02:00'
end: '2022-08-23T00:00:00+02:00'
value: 3.73
```
