### DISCUSSION TITLE
How to hide the legend

### DISCUSSION THREAD

**Discussion by PuckeyP** [RomRider/apexcharts-card#388] [General]
Hi All,
I managed to find the "hide legend **values**" in the documentation, but is it also possible to hide the total legend?
PPee

**Comment by EvisHome** [comment]
Hi, use apex_config

```YAML
type: custom:apexcharts-card
apex_config:
  legend:
    show: false
```
