### DISCUSSION TITLE
Graphing binary sensor

### DISCUSSION THREAD

**Discussion by rossens** [RomRider/apexcharts-card#395] [Q&A]
Hi, I'm using `transform: 'return x === ''ON'' ? 5 : 0;'` to graph value of a binary_sensor - to show when air-conditioner power was on/off, along side the room temp.
I was hoping to see a square-ish graph showing when on/off. But instead the graph looks like a saw-tooth.
I guess the problem is HA reduces the number of data points to only the transitions.
Is there anything I can do on my side to get a more "square" looking graph?

![image](https://user-images.githubusercontent.com/112799663/190011551-763c435f-75a5-4451-b3c4-8fdd7ece9e01.png)

**Comment by tarmor1** [comment]
Hi!
What I have for the similar thing is _stepline_:
```
  - entity: sensor.valve_operation
    name: DWH heating
    type: line
    curve: stepline
    color: blue
    stroke_width: 2
    opacity: 0.8
    transform: 'return x === ''ON'' ? 2 : 0;'
    show:
      in_header: false
      legend_value: false
```
