### DISCUSSION TITLE
color by positive/negative value historically

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [RomRider/apexcharts-card#416] [Q&A]
before turning this into an idea... if love to ask the community for help

I have 3 grid phases, and want to plot them, positive being purple, negative being green. never mind the choice, its a native color setting from Homewizard.

Ive been studying the docs for 2 days now, and can not find a setting to do so. Also tried the color_thresholds, but that seems not what I am after, as it 
- needs arbitrary high thresholds in the first place, because we never know what the max is in usage
- seems to color along the current state, and not the historic state

I posted something in the [community thread](https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1811?u=mariusthvdb) so if you could, please have a look:

this is what I have now, and forced not to look like this, by splitting up the phases in positive and negative values, so I could set the color on them:

<img width="517" alt="Schermafbeelding 2022-10-12 om 15 15 41" src="https://user-images.githubusercontent.com/33354141/195352732-a9f591c1-1884-4848-9504-fb8db090a120.png">

```
  - type: custom:apexcharts-card
    graph_span: 6h
#     span:
#       start: day
#       offset: -1d
    all_series_config:
      type: area
      stroke_width: 1
      opacity: 0.5
    header:
      title: 'Apex: Energy gebruik per Fase'
      show: true

    entities:
      - entity: sensor.l1_power_import
        name: L1
        color: purple
      - entity: sensor.l2_power_import
        name: L2
        color: purple
      - entity: sensor.l3_power_import
        name: L3
        color: purple
      - entity: sensor.l1_power_export
        name: -L1
        color: green
      - entity: sensor.l2_power_export
        name: -L2
        color: green
      - entity: sensor.l3_power_export
        name: -L3
        color: green
```
