### DISCUSSION TITLE
Mouseover data

### DISCUSSION THREAD

**Discussion by direx1** [RomRider/apexcharts-card#420] [Q&A]
How do I disable the data popup boxes that appear on mouse over of my data? There are two generated, one on the y axis and one on the plotted data. Thanks and sorry if I missed this in the documentation.

**Comment by KDYR** [comment]
Struggling with the boxes as well - in practice not helpful as I cannot see the point for which the values in the boxes apply and when shown it is difficult to select another data point. 
Anyway; found a way to switch them off. They are so-called tooltips and starting a chart with this apex_config will turn them off:
```
type: custom:apexcharts-card
apex_config:
  tooltip:
    enabled: false
experime ...
```
Next step is to find a way to tailor them instead.

**Comment by KDYR** [comment]
After a bit more studying, I arrived at this solution, which works for me (for now, at least):
```
apex_config:
  tooltip:
    enabled: true
    x:
      show: false
    fixed: 
      enabled: true
      position: topRight
```
