### DISCUSSION TITLE
Is it possible to have an action when tapped on element of pie chart?

### DISCUSSION THREAD

**Discussion by wigster** [RomRider/apexcharts-card#443] [Q&A]
HI,

I have some pie/donut charts. I would like to be able to drill down in the data if I ever chose to tap on a particular element of the chart. For example:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/10956987/205078006-e3c25fc7-0f11-435b-aeb7-bfe69b7afd2f.png">
in this chart I would like to be able to tap the Cooking segment and open up a subview with another apex donut chart. I've tried assigning a heade_action to the Cooking series, but this doesn't seem to do anything in this setup:
 ```yaml
type: custom:apexcharts-card
chart_type: donut
update_interval: 1min
series:
  - entity: sensor.cooking_all_energy_daily
    name: Cooking
    header_actions:
      tap_action:
        action: navigate
        navigation_path: /lovelace/cooking-energy-today
  - entity: sensor.cleaning_all_energy_daily
    name: Cleaning
  - entity: sensor.all_light_energy_daily
    name: Lights
  - entity: sensor.climate_all_energy_daily
    name: Climate
  - entity: sensor.media_players_all_energy_daily
    name: Media
  - entity: sensor.it_network_all_energy_daily
    name: IT
  - entity: sensor.electricity_uncategorised_energy_daily
    name: Unk.
header:
  show: true
  show_states: false
  colorize_states: true
  title: Energy Consumption Today
```

Is something like that possible?
