### DISCUSSION TITLE
Custom Legend Not Being Displayed

### DISCUSSION THREAD

**Discussion by jesawyers** [RomRider/apexcharts-card#456] [Q&A]
Trying to configure a custom legend for the apexcharts-card.

I have tried the following in the card configuration editor.  

When I try...

customLegendItems: {"Living Room", "Bedroom"}

I get...

```
  legend:
    show: true
    customLegendItems:
       Living Room: null
       Bedroom: null
    offsetY: 8

```

When I try...

customLegendItems: ["Living Room", "Bedroom"]

I get...

```
  legend:
    show: true
    customLegendItems:
       - Living Room
       - Bedroom
    offsetY: 8

```

Neither one works.  Any ideas???
