### DISCUSSION TITLE
Dynamic HA entities values passes to apex_config key/value pairs

### DISCUSSION THREAD

**Discussion by deepcoder** [RomRider/apexcharts-card#46] [Ideas]
If you are looking for things that might be useful if given some type of dynamic content from HA passed to ApexCharts:

Be able to a minimum send ‘first’ and ‘last’ values of series to dataPointIndex. More would be to be able to send a ‘every(x) list of values’ to it as well.

```
      markers:
        size: 5
        colors: '#0000ff'
        discrete: [{
          seriesIndex: 0,
          dataPointIndex: 3,
          fillColor: '#e3e3e3',
          strokeColor: '#ff0000',
          size: 25
```
entity value to both ‘min’ and ‘max’. Ideally a jinja function that would for example return a number for the min and/or max value based on an entity like ‘month of year’ then do a modulus division division on that number and multiply it by a value to get a different y max and y min depending on what quarter of the year it is. Again, letting ApexCharts choose the min and max by itself does not yield a useful visualization. Fixing the upper and lower bound ‘manually’ but different depending on a factor the author sets, allows proper visualization of slope of lines/data. Important for users to understand trends. Thx!

```
      yaxis:
        - seriesName: Backyard Govee Temp
          title:
            text: 'Temperature °F'
          show: true
          showAlways: true
          showForNullSeries: true
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 30
          max: 100

```
