### DISCUSSION TITLE
use of 'now'  with 'extend_to_end: false'

### DISCUSSION THREAD

**Discussion by deepcoder** [RomRider/apexcharts-card#50] [Show and tell]
'now' is also pretty handy for graphs that use the 'extend_to_end: false' option

```
  cards:
  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.backyard_atc_mi_temperature
      type: line
      extend_to_end: false
    - entity: sensor.backyard_atc_mi_temperature
      offset: -1d
      type: line
    - entity: sensor.backyard_atc_mi_temperature
      offset: -2d
      type: line
    update_interval: 60s
    now:
      show: true
      label: 'now🌡🎉'
    graph_span: 1d
    span:
      start: day
```
<img width="952" alt="apex-now" src="https://user-images.githubusercontent.com/1409547/106826688-44023b80-663c-11eb-9259-1425f78cde79.png">
