### DISCUSSION TITLE
Possibility to exempt one entity from "stacked" option

### DISCUSSION THREAD

**Discussion by SilverFolfy** [RomRider/apexcharts-card#519] [Q&A] [answered]
Hi all,

I have set up some power consumption sensor on some devices and one overall power consumption sensor on my smart meter.
So far I was able to create a stacked chart which adds up all of the single device meters, and that works great.

Now I want to add in the consumption sensor from my smart meter, which already shows the combined power consumption of the whole house. The difference between the highest point on the "stacked" devices and the overall consumption should then be the consumption for which I have not added a device power meter yet.
However the option "stacked: true" is defined for the whole chart, so the overall consumption sensor will be stacked on top, which I don't want.

This is what I have so far showing only 3 of my single devices:
```
type: custom:apexcharts-card
stacked: true
graph_span: 8h
apex_config:
  chart:
    height: 1200px
header:
  show: false
series:
  - entity: sensor.shellyplug_01_power
    name: Infrared Heater WS
    curve: smooth
    type: area
    group_by:
      duration: 1min
      func: avg
  - entity: sensor.shellyplug_02_power
    name: Freezer & Fridge
    curve: smooth
    type: area
    group_by:
      duration: 1min
      func: avg
  - entity: sensor.shellyplug_03_pc_power
    name: PC
    curve: smooth
    type: area
    group_by:
      duration: 1min
      func: avg
```

Now I am unsure if it's supported to add another entity that is not stacked like the rest, but a "standalone" y-axis line on the same chart.
I thought about subtracting all the devices which I already have in the chart from the overall consumption sensor and then stack that on top, but I am not sure how to go on about that.

Any ideas greatly appreciated!

**Comment by SilverFolfy** [comment, marked as answer]
Forgot to check in again, I have solved this to a satisfactory degree.
I have created a template entity which calculates the remaining unmeasured power, which is then just stacked on the top of the chart like all other values.

The following is the final chart:
```
type: custom:apexcharts-card
graph_span: 30m
stacked: true
all_series_config:
  curve: smooth
  type: area
  group_by:
    duration: 1min
    fill: 'null'
    func: avg
apex_config:
  chart:
    height: 1200px
header:
  show: true
series:
  - entity: sensor.shellyplug_01_power
    name: Heater
  - entity: sensor.shellyplug_02_power
    name: Freezer & Fridge
  - entity: sensor.shellyplug_03_power
    name: PC-Room Fridge
  - entity: sensor.shellyplug_04_power
    name: PC1
  - entity: sensor.shellyplug_05_power
    name: PC2
  - entity: sensor.shellyplug_06_power
    name: Server
  - entity: sensor.remaining_unmeasured_power
    name: Remaining Unmeasured Power Consumption
```

And this is the template which is placed in the HA configuration.yaml
The "sensor.ha_glow_power_consumption" is the total power consumption as measured on the main power meter.
```
template:
  - sensor:
      - name: "Remaining unmeasured power"
        unique_id: remaining_unmeasured_power
        unit_of_measurement: "W"
        state: >
          {% set total = states('sensor.ha_glow_power_consumption') | float %}
          {% set shelly01 = states('sensor.shellyplug_01_power') | float %}
          {% set shelly02 = states('sensor.shellyplug_02_power') | float %}
          {% set shelly03 = states('sensor.shellyplug_03_power') | float %}
          {% set shelly04 = states('sensor.shellyplug_04_power') | float %}
          {% set shelly05 = states('sensor.shellyplug_05_power') | float %}
          {% set shelly06 = states('sensor.shellyplug_06_power') | float %}
          {% set remaining_power = '%0.1f' | format(total - shelly01 - shelly02 - shelly03 - shelly04 - shelly05 - shelly06) %}
          {{ remaining_power }}
```
