### DISCUSSION TITLE
tip: make sure you DO NOT duplicate keys, doing so is a frustrating time waster...

### DISCUSSION THREAD

**Discussion by deepcoder** [RomRider/apexcharts-card#52] [Show and tell]
In the example shown below, there are two 'chart' keys under the 'apex_config' key, the second 'chart' key will override the options set in the first 'chart' key, leading to head scratching debugging:

<img width="627" alt="dups-apex" src="https://user-images.githubusercontent.com/1409547/106837523-808b6280-664f-11eb-8dd5-0f4976ec78af.png">

```
  - type: custom:apexcharts-card
    chart_type: scatter
    header:
      show: false
    series: 
    - entity: sensor.backyard_govee_temperature
    - entity: sensor.backyard_atc_mi_temperature
    update_interval: 5m
    graph_span: 1h
    cache: true
    apex_config:
      stroke:
        show: true
        width: 1
      chart:
        height: 450
        sparkline:
          enabled: false
        toolbar:
          show: true
      markers:
        size: 4
        shape: 'circle'
        strokeWidth: 1
        hover:
          size: 20
      title:
        text: 'Backyard Temperature 1h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 40
          max: 80
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0
```
