### DISCUSSION TITLE
Display only the max value per day

### DISCUSSION THREAD

**Discussion by JulianPSLearner** [RomRider/apexcharts-card#538] [Q&A]
Hi guys,
I want to have an electricity monitoring. Currently I have a home assistant helper that counts the used energy per day. At 0.00 it resets it and starts counting again.
I want to have graph that only displays one bar per day (electricity consumed).

But as I have multiple time stamps it shows me multiple bars for every day. What needs to be changed so I only see the max value per day?
Current draft:
`type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
header:
  show: true
  title: Stromverbrauch der Wärmepumpe pro Tag
  show_states: true
  colorize_states: true
  
series:
  - entity: sensor.verbrauchszahler_strom_warmepumpe_taglich
    type: column
    statistics:
      period: day
      type: state
    group_by:
      func: max
`

**Comment by wipash** [comment]
Try putting a `duration` in your group_by property, eg

```
type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
header:
  show: true
  title: Stromverbrauch der Wärmepumpe pro Tag
show_states: true
colorize_states: true
series:
  - entity: sensor.verbrauchszahler_strom_warmepumpe_taglich
    type: column
    group_by:
      func: max
      duration: 1d
```
