### DISCUSSION TITLE
How would I show the most recent 1 hour of data in a chart?

### DISCUSSION THREAD

**Discussion by nkamenar** [RomRider/apexcharts-card#551] [Q&A]
I am trying to use this to display CPU usage/Temperature over time and I would like it to always show the most recent hour worth of data. If I set the graph_span to 1h then it just statically shows 12AM-1AM. How would I make that window keep up to always show the latest hour or data with the older data trailing off to the left? Here is my current config:

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 1h
update_interval: 1sec
show:
  last_updated: true
  loading: false
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: CPU Use / Temperature
now:
  show: true
  color: red
  label: Now
span:
  end: day
series:
  - entity: sensor.processor_use
    name: Processor Usage
    stroke_width: 5
    group_by:
      duration: 30sec
    show:
      extremas: true
      header_color_threshold: true
  - entity: sensor.cpu_temperature
    stroke_width: 5
    group_by:
      duration: 30sec
    show:
      extremas: true
      header_color_threshold: true
```
