### DISCUSSION TITLE
Avoid using last value on the first line with a span interval?

### DISCUSSION THREAD

**Discussion by CumpsD** [RomRider/apexcharts-card#569] [Q&A]
I'm wondering if anyone has an idea to avoid apexcharts-card to not draw this first line? it's coming from last span's value to 0

I am drawing the current month on top off the previous month, but the first value of the current month is a line from the steep drop from last month's value to the starting 0 of the new month (or day):

![image](https://github.com/RomRider/apexcharts-card/assets/1201644/900693e7-c244-4263-bc98-657d2def2dee)

My config for this chart:

```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Waterverbruik Vandaag / Gisteren
  show_states: true
  colorize_states: true
span:
  start: day
update_interval: 15min
graph_span: 24h
all_series_config:
  stroke_width: 2
  type: line
  extend_to: now
  float_precision: 2
color_list:
  - lightblue
  - grey
series:
  - entity: sensor.waterverbruik_vandaag
    name: Vandaag
    yaxis_id: water
    type: area
    group_by:
      func: raw
    header_actions:
      tap_action:
        action: none
      hold_action:
        action: none
      double_tap_action:
        action: none
  - entity: sensor.waterverbruik_vandaag
    name: Gisteren
    offset: '-24h'
    opacity: 0.2
    yaxis_id: water
    group_by:
      func: raw
    show:
      in_header: true
    header_actions:
      tap_action:
        action: none
      hold_action:
        action: none
      double_tap_action:
        action: none
apex_config:
  yaxis:
    - id: water
      seriesName: Water
      decimalsInFloat: 2
  xaxis:
    tooltip:
      enabled: false
  legend:
    show: false
  grid:
    borderColor: rgba(123, 123, 123, 0.2)
  chart:
    foreColor: '#7B7B7B'
    toolbar:
      show: false
```
