### DISCUSSION TITLE
Difficulty using helper templates in apex graphs

### DISCUSSION THREAD

**Discussion by cybermaus** [RomRider/apexcharts-card#576] [Q&A]
Today I discovered apexcharts.

I wrote below graph, but I want to provide non-savy users ability to select the period. And yes, this thing I do does look like the brush option, but is not quite the same. The brush option zooms, but does not realy selects a different period.

So I figured I used helper input numbers, but they seem to not work. They seem accepted during code entry validation, but then go wrong when actually running.

Is this not supported, or am I doing something wrong?
How it should look (how it does looks when I type  ```graph_span: 7d``` myself)

![image](https://github.com/RomRider/apexcharts-card/assets/3198100/3ee9f73f-2b77-4f8c-8c2a-e6dd18247cc2)

How it looks
(and I did check the formula nicely evaluates to ```7d```)
![image](https://github.com/RomRider/apexcharts-card/assets/3198100/d502c2ea-e72f-46ef-a100-7aedcc4f28de)

```yaml
type: custom:apexcharts-card
graph_span: >-
  [[[ return ((states["input_number.graph_duration"].state | round(0) | string)
  + "d") ]]]
span:
  end: day
show:
  last_updated: true
header:
  show: true
  show_states: true
  colorize_states: true
  title: Daily Airco Energy till noon
now:
  show: true
  color: red
series:
  - entity: sensor.airco_pm_energy_total
    show:
      datalabels: true
    name: To Noon
    type: column
    unit: ' KWh'
    offset: '-12h'
    group_by:
      func: delta
      duration: 1d
  - entity: sensor.airco_pm_energy_total
    show:
      in_header: true
      in_chart: false
    name: Total
    type: column
    unit: ' KWh'
    offset: '-12h'
    group_by:
      func: delta
      duration: >-
        [[[ return ((states["input_number.graph_duration"].state | round(0) |
        string) + "d") ]]]
```
