### DISCUSSION TITLE
Stacking Apexchart and Entities in Vertical Card

### DISCUSSION THREAD

**Discussion by Bosty01** [RomRider/apexcharts-card#591] [General]
I'm trying to merge these 2 items into one card but an getting this error: 

// apexcharts-card version 2.0.4 /// value.offset is
extraneous

```
type: 'custom:vertical-stack-in-card'
title: Outside
cards:
  - type: entities
    entities:
      - entity: sensor.temperatureoutdoor
        name: Temp
      - entity: sensor.tomorrow_io_home_feels_like
        name: Feels Like
      - entity: sensor.tomorrow_io_home_dew_point
        name: Dew Point
      - entity: sensor.humidityoutdoor
        name: Humidity
      - entity: sensor.barometricpressureabsolute
        name: Abs. Pressure
      - entity: sensor.barometricpressurerelative
        name: Rel. Pressur
  - type: 'custom:apexcharts-card'
    experimental:
      color_threshold: true
    graph_span: 72h
    show:
      last_updated: true
    header:
      standard_format: false
      show: true
      show_states: true
      colorize_states: true
      title: Outdoor Temperature
    now:
      show: true
      color: red
      label: Now
    span:
      start: day
    offset: '-2.5d'
    series:
      - entity: sensor.temperatureoutdoor
        type: line
        name: Outdoor Temperature
        group_by:
          func: last
          duration: 15m
        stroke_width: 2
        show:
          extremas: true
          header_color_threshold: true
        color_threshold:
          - value: 18
            color: steelblue
          - value: 21
            color: midnightblue
          - value: 22
            color: orange
          - value: 23
            color: orangered
          - value: 24.5
            color: red
      - entity: sensor.humidityoutdoor
        name: Outdoor Humidity
        stroke_width: 2
        show:
          in_chart: true
```

Both YAML codes work by themselves but together, they do not.
