### DISCUSSION TITLE
Is XY scatter even possible?

### DISCUSSION THREAD

**Discussion by degreal** [RomRider/apexcharts-card#630] [Q&A]
```
type: custom:apexcharts-card
graph_span: 6months
chart_type: scatter
series:
  - entity: sensor.outside_temperature
    statistics:
      type: mean
      period: day
  - entity: sensor.heater_flow_temperature
    statistics:
      type: mean
      period: day
```
![pilt](https://github.com/RomRider/apexcharts-card/assets/4028600/c85dd79c-7750-43eb-ae16-e0080d7b6a16)
It plots two series against time but I need one XY chart to plotting outside vs flow. Since I use statistics they have perfectly matching items with shared timestamps.
