### DISCUSSION TITLE
Display resetting entity with 'diff' or 'delta' grouping

### DISCUSSION THREAD

**Discussion by justcoding-dev** [RomRider/apexcharts-card#636] [Q&A]
I have an entity that counts the energy imported from the grid over the day. It increases steadily and resets to zero at midnight. Since I want to display the hourly import, I have made a graph like this:

```
type: custom:apexcharts-card
stacked: true
update_interval: 5min
graph_span: 12h
span:
  start: hour
  offset: '-12h'
all_series_config:
  type: column
  group_by:
    func: delta
    duration: 60min
yaxis:
  - min: 0
series:
  - entity: sensor.solax_today_s_import_energy
    name: Grid Import
    color: red
```

Problem is, when the counter resets at midnight, the 'diff' function returns a large negative value, because the first bin value seems to be the last days accumulated value (the attached image shows the delta function, where the value is large and positive).

![Screenshot 2023-12-07 at 16 58 55](https://github.com/RomRider/apexcharts-card/assets/2361475/c0b26a9d-748a-46b7-ac67-05ee4cb22875)

Is there a ways to calculate the diff value as 
`diff = last > first ? last - first : last`
for each bin?
