### DISCUSSION TITLE
Reduce Datapoints

### DISCUSSION THREAD

**Discussion by smooth-baking-powder** [RomRider/apexcharts-card#660] [General]
Hi,

i have some energy Charts for my solarengine and devices. If i set graph_span on 30m all is fine. If i set 3h i cant go on the dashboard with my tablet. the app crash. On my PC my browser stops playing media in the background. if i go to another dashboard the media resume automatically (loading icon went away).

I think the datapoints are overloading the chart. Can i set "per hour max 500 datapoints" or similar? Or can i use another way to make it faster and smaller to load? My energy site is already very slow, with the charts it simply stuck.

```
type: custom:apexcharts-card
graph_span: 30m
update_delay: 5s
update_interval: 5min
yaxis:
  - min: 0
    max: 1500
header:
  show: true
  title: Energie
  show_states: true
  colorize_states: true
all_series_config:
  stroke_width: 2
series:
  - entity: sensor.tasmota_energy_power_3
    name: Solarkraftwerk
  - entity: sensor.shelly_strom_phase_channel_a_power
    name: Netzbezug
```

Thanks

**Comment by FlySmack** [comment]
Hi,
I had the same issue with data collected from a solar inverter. HA received a data point in the short term statistics every 5 seconds. For this you can define for a series that it shall take the data from the long term statistics. Have look into the statistics section of the documentation. 

Here an example:
```
type: custom:apexcharts-card
graph_span: 48h
update_interval: 5min
span:
  end: hour
now:
  show: true
  label: Now
header:
  show: true
  title: PV Production last 48h
  show_states: true
  colorize_states: true
chart_type: line
series:
  - entity: sensor.grm_balcony_power
    name: Actual Production
    unit: W
    min: 0
    max: 1.2
    statistics:
      type: mean
      period: 5minute
```

I hope this helps.
