### DISCUSSION TITLE
Remove/Filter data based on value

### DISCUSSION THREAD

**Discussion by cardozaj** [RomRider/apexcharts-card#752] [Q&A]
Is it possible to remove or filter data points from a series based on the value?
I am trying to do so with transform, but when I return `null` for values that I want to filter out I end up with a blank chart.
Returning `0` also doesn't work because then the chart looks like a wave.
This is what my series looks like:
```
series:
  - entity: sensor.litter_robot_4_pet_weight
    transform: "return x > 11 ? x : null;"
```

**Comment by cardozaj** [comment]
nvm, I figured out I just needed to add a group_by
```
series:
  - entity: sensor.litter_robot_4_pet_weight
    transform: "return (x > 11 && x < 15) ? x : null;"
    group_by:
      func: avg
      duration: 1d
      fill: last
      start_with_last: true
```
