### DISCUSSION TITLE
How to add a 2nd line on top of the first one to show 5 kW feeding into the grid in GREEN and 3 kW charging in ORANGE on top ?

### DISCUSSION THREAD

**Discussion by typxxi** [RomRider/apexcharts-card#762] [General]
I have this graph which shows the power I am feeding over the time

![image](https://github.com/user-attachments/assets/acd3629c-148d-4bf2-8860-e0df5ebed2f9)

But how can I add a second sensor maybe in orange on top of the current one which would be on top of the current one and showing around 3000W value?

I want to see the power I am feedin into the grid and also the power used to charge the battery.

I really aprreciate the help from anyone of the community to solve that issue for my 85 year old father who started the journey to move ahead and buy a silent EV and then PV system now with even a battery and a heatpump.

Thanks a lot

**Comment by typxxi** [comment]
Here is the code for the feeding and als the battery charging, but not on top of each other as intended.

![image](https://github.com/user-attachments/assets/4bb03018-a72d-4902-b5f9-3d6e4bc7e683)


```
type: custom:apexcharts-card
experimental:
  color_threshold: true
  brush: true
graph_span: 10h
brush:
  selection_span: 6 h
  apex_config: null
all_series_config:
  stroke_width: 1
  show:
    name_in_header: true
    legend_value: false
header:
  show: true
  title: ''
  show_states: true
  colorize_states: true
apex_config:
  grid:
    show: true
    borderColor: black
  chart:
    height: 600px
  tooltip:
    enabled: true
    followCursor: false
    x:
      show: false
    fixed:
      enabled: false
yaxis:
  - id: first
    min: 0
    max: 16000
    decimals: 0
    apex_config:
      tickAmount: 8
  - id: second
    opposite: true
    min: 0
    max: 24
    decimals: 0
    apex_config:
      tickAmount: 6
series:
  - entity: sensor.tibber_pulse_hbb_k5_stromerzeugung
    name: ' '
    type: area
    yaxis_id: first
    color: green
    stroke_width: 1
    curve: stepline
  - entity: sensor.hbb_pb2a16s20_battery1_power
    name: ' '
    type: area
    yaxis_id: first
    color: orange
    stroke_width: 1
    curve: stepline
 
```
