### DISCUSSION TITLE
Dont show future line

### DISCUSSION THREAD

**Discussion by xamrex** [RomRider/apexcharts-card#766] [Q&A]
Hello
I am following this website:
https://smarthomescene.com/guides/apexcharts-card-advanced-graphs-for-your-home-assistant-ui/
I d like to create a **Raspberry Pi Monitor**
![Przechwytywanie](https://github.com/user-attachments/assets/43cf96bf-33fa-4462-ab01-0c24be4f8476)

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 24h
show:
  last_updated: true
  loading: false
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: Raspberry Pi 4 CPU
now:
  show: true
  color: red
  label: Now
span:
  start: day
series:
  - entity: sensor.processor_use_percent
    name: Processor Usage
    stroke_width: 5
    group_by:
      duration: 30sec
    show:
      extremas: true
      header_color_threshold: true
  - entity: sensor.processor_temperature
    stroke_width: 5
    group_by:
      duration: 30sec
    show:
      extremas: true
      header_color_threshold: true
```

But when I do it on my dahsboard it looks like:
![Przechwytywanie2](https://github.com/user-attachments/assets/fe493259-9ce8-4799-a052-1415b14d5b96)

**How can I get rid of this 'future' plot?**

**Comment by xamrex** [comment]
ahh, just remove span option:
```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 24h
show:
  last_updated: true
  loading: false
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: Raspberry Pi 4 CPU
now:
  show: true
  color: red
  label: Now
series:
  - entity: sensor.system_monitor_obciazenie_procesora
    name: Processor Usage
    stroke_width: 5
    group_by:
      duration: 30sec
    show:
      extremas: true
      header_color_threshold: true
  - entity: sensor.system_monitor_temperatura_procesora
    stroke_width: 5
    group_by:
      duration: 30sec
    show:
      extremas: true
      header_color_threshold: true
```
