### DISCUSSION TITLE
The columns disappear unless I add a stroke width

### DISCUSSION THREAD

**Discussion by bazcurtis** [RomRider/apexcharts-card#774] [General]
I have the following yaml

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: Living Room Temperature
now:
  show: true
  color: red
  label: Now
series:
  - entity: sensor.espaltherma_indoor_air_temperature
    type: line
    name: Lounge
    group_by:
      func: last
      duration: 15m
    stroke_width: 5
    show:
      extremas: true
      header_color_threshold: true
    color_threshold:
      - value: 15
        color: steelblue
      - value: 18
        color: midnightblue
      - value: 21
        color: orange
      - value: 25
        color: orangered
      - value: 27
        color: red
  - entity: sensor.espaltherma_lw_setpoint_main
    name: Leaving Water Set Point
    type: column
    group_by:
      func: last
      duration: 15m
    show:
      in_chart: true
      extremas: true
```

It produces this graph. When I try to use columns instead of area the columns disappear. If I had a stroke with a value of 2 they will appear, What am I missing?

I also want to use colour threshold and use this code.

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 24h
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: Living Room Temperature
now:
  show: true
  color: red
  label: Now
series:
  - entity: sensor.espaltherma_indoor_air_temperature
    type: line
    name: Lounge
    group_by:
      func: last
      duration: 15m
    stroke_width: 5
    show:
      extremas: true
      header_color_threshold: true
    color_threshold:
      - value: 15
        color: steelblue
      - value: 18
        color: midnightblue
      - value: 21
        color: orange
      - value: 25
        color: orangered
      - value: 27
        color: red
  - entity: sensor.espaltherma_lw_setpoint_main
    name: Leaving Water Set Point
    type: column
    group_by:
      func: last
      duration: 15m
    show:
      in_chart: true
      extremas: true
    color_threshold:
      - value: 30
        color: steelblue
      - value: 35
        color: midnightblue
      - value: 38
        color: orange
      - value: 40
        color: orangered
      - value: 45
        color: red
```

![Screenshot 2024-09-12 at 09 20 05](https://github.com/user-attachments/assets/9840993c-88e8-43c0-a593-a31fe0c7e8b7)
![Screenshot 2024-09-12 at 09 22 21](https://github.com/user-attachments/assets/1722b622-a5d8-42ed-87d7-93c98f2cd5c1)
