### DISCUSSION TITLE
Compare statistic data from different days via line chart

### DISCUSSION THREAD

**Discussion by Steph-74** [RomRider/apexcharts-card#781] [Q&A]
Hi, I recently stumbled across the Apex-Card and think it is a greate way to push HA charts to a new level. However, I am struggeling with one thing, where I am not quite sure how to find a solution or if it is possible at all: I would like to compare seonsor data from one day with a previous day, i.e. photovoltaic production today with the photovoltaic production yesterday. I thougt to pull the data from statistics, but now I am struggeling to align the data so that it always starts at 0 at midnight for each day. The chart looks like this:

![image](https://github.com/user-attachments/assets/67cd07a8-e053-43b6-abfb-c9aedcd26aa4)

What I actually want to achieve:
- the y-scale shall start with 0
- in this example, the chart shall show the production during the day

My current code looks likt this:
```
type: custom:apexcharts-card
graph_span: 24h
update_interval: 5min
span:
  start: day
all_series_config:
  stroke_width: 2
now:
  show: true
series:
  - entity: sensor.pv_dc_lifetime_energy_total
    statistics:
      type: sum
      period: 5minute
    extend_to: now
  - entity: sensor.pv_dc_lifetime_energy_total
    offset: '-1d'
    statistics:
      type: sum
      period: 5minute
  - entity: sensor.pv_dc_lifetime_energy_total
    offset: '-2d'
    statistics:
      type: sum
      period: 5minute

```
Is this possible with the Apex Card? Did not find anything here in the disucssion that might bring mo on the right track :( 

Thanks!
