### DISCUSSION TITLE
showing a horizontal verge line like kWh price 20 Cent in a day ahead price chart for TOMORROW

### DISCUSSION THREAD

**Discussion by typxxi** [RomRider/apexcharts-card#791] [Ideas]
I am talking about the prices of tomorrow and a "horizontal line" of 20 cent as the verge line when I might consider charging up the battery during night.

For today it is easy cause if I use an inputhelper with 20 cent I have at least 1 data point from today and can plot the line to the end of the day with **`extend_to: end`** as seen here
![image](https://github.com/user-attachments/assets/f5a8cc69-4d2b-4b2b-b7fe-fd80d7b4cfb6)

But for tomorrow it does not work if push the focus 1 day ahead with **`offset: +1d`**
```
graph_span: 24h
span:
  start: day
  offset: +1d
```
The my 2nd entity the inputhelper can not be displayed cause that has no datapoint in that time span from midnight on.
So I would have to create such data point but I have no clue how to create that 00:00:01 datapoint for tomorrow with the value of 20 aks the input helper verge.
```
  - entity: input_number.tibber_ac_ladepreis_schwelle
    float_precision: 1
    yaxis_id: second
    name: AKKU LADE SCHWELLE (vom Netz laden)
    show:
      name_in_header: true
      legend_value: false
      extremas: true
    color: darkblue
    stroke_width: 2
    stroke_dash: 25
```

Any ideas of how to achieve that for the day of tomorrow only?

I mean i will not work for me to push the span from 1 day to 2 days in a chart cause I want to show both days in 2 different cards next to each other which is a must at least for now cause the whole dashboard is based on 2 columns of cards for today and the other for tomorrow and there might be also a third one soon for yesterday.
