### DISCUSSION TITLE
How to increase the font size on the Y-Axis ?

### DISCUSSION THREAD

**Discussion by typxxi** [RomRider/apexcharts-card#796] [Q&A]
I was able to increase the fontsize 
* along the y-axis  (labels)
* of the legend
* of a title

by using this code I had put together from the Java Script ApexChart documentation piece by piece.

```
apex_config:
  legend:
    show: true
    position: 'bottom'
    horizontalAlign: 'center' 
    floating: false
    fontSize: '14px'
  xaxis:
    title:
      text: Test
      show: true
      style:
        color: blue
        fontSize: 22px
    labels:
      style:
        colors: black
        fontSize: 16px
        fontWeight: bold
now:
  show: true
  label: "\_\_\_\_ J\_\_E\_\_T\_\_Z\_\_T \_\_\_\_"
  color: red
```

But it did not work out this way for the y-axis or the annotation (read rectangle "JETZT" aka now )

![image](https://github.com/user-attachments/assets/6751798e-4f50-429f-a5eb-11a2ac2d4f8c)

Any suggestions how to fix the y-axis too cause I could not find a typo ? 

```
apex_config:
  xaxis:
    labels:
      style:
        colors: black
        fontSize: 16px
        fontWeight: bold
```
thanks !
