### DISCUSSION TITLE
BST changes breaking grouped entries

### DISCUSSION THREAD

**Discussion by Euan-p** [RomRider/apexcharts-card#808] [Q&A]
I've got a graph for energy monitoring that groups the entries into buckets of each day, then reads the last in each  bucket to tell me what the final value was at the end of the day, but it's been broken by the fact that we had a 25-hour day on Sunday to account for BST ending. It's now reading 12:00 am for every day since the change, but 1:00 am for all the days before it. I was wondering if anyone knew a way to actually group the entries by date? It's not a major issue  - think I can probably cope with it breaking twice a year! 

```
type: custom:apexcharts-card
graph_span: 10d
stacked: true
span:
  end: day
series:
  - entity: sensor.octopus_standing_charge
    type: column
    name: Standing charge
    group_by:
      func: last
      duration: 1d
    float_precision: 2
    color: yellow
    stack_group: all
    show:
      in_header: false
```
