### DISCUSSION TITLE
Is there any way to access other series in data_generator?

### DISCUSSION THREAD

**Discussion by Plug11** [RomRider/apexcharts-card#814] [Q&A]
Is there a way to access the values of other series in the charts in a data_generator? 

I think the easiest way to describe this is through an example. In the following code, I have two series (representing heat generated and electricity consumption from a heat pump) which are aggregated using group_by and diff. I would like to be able to calculate the COP (heat/electricity) using the aggregated series, so the ratio is calculated for each element of the aggregated series.

```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Energy
  show_states: true
  colorize_states: true
series:
  - entity: sensor.heat_pump_electrical_energy
    name: elec
    type: column
    group_by:
      func: diff
      duration: 1hour
  - entity: sensor.heat_pump_heat_energy
    name: heat
    type: column
    group_by:
      func: diff
      duration: 1hour
### The following is illustrative pseudo code...
  -entity: XXX (not needed)
    name: COP
    data_generator: | # would need some code to do element-wise calculation of this ratio
      return series["heat"] / series["elec"] 
```
