### DISCUSSION TITLE
Is this a Y axis bug or am I missing a setting?

### DISCUSSION THREAD

**Discussion by dansity** [RomRider/apexcharts-card#816] [General]
Image explains well. I have hidden one value from the chart and yet the Y axis max value is still considered to that number.
Am I missing something or is it a bug?

![image](https://github.com/user-attachments/assets/00777765-865d-450b-b814-83442ace6e21)

```
type: custom:apexcharts-card
header:
  show: true
  title: Kinti időjárás
  show_states: true
  colorize_states: true
graph_span: 48h
series:
  - entity: sensor.temperature
    name: Temperature
    show:
      extremas: true
  - entity: sensor.humidity
    name: Humidity
    show:
      in_header: true
      in_chart: false
  - entity: sensor.wind_speed
    name: Wind Speed
yaxis:
  - id: default
    min: auto
    max: auto
apex_config:
  chart:
    type: line
  stroke:
    width: 2
```
