### DISCUSSION TITLE
Monthly statistics just presents last month value

### DISCUSSION THREAD

**Discussion by bengtner** [RomRider/apexcharts-card#832] [Q&A]
Hi,

I have a problem with monthly statistics of a utility meter measuring rain fall. I have similar cards displaying daily and weekly statistics and those work fine. However, my month graph just presents last month readings. Here is my configuration of the card.
```

type: custom:apexcharts-card
graph_span: 12month
header:
  show: true
  title: Rain/month
  show_states: false
span:
  end: month
series:
  - entity: sensor.rain_month
    color: aqua
    type: column
    group_by:
      func: max
      duration: 1month
yaxis:
  - min: 0
```
The utility meter sensor_month seems OK.

![image](https://github.com/user-attachments/assets/7897ac3c-c827-4b23-a6f4-2753850bc55f)
Any help on this is appreciated! 
(I have made a post in HA Frontend forum about this as well. But it seems like this one could be more appropriate.)

**Comment by bengtner** [comment]
This is quite strange. Everything is fine when using the Homeassistant app. But on the web there is just one value for the last month. I have tried two different computers so it is not related to web browser or anything like that.

![Screenshot 2024-12-28 08 47 46](https://github.com/user-attachments/assets/4abd2308-925a-42ed-9764-c3591cdd922b)
![Screenshot_20241228-210200](https://github.com/user-attachments/assets/9ad4144c-a583-481b-8a19-a364750547b3)

**Reply by gurka** [reply]
Did you solve this? I'm having the same issue

**Reply by gurka** [reply]
I got it working now. No group_by, just added this:

```
    statistics:
      type: mean
      period: day
```

Full yaml:

```
type: custom:apexcharts-card
graph_span: 1month
header:
  show: true
  title: Month
series:
  - entity: sensor.0x54ef441000a4ac46_temperature
    name: Vardagsrum
    stroke_width: 2
    show:
      legend_value: false
    statistics:
      type: mean
      period: day
```

**Comment by rrozema** [comment]
'''
series:
  - entity: sensor.rain_month
    statistics:
      type: change
      period: day
      align: start
'''
Your sensor is most likely a long term statistics (LTS). = It has an
attribute of state_class: total or state_class: total_increasing or
state_class: measurement. Having this attribute makes that statistical
values, calculated from the original states, are stored into the statistics
table. The original states captured will however still be removed after the
standard cleanup period like they are for all sensors (by default 10 days).
For the apex chart card to show any values older than the cleanup period
(i.e. read the values from that statistics table) you need to instruct
apexchart card to retrieve the series as 'change over a period' according
the example above when state_class is either of the both total classes. Use
type: avg, min or max  when your entity has state_class: measurement.

Op za 28 dec 2024 21:03 schreef bengtner ***@***.***>:

**Comment by bengtner** [comment]
Thanks! Yes, the sensor is a utility meter, i.e long term statistics. Your advice solved my issue. I have never managed to figure this out myself. Especially since the behaviour was different with the app frontend.

**Comment by bengtner** [comment]
Oops, I was too quick with my conclusion. The proposed addition of a statistics block in the configuration did a change. I get bars for several months. However, the values are completely wrong. Just a fraction of the monthly total. However, in the HA app everthing is fine. Multple bars and the values are reasonable. 

???

**Comment by rrozema** [comment]
Add a group_by: func: sum or something similar. The statistics: key plus it's subs tells the card to retrieve the values from the statistics table instead of from the states. The rest of the data selection for the graph however remains the same, i.e. you still need to group_by etc per the grouping that you want your graph to show.

**Comment by bengtner** [comment]
I do have a group by: item in the yaml.

```
type: custom:apexcharts-card
graph_span: 12month
header:
  show: true
  title: Regn/månad
  show_states: false
span:
  end: month
series:
  - entity: sensor.rain_month
    color: aqua
    type: column
    statistics:
      type: change
      period: day
      align: start
    group_by:
      func: max
      duration: 1month
yaxis:
  - min: 0
```

I don't get this. The HA app presents everything correctly without any statistics: item.
