### DISCUSSION TITLE
Error in bar graph value

### DISCUSSION THREAD

**Discussion by maconly34** [RomRider/apexcharts-card#861] [Q&A]
Hello,
I think there's a display error...
In the code below, I've had to change the multiplier from 1000 to 1, because the data received is already in kW.
The size of the bar is correct but not the numerical indication which is 10 times too large.

For example, one purple bar is the correct size at 4.2kW, whereas the value displayed is 42kW.
penultimate purple bar on the screenshot
<img width="1219" alt="Screenshot" src="https://github.com/user-attachments/assets/0770ef2c-9d33-4dd6-b033-10cbff0646ae" />

Do I need to correct anything or is this a bug?
THANK YOU
Code :
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 450px
stacked: true
graph_span: 15day
span:
  end: day
show:
  last_updated: true
header:
  show: true
  show_states: true
  colorize_states: true
  title: Daily Power Needs
yaxis:
  - min: 0
    max: "|+0|"
    decimals: 0
    apex_config:
      tickAmount: 4
series:
  - entity: sensor.deye_1_today_energy_import
    type: column
    name: Grid/Gen
    color: rgb(84, 144, 194)
    show:
      datalabels: true
    group_by:
      func: diff
      duration: 1day
    statistics:
      type: state
      period: hour
    transform: return Number(x) * 1.0;
    unit: kWh
  - entity: sensor.deye_1_today_production
    type: column
    name: PV
    show:
      datalabels: true
    color: rgb(255, 155, 48)
    group_by:
      func: diff
      duration: 1day
    statistics:
      type: state
      period: hour
    transform: return Number(x) * 1.0;
    unit: kWh
  - entity: sensor.deye_1_today_battery_discharge
    type: column
    name: Discharge
    color: purple
    group_by:
      func: diff
      duration: 1day
    statistics:
      type: state
      period: hour
    transform: return Number(x) * 1.0;
    unit: kWh
    show:
      datalabels: total
```
