### DISCUSSION TITLE
How to make stacked bar charts work??

### DISCUSSION THREAD

**Discussion by henriknordgren** [RomRider/apexcharts-card#873] [General]
I am using latest version of the card, latest HA etc etc.

The code below just put the two bars on top of each other they are not stacked... it is totally confusing. What am I missing?

I am working on a very graph-heavy dashboard for a friend of mine, and the apex charts is just giving me a lot of issues all the time. I really like it when it works, but now and then I stumble upon issues like this... :/ Any ideas?

  ```
type: custom:apexcharts-card
  graph_span: 1month
  update_interval: 1d
  stacked: true
  header:
    show: false   
    show_states: true
    colorize_states: false
    standard_format: true
  series:
    - entity: sensor.qubino_3_phase_smart_meter_electric_consumption_kwh
      color: lightblue
      type: column     
      name: Daily Usage
      statistics:
        type: change
        period: day
    - entity: sensor.easee_lifetime_energy
      color: purple
      type: column      
      name: Daily Usage
      statistics:
        type: change
        period: day

```

**Comment by Grana96** [comment]
I'm still struggling with it, but it seems you missed the stack_group in the series options:

```
type: custom:apexcharts-card
graph_span: 1month
update_interval: 1d
stacked: true
header:
  show: false   
  show_states: true
  colorize_states: false
  standard_format: true
series:
  - entity: sensor.qubino_3_phase_smart_meter_electric_consumption_kwh
    color: lightblue
    stack_group: Group1
    type: column     
    name: Daily Usage
    statistics:
      type: change
      period: day
  - entity: sensor.easee_lifetime_energy
    color: purple
    stack_group: Group1
    type: column      
    name: Daily Usage
    statistics:
      type: change
      period: day
```


But this is giving me some issue that when I have multiple chart on the same page I have some data that start from 0 instead of the top of the stack
