### DISCUSSION TITLE
combine span>offset and group_by>func>delta

### DISCUSSION THREAD

**Discussion by brazoayeye** [RomRider/apexcharts-card#876] [Q&A]
I have a graph that works well but if I add offset the extend_to: now option seems to extend a point more.
The last point is always 0, is there a way to remove it?

Thanks
```
type: custom:apexcharts-card
graph_span: 10d
now:
  show: true
header:
  show: true
  title: Name
  show_states: true
  colorize_states: true
span:
  offset: +2d
series:
  - entity: sensor.inverter_total_dc_input_energy
    name: GIU
    transform: return x/14.7
    curve: straight
    group_by:
      func: diff
      duration: 24h
    extend_to: now
```

![image](https://github.com/user-attachments/assets/d18d53fc-9001-4ae6-8b9d-a3d11ae7394d)
![image](https://github.com/user-attachments/assets/1c7b9d9a-11e8-4550-b1c0-9092d94c474d)
