### DISCUSSION TITLE
Need help to fetch value by transform

### DISCUSSION THREAD

**Discussion by cily35** [RomRider/apexcharts-card#881] [General]
Hi,

I would like to do some simple subtraction with the transform referring to other sensor but it's like not supported,

I don't want to build a template sensor on the configuration HA YAML as I'm running in a closed docker,

this is what I'm trying to build, however the last entity return NA
if I do x-1 is working fine

```
type: custom:apexcharts-card
graph_span: 1d
header:
  show: true
  title: Energy Breakdown (Today)
  show_states: true
  colorize_states: true
chart_type: donut
series:

  - entity: sensor.solarman_today_grid_consumption
    name: From Grid
    color: "#FF5733"
    
  - entity: sensor.solarman_battery_daily_discharge
    name: From Battery
    color: "#3366FF"
    
  - entity: sensor.solarman_today_power_consumption
    name: From Solar 
    color: "#00FF00"
    transform: |
      return x-sensor.solarman_today_grid_consumption-sensor.solarman_battery_daily_discharge ;
```

thanks
