### DISCUSSION TITLE
Show all values when hovering

### DISCUSSION THREAD

**Discussion by jakeycrx** [RomRider/apexcharts-card#883] [General]
Hi,

Is it possible to show all values when hovering? It does show all values when you have group by last:
```
group_by:
  func: last
```
![image](https://github.com/user-attachments/assets/2b1f283e-2d52-416d-a4fd-baf1e8bdb561)

Without that it only shows 1 value at a time:

![image](https://github.com/user-attachments/assets/b321fe55-e46e-4039-9a20-e3f295ed2da7)

I tried setting the tooltip options, but it doesn’t seem to do anything:
```
apex_config:
  tooltip:
    shared: true
    intersect: false
```
