### DISCUSSION TITLE
Removing the future tail

### DISCUSSION THREAD

**Discussion by richardsg307** [RomRider/apexcharts-card#887] [Q&A] [answered]
I want to show power usage today so set up the following code:
```
type: custom:apexcharts-card
header:
  show: true
  title: Household Power Consumption Today (kW)
  show_states: false
  colorize_states: true
series:
  - entity: sensor.electricity_meter_power
    stroke_width: 2
graph_span: 24h
span:
  start: day
```
<img width="362" alt="image" src="https://github.com/user-attachments/assets/e2ba4373-6cae-4e31-9a07-f3e5392dc817" />

However, it displays with a horizontal tail from now to midnight tonight at whatever is the most recent power level. It looks ugly.

How can I rid of it?

**Comment by richardsg307** [comment, marked as answer]
Found the answer!

```
series:
  - entity: sensor.electricity_meter_power
    stroke_width: 2
    extend_to: now
```
