### DISCUSSION TITLE
Is dynamic `graph_span` possible ?

### DISCUSSION THREAD

**Discussion by stefaanv** [RomRider/apexcharts-card#912] [Q&A]
I have a entity with dynamic electricity prices which I'm showing with this (apexcharts) integration.
The number of values depends on the time ot day: 24 before 14:00 ; 48 after 14:00.
Is it somehow possible to change the `graph_span` dynamically or to show all values and adapt the datetime x-axis to the available values ?

**Comment by mooseBringer** [comment]
Nor really an answer to your question but a workaround. You could make two graphs(cards) and them show them contitionally in a section view. 

Make a time of day binary sensor this will be on 14 and off 00
![Screenshot_20250607_080931_Home Assistant.jpg](https://github.com/user-attachments/assets/804a7159-d7d6-4dd5-ada9-cfb8dbd5a03c)

Then you need to add the separate cards in a two vertical stack to be able to use conditions
```
type: vertical-stack
cards:
  - type: custom:apexcharts-card
    header:
      show: true
      title: ApexCharts-Card
      show_states: true
      colorize_states: true
    graph_span: 24h
    series:
      - entity: sensor.price_sensor #and data generator
visibility:
  - condition: state
    entity: binary_sensor.price_graph_48h
    state: "Off"
```
and also
```
type: vertical-stack
cards:
  - type: custom:apexcharts-card
    header:
      show: true
      title: ApexCharts-Card
      show_states: true
      colorize_states: true
    graph_span: 48h
    series:
      - entity: sensor.price_sensor #and data generator 
visibility:
  - condition: state
    entity: binary_sensor.price_graph_48h
    state: "On"
```
You will of course use your apex card and change ```graph_span: 48h```
