### DISCUSSION TITLE
Force 0 value on y axis

### DISCUSSION THREAD

**Discussion by psfshr** [RomRider/apexcharts-card#924] [Q&A]
Is there a way to force the display of a ‘0’ line/value on the y-axis?
I have a number of graphs where values go both +ve and -ve, but the axis never shows 0 as a baseline.

![image](https://github.com/user-attachments/assets/085b3e13-750d-4e9c-9024-62ffb9062d98)

It would be good to be able to enforce to show the 0 line so that it’s more obvious where a value crossed from +ve to -ve etc.

**Comment by vingerha** [comment]
looking at your graph, how would the card need to act then, the left hand side (import price?) seems OK so do you expect a seconday 0 line?

**Comment by psfshr** [comment]
Here’s a better example with a single y axis:
<img width="1179" height="635" alt="image" src="https://github.com/user-attachments/assets/e331ed7c-bf90-45ea-882b-41e94565248f" />

**Comment by vingerha** [comment]
share the yaml please

**Reply by vingerha** [reply]
and this 'discussion' stuff is poorly read, better here: https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877 (yes...very VERY long but more people involved)

**Reply by psfshr** [reply]
YAML...

```
type: custom:apexcharts-card
header:
  title: Power
  show: true
  show_states: false
  colorize_states: true
series:
  - entity: sensor.encharge_492447007140_power
    name: Battery 140
    color: lightblue
  - entity: sensor.encharge_492447011435_power
    name: Battery 435
    color: lightgreen
now:
  show: true
graph_span: 24h
span:
  start: day
apex_config:
  chart:
    height: 150px
  tooltip:
    enabled: true
    shared: true
    followCursor: true
  legend:
    show: false
    showForSingleSeries: true
all_series_config:
  type: area
  opacity: 0.25
  stroke_width: 2
  extend_to: false
  group_by:
    func: avg
    duration: 15min
    fill: last
  show:
    legend_value: true
    name_in_header: true
yaxis:
  - decimals: 0
    apex_config:
      tickAmount: 4
```

Though from reading around elsewhere I think it's a limitation of the back end .js, so there's probably not a lot that can be done...
