### ISSUE TITLE
Show time during flyover

### ISSUE THREAD

**Issue by manu3b1** [RomRider/apexcharts-card#100]
When we fly over the graph, we see the date and value.
Would be nice to get time also, moreover when the span if 1 or few days large.
Thx.

**Comment by RomRider** [comment]
That's already the case in the tooltip and in the bottom of the graph. If there are more than 1 days displayed at the same time, it shows the date and time. Else only the time.

Else I don't understand your request so maybe provide a screenshot of what you are talking about.

**Comment by manu3b1** [comment]
Strange.
Here is what I see:
<img width="402" alt="Capture d’écran 2021-02-22 à 14 23 58" src="https://user-images.githubusercontent.com/46264838/108714426-cf733c00-7519-11eb-9208-088208fa7e6a.png">

**Comment by RomRider** [comment]
Share your config please

**Comment by manu3b1** [comment]
Here you have:
```
type: 'custom:apexcharts-card'
span:
  end: day
header:
  show: true
  show_states: true
  colorize_states: true
all_series_config:
  stroke_width: 2
series:
  - entity: sensor.daikin_heat_energy_consumption
    name: Daikin
    type: column
    group_by:
      func: sum
      duration: 120min
```
