### ISSUE TITLE
seres.show datalabes overlapped in stacked graph

### ISSUE THREAD

**Issue by terminet85** [RomRider/apexcharts-card#101]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When using series.show datalabes, on a stacked graph, labels will be overlapped 

**Version of the card**
Version: 1.7.1

**To Reproduce**
This is the configuration I used:
```
type: 'custom:apexcharts-card'
cache: false
stacked: true
graph_span: 7d
header:
  show: true
  title: FV Giornaliero
span:
  end: day
series:
  - entity: sensor.solaredge_power_production_template
    invert: true
    show:
      datalabels: true
    color: green
    name: Produzione
    unit: kW
    float_precision: 2
    curve: smooth
    type: column
    group_by:
      func: max
      duration: 1d
  - entity: sensor.solaredge_power_consumption_template
    show:
      datalabels: true
    color: red
    curve: smooth
    name: Consumo
    float_precision: 2
    unit: kW
    type: column
    group_by:
      func: max
      duration: 1d
apex_config:
  chart:
    height: 130%

```

**Screenshots**
![immagine](https://user-images.githubusercontent.com/14027613/108816903-4ad6fb00-75b7-11eb-8baf-2c6f4489001a.png)

**Expected behavior**
Green labels are missing because overlapped by red one. 

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 87
