### ISSUE TITLE
Extrema display bug with mixed units of measurements

### ISSUE THREAD

**Issue by romquenin** [RomRider/apexcharts-card#103]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Hey RomRider, Thank you very much for this gorgeous card, i love it. Farewell to Ingress and Grafana with such a wonder.
However i maybe have a bug to report or my config is faulty.
When i mix units of measurements in a line card, one of the entity will have it's extrema placed in a wrong position

**Version of the card**
Version: 1.7.7

**To Reproduce**
This is the configuration I used:

```
          - type: 'custom:apexcharts-card'
            graph_span: 7d
            header:
              show: true
              show_states: true
              colorize_states: true                                             
            apex_config:
              chart:
                height: 250  
                zoom:
                  enabled: true
                toolbar:
                  show: true
                  tools:
                    zoom: true
                    zoomin: true
                    zoomout: true
                    pan: true
                    reset: true                             
              yaxis:
                - title:
                    text: Température
                  decimalsInFloat: 0
                  #min: 18
                - title:
                    text: Humidité
                  decimalsInFloat: 1
                  opposite: true
                  #min: 29
            series:                  
              - entity: sensor.humidity
                color: '#3498db'
                name: Extérieur Humidité
                curve: smooth
                show:
                  extremas: true            
                group_by:
                  func: avg
                  duration: 120min                
              - entity: sensor.temperature
                color: orange
                name: Extérieur Température
                curve: smooth  
                group_by:
                  func: avg
                  duration: 120min  
                show:
                  extremas: true  

```

**Screenshots**
![Screenshot 2021-02-26 at 00 51 04](https://user-images.githubusercontent.com/34734431/109235632-594b2f80-77ce-11eb-8ee1-c8091e961ea1.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 88.0.4324.192 (Official Build) (x86_64)
