### ISSUE TITLE
card-mod v3.0 syntax

### ISSUE THREAD

**Issue by CDRX2** [RomRider/apexcharts-card#104]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser
- [ X] I verified that I'm really running the lastest version in my browser console
- [ X] I checked if there is another issue opened with the same problem

**Describe the bug**
Apexcharts-card is not yet liking the new card-mod syntax. I get a "value.card_mod is extraneous" error.

**Version of the card**
Version: 1.8.0-dev3

**To Reproduce**
This is the configuration I used:
```
    type: 'custom:apexcharts-card'
    chart_type: radialBar
    header:
      show: true
      title: '[[title]]'
    apex_config:
      title:
        margin: 0
      chart:
        height: 150%
      legend:
        horizontalAlign: left
      fill:
        type: 'gradient'
        gradient:
          shade: 'dark'
          type: 'horizontal'
          gradientToColors: ['#ff1a1a', '#ff1a1a']
          stops: [80, 100]
      plotOptions:
        radialBar:
          startAngle: -135
          endAngle: 135
          track:
            startAngle: -135
            endAngle: 135 
            strokeWidth: '100%'
            background: '#333'
            dropShadow:
              enabled: true
              top: 2
              left: 0
              blur: 4
              opacity: 0.15
    series:
      - entity: '[[sensor_1]]'
        name: '[[name_1]]'
        color: '#03a8f4'
      - entity: '[[sensor_2]]'
        name: '[[name_2]]'
        color: '#ffa31a'
    card_mod:
      style: |
        ha-card {
          box-shadow: none !important;
        }    
```

**Expected behavior**
Card should be showing.

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version 88
