### ISSUE TITLE
Define start of week for the span options

### ISSUE THREAD

**Issue by davidclemens** [RomRider/apexcharts-card#106]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

First off, thanks for this awesome lovelace card!

**Is your feature request related to a problem? Please describe.**
When using the `span` options with the `week` value, it appears as if the beginning of a week is defined as Sundays 0:00AM. I'm trying to compare the total energy consumption of the last 3 weeks (by using the `series.offset` functionality.

**Describe the solution you'd like**
I'd like the start to be Mondays 0:00AM.
It'd be great if this was another parameter to set the `start_of_week`.

**Describe alternatives you've considered**
- I tried using the `span.offset` parameter with value `+1d`. This looses the current data (see attached screenshots).
- I tried using the `span.offset` parameter with value `-6d`. This seems to be a valid workaround (see attached screenshots). But a parameter would be more straight forward, in my opinion.
- I have not tried fiddling with the language or locale settings of HA. 

**Additional context**
The default behaviour:
```
  - type: custom:apexcharts-card
    config_templates: templateA
    header:
      title: Energieverbrauch
    graph_span: 1week
    update_interval: 1h
    span:
      start: week
    now:
      show: true
      label: "jetzt"
    all_series_config:
      group_by:
        func: avg
        duration: 1h
    series:
      - entity: sensor.weekly_energy_default
      - entity: sensor.weekly_energy_default
        offset: -1week
      - entity: sensor.weekly_energy_default
        offset: -2week
```
![default behaviour](https://user-images.githubusercontent.com/43437141/109432160-3a38e180-7a0a-11eb-8aa0-5d38b874563c.png)

The `span.offset: -6d` workaround:
```
  - type: custom:apexcharts-card
    config_templates: templateA
    header:
      title: Energieverbrauch
    graph_span: 1week
    update_interval: 1h
    span:
      start: week
      offset: -6d
    now:
      show: true
      label: "jetzt"
    all_series_config:
      group_by:
        func: avg
        duration: 1h
    series:
      - entity: sensor.weekly_energy_default
      - entity: sensor.weekly_energy_default
        offset: -1week
      - entity: sensor.weekly_energy_default
        offset: -2week
```
![-6d offset](https://user-images.githubusercontent.com/43437141/109432162-3b6a0e80-7a0a-11eb-80e4-d9b61c210a58.png)
