### ISSUE TITLE
Graph with span: end: day 1rst value issue

### ISSUE THREAD

**Issue by manu3b1** [RomRider/apexcharts-card#110]
Hi,
I get strange value for the 1rst item of a hourly chart: it is always far too high compared to what is reported on larger chart, as if it contains the whole day:
Here the charts for 1 day, 2 days and 3 days about the same data:

<img width="395" alt="1day" src="https://user-images.githubusercontent.com/46264838/109653621-88acc400-7b61-11eb-8764-9cf08ee5ecb8.png">
<img width="395" alt="2days" src="https://user-images.githubusercontent.com/46264838/109653625-89455a80-7b61-11eb-9164-cec17a2233ed.png">
<img width="395" alt="3days" src="https://user-images.githubusercontent.com/46264838/109653628-89ddf100-7b61-11eb-9e1f-deb98cb5b3c8.png">

```
type: 'custom:apexcharts-card'
graph_span: 2d
header:
  title: Conso par Heure
  show: true
  show_states: true
  colorize_states: true
apex_config:
  legend:
    show: false
span:
  end: day
now:
  show: true
all_series_config:
  stroke_width: 2
  show:
    legend_value: false
series:
  - entity: sensor.linky_hc
    name: Linky HC
    type: column
    transform: return x / 1000;
    unit: kWh
    group_by:
      func: diff
      duration: 60min
```

Looks like it is linked to the “end: day” option mixed with "fun: diff":
```
span:
  end: day
```
Thx.

**Comment by RomRider** [comment]
Could you try with `fill: 'null'` in the `group_by` please? Also another idea would be `graph_span: 2h-1s`.

**Comment by manu3b1** [comment]
Same issue with each of these tricks.
Here are the data viewed by HA:
<img width="395" alt="HP" src="https://user-images.githubusercontent.com/46264838/109688525-a50e2800-7b84-11eb-8487-64458b5ca591.png">
<img width="395" alt="HC" src="https://user-images.githubusercontent.com/46264838/109688531-a63f5500-7b84-11eb-9503-62c04d6e773f.png">

**Comment by manu3b1** [comment]
I've reproduced the issue with a simple incremental sensor:
```
sensor:
  - platform: template
    sensors:
      counter:
        friendly_name: "Counter"
        unit_of_measurement: "s"
        value_template: "{{ as_timestamp(now()) }}"

automation:
  - alias: "Update counter"
    trigger:
      - platform: time_pattern
        seconds: "/1"
    action:
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.counter
```
<img width="625" alt="Capture d’écran 2021-03-02 à 23 11 05" src="https://user-images.githubusercontent.com/46264838/109722303-ce42ae80-7bac-11eb-95a9-dd2cd2210369.png">
