### ISSUE TITLE
Datapoints not connected on line chart

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#120]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I have noticed that on this graph, the lines are not connected.

**Version of the card**
Version: 1.8.1

**To Reproduce**
This is the configuration I used:
```yaml
apexcharts_card_templates:
  200px_chart:
    apex_config:
      chart:
        height: 200px
  
  all_series_no_legend_value:
    all_series_config:
      show:
        legend_value: false

- type: 'custom:apexcharts-card'
  graph_span: 14d
  y_axis_precision: 0
  config_templates:
    - 200px_chart
    - all_series_no_legend_value
  all_series_config:
    # extend_to_end: false
    stroke_width: 3
    curve: stepline
  header:
    show: true
    title: Printer Ink Remaining
    show_states: true
    colorize_states: true
  series:
    - entity: sensor.mfc_j890dw_black_ink_remaining
      name: Black
      color: BLACK
    - entity: sensor.mfc_j890dw_magenta_ink_remaining
      name: Magenta
      color: MAGENTA
    - entity: sensor.mfc_j890dw_cyan_ink_remaining
      name: Cyan
      color: CYAN
    - entity: sensor.mfc_j890dw_yellow_ink_remaining
      name: Yellow
      color: GOLD

```

**Screenshots**
![printer](https://user-images.githubusercontent.com/54566217/110033896-179e2400-7d8e-11eb-9096-d8e09500dba6.png)

**Expected behavior**
I would expect the data points to be connected.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 88.0.4324.190 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
