### ISSUE TITLE
Blank Column

### ISSUE THREAD

**Issue by romquenin** [RomRider/apexcharts-card#121]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem (i think)

**Describe the bug**
Since the last update all my graphs with "column" are not displaying any column and if i don't add "datalabels" the card will be kind of blank

**Version of the card**
Version: 1.8.1

**To Reproduce**
This is the configuration I used:
```yaml
      - type: 'custom:apexcharts-card'   
        graph_span: 7d
        span:
          end: day      
        series:
          - color: 'rgb(235,10,104)'
            entity: sensor.tplink_1_today_energy_kwh
            type: column     
            group_by:
              func: max
              duration: 1d
            show:
              datalabels: true   
```

**Screenshots**
![Screenshot 2021-03-04 at 22 47 29](https://user-images.githubusercontent.com/34734431/110035181-9e75e100-7d3b-11eb-99ba-7903a091a3f9.png)

**Expected behavior**
Visible column.

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [88.0.4324.192 (Official Build) (x86_64)]

**Smartphone (please complete the following information):**
 - Device: [Android]
 - Browser [mobile app]
 - Version [last]

**Additional context**
I have tried several graph config with "columns" i've found on the forum and this repo with no success at all. I have tried to delete the card, reboot, install the card back, refresh cache, etc, etc.. 
Sorry for maybe a dumb config problem, but i'm completely stuck on this bug.
Thanks for your help.
