### ISSUE TITLE
Datalabels with multiple axis

### ISSUE THREAD

**Issue by rasssta** [RomRider/apexcharts-card#123]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
Not sure if this is a bug or a missing feature.

I have 2 stacked sensors for one axis and a temperature line for another axis. When I show the temp line, it includes that value in the stack's datalabel total, while it at the same time shows the "proper" line. Is it possible somehow to exclude it from the datalabel total? I've tried using "datalabels: false" for the temp sensor but no workie.

**Version of the card**
Version:1.8.1

**To Reproduce**
This is the configuration I used:
```
type: 'custom:apexcharts-card'
graph_span: 6d
span:
  end: day
update_interval: 3min
all_series_config:
  stroke_width: 4
stacked: true
experimental:
  color_threshold: true
header:
  show: true
  show_states: true
  colorize_states: true
  title: Strömförbrukning per dag
series:
  - entity: sensor.energy_wh_lvp_annex_daily
    name: Annex
    curve: smooth
    type: column
    transform: return x / 1000;
    unit: kWh
    group_by:
      duration: 24h
      func: last
    show:
      legend_value: false
  - entity: sensor.energy_wh_lvp_storstugan_daily
    name: Storstugan
    curve: smooth
    type: column
    transform: return x / 1000;
    unit: kWh
    group_by:
      duration: 24h
      func: last
    show:
      datalabels: total
      legend_value: false
  - entity: sensor.temperature_011_utomhus
    curve: smooth
    type: line
    group_by:
      duration: 24h
      func: avg
    show:
      in_header: false
      legend_value: false
      datalabels: false
    opacity: 0.5
    color_threshold:
      - value: -10
        color: blue
        opacity: 1
      - value: 0
        color: pink
      - value: 20
        color: red
apex_config:
  legend:
    show: true
  chart:
    height: 225
  yaxis:
    - show: true
      showAlways: true
      decimalsInFloat: 0
      seriesName: Annex
      title:
        text: kWh
    - show: false
      decimalsInFloat: 0
      seriesName: Annex
    - show: true
      opposite: true
      decimalsInFloat: 0
      title:
        text: ℃
  xaxis:
    type: datetime
    zoom:
      type: x
      enabled: true
      autoScaleYaxis: true

```

**Screenshots**
![image](https://user-images.githubusercontent.com/4455235/110205398-02052900-7e78-11eb-94ed-56352dc253fd.png)

![image](https://user-images.githubusercontent.com/4455235/110205034-8e165100-7e76-11eb-85ef-8c7ff2516523.png)

**Expected behavior**
Only include the stacked columns in the datalabels total.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 88.0.4324.192
