### ISSUE TITLE
Interaction with card_templater causes glitching

### ISSUE THREAD

**Issue by wigster** [RomRider/apexcharts-card#124]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
If an ApexChart is wrapped inside the card-templater card, the chart keeps on disappearing and redrawing every few seconds, also moving the viewport of the browser. I appreciate this may be an issue with the templater rather than ApexCharts, but I thought I would report this at least.

**Version of the card**
Version: 1.8.2 for ApexCharts, card-templater v 0.0.16

**To Reproduce**
This is the configuration I used. As you can see, there is no templating happening, this is just a simple area chart plotting a single sensor.
```yaml
type: 'custom:card-templater'
entities:
  - wu_dejvice_status
  - wu_podbaba_status
card:
  type: 'custom:apexcharts-card'
  series:
    - entity: sensor.wu_dejvice_temperature
      type: area
  graph_span: 24h
```

**Screenshots**
This is what I happens for 2-3 second every 5-10 seconds:

![image](https://user-images.githubusercontent.com/10956987/110259501-41329780-7fa8-11eb-9f85-059302a195e8.png)

**Expected behavior**
A nice and stable plot
**Desktop (please complete the following information):**
 - MS Edge v 90
 - Firefox  v86

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS14.4
 - Browser safafri stock
