### ISSUE TITLE
Issue with color_threshold in combination with multiple axis

### ISSUE THREAD

**Issue by rasssta** [RomRider/apexcharts-card#127]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
I have 2 outdoor temp sensors on 2 different HASS installations. 

I have the same color_threshold configured for both of these temp sensors, but one does not show the color variations properly. The configuration is actually identical between the 2 installations as the outdoor sensor just happen to have the same ID in both installations.

**Version of the card**
Version: 1.8.2

**To Reproduce**
This is the configuration I used:
Working:
```
type: 'custom:apexcharts-card'
graph_span: 24h
update_interval: 3min
locale: sv
all_series_config:
  stroke_width: 4
experimental:
  color_threshold: true
header:
  show: true
  show_states: true
  colorize_states: true
  title: Utomhus - Temperatur
series:
  - entity: sensor.temperature_011_utomhus
    curve: smooth
    type: line
    color_threshold:
      - value: -10
        color: blue
        opacity: 1
      - value: 0
        color: white
      - value: 20
        color: red
apex_config:
  legend:
    show: false
  chart:
    height: 225
```

Not working:
```
type: 'custom:apexcharts-card'
graph_span: 24h
update_interval: 3min
locale: sv
all_series_config:
  stroke_width: 4
experimental:
  color_threshold: true
header:
  show: true
  show_states: true
  colorize_states: true
  title: Utomhus - Temperatur
series:
  - entity: sensor.temperature_011_utomhus
    curve: smooth
    type: line
    color_threshold:
      - value: -10
        color: blue
        opacity: 1
      - value: 0
        color: white
      - value: 20
        color: red
apex_config:
  legend:
    show: false
  chart:
    height: 225
```

**Screenshots**
Working:
![image](https://user-images.githubusercontent.com/4455235/110463867-b8fce100-80d2-11eb-9bf6-9e56b96c8253.png)

Not working:
![image](https://user-images.githubusercontent.com/4455235/110463895-c0bc8580-80d2-11eb-9070-024069502db0.png)

**Expected behavior**
Same conf should both give the working type of color variation.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 88.0.4324.192
