### ISSUE TITLE
Chart with multiple Y-axes not being rendered correctly

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#128]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**

I created a chart that shows the current and mean download and upload speeds for the last 3 days with an area chart highlighting the usage during evening time. However, I noticed that the charts are not being generated properly with the upload charts not properly matched with the Y-axis.

If I remove the area chart, then everything looks good.

**Version of the card**
Version: 1.8.2

**To Reproduce**
This is the configuration I used:
```yaml
apexcharts_card_templates:
  200px_chart:
  apex_config:
    chart:
      height: 200px

  stepline_chart:
    all_series_config:
      extend_to_end: false
      stroke_width: 2
      curve: stepline
      show:
        legend_value: false

- type: custom:apexcharts-card
  config_templates:
    - 200px_chart
    - stepline_chart
  apex_config:
    yaxis:
      - show: true
        decimalsInFloat: 0
        opposite: true
        min: 0
        max: 1
        tickAmount: 1
      - show: true
        decimalsInFloat: 0
      - show: false
        decimalsInFloat: 0
  all_series_config:
    unit: Mbps
  header:
    show: true
    show_states: true
    title: Internet Download (Last 3 days)
  graph_span: 3d
  y_axis_precision: 0
  color_list: ['lightgray','#983da1','Plum']
  series:
    - entity: binary_sensor.evening_time
      transform: "return x === 'on' ? 1 : 0;"
      curve: stepline
      type: area
      opacity: 0.2
      unit: ' '
      show:
        in_header: false
    - entity: sensor.speedtest_download
    - entity: sensor.stat_speedtest_download
      name: Mean Download
      show:
        in_header: false

- type: custom:apexcharts-card
  config_templates:
    - 200px_chart
    - stepline_chart
  apex_config:
    yaxis:
      - show: true
        decimalsInFloat: 0
        opposite: true
        min: 0
        max: 1
        tickAmount: 1
      - show: true
        decimalsInFloat: 0
      - show: false
        decimalsInFloat: 0
  all_series_config:
    unit: Mbps
  header:
    show: true
    show_states: true
    title: Internet Upload (Last 3 days)
  graph_span: 3d
  y_axis_precision: 0
  color_list: ['lightgray','DARKKHAKI','LightSeaGreen']
  series:
    - entity: binary_sensor.evening_time
      transform: "return x === 'on' ? 1 : 0;"
      curve: stepline
      type: area
      opacity: 0.2
      unit: ' '
      show:
        in_header: false
    - entity: sensor.speedtest_upload
    - entity: sensor.stat_speedtest_upload
      name: Mean Upload
      show:
        in_header: false

- type: custom:apexcharts-card
  config_templates:
    - 200px_chart
    - stepline_chart
  apex_config:
    yaxis:
      - show: true
        decimalsInFloat: 0
        opposite: true
        min: 0
        max: 1
        tickAmount: 1
      - show: true
        decimalsInFloat: 0
      - show: false
        decimalsInFloat: 0
      - show: false
        decimalsInFloat: 0
      - show: false
        decimalsInFloat: 0
  all_series_config:
    unit: Mbps
  header:
    show: true
    show_states: true
    title: Internet Performance (Last 3 days)
  graph_span: 3d
  y_axis_precision: 0
  color_list: ['lightgray','#983da1','DARKKHAKI','Plum','LightSeaGreen']
  series:
    - entity: binary_sensor.evening_time
      transform: "return x === 'on' ? 1 : 0;"
      curve: stepline
      type: area
      opacity: 0.2
      unit: ' '
      show:
        in_header: false
    - entity: sensor.speedtest_download
    - entity: sensor.speedtest_upload
    - entity: sensor.stat_speedtest_download
      name: Mean Download
      show:
        in_header: false
    - entity: sensor.stat_speedtest_upload
      name: Mean Upload
      show:
        in_header: false
```
This is the code for the chart without the secondary Y-axis

```
- type: custom:apexcharts-card
  config_templates:
    - 200px_chart
    - stepline_chart
  all_series_config:
    unit: Mbps
  header:
    show: true
    show_states: true
    title: Internet Performance (Last 3 days)
  graph_span: 3d
  y_axis_precision: 0
  color_list: ['#983da1','DARKKHAKI','Plum','LightSeaGreen']
  series:
    - entity: sensor.speedtest_download
    - entity: sensor.speedtest_upload
    - entity: sensor.stat_speedtest_download
      name: Mean Download
      show:
        in_header: false
    - entity: sensor.stat_speedtest_upload
      name: Mean Upload
      show:
        in_header: false
```

**Screenshots**
Charts 1 and 2 are being generated correctly. (Note the Y-axis). However, when I combine the 4 lines into 1 chart (chart 3), the lines which were generated properly in chart 2 is now not being generated properly.

![chart](https://user-images.githubusercontent.com/54566217/110556129-04c28f80-8192-11eb-856e-bae3b698d622.png)

This chart below does not contain the secondary Y-axis area series.

![chart1](https://user-images.githubusercontent.com/54566217/110556234-320f3d80-8192-11eb-8c1d-c993061da06a.png)

**Expected behavior**
The charts to be generated properly

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 89.0.4389.82

**Smartphone (please complete the following information):**

**Additional context**
