### ISSUE TITLE
Y_axis constant min and max.

### ISSUE THREAD

**Issue by ikavior** [RomRider/apexcharts-card#129]
Hi,
 
Is there any possibility to make constans min and max values on the y_axis?

BR,
K.

**Comment by RomRider** [comment]
Yes

```yaml
apex_config:
  yaxis:
    min: xxx
    max: xxx
```
