### ISSUE TITLE
Y Axis max value does not reflect data in graph

### ISSUE THREAD

**Issue by MatteGary** [RomRider/apexcharts-card#133]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [ ] I checked if there is another issue opened with the same problem

**Describe the bug**
I use a Rest sensor to get a list of value from an influxdb. Long story short, I have an attribute with an array of [datetime, value] field. Graph is working fine with that. Only problem is that if I collect 24h of data, but showing only latest 6 hour, the max on the Y axis is based on the whole 24h and not on the data actually shown.

In screenshot you can see that data are below 4k, but the max is calculated on the max value in the array which is from yesterday (around 10k).

 

**Screenshots**
![image](https://user-images.githubusercontent.com/7734219/111293400-88282900-8649-11eb-90f9-d4e421be320f.png)

**Expected behavior**
I expect the max range on the Y axis to be on the max value actually shown in the graph. I don't want to manually configure a max value.

**Comment by RomRider** [comment]
That's how it works with ApexCharts, if you don't want that, in your data_generator, ignore the values before the beginning of the chart: you have access to `start` as a variable in `data_generator` which is a Date object so you can compare the data timestamp with `start.getTime()`

**Comment by MatteGary** [comment]
The problem is with how InfluxDB works then. 
I'll try to make an example: I want to plot data between 04:00 and 10:00, but data are available starting only from 08:00. If I do that I will have the line starting from 08:00. If I download data from 24h, I will have data available also from the day before, so the line will  be plotted for the whole timespan, but as I said the Y axis will be wrongly fitted.
Any suggestion?

**Comment by RomRider** [comment]
What about just keeping the last value before `start` and excluding everything else in the `data_generator` ?
If you share your config, I could have a look and help you :)

**Comment by MatteGary** [comment]
I'm not so good with javascript, so yourhelp would be really appreciated :D 

Right now I'm not using a data_generator, and this is my configuration
 
```
type: 'custom:apexcharts-card'
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
graph_span: 6h
series:
  - entity: sensor.rest_pannelli_solari
    data_generator: |
      return entity.attributes.values
  - entity: sensor.rest_energia_immessa
    data_generator: |
      return entity.attributes.values
```

as I told you, the attribute _values_ on each entity already contains an array of object [timestamp, value] to be plotted.

Data looks like this

![image](https://user-images.githubusercontent.com/7734219/111439308-84f27300-8705-11eb-8116-8743240ec636.png)

Do you need the proper data to play with?
Thanks
Matteo
