### ISSUE TITLE
Markings Different to Threshold Colours

### ISSUE THREAD

**Issue by eximo84** [RomRider/apexcharts-card#134]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
ApexChart Markings are not the same colour the same as the threshold colours, instead follow standard stroke colour instead.

**Version of the card**
Version: 1.8.2

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
header:
  show: true
  show_states: true
  colorize_states: true
  title: Daily Cost / Usage
  standard_format: true
span:
  end: day
graph_span: 1w
all_series_config:
  stroke_width: 4
  extend_to_end: false
  group_by:
    func: diff
    start_with_last: true
    duration: 1d
  color_threshold:
    - value: 0
      color: '#2196F3'
    - value: 5
      color: '#4CAF50'
    - value: 20
      color: '#FFC107'
    - value: 30
      color: '#FF5722'
  show:
    header_color_threshold: true
experimental:
  color_threshold: true
y_axis_precision: 0
series:
  - entity: octopusagile.monthly_cost
    type: line
  - entity: octopusagile.monthly_usage
    type: column
apex_config:
  legend:
    show: false
  chart:
    foreColor: '#ccc'
    dropShadow:
      enabled: false
      enabledOnSeries:
        - 0
        - 1
      top: 3
      left: 2
      blur: 4
      opacity: 1
  markers:
    size: 5
    shape: circle
    strokeWidth: 2
    hover:
      size: 7
  grid:
    borderColor: '#2a2b2d'
    show: true
    strokeDashArray: 0
    xaxis:
      lines:
        show: true

```

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25502878/111308999-4ac89900-8653-11eb-8cfe-73873c004cbd.PNG)

**Expected behavior**
Markings to be the same colour as defined in the threshold colours

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22]  89.0.774.54

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11
 - OS: [e.g. iOS8.1] iOS 14.4
 - Browser [e.g. stock browser, safari] HA companion app

**Additional context**
