### ISSUE TITLE
Issue with thomasloven/lovelace-layout-card in Grid layout

### ISSUE THREAD

**Issue by woodmj74** [RomRider/apexcharts-card#135]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
When using thomasloven/lovelace-layout-card in _grid layout_ the following parameters are added to the lovelace cards to position it in the defined grid:
```
layout:
  grid-area: [position]
```
When using this with ApexCharts an error is thrown.

There appears to be some conversation around layout-card here: https://github.com/RomRider/apexcharts-card/issues/121 but don't think this is the same issue

**Version of the card**
Version: 1.8.2

**To Reproduce**
This is the configuration I used:

Card Configuration:
```
      - type: 'custom:apexcharts-card'
        header:
          show: true
          title: Temperature
          show_states: true
          colorize_states: true
        all_series_config:
          show:
            legend_value: false
        series:
          - entity: sensor.lounge_temperature
          - entity: sensor.landing_temperature
          - entity: sensor.roof_temperature
        layout:
          grid-area: p22
```
View Configuration:
```
  - title: People Places
    path: people-places
    background: center / cover no-repeat url("/local/blue-back2.jpg") fixed
    icon: 'mdi:motion-sensor'
    panel: false
    type: 'custom:grid-layout'
    layout:
      grid-template-columns: 20px 1fr 20px 1fr 20px 1fr 20px
      grid-template-rows: auto
      grid-template-areas: |
        ". p11 . p12 . p13 ."
        ". p21 . p22 . p23 ."
      mediaquery:
        '(max-width: 800px)':
          grid-template-columns: 95%
          grid-template-areas: |
            "p11"
            "p12"
            "p13"
            "p21"
            "p22"
            "p23"
    badges: []
    cards:
```

**Screenshots**

![image](https://user-images.githubusercontent.com/68328701/111443707-8c178200-8701-11eb-8421-0516bd81b6a2.png)

**Expected behavior**
To be able to place an apexchart-card in my chosen layout-card grid location

**Desktop (please complete the following information):**
 - Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Appreciate this is probably not an apexchard-card specific issue and a result of using layout-card, specifically the Grid option. Raising it see if there is anything could be done but happily accept an answer that this isn't in scope.
