### ISSUE TITLE
Adding secondary y-axis produces empty space left of graph

### ISSUE THREAD

**Issue by comatose-tortoise** [RomRider/apexcharts-card#144]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser
- [*] I verified that I'm really running the lastest version in my browser console
- [*] I checked if there is another issue opened with the same problem

**Describe the bug**
Adding a secondary y-axis, even without showing it on the graph, produces an empty space to the left of the graph. This space is not present if the invisible y-axis is removed.

**Version of the card**
Version: 1.8.2

**To Reproduce**
This is the configuration I used:

One y-axis, no empty space:
```
  yaxis:
    - show: true
      title:
        text: Detections / 15 min
        rotate: -90
        offsetX: 0
        offsetY: 0
      min: 0
      labels:
        show: true
      decimalsInFloat: 0
      forceNiceScale: true
```
Two y-axis, empty space to the left of the graph:
```
  yaxis:
    - show: true
      title:
        text: Detections / 15 min
        rotate: -90
        offsetX: 0
        offsetY: 0
      min: 0
      labels:
        show: true
      decimalsInFloat: 0
      forceNiceScale: true
    - show: false
      labels:
        show: false
```
**Screenshots**
First yaml: 
![nobug](https://user-images.githubusercontent.com/32922688/113578344-f2b5fe80-9622-11eb-8e89-43ab186a8302.png)

Second yaml:
![bug](https://user-images.githubusercontent.com/32922688/113578354-f77ab280-9622-11eb-9cb6-f051f7a33a53.png)

**Expected behavior**
I expect the graph to have the same appearance if the secondary y-axis is not shown.

**Desktop (please complete the following information):**
 - Browser: Safari
 - Version 14.0.3
