### ISSUE TITLE
incorrect buckets with group_by.duration: 1d and span.start: month

### ISSUE THREAD

**Issue by hk-ret** [RomRider/apexcharts-card#145]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Description**
When rendering daily aggregated values for the current month the bucket boundary time seems to be always `10:30`. This is independent of the data displayed (I used temperature values in my example with plenty of values without gaps).
When not using `span: {start: month}` the boundary as at the current time (which is also not always desirable).

**Version of the card**
Version: v1.9.0-dev.1 (same behavior with version v1.8.2)

**To Reproduce**
This is the configuration I used:
```
type: 'custom:apexcharts-card'
graph_span: 1 month
span: {start: month}
series:
  - entity: sensor.north_out_temperature
    group_by: {func: avg, duration: 1d}
```

**Screenshots**
![Screenshot 2021-04-14 172449](https://user-images.githubusercontent.com/55021191/114736452-643e2d00-9d46-11eb-9775-3d0806cfcccd.png)

**Expected behavior**
If `span: {start: month}` and `group_by: {duration: 1d}` buckets should start at `00:00`

**Desktop (please complete the following information):**
 - Browser any

**Smartphone (please complete the following information):**
 - Device: any
