### ISSUE TITLE
Group_by makes “extend_to_end: false” not work - and without group_by makes extremas not work

### ISSUE THREAD

**Issue by TheArcturian** [RomRider/apexcharts-card#148]
I have a small problem with my electric price graph. To show extremas, it seems like I have to use “group_by” to make it show up. But if I use "group_by", the orange todays graph extends to the right all the way even though I have stated “extend_to_end: false”.

![apex1](https://user-images.githubusercontent.com/16746633/115952296-70b04b80-a4e5-11eb-8f2e-0ecb946c9e17.png)

Is this a bug or can I stop the orange todays graph from filling up behind tomorrows blue price graph?

The following screenshot is without "group_by" on the orange graph which shows correctly, but the two extremas values disappear:

![apex2](https://user-images.githubusercontent.com/16746633/115952306-7a39b380-a4e5-11eb-8edf-4e3b03070f2a.png)

Here is the code:

```type: 'custom:apexcharts-card'
header:
  title: Strømpris
  show: true
  show_states: true
  colorize_states: true
hours_12: false
y_axis_precision: 2
graph_span: 2d
span:
  start: day
now:
  show: true
series:
  - entity: sensor.nordpool
    name: I dag
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        return [new Date(entry.start), entry.value];
      });
    type: column
    show:
      legend_value: false
      in_header: raw
      name_in_header: false
      extremas: true
    group_by:
      duration: 1h
      func: last
    extend_to_end: false
    float_precision: 2
  - entity: sensor.nordpool
    name: I morgen
    data_generator: |
      return entity.attributes.raw_tomorrow.map((entry) => {
        return [new Date(entry.start), entry.value];
      });
    type: column
    show:
      legend_value: false
      in_header: false
      extremas: true
    group_by:
      duration: 60min
      func: avg
    extend_to_end: false
    float_precision: 2
  - entity: sensor.nordpool
    name: Med nettleie
    stroke_width: 4
    opacity: 0.2
    color: 'rgb(2,93,136)'
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        return [new Date(entry.start), entry.value + 0.2711];
      });
    type: line
    show:
      legend_value: false
      in_header: true
      name_in_header: false
      extremas: true
    group_by:
      duration: 1h
      func: last
    extend_to_end: false
    float_precision: 2
  - entity: sensor.nordpool
    name: Med nettleie
    stroke_width: 4
    opacity: 0.2
    color: 'rgb(2,93,136)'
    data_generator: |
      return entity.attributes.raw_tomorrow.map((entry) => {
        return [new Date(entry.start), entry.value + 0.2711];
      });
    type: line
    show:
      legend_value: false
      in_header: false
      extremas: true
    group_by:
      duration: 1h
      func: last
    extend_to_end: false
    float_precision: 2
locale: nb
apex_config:
  plotOptions:
    bar:
      columnWidth: 90%
  tooltip:
    x:
      show: false
      format: 'HH:mm'
    marker:
      show: false
    followCursor: true
  legend:
    show: true
  dataLabels:
    enabled: false
  yaxis:
    tickAmount: 6
    forceNiceScale: true
    min: 0
```

**Comment by RomRider** [comment]
I'll have a look, that might be a bug

**Comment by TheArcturian** [comment]
Thanks! That would be great!

**Comment by AivarJ** [comment]
Is there a possibility to use extend_to_end function for limited time only. I would like to fill two day graph today last houer (23:00->00:00) (first picture).

![extend_to_end_false](https://user-images.githubusercontent.com/39031311/119140940-64b89a80-ba4d-11eb-812d-c0c00cf137fc.jpg)
![extend_to_end_true](https://user-images.githubusercontent.com/39031311/119140957-671af480-ba4d-11eb-9929-106c48945570.jpg)

**Comment by RomRider** [comment]
> Is there a possibility to use extend_to_end function for limited time only. I would like to fill two day graph today last houer (23:00->00:00) (first picture).

Since you're using data_generator, you can extend it yourself by adding an entry at the end of the array (in this example it adds the entry at "now" with the last known value):
```yaml
    data_generator: |
      let res = entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
      });
      res.push([new Date().getTime(), entity.attributes.raw_today[entity.attributes.raw_today.length() - 1].value];
      return res;
```

**Comment by AivarJ** [comment]
@RomRider 
Adding this line to my card configuration
> ```yaml
>     data_generator: |
>       let res = entity.attributes.raw_today.map((start, index) => {
>         return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
>       });
>       res.push([new Date().getTime(), entity.attributes.raw_today[entity.attributes.raw_today.length() - 1].value];
>       return res;
> ```
gives me this outcome.
![image](https://user-images.githubusercontent.com/39031311/119663792-5dbdcd80-be3b-11eb-9013-9c26952f8301.png)

Any more thoughts . I can use the start and end time of the last hour of the day, but don't know how to implement that to add that extra datapoint.
```
- start: '2021-05-26T23:00:00+03:00'
  end: '2021-05-27T00:00:00+03:00'
  value: 3.446
```

@TheArcturian 

Extremas working fine using this configurations. Last hour is still missing, using area type but if you change that to column type, then the last hour is also present.
```yaml
type: 'custom:apexcharts-card'
graph_span: 48h
span:
  start: day
  offset: +0H
header:
  title: Electricity Price
  show: true
  show_states: false
  colorize_states: true
hours_12: false
stacked: false
experimental:
  color_threshold: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: true
  float_precision: 3
  invert: false
  fill_raw: last
  color_threshold:
    - value: -1
      color: 1E90FF
    - value: 2.5
      color: 008000
    - value: 3.5
      color: DAA520
    - value: 4.5
      color: FF0000
now:
  show: true
  label: Now
  color: red
series:
  - entity: sensor.nordpool_kwh_ee_eur_3_10_02
    name: Current day
    opacity: 0.3
    extend_to_end: false
    offset: +0h
    type: area
    stroke_width: 0.5
    curve: stepline
    data_generator: |

      return entity.attributes.raw_today.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];

      });
  - entity: sensor.nordpool_kwh_ee_eur_3_10_02
    name: Tomorrow
    opacity: 0.3
    type: area
    stroke_width: 0.5
    curve: stepline
    data_generator: |
      return entity.attributes.raw_tomorrow.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];

      });
  - entity: sensor.nordpool_kwh_ee_eur_3_10_02
    name: Med nettleie
    opacity: 1
    extend_to_end: false
    offset: +0h
    type: line
    stroke_width: 2
    curve: smooth
    data_generator: |

      return entity.attributes.raw_today.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]+2.711];

      });
  - entity: sensor.nordpool_kwh_ee_eur_3_10_02
    name: Med nettleie
    opacity: 1
    extend_to_end: false
    offset: +0h
    type: line
    stroke_width: 2
    curve: smooth
    data_generator: |

      return entity.attributes.raw_tomorrow.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]+2.711];

      });
apex_config:
  chart:
    height: 400px
    animations:
      enabled: true
      easing: easeinout
      speed: 800
      animateGradually:
        enabled: true
        delay: 150
    zoom:
      enabled: true
      type: x
      autoScaleYaxis: true
      zoomedArea:
        fill:
          color: '#90CAF9'
          opacity: 0.4
        stroke:
          color: '#0D47A1'
          opacity: 0.4
          width: 1
  legend:
    show: false
    floating: true
    offsetY: 25
  yaxis:
    opposite: false
    reversed: false
    logarithmic: false
    decimalsInFloat: 2
    labels:
      show: true
    tooltip:
      enabled: true
    crosshairs:
      show: true
  xaxis:
    labels:
      show: true
      rotate: -45
      rotateAlways: true
    logarithmic: true
  stroke:
    show: true
    dashArray:
      - 0
      - 0
      - 2
      - 2
  plotOptions:
    candlestick:
      colors:
        upward: '#00B746'
        downward: '#EF403C'
      wick:
        useFillColor: true
  markers:
    size:
      - 2
      - 1
      - 0
      - 0
  grid:
    show: true
    strokeDashArray: 1
    position: front
    xaxis:
      lines:
        show: true

```
![image](https://user-images.githubusercontent.com/39031311/119670691-c60fad80-be41-11eb-98d5-0746b40d20b5.png)
