### ISSUE TITLE
color_threshold only works with type column

### ISSUE THREAD

**Issue by Bokbacken** [RomRider/apexcharts-card#149]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
In my graph I have values between 0 - 65 ish with thresholds @0, 20, 40, 50, 100 and 150
when using area or line all the colors are repeated in a rainbow mannor in every value, but when using columns it works as it should.
**Version of the card**
Version: 1.9.2 dev (tried with 1.8.0 also)

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
graph_span: 1week
experimental:
  color_threshold: true
series:
  - entity: sensor.aqi_baksidan_pms5003_pm10_2
    color: blue
    type: line
    stroke_width: 1
    color_threshold:
      - value: 0
        color: '#50f0e6'
      - value: 20
        color: '#50ccaa'
      - value: 40
        color: '#F0E641'
      - value: 50
        color: '#FF5050'
      - value: 100
        color: '#960032'
      - value: 150
        color: '#7D2181'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/69871284/116004799-b7e12e00-a604-11eb-844c-8756f29b555e.png)
type: line

![image](https://user-images.githubusercontent.com/69871284/116004821-db0bdd80-a604-11eb-82b4-e1c34398ef15.png)
type: area

![image](https://user-images.githubusercontent.com/69871284/116004875-0abae580-a605-11eb-83bf-65ceb7302c1c.png)
type: column (removed stroke_width)

**Expected behavior**

Should look similar to:
![image](https://user-images.githubusercontent.com/69871284/116004928-376efd00-a605-11eb-8d4b-a5f0f5c489c4.png)
from mini-graph-card that I try to replace with your card instead :)

**Desktop (please complete the following information):**
 - Browser chrome, 90.0.4430.85 64bit

**Additional context**
