### ISSUE TITLE
Brush selection jumps back to previous or default position

### ISSUE THREAD

**Issue by rousveiga** [RomRider/apexcharts-card#152]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**

When adjusting the selection in the brush, it sometimes jumps back to the default position or the previous one, either after the pointer has been released, or while I'm still dragging.

Same behavior on Chrome desktop and mobile, and also the Home Assistant app.

I also get this error in the console when I first click on the selection (both when the bug triggers and when it doesn't).

```
apexcharts-card.js:1 Unable to preventDefault inside passive event listener invocation.
```

**Version of the card**

Version: first seen on v1.8.2, remains in v1.9.0-dev.1

**To Reproduce**
This is the configuration I used:
```yaml
      - type: custom:apexcharts-card
        graph_span: 7d
        brush:
          selection_span: 24h
        header:
          show: true
          title: Consumo eléctrico
          show_states: true

        show:
          loading: false

        series:
          - entity: sensor.consumo_global
            name: Consumo eléctrico
            type: line
            float_precision: 0

            group_by:
              func: avg
              duration: 1h
            
            show:
              name_in_header: false
              header_color_threshold: true
              in_brush: true
              in_header: raw

            color_threshold:
              - value: 0
                color: "#64DD17"
              - value: 7000
                color: "#FFAB00"
              - value: 9000
                color: "#DD2C00"

        experimental:
          color_threshold: true
          brush: true
```

**Screenshots**
Here's a gif:
![bug-apexcharts](https://user-images.githubusercontent.com/11377258/116366644-cbf47d80-a806-11eb-8d1d-f643a7af1ab2.gif)

**Expected behavior**

I expected the selected area to:
- expand following the pointer while I'm dragging
- stay where I left it when I've released the pointer

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 90.0.4430.93

**Smartphone (please complete the following information):**
 - Device: Samsung S8+
 - OS: Android 9
 - Browser: Chrome
 - Version: 90.0.4430.82

**Additional context**

For me, it almost always triggers when I leave the right end of the selection at the starting position and expand the selection to the other end.
