### ISSUE TITLE
Tooltip multiple values legend 

### ISSUE THREAD

**Issue by Saentist** [RomRider/apexcharts-card#154]
Currently if I move mouse over chart, I see data from only one type, 
or in some cases dont see data of that what im pointed.
Is it possible to see all data in vertical line where mouse is pointed as on NVD3
ex:
https://nvd3.org/livecode/index.html#codemirrorNav

**Comment by RomRider** [comment]
That's happening when all the data points are aligned. If you use group_by with a func and the same duration for all the series, it's going to happen.

**Comment by Saentist** [comment]
Add some example. 
It's enough hard to configure, without assistance of menus.

**Comment by AivarJ** [comment]
Enable crosshairs should to what you want.

[My HA code](https://controlc.com/01e5fa64)

![Today_only](https://user-images.githubusercontent.com/39031311/119137632-ad6e5480-ba49-11eb-8360-2bee61649345.jpg)

**Comment by RomRider** [comment]
> Add some example.

Please?
```yaml
series:
  - entity: x.y
    group_by:
      func: avg
      duration: 1h
  - entity: x.z
    group_by:
      func: avg
      duration: 1h3
```

**Comment by Saentist** [comment]
> > Add some example.
> 
> Please?
> 
> ```yaml
> series:
>   - entity: x.y
>     group_by:
>       func: avg
>       duration: 1h
>   - entity: x.z
>     group_by:
>       func: avg
>       duration: 1h3
> ```

how to implement in this case

![image](https://user-images.githubusercontent.com/16975883/119181575-719fb300-ba7a-11eb-9e58-5c992eb651da.png)


```yaml
type: 'custom:apexcharts-card'
graph_span: 32d
header:
  title: Daily consumption /31 days/
  show: true
  show_states: true
  colorize_states: true
apex_config:
  legend:
    show: false
span:
  end: day
now:
  show: true
all_series_config:
  stroke_width: 1
  show:
    legend_value: false
series:
  - entity: sensor.total_ele
    name: LG
    type: column
    transform: return x / 1;
    unit: kWh
    group_by:
      func: diff
      duration: 1440min
  - entity: sensor.openweathermap_temperature
    name: Temp
    type: line
    transform: return x / 1;
    unit: C
    stroke_width: 5
    group_by:
      func: median
      duration: 1440min

```

**Comment by AivarJ** [comment]
Did you mean something like this.

![Daily30](https://user-images.githubusercontent.com/39031311/119218773-c9760280-baea-11eb-87eb-7f06fbddffc0.jpg)

[Code](https://controlc.com/7cdfdfb2)

**Comment by Saentist** [comment]
> Did you mean something like this.
> 

No /see examples in link in first post/

I want to see values of all vertical crossed values in graph.

![image](https://user-images.githubusercontent.com/16975883/119219954-a9494200-baf0-11eb-930e-f0f82324ecc2.png)

**Comment by AivarJ** [comment]
Ok, got the graph to work the way you wanted by replacing the series type column with the area  type. 
![stacked](https://user-images.githubusercontent.com/39031311/119236998-2f8e7400-bb43-11eb-80a9-3c45ed4e5a19.jpg)

**Comment by Saentist** [comment]
Any explenation, how need to be done?

**Comment by AivarJ** [comment]
[My code. Modified a littel, to make the area type chart look more like a bar chart.](https://controlc.com/29c8b236)

**Comment by Saentist** [comment]
Yes this works. 


Again question.
How to put in right side values scale with semi-IQ ability to dinamic resizing 

example:
if values are in range from X to Y
but values in time range are in range X+20 to X+40
as result scale to be from X+20-10% to X+40+10% 

p.s.
If needed can put this as separate issue.

**Comment by AivarJ** [comment]
Something like this?
![2bar](https://user-images.githubusercontent.com/39031311/119716875-4b10bc00-be6e-11eb-8090-9ee8f746a49b.jpg)


 ```yaml
type: 'custom:apexcharts-card'

apex_config:
  
  xaxis:
    labels:
      show: true
      rotate: -45
      rotateAlways: true
    type: datetime
  yaxis:
    - title:
        text: Energiakulu
      axisTicks:
        show: true
        color: yellow
      min: 0
      max: 3
      axisBorder:
        show: false
        color: '#008FFB'
      decimalsInFloat: 1
      opposite: false
      labels:
        show: true
        style:
          colors: Yellow
      tooltip:
        enabled: true
    - title:
        text: Tempertuur
      axisTicks:
        show: true
        color: '#008FFB'
      axisBorder:
        show: true
        color: '#008FFB'
      decimalsInFloat: 0
      opposite: true
      labels:
        show: true
        style:
          colors: '#008FFB'
      tooltip:
        enabled: true


 ```
