### ISSUE TITLE
Chart never loads due to large history

### ISSUE THREAD

**Issue by rousveiga** [RomRider/apexcharts-card#156]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
The graph never loads or displays ("Loading..." string on top of both empty graph and brush), due to a massive amount of history data.

This is a sensor that updates status every second, so I imagine this error is caused by the massive amount of data the card needs to process in order to draw the graph with the weekly history. The error disappears (or appears less often) if I set `graph_span` to less days, or if the sensor stops reporting for a while (for example, I had some network issues last week, and my sensors went unavailable - which meant less history data, which made the graph display just fine).

I understand if this is something that can't be improved, but I'd be very grateful if there was a way to prevent this from happening (maybe filter the number of points that go into the `group_by` calculations?).

The specific errors I get are:

On v1.9.0-dev.1, the console displays a 504 error after a while, and after that, this error:

```
The FetchEvent for "http://192.168.0.139:8123/api/history/period/2021-05-14T08:47:45.306Z?filter_entity_id=sensor.m5co2_laboratorio_co2&end_time=2021-05-14T08:48:50.438Z&skip_initial_state&significant_changes_only=0" resulted in a network error response: the promise was resolved with an error response object.
```

I've also seen a "infinite recursivity"-type error on 1.8.2 with the same behavior, but I cannot replicate it right now. I will update this post as soon as I get it again.

I was unsure whether to submit this as a bug report or a feature request, so I apologize if this is the wrong place.

Thanks in advance!

**Version of the card**
Version: Seen on both 1.9.0-dev.1 and 1.8.3. 

**To Reproduce**
This is the configuration I used:

```yaml
  - type: custom:apexcharts-card-dev
    graph_span: 7d
    update_interval: 1min
    brush:
      selection_span: 24h
    header:
      show: true
      title: Consumo eléctrico
      show_states: true

    show:
      loading: true

    series:

      - entity: sensor.consumo_global
        name: Máximo
        type: line
        color: red
        stroke_width: 2
        opacity: 0.3
        float_precision: 0

        group_by: 
          func: max
          duration: 1h

        show:
          name_in_header: false
          in_brush: false
          in_header: false
          in_chart: true

      - entity: sensor.consumo_global
        name: Mínimo
        type: line
        color: blue
        stroke_width: 2
        opacity: 0.3
        float_precision: 0

        group_by: 
          func: min
          duration: 1h

        show:
          name_in_header: false
          in_brush: false
          in_header: false
          in_chart: true

      - entity: sensor.consumo_global
        name: Media
        type: line
        float_precision: 0

        group_by:
          func: avg
          duration: 1h
        
        show:
          name_in_header: false
          #extremas: true # quedan mal con el brush
          header_color_threshold: true
          in_brush: true
          in_header: raw

        color_threshold:
          - value: 0
            color: "#64DD17"
          - value: 7000
            color: "#FFAB00"
          - value: 9000
            color: "#DD2C00"

    experimental:
      color_threshold: true
      brush: true
```

**Screenshots**

![image](https://user-images.githubusercontent.com/11377258/118245905-9c4da280-b4a1-11eb-882a-a02e94da9706.png)

**Expected behavior**

I don't really have an answer for this - as I said before, I understand if this is something that can't be done. I'm just looking for a way to reduce the amount of data the graph receives without losing the immediate value from my sensor.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 90.0.4430.212

**Smartphone (please complete the following information):**
 - Device: Samsung S8+
 - OS: Android 9
 - Browser: Chrome 
 - Version: 90.0.4430.210

**Additional context**
