### ISSUE TITLE
Second y-axis stops auto-scale from working (y-axis scale always starts with 0)

### ISSUE THREAD

**Issue by chah90** [RomRider/apexcharts-card#158]
**Checklist**
- [x] I updated the card to the latest version available => tested with 1.9.0-dev.1
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
As soon as I add a second y-axis, both y-axis are starting with 0. I already tested 1.9.0-dev.1 and specified a min function (see my configuration) but this doesn't work neither.

**Version of the card**
Version: 1.8.2 and 1.9.0-dev.1

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
apex_config:
  yaxis:
    - title:
        text: Axis 1
      min: |
        EVAL:function(min) {
          return min;
        }
    - title:
        text: Axis 2
      opposite: true
      min: |
        EVAL:function(min) {
          return min;
        }
series:
  - entity: sensor.Schlafzimmer_Temperatur
    name: Temperature
  - entity: sensor.Schlafzimmer_Humidity
    name: Humidity
```

**Screenshots**
Appearance when using one y-axis (just removed the second axis from the configuration above):
<img width="441" alt="one-y-axis" src="https://user-images.githubusercontent.com/5701413/119137126-c0305b80-ba40-11eb-901d-2e235095e3b1.png">
The axis starts at ~ 19.

When using the configuration from above with two y-axis, both y-axis starts at 0:
<img width="402" alt="two-y-axis" src="https://user-images.githubusercontent.com/5701413/119137239-e1914780-ba40-11eb-828c-23e8080f637c.png">

**Expected behavior**
The min values of the y-axis are dynamically identified (either per default or per function as above) just as it is determined if only one y-axis is defined.

**Desktop (please complete the following information):**
 - Firefox 88.0.1 
 - Safari 14.1
 - macOS 11.3.1

**Smartphone (please complete the following information):**
 - Device: Phone 12 Pro
 - OS: iOS 14.5.1
 - stock Safari browser

**Additional context**
-

**Comment by RomRider** [comment]
That's the behavior of the library I use, not much I can do about it. You need to hard-code the values if you want something different unfortunately :(

**Comment by chah90** [comment]
Too bad 😞 I managed to get the desired behavior in a fiddle (although not with the default config but with defining the min function as above). That’s why I hoped that this is a bug in the card library. 

Would the fiddle help or are you sure that this is a library issue?

**Comment by RomRider** [comment]
Sure, share it, I'll have a look

**Comment by chah90** [comment]
I couldn't manage this now, neither 😄 at least with plain javascript and the latest apex charts version.
But previously I just edited an existing example based on Angular and there it's working:
https://codesandbox.io/s/apx-line-data-labels-forked-41yht?file=/src/app/app.component.ts

It uses apexcharts in an older version (3.15.0) and updating it to the version used in the card I can reproduce the bug. So it's a library issue as you already stated.

**Comment by RomRider** [comment]
I think I can hack something to make it work, but it's going to be super ugly... I'll try and report back.

**Comment by chah90** [comment]
This would be awesome 😊

**Comment by RomRider** [comment]
👀 https://github.com/RomRider/apexcharts-card/pull/160

**Comment by chah90** [comment]
I tried the new version, but the axis still start at 0. Did I miss an important line in the configuration?
<img width="341" alt="Bildschirmfoto 2021-05-24 um 17 16 17" src="https://user-images.githubusercontent.com/5701413/119368838-caa65b80-bcb3-11eb-81f8-19d4ce2d46e0.png">

```
type: 'custom:apexcharts-card'
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.Badezimmer_Temperatur
    name: Temperature
    yaxis_id: temperature
  - entity: sensor.Badezimmer_Humidity
    name: Humidity
    yaxis_id: humidity
yaxis:
  - id: temperature
  - id: humidity
    opposite: true
```
