### ISSUE TITLE
Graph disappears when applying a formatter function to legend (only in HA android app).

### ISSUE THREAD

**Issue by mathias-jakobsen** [RomRider/apexcharts-card#162]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
In the Home Assistant android app, the graph will disappear when a formatting function is applied to the legend via the apex_config configuration parameter.

**Version of the card**
Version: 1.9.0

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
apex_config:
  legend:
    formatter: "EVAL:function(seriesName) { return seriesName; }"
brush:
  selection_span: 1d
experimental:
  brush: true
graph_span: 5d
series:
  - entity: {{ _global.mobile.weather.wind_strength_entity }}
    group_by:
      func: avg
      duration: 1h
    name: Wind strength
    show:
      in_brush: true
      in_chart: true
      in_header: true
    stroke_width: 2     
    type: line
  - entity: {{ _global.mobile.weather.wind_gust_strength_entity }}
    group_by:
      func: avg
      duration: 1h
    name: Gust strength
    show:
      in_brush: true
      in_chart: true
      in_header: true
    stroke_width: 2
    type: line
```

**Screenshots**
Working in the browser:
![browser](https://user-images.githubusercontent.com/55285073/119558055-3dd9cb80-bda1-11eb-9660-cb745f4bda2b.jpg)

Not working in the Home Assistant android app:
![android app](https://user-images.githubusercontent.com/55285073/119558049-3d413500-bda1-11eb-9f0d-0a979e7e4a30.jpg)

**Expected behavior**
The graph should be displayed in the Home Assistant android app.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: One UI 3.1
