### ISSUE TITLE
Legend not shown for 1 series charts

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#163]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Legend is shown only when there are 2 or more series in the chart. If there is only 1 series, the leged is not displayed.

**Version of the card**
Version: 1.9.0

**To Reproduce**
This is the configuration I used:

Refer to screenshot# 1
```yaml
type: 'custom:apexcharts-card'
graph_span: 14d
y_axis_precision: 0
all_series_config:
  stroke_width: 3
  fill_raw: last
  show:
    legend_value: true
series:
  - entity: sensor.home_assistant_v2_db
```

Refer to screenshot# 2
```
type: 'custom:apexcharts-card'
graph_span: 14d
y_axis_precision: 0
all_series_config:
  stroke_width: 3
  fill_raw: last
  show:
    legend_value: true
series:
  - entity: sensor.home_assistant_v2_db
  - entity: input_number.daytime

```

**Screenshots**

![image](https://user-images.githubusercontent.com/54566217/119747263-b0e45e80-bed5-11eb-8a97-68c7d4d6dae9.png)

![image](https://user-images.githubusercontent.com/54566217/119747547-4f70bf80-bed6-11eb-82b8-39a69a2846bb.png)

**Expected behavior**
Legend is displayed irrespective of how many series are in the chart

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 90.0.4430.212 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
That's not a bug, it's the behavior of the library I use. 

Add:
```yaml
apex_config:
  legend:
    showForSingleSeries: true
```
