### ISSUE TITLE
y-axis float precision is huge when y-axis defined

### ISSUE THREAD

**Issue by ianschorr** [RomRider/apexcharts-card#164]
This may be a known issue, but not only is float_precision not usable when yaxis is defined, but it seems to set to 15 digits when enabled - which makes the y-axis labels overwhelm the chart.

Even if float_precision support isn't added, it'd be good to set the default precision to something more reasonable, like the default of "1"

**Version of the card**
Version: 1.9.0

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
series:
  - entity: sensor.upstairs_running
    color: red
    group_by:
      func: max
      duration: 30m
    yaxis_id: left
  - entity: sensor.openweathermap_temperature
    color: yellow
    group_by:
      func: avg
      duration: 30m
    yaxis_id: right
graph_span: 14d
yaxis:
  - id: left
    apex_config:
      tickAmount: 4
  - id: right
    opposite: true
    apex_config:
      tickAmount: 4


```

**Screenshots**
![image](https://user-images.githubusercontent.com/68305857/119871847-dcc10d80-bef0-11eb-9089-fcf5add1045a.png)
