### ISSUE TITLE
Stacked not working as expected with multiple axis

### ISSUE THREAD

**Issue by wormiedk** [RomRider/apexcharts-card#166]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Stacked: true not working as expected with multiple axis.
I have a view which shows total docker memory used on one axis and then the idea was to have the memory usage of different docker containers on the other axis stacked. However when I try to stack the values they are not stacked.
Example without stacked 
![Screenshot 2021-05-30 at 07 53 03](https://user-images.githubusercontent.com/4417857/120093754-93ed9c80-c11c-11eb-85ff-8d3ded6ac5bc.png)

Example of same data after stacked: true
![Screenshot 2021-05-30 at 07 53 12](https://user-images.githubusercontent.com/4417857/120093760-9bad4100-c11c-11eb-9b3d-0306aba78e5b.png)

**Version of the card**
Version: 1.9.0

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
update_interval: 15m
stacked: true
header:
  show: true
span:
  end: hour
yaxis:
  - id: left
    apex_config:
      decimalsInFloat: 1
      forceNiceScale: true
  - id: right
    apex_config:
      decimalsInFloat: 1
      forceNiceScale: true
      min: 0
    opposite: true
all_series_config:
  fill_raw: last
  type: column
  stroke_width: 1
  group_by:
    func: avg
    duration: 1h
  show:
    datalabels: false
    legend_value: false
series:
  - entity: sensor.docker_memory
    name: Docker
    type: line
    stroke_width: 1
    color: black
    yaxis_id: right
  - entity: sensor.docker_homeassistant_memory
    name: HASS
    yaxis_id: left
  - entity: sensor.docker_mc_java1_memory
    name: Java 1
    yaxis_id: left
  - entity: sensor.docker_mc_java2_memory
    name: Java 2
    yaxis_id: left
  - entity: sensor.docker_mc_bedrock1_memory
    name: Bedrock 1
    yaxis_id: left
  - entity: sensor.docker_calibre_memory
    name: Calibre
    yaxis_id: left

```

**Expected behavior**
Columns should be stacked

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version: 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)
