### ISSUE TITLE
Min/Max cuts off when using multiple y-axis

### ISSUE THREAD

**Issue by Fusseldieb** [RomRider/apexcharts-card#172]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When using multiple y-axis the min/max cuts one of them off

**Version of the card**
Version: APEXCHARTS-CARD  v1.9.0 

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
update_interval: 1min
graph_span: 24h
header:
  show: true
  title: Temp. piscina
  standard_format: true
  show_states: true
experimental:
  color_threshold: true
apex_config:
  xaxis:
    tooltip:
      enabled: false
yaxis:
  - id: first
    apex_config:
      tickAmount: 4
      decimalsInFloat: 1
  - id: second
    opposite: true
    apex_config:
      tickAmount: 1
      decimalsInFloat: 0
series:
  - entity: sensor.temperatura_piscina
    fill_raw: last
    type: line
    stroke_width: 4
    name: Hoje
    color_threshold:
      - value: 20
        color: green
      - value: 28
        color: yellow
      - value: 35
        color: red
    group_by:
      duration: 15min
      func: avg
    show:
      extremas: true
    yaxis_id: first
  - entity: sensor.temperatura_piscina
    fill_raw: last
    offset: '-1d'
    type: line
    stroke_width: 4
    name: Ontem
    group_by:
      duration: 15min
      func: avg
    color: '#888888'
    show:
      extremas: true
    yaxis_id: first
    opacity: 0.4
  - entity: switch.sonoff_4ch_relay_1
    transform: 'return x === ''on'' ? 1 : 0;'
    yaxis_id: second
    curve: stepline
    opacity: 0.3
    stroke_width: 0
    color: '#888888'
    show:
      in_header: false
      name_in_header: false
      legend_value: false
    type: area

```

**Screenshots**
![image](https://user-images.githubusercontent.com/4715129/122987943-920fa580-d377-11eb-8af9-369ebffb38cb.png)

**Expected behavior**
Not cut off?

**Desktop (please complete the following information):**
 - Google Chrome | 91.0.4472.106 (Versão oficial) 64 bits (cohort: Stable)

**Additional context**
-
