### ISSUE TITLE
Soft Min/Max values not working as expected

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#173]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I have been playing around with the code below.

```
type: custom:apexcharts-card
yaxis:
  - id: primary
    min: 16
    max: 23
    apex_config:
      title:
        text: Temperature (°C)
      decimalsInFloat: 0
      forceNiceScale: true
all_series_config:
  stroke_width: 2.5
  extend_to_end: false
  show:
    legend_value: true
span:
  start: day
  offset: +7h
graph_span: 8h
color_list:
  - firebrick
series:
  - entity: sensor.heater_target_temp
    name: Target
    transform: 'return x === "8" ? 0 : x;'
    curve: stepline
    yaxis_id: primary
```
Screenshot for the code above.

![image](https://user-images.githubusercontent.com/54566217/123375536-3ee26080-d5cc-11eb-9f9d-c4e81d565ca6.png)

There are different issues I have come across - 

1. I changed the `max` parameter from 23 to 20. The y-axis is now showing the precision as 1.

```
type: custom:apexcharts-card
yaxis:
  - id: primary
    min: 16
    max: 20
    apex_config:
      title:
        text: Temperature (°C)
      decimalsInFloat: 0
      forceNiceScale: true
all_series_config:
  stroke_width: 2.5
  extend_to_end: false
  show:
    legend_value: true
span:
  start: day
  offset: +7h
graph_span: 8h
color_list:
  - firebrick
series:
  - entity: sensor.heater_target_temp
    name: Target
    transform: 'return x === "8" ? 0 : x;'
    curve: stepline
    yaxis_id: primary
```
![image](https://user-images.githubusercontent.com/54566217/123375689-8e289100-d5cc-11eb-939a-a2a82ece9864.png)

2. I changed the `max` from 20 to ~20. The min value for the axis gets disregarded.

```
type: custom:apexcharts-card
yaxis:
  - id: primary
    min: 16
    max: ~20
    apex_config:
      title:
        text: Temperature (°C)
      decimalsInFloat: 0
      forceNiceScale: true
all_series_config:
  stroke_width: 2.5
  extend_to_end: false
  show:
    legend_value: true
span:
  start: day
  offset: +7h
graph_span: 8h
color_list:
  - firebrick
series:
  - entity: sensor.heater_target_temp
    name: Target
    transform: 'return x === "8" ? 0 : x;'
    curve: stepline
    yaxis_id: primary
```
![image](https://user-images.githubusercontent.com/54566217/123376178-6259db00-d5cd-11eb-9740-62b88b37e58e.png)

3. I changed the `min` from 16 to ~16. The page crashes.

```
type: custom:apexcharts-card
yaxis:
  - id: primary
    min: ~16
    max: 23
    apex_config:
      title:
        text: Temperature (°C)
      decimalsInFloat: 0
      forceNiceScale: true
y_axis_precision: 0
all_series_config:
  stroke_width: 2.5
  extend_to_end: false
  show:
    legend_value: true
span:
  start: day
  offset: +7h
graph_span: 8h
color_list:
  - firebrick
series:
  - entity: sensor.heater_target_temp
    name: Target
    transform: 'return x === "8" ? 0 : x;'
    curve: stepline
    yaxis_id: primary

```
![image](https://user-images.githubusercontent.com/54566217/123376307-9f25d200-d5cd-11eb-9a06-c8691295547b.png)

**Version of the card**
Version: 1.9.0

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] Version 91.0.4472.114

**Smartphone (please complete the following information):**

**Additional context**
