### ISSUE TITLE
radialBar calculated percent is not rounded when using min/max

### ISSUE THREAD

**Issue by bkupidura** [RomRider/apexcharts-card#174]
**Checklist**
- [+] I updated the card to the latest version available
- [+] I cleared the cache of my browser
- [+] I verified that I'm really running the lastest version in my browser console
- [+] I checked if there is another issue opened with the same problem

**Describe the bug**
When using radialBar with min/max, calculated value is not rounder. Please check screenshot

**Version of the card**
Version: v1.9.0

**To Reproduce**
This is the configuration I used:
```yaml
      - type: "custom:apexcharts-card"
        apex_config:
          chart:
            height: 250px
        chart_type: radialBar
        experimental:
          color_threshold: true
        header:
          show: false
        series:
          - entity: sensor.dypsis_playroom_moisture
            name: Woda
            show:
              legend_value: true
            color_threshold:
              - value: 0
                color: orange
              - value: 20
                color: green
              - value: 60
                color: red
          - entity: sensor.dypsis_playroom_conductivity
            name: Nawóz
            show:
              legend_value: true
            min: 0
            max: 2500
            color_threshold:
              - value: 0
                color: orange
              - value: 14
                color: green
              - value: 80
                color: red
```

**Screenshots**
<img width="253" alt="Screenshot 2021-06-26 at 20 30 56" src="https://user-images.githubusercontent.com/4814684/123522526-0c189500-d6be-11eb-8fb8-ee569242cb56.png">

**Expected behavior**
When hover over data, i want to see rounded value (as visible in series).

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 89.0.1 (64-bit)
