### ISSUE TITLE
Add the ability to display current state with formatting in header

### ISSUE THREAD

**Issue by sylphaenos** [RomRider/apexcharts-card#176]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I'm trying to replicate `mini-graph-card` but can't find a nice way to show the current state in the header while using `func: avg` (for smoother graphs).

`in_header: raw` is close, but removes formatting like `float_precision: 0` which clutters up the graphs.

**Describe the solution you'd like**
Ideally an option like `in_header: now`–just like `raw` but with formatting applied.

**Describe alternatives you've considered**
- I've tried using `in_header: raw`, but it removes important formatting like `float_precision: 0`.
- I've tried using `func: last` which fixes the header formatting, but makes the graph less useful and less smooth.

**Additional context**

<details>
<summary>YAML template</summary>

```yaml
apexcharts_card_templates:
  mini:
    graph_span: 24h
    y_axis_precision: 0
    apex_config:
      chart:
        height: 135%
      grid:
        show: false
        padding:
          bottom: -14
          left: 0
          right: 0
      legend:
        show: false
      stroke:
        width: 3
      tooltip:
        fixed:
          enabled: true
          position: topRight
          offsetY: -30
        x:
          format: h:mmtt
      xaxis:
        tickPlacement: 'on'
        axisTicks:
          show: false
          color: '#444'
        axisBorder:
          show: false
          color: '#444'
        labels:
          show: false
          format: htt
      yaxis:
        show: false
    header:
      show: true
      show_states: true
    all_series_config:
      curve: smooth
      fill_raw: last
      float_precision: 0
      opacity: 0.1
      show:
        in_header: raw
      type: area
      group_by:
        duration: 2h
        func: avg
    card_mod:
      style: |
        ha-card {
            {% if states('entity_id') | float > 80 %}
            background-color: rgba(255, 10, 10, 0.08);
            {% elif states('entity_id') | float < 15 %}
            background-color: rgba(30, 30, 255, 0.04);
            {% endif %}
        }
        #header__title {
            margin-top: 5px;
        }
        #state__name {
            font-size: 1em !important;
            font-weight: 400 !important;
            margin-top: -18px;
            opacity: 0.6;
        }
        #state__value {
            font-size: 1.25em;
            margin: 25px 0 20px;
        }
        #state {
            font-weight: 300 !important;
        }
        #uom {
            opacity: 0.6 !important;
        }
```
</details>

In this screenshot, ideally the header numbers would be rounded to 78, 71, 79.

<img width="501" alt="Screen Shot 2021-07-05 at 4 25 29 PM" src="https://user-images.githubusercontent.com/1770409/124521673-ee46e080-dddf-11eb-9848-8d408c9ac333.png">
