### ISSUE TITLE
Apexchart breaks linecharts when data has NULL values

### ISSUE THREAD

**Issue by Fusseldieb** [RomRider/apexcharts-card#177]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Apexchart breaks linecharts sometimes

**Version of the card**
Version: v1.10.0-dev.2

**To Reproduce**
When a data with null or undefined value are used

**Screenshots**
![image](https://user-images.githubusercontent.com/4715129/124812397-ec913000-df39-11eb-964a-ff1e9d05f9c8.png)

**Expected behavior**
I have read somewhere in an issue that this the issue of ApexChart itself, however, maybe something can be done on this side to help mitigate this issue. Maybe completely ignore those points, instead of reading them.

**Desktop (please complete the following information):**
 - Chrome x64
 - Version 91.0.4472.124

**Additional context**
\-

**Comment by RomRider** [comment]
You can use `fill_raw: last` to fix this already :)

**Comment by Fusseldieb** [comment]
> You can use `fill_raw: last` to fix this already :)

I'm alewady using that, doesn't seem to fix it. Sometimes it is entire and sometimes it breaks.

**Comment by RomRider** [comment]
Please share your config :)

**Comment by Fusseldieb** [comment]
Oh, of course! ahaha

```
type: custom:apexcharts-card
update_interval: 1min
graph_span: 24h
header:
  show: true
  title: Temp. piscina
  standard_format: true
  show_states: true
experimental:
  color_threshold: true
apex_config:
  xaxis:
    tooltip:
      enabled: false
yaxis:
  - id: first
    apex_config:
      tickAmount: 4
      decimalsInFloat: 1
  - id: second
    opposite: true
    apex_config:
      labels:
        show: false
      tickAmount: 1
      decimalsInFloat: 0
series:
  - entity: sensor.temperatura_piscina
    fill_raw: last
    type: line
    stroke_width: 4
    name: Hoje
    color_threshold:
      - value: 24
        color: blue
      - value: 27
        color: yellow
      - value: 35
        color: red
    group_by:
      duration: 15min
      func: avg
    show:
      extremas: true
    yaxis_id: first
  - entity: sensor.temperatura_piscina
    fill_raw: last
    offset: '-1d'
    type: line
    stroke_width: 4
    name: Ontem
    group_by:
      duration: 15min
      func: avg
    color: '#888888'
    show:
      extremas: true
    yaxis_id: first
    opacity: 0.4
  - entity: switch.sonoff_4ch_relay_1
    transform: 'return x === ''on'' ? 1 : 0;'
    yaxis_id: second
    curve: stepline
    opacity: 0.3
    stroke_width: 0
    color: '#888888'
    show:
      in_header: false
      name_in_header: false
      legend_value: false
    type: area
```
