### ISSUE TITLE
24h graph span with 1d group by lists multiple days along X-Axis

### ISSUE THREAD

**Issue by magnetic157** [RomRider/apexcharts-card#179]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
With the below configuration I believe it should only have the current date with two bars that auto-fill the width, but instead the x-axis shows multiple days in the future and the bars are not even under the correct date (**today is 7/8 and they display under 7/10**). 

The X-Axis has 7/9 - 7/12 displayed.

**Code:**
```
type: custom:apexcharts-card
update_interval: 15m
graph_span: 24h
span:
  start: day
apex_config:
  yaxis:
    show: true
    decimalsInFloat: 0
    tickAmount: 12
    min: 0
    max: 24
series:
  - color: purple
    entity: sensor.office_lights
    name: Office
    type: column
    group_by:
      func: max
      duration: 1d
  - color: green
    entity: sensor.lr_lights
    name: living room
    type: column
    group_by:
      func: max
      duration: 1d
```

**configuration.yaml**
```
sensor:
  - platform: history_stats
    name: LR_Lights
    entity_id: light.living_room_recessed_lights
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Office_Lights
    entity_id: light.office_recessed_lights
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

```

**Version of the card**
Version: 1.9.0

**Screenshots**
![image](https://user-images.githubusercontent.com/78054864/124927494-b224a300-dfcc-11eb-99a0-40ba39c2b529.png)

**Expected behavior**
I'm trying to have the total time on per day per entity refreshed every 15 minutes.

The X-Axis should be labeled with only the current date and contain a bar for each entity I add.  Since it's grouped by the single date (midnight - 23:59), this particular example should have two large bars that fill the width of the card.

**Desktop (please complete the following information):**
 - Browser Safari
 - Version: MacOS Big Sur
