### ISSUE TITLE
graph_span logic at entity level to compare data over period

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#18]
Question/enhancement :

It seems like graph_span is at chart level only, would it possible to enable something similar at series/entity level? The specific use case I am looking at would be to graph the same entity over 2 or more periods. Compare last 24 hours to prior 24 hours for example.

Thanks! Keep up the great work!

**Comment by RomRider** [comment]
What you want is probably an offset but at the serie level.

I can probably hack something to make it possible but a timeline is a timeline so it naturally displays data based on the time of that specific data.
For eg: the Y axis information would not represent the correct time for that offsetted serie, nor would the tooltip

**Comment by deepcoder** [comment]
Yes at series level.

If I put 2 or more series/entities on a chart, all the tooltips and y-axis get figured out so as to display correct for all the series on the chart. So if you could 'fool' it to think that each series was just like the way it work now but under the covers it is just the 1st series but say 24 hours ago, and the 3rd series is the first series but 48 hours ago.

I can certainty stack three charts on vertically and compare. However, for example in temperature entities. Overlaying the temp from 1 month ago to what it is this month is a nice graph. Same with energy use.

Bar charts are kind of the classic example, but line graphs work as well:

<img width="584" alt="bar-compare" src="https://user-images.githubusercontent.com/1409547/106219671-bbdceb80-618e-11eb-8ad3-c4db5e67d4aa.png">


If what I am saying is too much of a hack, drop it.

**Comment by RomRider** [comment]
I can probably make it work, but not for months. Months sucks, it's not a fixed timerange :( You'd have to offset by `30days` which is not perfect but close enough.
But still X-axis info (in the tooltip) would be wrong for the offsetted series, that could be confusing for users.

Let me think about it.

**Comment by deepcoder** [comment]
I should have hacked my example better. I see you point on calendars. 
being able to do -24h -48h
-1d ? -2d? -3d?
would be more than useful.
But I can see how it can out of control....

**Comment by deepcoder** [comment]
Not sure if this would help:
Under span:
add 
  split: 4 (or whatever)

so the listed series would replotted 'split' times
might have to restrict 'group_by' to not work if split selected

I don't think it would reduce the functionality that I am thinking about. Ideally you could still specify multiple 'series' and they would all get split. But even if the limit was a single series, still useful.

**Comment by RomRider** [comment]
I've put an example for what you want to achieve here:
https://github.com/RomRider/apexcharts-card/tree/dev#compare-data-from-today-with-yesterday

**Comment by deepcoder** [comment]
Dude! You are rocking it!!! You are delivering some exceptionally great code. Thank YOU!

Giving it some initial tests now.

```
  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.backyard_atc_mi_temperature
      type: line
    - entity: sensor.backyard_atc_mi_temperature
      offset: -1d
      type: line
    - entity: sensor.backyard_atc_mi_temperature
      offset: -2d
      type: line
    update_interval: 60s
    graph_span: 1d
    span:
      start: day
    cache: true
    apex_config:
      stroke:
        show: true
        width: 1
      title:
        text: 'Backyard Temperature Today, -1 Day, -2 Days'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450

```

<img width="1443" alt="multi-series-test-01" src="https://user-images.githubusercontent.com/1409547/106324209-9f43c080-622d-11eb-860f-620b5627b75d.png">

**Comment by RomRider** [comment]
Glad it suits your need :)

**Comment by deepcoder** [comment]
Group_by : I'm not getting this one to work, any ideas what I am doing wrong?

Trying to plot sum by hour for today 24 hours and yesterday 24 hours for following sensor.
The two individual sums work as shown at bottom. But when I try to combine, the second series (-1d) does not show.
Raw data attached.

```
sensor.home_instantaneous_demand
timestamp: 20210129133634
instantaneous_demand: 731
unit_of_measurement: Watt
friendly_name: Home Instantaneous Demand
```

Does not plot second series, see first picture:

```
  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      type: column
      group_by:
        func: sum
        duration: 1h
        fill: 'zero'
    - entity: sensor.home_instantaneous_demand
      offset: -1d
      type: column
      group_by:
        func: sum
        duration: 1h
        fill: 'zero'
    update_interval: 60s
    graph_span: 1d
    span:
      start: day
    cache: true
    apex_config:
      chart:
        height: 450
      title:
        text: 'SCE Watts Today, Yesterday'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 1000000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0

```


These two plot fine:

```
title: T11 Multiple Bar History
panel: true
cards:
- type: vertical-stack
# - type: grid
  # columns: 1
  cards:
  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      # color: blue
      type: column
      group_by:
        func: sum
        duration: 1h
        fill: 'zero'
    update_interval: 30s
    graph_span: 24h
    span:
      start: day
      # offset: -1d
    cache: true
    apex_config:
      title:
        text: 'SCE Watts per Hour Today 24h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 1000000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0

  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      # color: blue
      type: column
      group_by:
        func: sum
        duration: 1h
        fill: 'zero'
    update_interval: 30s
    graph_span: 24h
    span:
      start: day
      offset: -1d
    cache: true
    apex_config:
      title:
        text: 'SCE Watts per Hour Yesterday 24h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 1000000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0

```
<img width="1448" alt="multiple-sum-not-working" src="https://user-images.githubusercontent.com/1409547/106330710-8db3e600-6238-11eb-8c18-c5f734ad1538.png">


<img width="1450" alt="indie-sum-works" src="https://user-images.githubusercontent.com/1409547/106330664-78d75280-6238-11eb-872a-beb70fcd6aca.png">



[home_instantaneous_demand-2-days.csv.zip](https://github.com/RomRider/apexcharts-card/files/5896459/home_instantaneous_demand-2-days.csv.zip)

**Comment by deepcoder** [comment]
Adding to prior comment. Data plots without 'grooup_by':

```
  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      type: line
    - entity: sensor.home_instantaneous_demand
      offset: -1d
      type: line
    update_interval: 60s
    graph_span: 1d
    span:
      start: day

```
<img width="1438" alt="no-grouping" src="https://user-images.githubusercontent.com/1409547/106331539-f8b1ec80-6239-11eb-97e2-3bd51d202720.png">

**Comment by RomRider** [comment]
Interesting, let me have a look. I think I introduced a bug. All those timestamps makes my brain hurt haha 😂

**Comment by deepcoder** [comment]
You and my Postgresql server ;-)

I realized I was doing 'sum', but should have been doing 'avg'. But even if I change this, the 2nd series (-1d) does not plot.

**Comment by RomRider** [comment]
Would you mind trying that new version please?

**Comment by deepcoder** [comment]
Yes, I am getting correct data for both periods, yeah! Thanks!
I am getting some phantom data for bins beyond the current time. Is there something I need to configure different to stop it a current time? I will continue to test.

Yaml, picture and data below, thank you for your work! :


```
# test 11
title: T11 Multiple Bar History
panel: true
cards:
- type: vertical-stack
# - type: grid
  # columns: 1
  cards:

  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      type: column
      group_by:
        func: avg
        duration: 1h
    - entity: sensor.home_instantaneous_demand
      offset: -1d
      type: column
      group_by:
        func: avg
        duration: 1h
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
    cache: true
    apex_config:
      title:
        text: 'SCE Average Watts per Hour Today & Yesterday 24h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 2000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0


  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      # color: blue
      type: column
      group_by:
        func: avg
        duration: 1h
        fill: 'zero'
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
      # offset: -1d
    cache: true
    apex_config:
      title:
        text: 'SCE Average Watts per Hour Today 24h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 2000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0

  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      # color: blue
      type: column
      group_by:
        func: avg
        duration: 1h
        fill: 'zero'
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
      offset: -1d
    cache: true
    apex_config:
      title:
        text: 'SCE Average Watts per Hour Yesterday 24h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 2000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0

```

[phantom-3day-data.csv.zip](https://github.com/RomRider/apexcharts-card/files/5897059/phantom-3day-data.csv.zip)


<img width="1448" alt="phantom-bars" src="https://user-images.githubusercontent.com/1409547/106341341-c4e2c100-6251-11eb-8a6d-d0c66708b6b7.png">

**Comment by RomRider** [comment]
I believe you are missing `fill: 'zero'` in the first config

**Comment by deepcoder** [comment]
That was the mistake, fixed. Thanks you!

```
# test 11
title: T11 Multiple Bar History
panel: true
cards:
- type: vertical-stack
# - type: grid
  # columns: 1
  cards:

  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.home_instantaneous_demand
      color: orange
      type: column
      group_by:
        func: avg
        duration: 1h
        fill: 'zero'
    - entity: sensor.home_instantaneous_demand
      color: blue
      offset: -1d
      type: column
      group_by:
        func: avg
        duration: 1h
        fill: 'zero'
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
    cache: true
    apex_config:
      title:
        text: 'SCE Average Watts per Hour Today & Yesterday 24h'
        align: 'center'
        floating: false
        style:
          fontSize:  '14px'
          fontWeight:  'bold'
          fontFamily:  'Arial'
          color:  '#263238'
      chart:
        height: 450
      yaxis:
          show: true
          showAlways: true
          showForNullSeries: true
          seriesName: undefined
          opposite: false
          reversed: false
          logarithmic: false
          tickAmount: 6
          min: 0
          max: 2000
          forceNiceScale: true
          floating: false
          decimalsInFloat: 0

```

<img width="1449" alt="phantom-bars-fixed" src="https://user-images.githubusercontent.com/1409547/106342171-bba72380-6254-11eb-822a-59e0e71f337f.png">
