### ISSUE TITLE
Graph sometimes not shown, blank box

### ISSUE THREAD

**Issue by breti** [RomRider/apexcharts-card#191]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
In Firefox on windows and android, the graph is sometimes not shown, only a blank box is rendered. There is no such issue in chrome or in the android companion app.

I've tried to create a simplified example of my lovelace pages to reproduce this issue, but I've not been successful. There's no such issue with simplified pages I've tried.

**Version of the card**
Version: v1.9.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 1d
all_series_config:
  stroke_width: 2
series:
  - entity: sensor.sz_ht_heizung_temperature
    name: Temperatur
    type: line
    yaxis_id: temp
  - entity: sensor.sz_ht_heizung_humidity
    name: Luftfeuchtigkeit
    type: line
    yaxis_id: hum
yaxis:
  - id: temp
    min: ~10
    max: ~30
    apex_config:
      tickAmount: 4
  - id: hum
    min: ~45
    max: ~65
    opposite: true
    apex_config:
      tickAmount: 4
```

**Screenshots**
After loading/opening lovelace in firefox, the graph is shown:

![Firefox_Screenshot_2021-07-30T10-54-24 639Z](https://user-images.githubusercontent.com/3628895/127643771-da7bfab8-1f37-43c7-a1a1-851b05769241.png)

It is still shown after switching between the pages of the same dashboard.

But it is not shown anymore after switching to another dashboard and back to the first one:

![Firefox_Screenshot_2021-07-30T10-54-56 329Z](https://user-images.githubusercontent.com/3628895/127643869-9e2a749b-9d4f-4542-8fbf-a4e2bd73d639.png)

It's shown again after CTRL+R.

**Expected behavior**
I'd expect to see the graph again.

**Desktop (please complete the following information):**
 - Browser: Firefox on windows
 - Version: 90.0.2

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 10, MIUI 12.0.5
 - Browser: Firefox
 - Version: 90.1.2

**Additional context**
