### ISSUE TITLE
Option to hide tooltip with date, year, time

### ISSUE THREAD

**Issue by thijselblaso** [RomRider/apexcharts-card#192]
I really like to hide the tooltip with the date, year and time. See screenshot for more information.

<img width="469" alt="Screenshot 2021-08-03 at 13 42 27" src="https://user-images.githubusercontent.com/38098396/128009859-d2135136-d3b3-42d6-a091-f7f1bbc04967.png">

**Comment by RomRider** [comment]
That's already possible with:
```
apex_config:
  xaxis:
    tooltip:
      enabled: false
```
From the [ApexCharts documentation](https://apexcharts.com/docs/options/xaxis/)
