### ISSUE TITLE
Total value calculated by donut is not rounded always

### ISSUE THREAD

**Issue by pollinolas** [RomRider/apexcharts-card#193]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
the total value calculated option by donut sometimes show several decimals and not round the total value, also tested in the last beta (v1.10.0-dev.6) and the problem persists

**Version of the card**
Version: v1.9.0

**To Reproduce**
This is the configuration I used:
```
  - type: custom:apexcharts-card
    graph_span: 24h
    cache: true
    span:
      start: day
    apex_config:
      legend:
        show: True
        position: top
      chart:
        height: 270px
      plotOptions:
        pie:
          customScale: 1
          expandOnClick: true
          donut:
            background: transparent
            labels:
              show: true
              total:
                show: true
                showAlways: false
                label: 'Mensual'
                fontFamily: helvetica
                fontWeight: bold
              value:
                show: true
                fontFamily: helvetica
                fontWeight: bold
    header:
      show: false
      title: Kwh Mensual
    chart_type: donut
    series:
      - entity: sensor.consumo_mensual_punta
        color: 'rgb(255,0,0)'
        name: Punta
        float_precision: 2
      - entity: sensor.consumo_mensual_llano
        color: 'rgb(255,247,0)'
        name: Llano
        float_precision: 2
      - entity: sensor.consumo_mensual_valle
        color: 'rgb(0,214,16)'
        name: Valle
        float_precision: 2
```

**Screenshots**
![photo_2021-08-03_18-04-43](https://user-images.githubusercontent.com/44624079/128048874-a9d085c3-0c01-46e3-9747-75f411a382a4.jpg)

**Desktop (please complete the following information):**
 - Browser : Google chrome
 - Version : 92.0.4515.107 (Build oficial) (64 bits)

**Smartphone (please complete the following information):**
 - Browser : home assistant app
 - Version : 2021.6.2-full
