### ISSUE TITLE
Can't use color_threshold with CSS variables

### ISSUE THREAD

**Issue by IzeQube** [RomRider/apexcharts-card#194]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
If I'm using a CSS variable as a color in color_threshold it just displays black instead of the color that is defined in the variable.

**Version of the card**
Version: 1.9.0 & 1.10.0-dev.6

**To Reproduce**
This is the configuration I used:
```yaml
color_threshold:
  - value: -1
    color: green
  - value: 0
    color: var(--ha-card-background)
  - value: 1
    color: red
```

**Screenshots**
This is what is shown
![image](https://user-images.githubusercontent.com/4445441/128236592-edc301e2-e160-4057-924c-663898c71395.png)

This is what I would expect
![image](https://user-images.githubusercontent.com/4445441/128236410-5f397b61-f8ea-488c-87e0-33545fbf04e2.png)

**Comment by RomRider** [comment]
If it's black, it's because that CSS variable doesn't exist.
I believe what you want is `var(--card-background-color)`

**Comment by IzeQube** [comment]
No, it also doesn't work if I use `var(--card-background-color)`.

The same variables work, if I use them in the `series `yaml part:
```yaml
      series:
        - entity: sensor.xxx
          color: var(--card-background-color)
          name: xxx
        - entity: sensor.yyy
          color: var(--card-background-color)
          name: yyy
```

I just can't use them in `color_threshold`

If I've looked at the right part of the source code, I think the reason is because normally you use the function [computeColor](https://github.com/RomRider/apexcharts-card/blob/76e5ba6e027aec7f4221764fc7d2ce38fa88cc57/src/utils.ts#L101) that will fetch the var-value and convert it.

And I think that part is different at the part where the colors are generated for `color_threshold`... But I can't find the exact location anymore...
