### ISSUE TITLE
Color of marker differs from series color

### ISSUE THREAD

**Issue by N3rdix** [RomRider/apexcharts-card#195]
When hovering over with the mouse it seems the markers on the graph use other colors as defined for the series in some cases. Just to give an example i marked 3 wrong markers.
The color in the legend is correct though.

![image](https://user-images.githubusercontent.com/70015952/128316951-8ab87136-258f-48da-920f-636db2e5f63d.png)

Might this be related to the grouping functionality?

Example config:
```
type: custom:apexcharts-card
yaxis:
  - id: cpu
    apex_config:
      tickAmount: 10
      decimalsInFloat: 1
      title:
        text: CPU
  - id: memory
    opposite: true
    apex_config:
      tickAmount: 10
      decimalsInFloat: 0
      title:
        text: RAM
apex_config:
  legend:
    show: false
header:
  show: true
  standard_format: true
  show_states: true
  colorize_states: true
graph_span: 12h
all_series_config:
  stroke_width: 2
series:
  - entity: sensor.processor_use
    name: HOST CPU
    yaxis_id: cpu
    type: line
    color: red
    show:
      in_header: false
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.memory_use_percent
    name: HOST RAM
    yaxis_id: memory
    type: area
    color: red
    opacity: 0.1
    stroke_width: 0
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.glances_jetson_cpu_used
    name: Jetson CPU
    yaxis_id: cpu
    type: line
    color: green
    show:
      in_header: false
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.glances_jetson_ram_used_percent
    name: Jetson RAM
    yaxis_id: memory
    type: area
    color: green
    opacity: 0.1
    stroke_width: 0
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.glances_adguard_cpu_used
    name: Adguard CPU
    yaxis_id: cpu
    type: line
    color: blue
    show:
      in_header: false
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.glances_adguard_ram_used_percent
    name: Adguard RAM
    yaxis_id: memory
    type: area
    color: blue
    opacity: 0.1
    stroke_width: 0
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.volkszahler_cpu
    name: VZ CPU
    yaxis_id: cpu
    type: line
    color: orange
    show:
      in_header: false
    group_by:
      func: avg
      duration: 10min
  - entity: sensor.volkszahler_ram_used_percent
    name: VZ RAM
    yaxis_id: memory
    type: area
    color: orange
    opacity: 0.1
    stroke_width: 0
    group_by:
      func: avg
      duration: 10min
```
