### ISSUE TITLE
First date is missing from graph

### ISSUE THREAD

**Issue by thijselblaso** [RomRider/apexcharts-card#198]
Hi, for some reason the first date of my graph is missing. Is this a bug or does someone know how to solve it?
I use the latest version. See also the screenshots.

This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 5d
span:
  end: day
header:
  show: true
  show_states: true
  colorize_states: true
  title: Stroomkosten vandaag
apex_config:
  chart:
    type: area
    height: 250
  xaxis:
    tooltip:
      enabled: false
series:
  - color: '#5F9BEA'
    entity: sensor.energy_import_total_dagelijks_eur
    float_precision: 2
    type: column
    group_by:
      func: max
      duration: 24h

```
<img width="470" alt="Screenshot 2021-08-10 at 12 26 39" src="https://user-images.githubusercontent.com/38098396/128852130-136fd3ce-c760-47e6-8610-da246d5e9191.png">

<img width="468" alt="Screenshot 2021-08-10 at 12 28 31" src="https://user-images.githubusercontent.com/38098396/128851932-71a79ba6-f77b-40a8-b26d-1264437e9028.png">
