### ISSUE TITLE
Throttle refresh?

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#2]
The bottom chart in this picture, two of the entities have a fair number of points about 30k each and are updating subsecond. The graph show the 'spinner' updating a lot. Is there a way to throttle updates, perhaps an option to set an update period in seconds, also to only plot every x values? On a 3.2 ghz i7 mac mini in chrome the lag shows, worried that charts in your tool will be very heavy. Thanks for your work!

```

  - type: custom:apexcharts-card
    series: 
    - entity: sensor.backyard_sensor_temperature
    cache: true

  - type: custom:apexcharts-card
    series: 
    - entity: sensor.backyard_govee_temperature
    - entity: sensor.backyard_sensor_temperature
    - entity: sensor.backyard_atc_mi_temperature
    cache: true

```

<img width="508" alt="temp-plot" src="https://user-images.githubusercontent.com/1409547/105772890-bd50ae80-5f17-11eb-884d-152b5a983d62.png">
