### ISSUE TITLE
Horizontal annotations

### ISSUE THREAD

**Issue by Gollam** [RomRider/apexcharts-card#209]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Annotations are available as part of the original chart API. I am using them in the following way:

```
    apex_config:
      annotations:
        yaxis:
          - y: 0
            borderColor: '#000'
            strokeDashArray: 0
```

This is useful for me when I'm displaying temperatures, the freezing point (0°C) is a thicker line than the others. Now the problem is that this line is always drawn, even if the temperatures rise high enough so that the zero line is not visible anymore. The result is that the line is drawn on the legend, where the zero line is in the background.

![image](https://user-images.githubusercontent.com/765342/133230810-215ea3d3-faba-4bda-bae6-e2c5d5cdb1ca.png)

**Describe the solution you'd like**
If you think it would be easy to incorporate this in your API, maybe you could only draw the annotation when you know it is visible.

**Describe alternatives you've considered**
I'm using it as it is right now, I did not find any workaround.
