### ISSUE TITLE
group_by func: last displaying first value.

### ISSUE THREAD

**Issue by tomlut** [RomRider/apexcharts-card#211]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When grouping a series by 1d and using the `func: last`, the first value for the day is displayed.

**Version of the card**
Version: v1.9.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 140%
  dataLabels:
    background:
      enabled: false
    style:
      colors:
        - var(--primary-text-color)
graph_span: 7d
header:
  show: true
  title: Daily Energy Cost
experimental:
  color_threshold: true
series:
  - entity: sensor.total_cost_today
    type: column
    float_precision: 2
    show:
      datalabels: true
    group_by:
      func: last
      duration: 1d
    color_threshold:
      - color: '#e45e65'
        value: 7
      - color: '#e0b400'
        value: 5
      - color: '#0da035'
        value: 3
      - color: '#039BE5'
        value: 0
```

**Screenshots**
![Screenshot 2021-09-16 at 11-13-10 Administration - Home Assistant](https://user-images.githubusercontent.com/10679300/133533855-d71556a7-205e-4ee9-af61-3eb474c9850e.png)

**Expected behavior**
The last value for the 1d period to be shown.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 91.0.2

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 14.8
 - Browser safari
 - Version ?

**Additional context**
