### ISSUE TITLE
In card edit mode the colors of series in graph does not update (but the state value does)

### ISSUE THREAD

**Issue by ahd71** [RomRider/apexcharts-card#212]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
In card edit mode the colors of series in graph does not update (but the state value does)

**Version of the card**
Version: v1.9.0

**To Reproduce**
This is the configuration I used:
```yaml

type: custom:apexcharts-card
y_axis_precision: 0
graph_span: 2h
header:
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.esp_13_water_temperature_from_radiators
    stroke_width: 2
    curve: straight
    color: lightblue
  - entity: sensor.esp_13_water_temperature_to_radiators
    stroke_width: 2
    curve: straight
    color: orange
  - entity: sensor.esp_13_water_temperature_boiler
    stroke_width: 2
    curve: straight
    color: purple
  - entity: sensor.esp_13_water_temperature_coldwater
    stroke_width: 2
    curve: straight
    color: blue
  - entity: sensor.esp_13_water_temperature_hotwater
    stroke_width: 2
    curve: straight
    color: red

```

**Screenshots**

**Expected behavior**
Line colors to chagne when trying out new colors in the configuration

**Desktop (please complete the following information):**
Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not tested

**Additional context**
Low priority but if it is easy to trigger an event to update the graph without affecting the performance (which may be why it has been actively disabled) it would be a nice to have
