### ISSUE TITLE
Apexcharts not following Home Assistant date/time setting

### ISSUE THREAD

**Issue by large** [RomRider/apexcharts-card#213]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
If a user profile is using 24hour time setting, Apexcharts still show 12hrs (AM/PM)

Please comply with this setting:
home-assistant/frontend#9042

**Version of the card**
Version: 1.9

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 1d
span:
  start: day
now:
  show: true
  color: '#ff0000'
  label: Now
series:
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        return [new Date(entry.start), entry.value];
      });
    type: column
    float_precision: 3
```

**Screenshots**
![image](https://user-images.githubusercontent.com/535446/133580245-334b0e25-381c-498f-9541-d8e7a6bd7c25.png)

**Expected behavior**
Show 12/24H time based on the profile setting

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version v92

**Additional context**
I know there is an option to override using https://apexcharts.com/docs/datetime/ but that require to add on all charts
