### ISSUE TITLE
Y-Axis Decimals includes entities not displayed in chart

### ISSUE THREAD

**Issue by Xeyame** [RomRider/apexcharts-card#223]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Before i used y_axis_precision, but as that is now deprecated i am using `yaxis: ` -> `decimals: 3`. I have one enitity that's not in the chart (its the sum of the values in the chart, so just the number needed in the graph header). Entities with `in_chart: false` are included with the y-axis height calculation, making graphs look like this:

![afbeelding](https://user-images.githubusercontent.com/34656654/138978444-9a829b59-3c81-4135-9945-b9679867f405.png)
instead of this:
![afbeelding](https://user-images.githubusercontent.com/34656654/138978460-62d7b629-1681-43a5-b26f-d83a5da89ce0.png)

(there is a line at y=0, just hidden so it always shows y=0 and negative values are possible too)

**Version of the card**
Version: v0.11.0-dev.4 (tried stable v0.10.0 too)

**To Reproduce**
 - Firefox 93
<details>
  <summary>    Configuration:</summary>
Pretty messy, i know 🙃

 ```yaml
 type: custom:apexcharts-card
header:
  show: true
  title: Power Consumption
  show_states: true
  colorize_states: true
update_delay: 0ms
show:
  loading: false
yaxis:
  - decimals: 3
apex_config:
  legend:
    show: false
  yaxis:
    show: true
    forceNiceScale: true
all_series_config:
  stroke_width: 2
  extend_to_end: true
  fill_raw: last
  curve: stepline
  show:
    in_header: raw
  float_precision: 3
graph_span: 10m
series:
  - entity: sensor.power_usage
    show:
      in_chart: false
  - entity: sensor.power_usage_phase_l1
  - entity: sensor.power_usage_phase_l2
  - entity: sensor.power_usage_phase_l3
  - entity: sensor.zero
    show:
      in_chart: true
      extremas: false
      in_header: false
    opacity: 0
    data_generator: |
      return [[end.getTime(), 0]];
 ```
  </details>
