### ISSUE TITLE
Config customHTML markers not working

### ISSUE THREAD

**Issue by matt8707** [RomRider/apexcharts-card#229]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I'm trying to use `customHTML` in [docs/options/legend/](https://apexcharts.com/docs/options/legend/) and the card goes blank

```log
Uncaught (in promise) TypeError: e.config.legend.markers.customHTML is not a function
```

**Version of the card**
Version: 1.10.0

**To Reproduce**

```yaml
apex_config:
  legend:
    markers:
      width: 50
      customHTML: >
        function() {
          return '<span class="custom-marker"><i class="fas fa-chart-pie"></i></span>'
        }
```

**Expected behavior**
To be able to render html

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 95.0.4638.69
