### ISSUE TITLE
Bug with height in combination with minus values

### ISSUE THREAD

**Issue by rasssta** [RomRider/apexcharts-card#23]
First of all. Thanks for a great card. I could finally get rid of my mini-graph cards and get something usable 😍

Now, to the bug :-) 

I have a card with the following config:

```
type: 'custom:apexcharts-card'
graph_span: 24h
update_interval: 1min
header:
  show: true
  show_states: true
  colorize_states: true
  title: Köket - Temperatur
series:
  - entity: sensor.temperature_21
    curve: smooth
    type: line
  - entity: sensor.temperature_23
    curve: smooth
    type: line
apex_config:
  legend:
    show: false
  chart:
    height: 300
```

It seems as when the value is -20.3 (too long?) it wraps the line and therefore the height of this card differs compared to the card next to it which also has "height: 300" configured. See picture below:

![image](https://user-images.githubusercontent.com/4455235/106355244-04afb400-62f7-11eb-9414-232eee1bebb7.png)

I get the same issue with, for example, height 350 for both.
