### ISSUE TITLE
State not showing in chart

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#233]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I noticed a state is not showing up in the chart even though it is present in the history for the day. I have highlighted the missing value.

**Version of the card**
Version: v1.10.0-dev.6

**To Reproduce**
This is the configuration I used:
```yaml

type: custom:apexcharts-card
yaxis:
  - apex_config:
      decimalsInFloat: 1
      forceNiceScale: true
apex_config:
  chart:
    height: 250px
all_series_config:
  group_by:
    func: last
    duration: 1d
graph_span: 7d
series:
  - entity: sensor.energy_grid_usage
    name: Grid
    type: column
    show:
      datalabels: true

```

**Screenshots**

![image](https://user-images.githubusercontent.com/54566217/140025284-a18df8dc-3f5c-42de-a313-070bff21fdad.png)

![image](https://user-images.githubusercontent.com/54566217/140025331-55fdba59-ef4c-4faa-b5af-9ce29580e673.png)

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 95.0.4638.54

**Smartphone (please complete the following information):**

**Additional context**
