### ISSUE TITLE
Processing of 'unavailable' values: displaying gaps

### ISSUE THREAD

**Issue by ildar170975** [RomRider/apexcharts-card#236]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
The card processes unavailable data in a strange way.

Here are two simple sensors:
1) Equal to some `input_number`, is available if some `input_boolean` = on.
2) Equal to the 1st sensor * 2, is available if that 1st sensor is available.
```
sensor:
  - platform: template
    sensors:

      test_availability:
        unit_of_measurement: "unit"
        icon_template: mdi:account
        value_template: >-
          {{ states("input_number.test_number") }}
        availability_template: >-
          {{ is_state("input_boolean.test_boolean","on") }} 

      test_availability_2:
        unit_of_measurement: "unit"
        icon_template: mdi:car
        value_template: >-
          {% set VALUE = states("sensor.test_availability") -%}
          {%- if is_number(VALUE) -%}
          {{ VALUE | float * 2 }}
          {%- else -%}
          {{ 0 }}
          {%- endif %}
        availability_template: >-
          {{ not states("sensor.test_availability") in ["unavailable","unknown"] }} 
```
Now let’s see graphs for these sensors:
```
title: availability
path: test-availability
badges: []
cards:
  - type: entities
    entities:
      - entity: input_boolean.test_boolean
        name: Available
      - entity: input_number.test_number
        name: Value
      - type: divider
      - entity: sensor.test_availability
      - entity: sensor.test_availability_2

  - type: vertical-stack
    cards:
      - type: history-graph
        entities:
          - entity: sensor.test_availability
          - entity: sensor.test_availability_2
        hours_to_show: 1
        refresh_interval: 0

      - type: custom:apexcharts-card
        series:
          - entity: sensor.test_availability
            curve: stepline
            stroke_width: 1
            fill_raw: 'null'
          - entity: sensor.test_availability_2
            curve: stepline
            stroke_width: 1
            fill_raw: 'null'
        graph_span: 1h
        cache: false
        now:
          show: true
```
There are 2 graphs:
- based on stock history-graph;
- based on apexcharts-card.

Play with the `input_number` & `input_boolean` values.
Note that:
- the stock `history-graph` shows gaps when sensors are unavailable (I consider this as a CORRECT processing);
- the `apexcharts-card` shows gaps - but in a strange manner (see below).

What I observe:
1) Data = available:
The apexcharts graphs are displayed as expected:
![image](https://user-images.githubusercontent.com/71872483/140430358-4f8d3b30-9d4a-4752-bd63-718bef9b66de.png)

2) Data = unavailable:
The last stepline disappears **(WHY?)**:
![image](https://user-images.githubusercontent.com/71872483/140430422-69f76246-44cf-46ac-9b59-7acc647a1f5c.png)

3) Data = available (after few minutes):
The previous stepline is still not displayed, a new stepline appears:
![image](https://user-images.githubusercontent.com/71872483/140431108-bb55fc98-20c7-472f-9883-57af917d2343.png)

4) Data = unavailable (after a few minutes):
The last stepline disappears too:
![image](https://user-images.githubusercontent.com/71872483/140431229-7b58c6ba-64e4-4528-9c88-9ef3612023c8.png)

5) Data = available (after few minutes):
The previous stepline**S** are still not displayed, a new stepline appears:
![image](https://user-images.githubusercontent.com/71872483/140431810-640194bd-7d19-4f96-8e8f-fce0457d14f6.png)

As a result - the `apexcharts-card` graph does not show curves between `unavailable` states.

**Version of the card**
Version: 1.10.0

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 95.0.4638.69
