### ISSUE TITLE
N/A in the header of the graph if the last value in the list is NULL

### ISSUE THREAD

**Issue by snagytx** [RomRider/apexcharts-card#242]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Since I don't seem to find a better way to treat 0s as null or ignore them I'm using a `transform: 'return x>0 ? x: null` but this causes the 'N/A' to be added in the header.

![Screen Shot 2021-11-16 at 4 47 32 PM](https://user-images.githubusercontent.com/10343781/142078694-5f389007-6c83-4ece-b2ca-35d95ca2a7f6.png)

**Version of the card**
Version:

**To Reproduce**
Use the below yaml, ensure that you update the transform to return null for the LAST item in the list for each sensor. If the last value of the sensor in the list is valid, the header would have the right value.
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
graph_span: 5h
chart_type: scatter
series:
  - entity: sensor.orp_dosing_time
    extend_to_end: false
    transform: 'return x>0 ? x: null'
  - entity: sensor.ph_dosing_time
    extend_to_end: false
    transform: 'return x>0 ? x: null'
```

**Screenshots**
![Screen Shot 2021-11-16 at 4 47 32 PM](https://user-images.githubusercontent.com/10343781/142078694-5f389007-6c83-4ece-b2ca-35d95ca2a7f6.png)

**Expected behavior**
To see the value of the last valid element in the header/

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [latest]
