### ISSUE TITLE
align_to: Does not work

### ISSUE THREAD

**Issue by hajo62** [RomRider/apexcharts-card#243]
Might you provide an example with an `align_to`?
In the example shown in the picture, I would expext a scaling like 0, 100, 200, 300 and 400
<img width="980" alt="grafik" src="https://user-images.githubusercontent.com/15800980/142492947-c4990616-6637-4e41-abb5-962f3278431e.png">

**Comment by RomRider** [comment]
For those features to work, `yaxis` shouldn't sit under `apex_config` as explained in the documentation

```yaml
type: custom:apexcharts-card
yaxis:
  - align_to: 100
```

**Comment by hajo62** [comment]
Perfect. Thanks.
```
yaxis:
  - align_to: 100
    decimals: 0
    apex_config:
      forceNiceScale: true
```

<img width="462" alt="grafik" src="https://user-images.githubusercontent.com/15800980/142612401-68a1e779-1572-4c10-8b83-890eff2cf53d.png">
