### ISSUE TITLE
align_to incorrect behavior with negative numbers

### ISSUE THREAD

**Issue by Shultc** [RomRider/apexcharts-card#251]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser
- [*] I verified that I'm really running the latest version in my browser console
- [*] I checked if there is another issue opened with the same problem

**Describe the bug**
When using align_to in graph with only negative numbers, with value of 1 it upper bound is at +2. On bigger number (e.g. 5) the max is 0

**Version of the card**
Version: 1.10.0

**To Reproduce**
This is the configuration I used:
```yaml
yaxis:
  - id: temp
    align_to: 1
    apex_config:
      decimalsInFloat: 1
      tickAmount: 4
```
```yaml
yaxis:
  - id: temp
    align_to: 5
    apex_config:
      decimalsInFloat: 1
      tickAmount: 4
```
**Screenshots**
Value: 1
![image](https://user-images.githubusercontent.com/458282/144772532-55907f37-e4a5-4775-a661-413ef4b120aa.png)
Value: 5
![image](https://user-images.githubusercontent.com/458282/144772559-62f75614-7863-48be-a6e9-a53891f6cc8e.png)

**Expected behavior**
Graph should stop on "-2" on y-axis

**Desktop:**
 - Browser FireFox
 - Version 93

**Smartphone:**
 - Device: OnePlus Nord
 - OS: Android
 - Browser: Home Assistant application
 - Version: Latest

**Additional context**
Removing "apex_config" does not change this behavior.
