### ISSUE TITLE
Datalabels percent in donut chart doesn't work

### ISSUE THREAD

**Issue by tjafbe** [RomRider/apexcharts-card#257]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
I understood a few releases ago, the donut chart behavior changed to show the value instead of the percentage. When this behavior changed, the release notes said the old behavior could be enabled with datalabels: percent, however this doesn’t work for me (assuming the below syntax is correct).

**Version of the card**
Version: v1.10.0

**To Reproduce**
This is the configuration I used:
```
header:
  show: true
  title: Consumption of load
  show_states: true
  colorize_states: true
chart_type: donut
series:
  - entity: sensor.pv_total_solar_use
    name: Solar use
  - entity: sensor.pv_total_buy
    name: Grid buy
apex_config:
  datalabels: percent
  legend:
    show: false
```

**Screenshots**
![image](https://user-images.githubusercontent.com/85074066/145677062-9d297b1d-8de0-486f-9eaf-233f8562b260.png)

**Expected behavior**
I would expect a percentage in the donut chart to appear instead of the sensor value.

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version Version 96.0.4664.93 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: same behavior on multiple Android devices (tablet, phone)
 - OS: Android
 - Browser: no browser, but the HA app (and I made sure to clear the cache)
