### ISSUE TITLE
Hidden series should not affect chart scale

### ISSUE THREAD

**Issue by lightheaded** [RomRider/apexcharts-card#266]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I'm having a problem with one series not showing up properly. It's as if the line is drawn with 0 values.
![bug](https://user-images.githubusercontent.com/3413870/148167330-f7d1e530-4433-456f-bf7e-3fccb1a1763e.gif)

I’m pretty sure my data is solid. Note what happens near the end when I change the formatter for my consumption series. The chart initially resembles a correct shape before snapping to 0 after other values are loaded, making me think that I have my chart misconfigured.
![glitching](https://user-images.githubusercontent.com/3413870/148167413-83882d10-5871-4b1c-bd4e-9dde477a8a76.gif)

I also discovered that if I remove the `sensor.nordpool_price` and `sensor.house_energy_cost` from series (both have `yaxis_id: hidden` set and `show: -> in_chart: false`), then the `sensor.hourly_house_energy` shows up correctly:
![corrrect](https://user-images.githubusercontent.com/3413870/148167522-bc4e640a-8c77-4732-9d4e-7719a54e8a3c.png)
This makes me think that the hidden series are somehow still affecting the chart scale.

**Version of the card**
Version v1.10.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
apex_config:
  grid:
    show: false
  legend:
    show: false
  chart:
    height: 100px
  tooltip:
    shared: true
    marker:
      show: true
graph_span: 48h
span:
  start: day
yaxis:
  - id: price_chart
    opposite: true
    apex_config:
      tickAmount: 1
      labels:
        formatter: |
          EVAL:v => `€${v.toFixed(2)}`
  - id: hidden
    show: false
  - id: consumption
    apex_config:
      tickAmount: 1
      labels:
        formatter: |
          EVAL:v => `${v.toFixed(2)} kWh`
series:
  - entity: sensor.nordpool_api
    yaxis_id: price_chart
    type: column
    color: green
    float_precision: 4
    show:
      in_header: false
    data_generator: |
      return entity.attributes.ee.map((p, i) => {
        const price = p.price * 1.2 / 1000;
        const timestamp = p.timestamp * 1000;
        return [timestamp, price];
      })
  - entity: sensor.nordpool_price
    yaxis_id: hidden
    color: green
    float_precision: 4
    show:
      in_chart: false
  - entity: sensor.house_energy_cost
    name: Cost
    yaxis_id: hidden
    color: green
    float_precision: 2
    show:
      in_chart: false
  - entity: sensor.hourly_house_energy
    name: Consumption
    yaxis_id: consumption
    color: orange
    stroke_width: 3
    opacity: 0.5
    float_precision: 2
    curve: stepline
    extend_to_end: false
    show:
      in_header: false
    group_by:
      func: max
      duration: 1h
      fill: last
  - entity: sensor.house_power
    name: Consumption
    yaxis_id: hidden
    color: orange
    float_precision: 0
    show:
      in_chart: false
```

**Expected behavior**
Series that have `show: -> in_chart: false` or are on an axis that has `show: false` should not affect y-axis scale.

**Desktop (please complete the following information):**
 - Browser: All (used Chrome 96.0.4664.110 for screenshots)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android 11
 - Browser: Chrome
 - Version: 96.0.4664.104
