### ISSUE TITLE
color_threshold with percentual values

### ISSUE THREAD

**Issue by crazytok** [RomRider/apexcharts-card#268]
I think it would be a good idea to have the "color_threshold" possible with percentual values instead of only fixed values.

For example, when using the chart for electricity price forecast, you could have the bar colors to show green, orange, and red based on the days Max and Min values.

Example
```
color_threshold:
      - value: 0%
        color: green
      - value: 50%
        color: yellow
      - value: 80%
        color: red
```
