### ISSUE TITLE
yaxis min and max values are ignored by using the brush function

### ISSUE THREAD

**Issue by Banis1** [RomRider/apexcharts-card#269]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
By using thr brush funcion i have the problem, that the yaxis values for min and max are ignored. 

**Version of the card**
Version: 1.10.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 12h
brush:
  selection_span: 2h
experimental:
  color_threshold: true
  brush: true
yaxis:
  - id: 1a
    min: 22
    max: 30
    apex_config:
      decimalsInFloat: 0
      range: 10
      opposite: false
      tickAmount: 10
  - id: 2a
    min: 0
    max: 10
    apex_config:
      decimalsInFloat: 0
      seriesName: Soll Vorlauf
      opposite: true
      tickAmount: 1
header:
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.Soll_Vorlauftemp
    yaxis_id: 1a
    name: Soll Vorlauf
    stroke_width: 2
    color: firebrick
    show:
      datalabels: false
      legend_value: false
      in_brush: false
  - entity: sensor.Ist_Vorlauftemp
    yaxis_id: 2a
    color: red
    stroke_width: 2
    name: Ist Vorlauf
    show:
      datalabels: false
      legend_value: false
  - entity: sensor.Betriebsart_in_Zahl
    yaxis_id: 2a
    name: A Betriebsart
    stroke_width: 1
    color: '#F78181'
    curve: stepline
    type: area
    color_threshold:
      - value: 0
        color: white
      - value: 1
        color: '#F78181'
      - value: 2
        color: blue
      - value: 3
        color: red
    show:
      datalabels: false
      legend_value: false
      in_header: false
      in_brush: true

```

**Screenshots**
[https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1364](url)

**Expected behavior**
The min and max values of the yaxis admin should realy bei taken in the chart

**Desktop (please complete the following information):**
 - Browser firefox
 - Version 95.0
