### ISSUE TITLE
DataLabels are missing in a stacked bar chart with negative values

### ISSUE THREAD

**Issue by nitobosch** [RomRider/apexcharts-card#279]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
With a stacked bar chart, the datalabels are not showed for negative series.
I searched the same bug for apexchart and it seems that was already fixed
https://github.com/apexcharts/apexcharts.js/issues/2640

**Version of the card**
Version: v1.10.0

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
stacked: true
graph_span: 7d
span:
  start: day
  offset: '-6d'
header:
  show: true
  title: Daily consumption
  show_states: false
all_series_config:
  type: column
  unit: kWh
  show:
    legend_value: false
series:
  - entity: sensor.wibeee_vertido_red_energy
    name: Returned to grid
    type: column
    opacity: 0.7
    color: '#dc32ff'
    float_precision: 1
    invert: true
    group_by:
      func: diff
      duration: 1d
    show:
      datalabels: true
  - entity: sensor.wibeee_autoconsumo_energy
    name: Autoconsumption
    type: column
    opacity: 0.7
    color: '#ffc72d'
    float_precision: 1
    group_by:
      func: diff
      duration: 1d
    show:
      datalabels: true
  - entity: sensor.wibeee_consumo_red_energy
    name: Grid consumption
    type: column
    opacity: 0.7
    color: '#50adf4'
    float_precision: 1
    group_by:
      func: diff
      duration: 1d
    show:
      datalabels: true
```

**Screenshots**
<img src="https://user-images.githubusercontent.com/11455488/150779926-9d0c8423-93db-43f4-a936-de1f28f31a6b.png" height="400">

**Expected behavior**
I would like that datalabels will display also for negative series
