### ISSUE TITLE
`hidden_by_default` does not work when `name` is not set even if all the series have a unique name

### ISSUE THREAD

**Issue by zanna-37** [RomRider/apexcharts-card#280]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
`hidden_by_default` does not work when `name` is not set even if **all the series have a unique name**. It does work if I add the `name` field. Is this expected behavior? Shouldn't the card pick the entity name?
_(and yes, I set the `experimental: hidden_by_default: true`)_

**Version of the card**
Version: `1.10.0`

**To Reproduce**
This does not hide the series
```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 500px
experimental:
  hidden_by_default: true
header:
  show: false
  show_states: true
  colorize_states: true
graph_span: 12h
all_series_config:
  group_by:
    func: avg
    duration: 4m
series:
  - entity: sensor.template_ensolar_power_in_house
    extend_to_end: false
    float_precision: 0
    color: '#3498db'
    stroke_width: 4
    yaxis_id: watt
# [...]
  - entity: sensor.template_ensolar_percentage_battery
    show:
      hidden_by_default: true    # <=================
    extend_to_end: false
    float_precision: 0
    color: '#f39c12'
    stroke_width: 3
    yaxis_id: percent
yaxis:
  - id: watt
    decimals: 0
    apex_config:
      forceNiceScale: true
  - id: percent
    decimals: 0
    max: 100
    min: ~50
    apex_config:
      forceNiceScale: true
      floating: true
```

while this does (notice the added `name: a`, `name: b`, ...)

```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 500px
experimental:
  hidden_by_default: true
header:
  show: false
  show_states: true
  colorize_states: true
graph_span: 12h
all_series_config:
  group_by:
    func: avg
    duration: 4m
series:
  - entity: sensor.template_ensolar_power_in_house
    name: a  # <---------------------------------
    extend_to_end: false
    float_precision: 0
    color: '#3498db'
    stroke_width: 4
    yaxis_id: watt
# [...]
  - entity: sensor.template_ensolar_percentage_battery
    name: e  # <---------------------------------
    show:
      hidden_by_default: true    # <=================
    extend_to_end: false
    float_precision: 0
    color: '#f39c12'
    stroke_width: 3
    yaxis_id: percent
yaxis:
  - id: watt
    decimals: 0
    apex_config:
      forceNiceScale: true
  - id: percent
    decimals: 0
    max: 100
    min: ~50
    apex_config:
      forceNiceScale: true
      floating: true
```

**Screenshots**
This doesn't work (first yaml)
![image](https://user-images.githubusercontent.com/43404980/150969537-5330db52-5e4a-43ca-b986-d5465941c044.png)
This does (second yaml)
![image](https://user-images.githubusercontent.com/43404980/150969666-aa0b84a6-9def-4ee2-a75f-5f28f5596389.png)

**Expected behavior**
I expect the card to pick the entity name without having to repeat it in the card configuration.

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 97.0.4692.71

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser chrome
 - Version 96.0.4664.45
