### ISSUE TITLE
Part of the data is missing from the graph.

### ISSUE THREAD

**Issue by rozhkovets** [RomRider/apexcharts-card#284]
**Checklist**

- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Part of the data is missing from the graph. But the data was always available and did not disappear, which can be seen on the charts of other cards (history-graph, custom: mini-graph-card)

**Version of the card**
Version: v1.10.0

This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 24h
cache: false
header:
  show: false
  title: hdd temp
  show_states: true
  colorize_states: true
apex_config:
  legend:
    show: false
series:
  - entity: sensor.nas_wmi_thdd1
  - entity: sensor.nas_wmi_thdd2
  - entity: sensor.nas_wmi_thdd3
  - entity: sensor.nas_wmi_thdd4
  - entity: sensor.nas_wmi_thdd5
```

**Screenshots**
the time period is the same for all charts - 24 hours
![Снимок](https://user-images.githubusercontent.com/38763175/152286080-e1078e57-89d4-4993-9d5d-3514301a33b2.PNG)

**Desktop (please complete the following information):**
 - Cent Browser 4.3.9.248, Microsoft Edge 97.0.1072.76
