### ISSUE TITLE
Specify series entity ID using template

### ISSUE THREAD

**Issue by dagwud** [RomRider/apexcharts-card#290]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Describe the solution you'd like**
Having the ability to specify `entity` using Javascript (or Jinja, either would work) templates.
e.g:
```yaml
series:
   # This checks a sensor which reports which device is using the most power at the moment:
  - entity: '[[[ return states["sensor.highest_electricity_usage_sensor"].state; ]]]'
  # This allows me to enter a particular device name via a custom:text-input-row and have it included in the graph:
  - entity: '[[[ return "sensor." + states["input_text.selected_sensor"] + "_power"; ]]]'
  # This shows total electricity usage of all devices combined:
  - entity: sensor.total_electricity_power
```

**Describe alternatives you've considered**
Tried using Jinja and JS templates, and using auto-entities card, though I couldn't get any of those working

**Additional context**
This is for advanced dashboarding... I would like to show which of the devices in my house is using the most power at any moment, and then also build a UI component which allows me to enter a device name and have the graphs update to show that device's electricity usage relative to the total power usage
