### ISSUE TITLE
[FR] Ignore extraneous "entity" option

### ISSUE THREAD

**Issue by ildar170975** [RomRider/apexcharts-card#291]
**Checklist**
- [ x] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

When trying to use the card with `auto-entities` card I see an error.
Here is the card:
```
type: custom:auto-entities
card:
  type: vertical-stack
unique: true
show_empty: true
card_param: cards
filter:
  include:
    - entity_id: sensor.cleargrass_1_*
      options:
        type: custom:apexcharts-card
        series:
          - entity: this.entity_id
        graph_span: 1h
```
![изображение](https://user-images.githubusercontent.com/71872483/154868829-c2da3759-9e98-4651-93c1-4179c46139b8.png)

First I talked with Thomas (https://github.com/thomasloven/lovelace-auto-entities/issues/234) and he proposed this FR.

**Describe the solution you'd like**

Ignore extraneous "entity" option.

**Describe alternatives you've considered**

**Additional context**
