### ISSUE TITLE
Add a total value for pie / donut chart

### ISSUE THREAD

**Issue by EmJay276** [RomRider/apexcharts-card#298]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
It would be awesome to be able to declare the total value of a pie / donut chart.
I am plotting my power consumption within the last 24h, I track the total power consumption and several devices independantly.

**Describe the solution you'd like**
An option like in https://github.com/cheelio/power-usage-card 
`total_power_usage: sensor.power_consumption      # Optional total power consumption (DSMR) sensor.`
to declare the total amount the pie / donut chart should have.

The additional slice to add would propably be relatively easy to calculate
`total_value - sum(other_values)`

**Describe alternatives you've considered**
Currently I have to declare a new sensor in HA to calculate the "other" / "Sonstiges" amount of power consumed.
(Values are not matching, that's due to my not (yet) consistent data)

![grafik](https://user-images.githubusercontent.com/8619525/155303504-36b72136-d8fe-4326-aef4-6ae2c6ea03a7.png)
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:apexcharts-card
    header:
      show: true
      title: Verbrauch letzte 24 Stunden
      show_states: true
      colorize_states: true
    chart_type: donut
    all_series_config:
      group_by:
        duration: 24h
        func: diff
    apex_config:
      legend:
        show: false
      dataLabels:
        formatter: |
          EVAL:function(value) {
            return value.toFixed(1) + "%";
          }
    series:
      - entity: sensor.energy_total
        show:
          in_chart: false
        name: Gesamt
      - entity: sensor.consumption_54
      - entity: sensor.consumption_64
      - entity: sensor.consumption_56
      - entity: sensor.consumption_60
      - entity: sensor.consumption_62
      - entity: sensor.energy_other
```
