### ISSUE TITLE
Stacked option, y-axis : v1.1.0-dev.1

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#3]
In v1.1.0-dev.1, I'm not sure if I am using the 'stacked' option correctly, the y-axis seems to odd:
```
  - type: custom:apexcharts-card
    series: 
    - entity: sensor.backyard_govee_temperature
    - entity: sensor.backyard_sensor_temperature
    - entity: sensor.backyard_atc_mi_temperature
    update_interval: 15s
    hours_to_show: 24
    cache: true
    stacked: true
```

<img width="522" alt="stacked" src="https://user-images.githubusercontent.com/1409547/105784472-bd5ba900-5f2d-11eb-8a4e-fa1cd101571c.png">
