### ISSUE TITLE
group-by and current data

### ISSUE THREAD

**Issue by terminet85** [RomRider/apexcharts-card#30]
Using group_by, with max function, duration 1 day and graph_span 7 days I can display series along 7 days grouped by day by day.

Anyway I cannot got the current day data, I missing something?

Thanks

**Comment by RomRider** [comment]
Please share your config and a screenshot :)

**Comment by terminet85** [comment]
![immagine](https://user-images.githubusercontent.com/14027613/106433616-bc1c0600-6470-11eb-9c74-daaf2a535d35.png)

```
type: 'custom:apexcharts-card'
cache: false
graph_span: 7d
header:
  show: true
series:
  - entity: sensor.solaredge_power_production_template
    color: green
    name: Produzione
    unit: kWh
    float_precision: 2
    curve: smooth
    type: column
    group_by:
      func: max
      duration: 1d
  - entity: sensor.solaredge_power_imported_template
    color: red
    curve: smooth
    name: Consumo
    float_precision: 2
    unit: kWh
    type: column
    group_by:
      func: max
      duration: 1d
```

Here you go!
