### ISSUE TITLE
color_threshold not render correctly

### ISSUE THREAD

**Issue by gabrio79** [RomRider/apexcharts-card#305]
**Describe the bug**
hello, first of all thank you for your job.
I know that is an experimental feature, but very useful. 
When I add the third element in the chart, the color_threshold feature break as image
**Version of the card**
Version: v1.10.0

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Scambio in rete
  show_states: true
update_interval: 10min
graph_span: 12h
experimental:
  color_threshold: true
yaxis:
  - id: first
    decimals: 0
    apex_config:
      tickAmount: 5
    max: 16000
    min: -4000
  - id: second
    opposite: true
    show: false
series:
  - entity: sensor.scambio_in_rete
    yaxis_id: first
    color_threshold:
      - value: 0
        color: '#54912a'
        opacity: 1
      - value: 1000
        color: '#fae664'
      - value: 12000
        color: '#d62839'
    group_by:
      duration: 10min
      func: avg
    show:
      legend_value: false
      in_header: true
      name_in_header: false
  - entity: input_number.zero
    color: '#888888'
    yaxis_id: first
    opacity: 0.5
    stroke_width: 1
    show:
      legend_value: false
      in_header: false
      name_in_header: false
  - entity: sensor.notte_giorno
    color: '#888888'
    yaxis_id: second
    opacity: 0.2
    stroke_width: 0.2
    curve: stepline
    type: area
    show:
      legend_value: false
      name_in_header: false
      in_header: false
```

**Screenshots**
![Schermata 2022-03-07 alle 15 54 01](https://user-images.githubusercontent.com/65911264/157058125-b5585483-3260-4d45-a330-36ffd46e753b.png)

**Expected behavior**
image like below but with "sensor.notte_giorno" trend
![Schermata 2022-03-07 alle 15 57 14](https://user-images.githubusercontent.com/65911264/157058742-fc3f36f7-105a-4b79-9cc3-553f8e7f4f66.png)

**Desktop (please complete the following information):**
 - Browser  chrome
 - Version Versione 98.0.4758.109 (Build ufficiale) (x86_64)
