### ISSUE TITLE
Color threshold not scaling properly

### ISSUE THREAD

**Issue by NateRobinsonS** [RomRider/apexcharts-card#317]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
When used in an area chart, the lowest value of the color threshold appears to ignore the lowest value on the y-axis and instead uses the lowest value of the series when coloring the area.  In other words, if the lowest color_threshold is set to 0.1, the next color_threshold is 0.2, and the y-axis goes down to 0 but the minimum value in the series is 0.25, the color associated with the color_threshold at 0.1 is never displayed.

**Version of the card**
Version: 1.10.1

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 72h
span:
  start: day
  offset: -1day
header:
  title: Electricity price forecast
  show: true
  show_states: false
  colorize_states: true
hours_12: false
stacked: false
experimental:
  color_threshold: true
yaxis:
  - id: cost
    min: 0
    apex_config:
      title: 
        text: "Cost (SEK/kWh)"
        style:
#          color: black
          fontsize: 10px
          fontWeight: 100
      decimalsInFloat: 1
      labels:
        show: true
      tooltip:
        enabled: false
      crosshairs:
        show: false
      forceNiceScale: false
  - id: power
    min: 0
    apex_config:
      title: 
        text: "Consumption (kW)"
        style:
#          color: black
          fontsize: 10px
          fontWeight: 100
    opposite: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: false
    in_brush: true
  float_precision: 3
  type: area
  invert: false
  fill_raw: zero
now:
  show: false
  label: Now
  color: red
series:
  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Current day
    opacity: 1
    extend_to_end: false
    data_generator: |
      var a = entity.attributes.raw_today.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];

      });

      var b = [a[a.length - 1][0] + 3600000, 0];

      a.push( b );

      return a;

    yaxis_id: cost
    color_threshold:
      - value: 0.0
        color: 1E90FF
      - value: 0.5
        color: "008000"
      - value: 1.0
        color: DAA520
      - value: 2.0
        color: FF0000
      - value: 3.0
        color: FE17EB
      - value: 4.0
        color: "000080"

  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Tomorrow
    opacity: 0.5
    data_generator: |
      return entity.attributes.raw_tomorrow.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];

      });
    yaxis_id: cost
    color_threshold:
      - value: 0.0
        color: 1E90FF
      - value: 0.5
        color: "008000"
      - value: 1.0
        color: DAA520
      - value: 2.0
        color: FF0000
      - value: 3.0
        color: FE17EB
      - value: 4.0
        color: "000080"

  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Cost
    opacity: 1
    extend_to_end: false
    yaxis_id: cost
    color_threshold:
      - value: 0.0
        color: 1E90FF
      - value: 0.5
        color: "008000"
      - value: 1.0
        color: DAA520
      - value: 2.0
        color: FF0000
      - value: 3.0
        color: FE17EB
      - value: 4.0
        color: "000080"

  - entity: sensor.energy_consumption_total
    name: Power consumption
    type: area
    yaxis_id: power
    extend_to_end: false
    color_threshold:
      - value: -1.0
        color: '888888'
      - value: 100000
        color: '888888'
    group_by:
      func: diff
      duration: 1h
      fill: last
    opacity: 0.5

apex_config:
  chart:
    height: 250px
    animations:
      enabled: true
      easing: easeinout
      speed: 800
      animateGradually:
        enabled: true
        delay: 150
    zoom:
      enabled: true
      type: x
      autoScaleYaxis: true
      zoomedArea:
        fill:
          color: '#90CAF9'
          opacity: 0.4
        stroke:
          color: '#0D47A1'
          opacity: 0.4
          width: 1
  legend:
    show: false
    floating: true
    offsetY: 25
  yaxis:
    decimalsInFloat: 1
    labels:
      show: true
    tooltip:
      enabled: true
    crosshairs:
      show: true
    forceNiceScale: false
  xaxis:
    labels:
      show: true
      rotate: -45
      rotateAlways: true
    logarithmic: false
  stroke:
    show: true
    curve: stepline
    lineCap: butt
    colors: undefined
  markers:
    size: 0
  grid:
    show: true
    strokeDashArray: 1
    position: front
    xaxis:
      lines:
        show: false
```

**Screenshots**

**Expected behavior**
I would expect the area under the curve to show all of the colors, defined via color_threshold for the series between the minimum value of the y-axis and the actual value of the series at each point.

**Desktop (please complete the following information):**
```
Google Chrome | 99.0.4844.82 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 8cc9edbaf13103187928be09721d5119481f9dc8-refs/branch-heads/4844_74@{#3}
OS | Windows 11 Version 21H2 (Build 22000.556)
JavaScript | V8 9.9.115.9
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
Command Line | "C:\Program Files\Google\Chrome\Application\chrome.exe" --origin-trial-disabled-features=ConditionalFocus --profile-directory=Default --restore-last-session --flag-switches-begin --flag-switches-end
```

**Smartphone (please complete the following information):**

**Additional context**
None

**Comment by RomRider** [comment]
Could you please post a screenshot to make it more explicit?

**Comment by NateRobinsonS** [comment]
Screenshot:

![Screenshot 2022-05-20 083707](https://user-images.githubusercontent.com/25130192/169468027-74477e5c-7730-44b3-b2f1-59500947af56.png)

This plot contains the current day's price (and tomorrow's when it becomes avaiable).  Data to the left of the "color shift" are historic (pulled from the HA history database).  Data to the right are from Nordpool's price forecast.  Note that I add a 0 value at midnight to the Nordpool forecast for today (and tomorrow) in the yaml below.  This causes these series to represent the colors correctly (including blue below 0.3).  However, I cannot add a 0 value to the historic data.  The historic data doesn't show the blue colors, but starts with green at 0.  I believe the defined "color thresholds" are identical for all 3 series.

Yaml that generated the graph above:
```
type: custom:apexcharts-card
graph_span: 72h
span:
  start: day
  offset: '-1day'
header:
  title: Electricity price forecast
  show: true
  show_states: false
  colorize_states: true
hours_12: false
stacked: false
experimental:
  color_threshold: true
yaxis:
  - id: cost
    min: 0
    apex_config:
      title:
        text: Cost (SEK/kWh)
        style:
          fontsize: 10px
          fontWeight: 100
      decimalsInFloat: 1
      labels:
        show: true
      tooltip:
        enabled: false
      crosshairs:
        show: false
      forceNiceScale: false
  - id: power
    min: 0
    apex_config:
      title:
        text: Consumption (kW)
        style:
          fontsize: 10px
          fontWeight: 100
    opposite: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: false
    in_brush: true
  float_precision: 3
  type: area
  invert: false
  fill_raw: zero
now:
  show: false
  label: Now
  color: red
series:
  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Current day
    opacity: 1
    extend_to: now
    data_generator: |
      var a = entity.attributes.raw_today.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];

      });

      var b = [a[a.length - 1][0] + 3600000, 0];

      a.push( b );

      return a;
    yaxis_id: cost
    color_threshold:
      - value: 0
        color: 1E90FF
      - value: 0.5
        color: '008000'
      - value: 1
        color: DAA520
      - value: 2
        color: FF0000
      - value: 3
        color: FE17EB
      - value: 4
        color: '000080'
  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Tomorrow
    opacity: 0.5
    data_generator: |
      var a = entity.attributes.raw_tomorrow.map((start, index) => {

        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];

      });

      var b = [a[a.length - 1][0] + 3600000, 0];

      a.push( b );

      return a;
    yaxis_id: cost
    color_threshold:
      - value: 0
        color: 1E90FF
      - value: 0.5
        color: '008000'
      - value: 1
        color: DAA520
      - value: 2
        color: FF0000
      - value: 3
        color: FE17EB
      - value: 4
        color: '000080'
  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Cost
    opacity: 1
    extend_to: now
    yaxis_id: cost
    color_threshold:
      - value: 0
        color: 1E90FF
      - value: 0.5
        color: '008000'
      - value: 1
        color: DAA520
      - value: 2
        color: FF0000
      - value: 3
        color: FE17EB
      - value: 4
        color: '000080'

apex_config:
  chart:
    height: 250px
    animations:
      enabled: true
      easing: easeinout
      speed: 800
      animateGradually:
        enabled: true
        delay: 150
    zoom:
      enabled: true
      type: x
      autoScaleYaxis: true
      zoomedArea:
        fill:
          color: '#90CAF9'
          opacity: 0.4
        stroke:
          color: '#0D47A1'
          opacity: 0.4
          width: 1
  legend:
    show: false
    floating: true
    offsetY: 25
  yaxis:
    decimalsInFloat: 1
    labels:
      show: true
    tooltip:
      enabled: true
    crosshairs:
      show: true
    forceNiceScale: false
  xaxis:
    labels:
      show: true
      rotate: -45
      rotateAlways: true
    logarithmic: false
  stroke:
    show: true
    curve: stepline
    lineCap: butt
    colors: undefined
  markers:
    size: 0
  grid:
    show: true
    strokeDashArray: 1
    position: front
    xaxis:
      lines:
        show: true
```
