### ISSUE TITLE
Line chart with extend_to_end: false stops at <last update> instead of at <now>.

### ISSUE THREAD

**Issue by StephanSchuster** [RomRider/apexcharts-card#318]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Line chart of today with `extend_to_end: false` stops at the point where the sensor was last updated/changed. Instead, I would expect that the line gets extended until the current moment in time.

**Version of the card**
Version: 1.10.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  title: Batterie
  standard_format: true
series:
  - entity: sensor.solar_battery_state_of_charge
    name: Ladezustand
    color: var(--energy-battery-in-color)
    opacity: 0.2
    stroke_width: 2
    type: area
    fill_raw: last
    extend_to_end: false
update_interval: 1min
graph_span: 24h
span:
  start: day
apex_config:
  chart:
    offsetY: -24
    parentHeightOffset: 0
  grid:
    borderColor: '#80808080'
    padding:
      top: 0
      right: 16
      bottom: 0
      left: 13
  yaxis:
    tickAmount: 2
    min: 0
    max: 100
    labels:
      formatter: |
        EVAL:function(value) {
          return (value) + " %";
        }
      style:
        colors: '#A0A0A0'
  xaxis:
    labels:
      style:
        colors: '#A0A0A0'
    axisTicks:
      color: '#A0A0A0'
      offsetY: 2
    axisBorder:
      show: false
    tooltip:
      enabled: false
```

**Screenshots**
This is the actual state at ~13:45:
![image](https://user-images.githubusercontent.com/5207269/160130108-82760f33-3fba-4862-9ac7-e69072e1f6d0.png)

This is the expected outcome at current point in time which is ~13:45:
![image](https://user-images.githubusercontent.com/5207269/160130219-08654165-215c-424e-b71f-b0eff49d84ef.png)

This is the history of the sensor used in the apex chart. In contrast to apex, it extends till now:
![image](https://user-images.githubusercontent.com/5207269/160129991-0691ac08-882a-4744-a2d4-01edc3b00b3e.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version latest

**Additional context**
As it can be seen in my config, I want to visualize the battery charge from today 0:00 till current point in time. Basically exactly like in the official HA energy dashboard.

Is there any chance to fix this (in case it is a bug)? Are there any workarounds? I played a bit with `data_generator ` but was not successful. Maybe there is also something that I can do on my template sensor which delivers the data?
