### ISSUE TITLE
Brush & multiple yaxis work together incorrectly

### ISSUE THREAD

**Issue by jannesaarinen** [RomRider/apexcharts-card#324]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**

**Version of the card**
Version: 0.10.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  brush: true
chart_type: line
graph_span: 3d
stacked: false
show:
  last_updated: true
apex_config:
  chart:
    height: 350px
yaxis:
  - id: y1
    decimals: 1
    apex_config:
      tickAmount: 5
  - id: y2
    decimals: 0
    opposite: true
brush:
  selection_span: 3d
header:
  show: true
  title: CO2 activity
  show_states: true
  colorize_states: true
all_series_config:
  curve: smooth
  opacity: 0.5
  stroke_width: 3
  group_by:
    duration: 30m
    func: avg
    fill: last
  show:
    in_brush: true
  yaxis_id: y1
series:
  - entity: sensor.fermenter_monitor_temperature_1
    name: Chamber
  - entity: sensor.fermenter_monitor_temperature_2
    color: blue
    name: Keg 1
  - entity: sensor.fermenter_room_temperature_2
    opacity: 0.2
    name: Room
    show:
      in_brush: false
  - entity: sensor.fermenter_monitor_illuminance
    name: Heating
    yaxis_id: y2
    opacity: 0.2
    show:
      in_brush: false
```

**Screenshots**

When brush is on:
![image](https://user-images.githubusercontent.com/50728680/162799881-20137103-4644-4c50-bc8f-42cfc018f8a5.png)

And when it is off (this is the expected behaviour):
![image](https://user-images.githubusercontent.com/50728680/162800016-0ffe6109-6ded-4426-ab79-05cc11dabe5e.png)

**Expected behavior**
It looks like the brush feature some how clashes with multiple yaxis functionality. When multiple yaxis is defined and there are several entities on same yaxis, they don't have the same scale and yaxis min and max are maybe stacked (even when stacked is explicitly set to false).

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version  100.0.4896.75
