### ISSUE TITLE
Horixontal level indicator

### ISSUE THREAD

**Issue by MEKadan** [RomRider/apexcharts-card#328]
**Checklist**
- [ x] I am running the latest version of the card
- [x ] I checked if there isn't another feature request opened with the same request
        (not that I could find...)
- [? ] I checked that the feature is not already available in the `dev` branch
       (unfortunately I do not quite know how to do that...)

**Is your feature request related to a problem? Please describe.**

- Not a problem, just a feature request

**Describe the solution you'd like**

- From Home Assistant user point of view, in automation world some kind of horizontal "level indicator" is very useful, that being a straight, horizontal line going from one end to another. The level value should be configurable also by variable (sensor etc. ) 

**Describe alternatives you've considered**

- This could be achieved with mixed chart, where there is separate horizontal line drawn along the desired values, However, this would require giving these value points separately from beginning to the end for each data point.
- There might be other ways to achieve that as well?

**Additional context**

**Comment by RomRider** [comment]
You can do that using [annotations](https://apexcharts.com/docs/options/annotations/)
```yaml
apex_config:
  annotations:
    yaxis:
      - y: 13
       ...
```
More complete example [here](https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/653?u=romrider)

Also for make it variable or dependant on a sensor, you can use the `config-template-card`

**Comment by MEKadan** [comment]
So, with apexcharts using variable as annotations y-value is not possible?  

Quickly checking config-template-chart, it does not have the visual elements I need and also I have to rewrite my "case" again, so it is not much an option.

**Comment by RomRider** [comment]
It is not supported directly in apexcharts-card but your use case can definitely be achieved combining config-template-card and apexcharts-card. I don't understand what is blocking you?

**Comment by RomRider** [comment]
I didn't test, but that should give you a good idea:

```yaml
type: 'custom:config-template-card'
variables:
  SENSOR_STATE: states['sensor.whatever'].state
entities:
  - sensor.whatever
card:
  type: custom:apexcharts-card
  apex_config:
    annotations:
      yaxis:
        - y: '${Number(SENSOR_STATE)}'
  series:
    - entity: sensor.temperature
```

**Comment by jose1711** [comment]
The suggested code does not seem to work with axes using id. Example:
```
type: custom:apexcharts-card
graph_span: 1d
yaxis:
  - id: temp
series:
  - entity: sensor.foo_sensor
    yaxis_id: temp
apex_config:
  yaxis:
    max: 100
    min: 0
  annotations:
    position: back
    yaxis:
      - "y": 33
        y2: 0
        strokeDashArray: 0
        fillColor: red
        borderColor: "#00000000"
      - "y": 66
        y2: 33
        strokeDashArray: 0
        fillColor: yellow
        borderColor: "#00000000"
      - "y": 100
        y2: 66
        strokeDashArray: 0
        fillColor: green
        borderColor: "#00000000"
```
It results in the following:

<img width="470" height="300" alt="Image" src="https://github.com/user-attachments/assets/571e73b8-c151-490e-bd70-99208456047c" />

I need to specify `id` as I want to have multiple series included in a single chart.
