### ISSUE TITLE
Title card

### ISSUE THREAD

**Issue by terminet85** [RomRider/apexcharts-card#33]
May can you add the option to set a card's title?

**Comment by RomRider** [comment]
It is already possible, please read the documentation:
```yaml
header:
  show: true
  title: You title
```
