### ISSUE TITLE
Extrema labels displaced when using logarithmic: true

### ISSUE THREAD

**Issue by N3rdix** [RomRider/apexcharts-card#330]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
Coming with version 2.0.0 it seems the extrema labels are not placed correctly any longer on the line when using logarithmic y-axis. It seems they are placed at the min/max of the shown logarithmic value.

Funny side note: I wonder why the extremas are different in the 2 screenshots, i would expect they are always identical...

**Version of the card**
Version: 2.0.0

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
yaxis:
  - id: aktuell
    apex_config:
      tickAmount: 10
      decimalsInFloat: 1
      logarithmic: true
      min: 1
      max: 20000
apex_config:
  legend:
    show: false
header:
  show: true
  title: Stromverbrauch
  standard_format: true
  show_states: true
  colorize_states: true
graph_span: 12h
update_interval: 15sec
all_series_config:
  stroke_width: 3
series:
  - entity: sensor.aktuelle_leistung_hausstrom
    name: Hausstrom
    yaxis_id: aktuell
    type: line
    color: green
    group_by:
      func: avg
      duration: 1min
    show:
      extremas: true
  - entity: sensor.aktuelle_leistung_hausstrom
    offset: '-1d'
    name: Strom gestern
    show:
      in_header: false
      name_in_header: false
    yaxis_id: aktuell
    type: area
    opacity: 0.1
    color: green
    stroke_width: 0
    group_by:
      func: avg
      duration: 1min
  - entity: sensor.aktuelle_leistung_heizung_shelly
    name: Heizstrom
    yaxis_id: aktuell
    type: line
    color: red
    group_by:
      func: avg
      duration: 1min
    show:
      extremas: true
  - entity: sensor.aktuelle_leistung_heizung_shelly
    offset: '-1d'
    name: Heizstrom gestern
    show:
      in_header: false
      name_in_header: false
    yaxis_id: aktuell
    type: area
    opacity: 0.1
    color: red
    stroke_width: 0
    group_by:
      func: avg
      duration: 1min
```

**Screenshots**
Linear:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/70015952/164968650-37dc4163-d0bc-4248-87d3-14e296bdef07.png">

Logarithmic:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/70015952/164968737-87b5e8cc-14c4-43f7-b758-624472b0eb9b.png">

**Expected behavior**
Labels should be placed near the line
