### ISSUE TITLE
Long term statistics for pressure multiplied by 100

### ISSUE THREAD

**Issue by matteocorti** [RomRider/apexcharts-card#332]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**

Long term statistics for pressure multiplied by 100.

**Version of the card**

Version: v2.0.1

**To Reproduce**

I have a sensor for atmospheric pressure: ```sensor.netatmo_casetta_studio_pressure``` with values in mbar (usually between 980 and 1045)

```
state_class: measurement
attribution: Data provided by Netatmo
unit_of_measurement: mbar
device_class: pressure
friendly_name: Netatmo Studio Pressure
```

**Screenshots**

The graphs are correct:

```
type: custom:apexcharts-card
graph_span: 1d
header:
  show: true
  title: Pressione
  show_states: true
  colorize_states: true
all_series_config:
  stroke_width: 2
yaxis:
  - decimals: 0
    min: ~980
    max: ~1045
entities:
  - entity: sensor.netatmo_casetta_studio_pressure
    name: Pressione
    group_by:
      duration: 1h
      func: avg
```

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/6011536/165247217-6a7431ae-923a-44b3-9d91-5b751545cadd.png">

But the long term statistics show values multiplied by 100:

```
type: custom:apexcharts-card
graph_span: 1y
header:
  show: true
  title: Pressione
  show_states: true
  colorize_states: true
all_series_config:
  stroke_width: 2
  statistics:
    type: mean
    period: day
yaxis:
  - decimals: 0
    min: ~980
    max: ~1045
entities:
  - entity: sensor.netatmo_casetta_studio_pressure
    name: Pressione
    group_by:
      duration: 1w
      func: avg
```

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/6011536/165247568-4abc4f34-aa49-44fe-b73b-3df411395241.png">

**Expected behavior**

The correct value for the pressure (graph and axis)

**Desktop (please complete the following information):**

 - Browser: any (e.g. Safari, Chrome, Firefox)

**Additional context**

All the other long term statistics with the same settings are OK.
