### ISSUE TITLE
Yaxis displaying decimals incorrectly

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#336]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I have set the decimals for the Y-axis to 0. Yet, it shows decimals.

![image](https://user-images.githubusercontent.com/54566217/167628201-7d5b9a68-cd2c-4b9d-9219-0b25003d05c2.png)

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Unavailable Devices
apex_config:
  chart:
    height: 220px
  xaxis:
    labels:
      format: d/M hhtt
yaxis:
  - min: 0
    apex_config:
      decimalsInFloat: 0
      forceNiceScale: true
graph_span: 24h
series:
  - entity: sensor.unavailable_devices
    extend_to: false
    curve: stepline
    stroke_width: 2.5
    color: FireBrick
```
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Unavailable Devices
apex_config:
  chart:
    height: 220px
  xaxis:
    labels:
      format: d/M hhtt
yaxis:
  - min: 0
    decimals: 0
    apex_config:
      forceNiceScale: true
graph_span: 24h
series:
  - entity: sensor.unavailable_devices
    extend_to: false
    curve: stepline
    stroke_width: 2.5
    color: FireBrick
```

**Screenshots**

**Expected behavior**
I would expect the chart to have no decimals in the yaxis.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 101.0.4951.54 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaizersoje** [comment]
Any idea why this is occurring?

**Comment by softservicegit** [comment]
same for me.

**Comment by kaizersoje** [comment]
This is still occurring for me.

**Comment by vogtrj** [comment]
I've also just encountered this in a very similar use case, graphing an integer from 0 to 3 and I would like to display 0 decimals on the y-axis.

**Comment by kaizersoje** [comment]
Any update on this?

**Comment by rvegele** [comment]
same

**Comment by AleXSR700** [comment]
Why are you using decimalsInFloat?

Just setting `decimals` works for me.
```
    yaxis:
      - id: first
        show: true
        decimals: 10
      - id: second
        show: true
        decimals: 2
```

**Comment by vogtrj** [comment]
I use decimals as you describe and it has no effect for me. In my case, I'm trying to get my y-axis lables to display a whole number but instead I'm seeing 1.0, 2.0, 3.0, etc.

Changing the decimals setting doesn't seem to have any effect at all on the number of decimal places being displayed on the y-axis.

    yaxis:
      - min: 0
        max: 3
        decimals: 0
        apex_config:
          labels:
            show: true
          tickAmount: 3

**Comment by AleXSR700** [comment]
Could you post an entire card's code? I would test it in my setup then.

**Comment by vogtrj** [comment]
sure! Here it is:

    type: custom:apexcharts-card
    apex_config:
      chart:
        height: 150px
    graph_span: 16h
    header:
      show: true
      show_states: false
    yaxis:
      - min: 0
        max: 3
        decimals: 0
        apex_config:
          labels:
            show: true
          tickAmount: 3
    series:
      - entity: sensor.hrv_level
        type: area
        curve: stepline
        stroke_width: 0
        opacity: 0.8

**Comment by AleXSR700** [comment]
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 150px
graph_span: 16h
header:
  show: true
  show_states: false
yaxis:
  - min: 0
    max: 3
    decimals: 0
    apex_config:
      labels:
        show: true
      tickAmount: 3
series:
  - entity: sensor.sony_kd_75xf9005_naim_audio_av_energy_power_0
    type: area
    curve: stepline
    stroke_width: 0
    opacity: 0.8
```


![Screenshot_20221102-042440_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/199388289-3ce4ce7f-8818-4422-9094-f7fd79c2b044.jpg)

Strange. Works for me.
Do you see the same behaviour for all entities?
