### ISSUE TITLE
Stacked columns hover incorrect

### ISSUE THREAD

**Issue by energywave** [RomRider/apexcharts-card#343]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When the chart is shown as stacked columns (I'm fetching data from statistics but was the same when I loaded them from entity history) the hover of the mouse is totally screwed. It will show the wrong serie of data in the popup.
That's not only a cosmetical bug as the popup contain even the value of that portion of data, that is available only in that way.

This could be related to the stacked issue when you hide a seie clicking on the legend that I can confirm: https://github.com/RomRider/apexcharts-card/issues/254

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
title: Grafico consumi
theme: Backend-selected
path: grafico-consumi
icon: mdi:chart-areaspline
type: panel
badges: []
cards:
  - type: custom:apexcharts-card
    stacked: true
    graph_span: 24h
    update_interval: 1min
    all_series_config:
      type: column
      statistics:
        type: mean
        period: hour
        align: middle
    series:
      - entity: sensor.altro_power
        name: Altro
      - entity: sensor.luci_power
        name: Luci
      - entity: sensor.lavanderia_power
        name: Lavanderia
      - entity: sensor.cucina_power
        name: Cucina
      - entity: sensor.condizionatori_power
        name: Condizionatori
      - entity: sensor.pompa_piscina_power
        name: Piscina
      - entity: sensor.tv_power
        name: TV
      - entity: sensor.tapparelle_power
        name: Tapparelle
    apex_config:
      chart:
        height: 940px
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2051567/171420738-409b251d-eb3e-41f3-bc92-b320cc0ff4b3.png)

**Expected behavior**
the popup must show the correct data the mouse is over

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 101
