### ISSUE TITLE
FR: allow template on graph_span

### ISSUE THREAD

**Issue by Mariusthvdb** [RomRider/apexcharts-card#344]
**Checklist**
- [X ] I am running the latest version of the card
- [ X] I checked if there isn't another feature request opened with the same request
- [X ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

using a template in the graph_span field yields:
<img width="496" alt="Schermafbeelding 2022-06-02 om 09 51 24" src="https://user-images.githubusercontent.com/33354141/171585485-d92738ff-e68d-4a95-91a1-90b24326f7c9.png">

**Describe the solution you'd like**

would love to natively be able to do:
```
graph_span: >
  [[[ states['input_select.apex_span'].state; ]]]
```

**Describe alternatives you've considered**
currently do:
```
type: custom:config-template-card
entities:
  - input_select.apex_span
variables:
  span: states['input_select.apex_span'].state
card:

  type: custom:apexcharts-card
  graph_span: ${span}
```

**Additional context**

even though 
```
        graph_span: >
          [[[
            switch (states['input_select.ui_pool_select_measure_period'].state) {
              case "Mois":
                return "4w";
                break
              case "Semaine":
                return "1w";
                break;
              case "Jour":
                return "1d";
                break;
            }
          ]]]
```
was posted and apparently used in a valid card config

more-info: https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1639

my card: https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1495

my input_select holds the correct options:

<img width="1038" alt="Schermafbeelding 2022-06-02 om 09 52 28" src="https://user-images.githubusercontent.com/33354141/171585346-471ead1e-2342-44a8-8a64-9250821b1d96.png">

<img width="525" alt="Schermafbeelding 2022-06-02 om 10 23 58" src="https://user-images.githubusercontent.com/33354141/171587663-3a8a53ac-a049-4c25-b4e2-7c21814cff3c.png">
<img width="513" alt="Schermafbeelding 2022-06-02 om 10 24 14" src="https://user-images.githubusercontent.com/33354141/171587679-cbf75a5e-6ed2-4456-bdc6-5bf1d796fa88.png">

full working card config:

```
type: entities
title: 'Energie: verbruik - levering'
card_mod:
  style: |
    .card-header {
      font-weight: 400;
      font-size: 20px;
      color: {% if states('sensor.netto_verbruik')|int(default=0) < 0 %} var(--primary-color)
             {% else %} var(--text-color-off)
            {% endif %};
      padding: 0px 12px;
      margin: 0px 0px 16px 0px;
      background: {% if states('sensor.netto_verbruik')|int(default=0) < 0 %} gold
                  {% else %} var(--background-color-off)
                  {% endif %};
    }
entities:
  - type: custom:hui-element
    card_type: glance
    card_mod: &mod
      style: |
        ha-card {
          box-shadow: none;
          margin: -8px -16px 0px -16px;
        }
    entities:
      - sensor.levering_of_verbruik
      - entity: sensor.calculated_bruto_verbruik
        name: Bruto verbruik
      - entity: sensor.zp_actuele_opbrengst
        name: Solar production

  - !include /config/lovelace/includes/include_verbruik_actueel_apex.yaml
  - entity: input_select.apex_span
 ```

and ofc the include_verbruik_actueel_apex.yaml:

```
type: custom:config-template-card
entities:
  - input_select.apex_span
variables:
  span: states['input_select.apex_span'].state
card:

  type: custom:apexcharts-card
  card_mod:
    style: |
      ha-card {
        box-shadow: none;
        margin: -8px -16px -16px -16px;
        padding: 0;
      }
  #header:
  #  title: Verbruik actueel
  update_interval: 1min
  graph_span: ${span}
  series:
    - entity: sensor.zp_actuele_opbrengst
      color: gold
      type: area
      name: Zon
      stroke_width: 3
      opacity: 0.5
    - entity: sensor.calculated_bruto_verbruik
      color: darkblue
      name: Verbruik
      group_by:
        func: avg
        duration: 2min
      stroke_width: 1
    - entity: sensor.netto_verbruik
      color: lightblue
      type: area
      name: Vermogen
      group_by:
        func: avg
        duration: 2min
      stroke_width: 3
      opacity: 0.5
```
