### ISSUE TITLE
Apex charts using local device time and not home assistant time

### ISSUE THREAD

**Issue by jack5mikemotown** [RomRider/apexcharts-card#349]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Apexcharts bases time off the local device time. For example, the following will have a graph that starts at 10am and goes until 10pm, but this time is always in local time, so if my home assistant is in GMT -4 and I am in GMT -4, it will show me the proper time. But if I am in GMT -5, the graph will show me 10am-10pm GMT-5 time, and the time will be an hour delayed from what I want to show, which is GMT -4, since that is where my home assistant is located.

  ```
graph_span: 12h
  span:
            start: day
            offset: +10h
```
**Version of the card**
Version:

**To Reproduce**
This is the configuration I used: v 2.0.1
```yaml
type: custom:apexcharts-card
          update_interval: 15s
          header:
            show: false
            show_states: true
            colorize_states: true
          graph_span: 12h
          span:
            start: day
            offset: +10h
          series:
            - entity: sensor.lexus
              attribute: Speed (OBD)(mph)
              type: area
              opacity: 0.7
              stroke_width: 1
              name: Speed
              color: 3498db
              show:
                legend_value: false
          yaxis:
            - id: first
              max: ~80
              min: 0
              decimals: 0
              apex_config:
                tickAmount: 4
                labels:
                  offsetX: -10
          layout: minimal
          now:
            show: true
            label: Now
          show:
            last_updated: true
          apex_config:
            chart:
              parentHeightOffset: 20
```

**Screenshots**
This is the graph taken in GMT -5 
![Screenshot 2022-06-09 1 15 34 PM](https://user-images.githubusercontent.com/72000916/172916457-7e6c31ee-f181-42b6-8920-314d85d272cf.png)
This is the same graph taken in GMT -4 a minute later
![Screenshot 2022-06-09 2 15 11 PM](https://user-images.githubusercontent.com/72000916/172916485-fb26db6e-47a5-4de3-8ab7-8f372d9930dc.png)

**Expected behavior**
I expect the chart to be displayed based on the time set by home assistant
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Chromebook]
 - OS: [ChromeOS]
 - Browser [Chrome]
 - Version [Version 101.0.4951.72 (Official Build) (64-bit)]

**Additional context**
