### ISSUE TITLE
Flat line at the end of "grouped by" serie

### ISSUE THREAD

**Issue by jrlacharnay** [RomRider/apexcharts-card#353]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
A flat line appears at the end of "grouped by average" series.
It was not the case a few months ago (and I didn't update my card conf at all in between), but I cannot say exactly which version brought this bug.

**Version of the card**
Version: v2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
series:
  - entity: sensor.temperature_chambre1
    name: Chambre 1
    group_by:
      func: avg
      duration: 60min
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20613054/174004102-3d477d50-1f4e-4ef0-862d-099d1fbca161.png)

Where this flat line is not visible in the standard history graph of HA :
![image](https://user-images.githubusercontent.com/20613054/174004210-0cb5794d-2060-48da-b320-5fd60ed862d1.png)

**Expected behavior**
This flat line does not correspond to a real value and should not be displayed.

**Desktop:**
 - Browser: Firefox
 - Version: 101.0.1 (64 bits)

**Additional context**

Actually, this is worst when I add a new serie, grouped by "last":

```yaml
type: custom:apexcharts-card
series:
  - entity: sensor.clim_temperature_cible
    name: Cible
    group_by:
      func: last
      duration: 2min
  - entity: sensor.temperature_chambre1
    name: Chambre 1
    group_by:
      func: avg
      duration: 60min
```

This new serie is not visible here because its value is "off" (not a number) at the moment, but even with a numeric value, I remember the side effect was still there.

![image](https://user-images.githubusercontent.com/20613054/174004804-a0c8a8e3-e46a-41d2-8b90-2390b269b86c.png)

Thank you!
