### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by lubbergerc** [RomRider/apexcharts-card#356]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
While editing a dashboard, the line charts start at the very left of the card (as expected). But when I turn off the dashboard's editing mode, parts of the lines disappear. When multiple series are shown on the same card, they all start at a different point in time, but data is always missing from the left. Looking at the corresponding SVG elements reveiled that the data is actually missing. Turning off the cache via the card's configuration fixes the issue, though.

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
cache: true
header:
  show: true
  title: Erdgeschoss
  show_states: true
  colorize_states: true
graph_span: 130min
update_interval: 1min
apex_config:
  yaxis:
    align_to: 0.1
  grid:
    borderColor: '#555555'
  legend:
    show: false
all_series_config:
  stroke_width: 2
  fill_raw: last
  attribute: current_temperature
  curve: smooth
  group_by:
    duration: 1min
    func: avg
color_list:
  - '#3fb950'
  - '#d29922'
  - '#ff7b72'
  - '#58a6ff'
  - '#f778ba'
series:
  - entity: climate.thermostat_eg_kuche
    name: Küche
  - entity: climate.thermostat_eg_wohnzimmer
    name: Wohnzimmer
  - entity: climate.thermostat_eg_flur
    name: Flur
  - entity: climate.thermostat_eg_gaste_wc
    name: Gäste-WC
```

**Screenshots**
![2022-06-22 15_37_23-Window](https://user-images.githubusercontent.com/26038819/175047607-0579e11f-13c1-4f09-b2e3-a396eb206c91.png)
![2022-06-22 15_38_03-Window](https://user-images.githubusercontent.com/26038819/175047612-9d1df0e3-2acf-4ac0-a202-a4ac631df6c2.png)

**Expected behavior**
All data should be displayed even with caching turned on and while not in edit mode.

**Desktop:**
 - Browser: Chrome
 - Version: 102.0.5005.115

**Smartphone:**
 - Device: iPhone12
 - OS: iOS 15.5
 - Browser: Home Assistant App
 - Version 2022.3
