### ISSUE TITLE
Minimal layout - Y offset not considered on iOS/MacOS(safari only)

### ISSUE THREAD

**Issue by Ristou** [RomRider/apexcharts-card#361]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I want to use minimal layout with graph starting at the very bottom of the card. 
No issue when I'm on desktop browser other than safari (MacOS Catalina or Windows 10).
I use mainly iOS device (Xr), issue occurs on all browser (iOS Companion app, Chrome, Safari).
Type of graph has no influence (Line, area, column, etc...).

**Version of the card**
Version: V2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
- type: horizontal-stack
  cards:
    - type: custom:apexcharts-card
      layout: "minimal"
      stacked: true
      graph_span: 7d
      series:
        - entity: sensor.teleinfo_off_peak_energy
          type: column
          name: Off-Peak Energy
          color: var(--google-blue)
          opacity: 1
          group_by:
            func: diff
            duration: 1d
        - entity: sensor.teleinfo_peak_energy
          type: column
          name: Peak Energy
          color: var(--google-blue)
          opacity: 0.4
          group_by:
            func: diff
            duration: 1d
```

**Screenshots**
| ✔️ Desired rendering | ❌ iOS/MacOS(safari Only)|
|:---------------:|:---------------:|
| <img width="300" alt="desktop" src="https://user-images.githubusercontent.com/82214530/177734078-c7c924b0-7c66-4fc6-b6b9-7c0e7e449ab9.png"> | <img width="300" alt="mobile" src="https://user-images.githubusercontent.com/82214530/177735330-fb4d860f-2af6-442e-bc6e-1b00df85d63c.png"> |

**Expected behavior**
I expect it is rendering the same way on every device.

**Desktop (please complete the following information):**
 - Browser: 
   - MacOS Catalina (❌Safari, ✔️Firefox, ✔️Chrome)
   - Windows 10 (✔️Firefox, ✔️Chrome)

**Smartphone (please complete the following information):**
 - Device: IPhone Xr
 - OS: iOS15.5
 - Browser: ❌iOS Companion app, ❌Safari, ❌Chrome

**Additional context**
No additional context
