### ISSUE TITLE
Max value not shown for all series

### ISSUE THREAD

**Issue by blackburn77** [RomRider/apexcharts-card#362]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When using extremas: max in combination with data_generator (?) the max value is not shown for all series

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I use:

```yaml


type: custom:apexcharts-card
graph_span: 23h
header:
  show: true
  title: Nordpool
span:
  start: day
now:
  show: true
  color: 357DA7
yaxis:
  - decimals: 0
    align_to: 10
apex_config:
  stroke:
    curve: stepline
  markers:
    size: 4
    strokeWidth: 0
    hover:
      sizeOffset: 2
  grid:
    show: true
    strokeDashArray: 0
    position: back
    xaxis:
      lines:
        show: true
all_series_config:
  stroke_width: 3
  show:
    legend_value: false
    extremas: max
    offset_in_name: false
series:
  - entity: sensor.nordpool_kwh_se3_sek_2_10_0
    name: Today
    color: 357DA7
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        return [new Date(entry.start), entry.value * 100];
      });    
  - entity: sensor.nordpool_kwh_se3_sek_2_10_0
    name: Tomorrow
    color: DD4B39
    offset: +1d
    data_generator: |
      return entity.attributes.raw_tomorrow.map((entry) => {
        return [new Date(entry.start), entry.value * 100];
      }); 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6384288/178160242-667b903c-ecfb-47e2-8a62-62c510c336b9.png)

**Expected behavior**
Max value shown on the blue "Today" curve just like on the red "Tomorrow" curve

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [103.0.5060.114]

**Smartphone (please complete the following information):**
 - Device: [iPhone 12]
 - OS: [iOS 15.5]
 - Browser [Safari]

**Additional context**
When using regular entities (i.e not data_generator ones) the max value is shown for all series.
