### ISSUE TITLE
Chart disappeared, console error logs are shown

### ISSUE THREAD

**Issue by Gollam** [RomRider/apexcharts-card#37]
Hi,
I've left home assistant dashboard opened for a while on a tab. When I went back, the charts were only a white rectangle, and the console had this kind of errors:

![image](https://user-images.githubusercontent.com/765342/106500531-3d4fb900-64c2-11eb-9945-545ccdcdbf83.png)
![image](https://user-images.githubusercontent.com/765342/106500564-43de3080-64c2-11eb-9358-050bf7025edf.png)

**Comment by Gollam** [comment]
Opening the charts on a new tab loads the charts correctly, the failed tab still only shows the error logs.

**Comment by RomRider** [comment]
Do you know how much time it took to get to this state?

Also, could you please share your config to see if I see something that would generate this issue?

**Comment by Gollam** [comment]
It didn't take too long, 20-30 minutes max. I have configured 5 apex charts, 2 of them are still working (and updating!) till this minue on that tab, and 3 went to this state.

the failed ones:

```
      - type: custom:apexcharts-card
        header:
          show: true
          title: hőmérséklet
        graph_span: 24h
        series:
          - entity: sensor.benti_homero_temperature
            name: benti
            float_precision: 2
            color: '#C9341C'
          - entity: sensor.kinti_homero_temperature
            name: kinti
            color: '#0191C8'
            float_precision: 2
        apex_config:
          stroke:
            width: 2
          grid:
            strokeDashArray: 0
            xaxis:
              lines:
                show: true
      - type: custom:apexcharts-card
        header:
          show: true
          title: páratartalom
        graph_span: 24h
        series:
          - entity: sensor.benti_homero_humidity
            name: benti
            float_precision: 2
            color: '#C9341C'
          - entity: sensor.kinti_homero_humidity
            name: kinti
            color: '#0191C8'
            float_precision: 2
        apex_config:
          stroke:
            width: 2
          grid:
            strokeDashArray: 0
            xaxis:
              lines:
                show: true
        - type: entities
          title: Konnektorok
          entities:
            - entity: switch.0x04cf8cdf3c7c114e
              name: hálószoba
            - entity: switch.nappali_konnektor
              name: nappali
        - type: custom:apexcharts-card
          graph_span: 24h
          series:
            - entity: sensor.0x04cf8cdf3c7c114e_power
              name: hálószoba
            - entity: sensor.nappali_konnektor_power
              name: nappali
          apex_config:
            stroke:
              width: 2
            grid:
              strokeDashArray: 0
              xaxis:
                lines:
                  show: true
```
the working ones:

```
      - type: custom:apexcharts-card
        header:
          show: true
          title: net sebesség
        graph_span: 24h
        series:
          - entity: sensor.speedtest_download
            name: le
          - entity: sensor.speedtest_upload
            name: fel
        apex_config:
          stroke:
            width: 2
          grid:
            strokeDashArray: 0
            xaxis:
              lines:
                show: true
          tooltip:
            followCursor: true
            fixed:
              enabled: false
      - type: custom:apexcharts-card
        header:
          show: true
          title: kinti hőmérséklet (7 nap)
        graph_span: 7d
        span:
          end: day
        series:
          - entity: sensor.kinti_homero_temperature
            group_by:
              duration: 24h
              func: max
            curve: straight
            extend_to_end: false
            name: max
            float_precision: 2
            color: '#C9341C'
          - entity: sensor.kinti_homero_temperature
            group_by:
              duration: 24h
              func: avg
            name: átlag
            float_precision: 2
            curve: straight
            extend_to_end: false
            color: '#99CC00'
          - entity: sensor.kinti_homero_temperature
            group_by:
              duration: 24h
              func: min
            color: '#0191C8'
            curve: straight
            extend_to_end: false
            name: min
            float_precision: 2
        apex_config:
          stroke:
            width: 2
          markers:
            size: 4
          grid:
            strokeDashArray: 0
            xaxis:
              lines:
                show: true
```
