### ISSUE TITLE
As graph_span: value increases some series become very wrong.

### ISSUE THREAD

**Issue by alexeiw123** [RomRider/apexcharts-card#379]
**Checklist**
- [ yes ] I updated the card to the latest version available
- [ yes ] I cleared the cache of my browser
- [ yes ] I verified that I'm really running the lastest version in my browser console
- [ yes ] I checked if there is another issue opened with the same problem

**Describe the bug**
As `graph_span:` value increases, some entities become incorrect.
The upper `graph_span:` value that triggers this bug seems to increase with time. I followed it up to beyond 24h yesterday, but today it was back to less than 24h.
In order to stack some values but not all, I am using `stacked: true` with a variation of >
```
group_by:
  func: avg
```
or >
```
group_by:
  func: raw
```
I didn't see this behaviour before getting the 'stacked' view to appear as I intended.

I have also observed that by  increasing the time period for duration that the noise reduces but does not get eliminated >
```
group_by:
  func: avg
    duration: 20s
```

**Version of the card**
v2.0.1

**To Reproduce**
This is the configuration I used - it will show 3 cards to allow testing of different `graph_span:` values
The only difference in the yaml for each card is the `graph_span:` value and the `title:` value for the header.
```yaml
views:
  - title: Home
    cards:
      - type: custom:apexcharts-card
        graph_span: 24h
        stacked: true
        all_series_config:
          stroke_width: 1
          unit: kW
          curve: smooth
          opacity: 1
          group_by:
            func: avg
            duration: 20s
            fill: zero
          type: area
          invert: true
          fill_raw: zero
          extend_to: now
          transform: return x / 1000;
          show:
            legend_value: false
        color_list:
          - '#7bc043'
          - '#ee4035'
          - '#0392cf'
          - '#1a936f'
          - '#c6dabf'
          - purple
          - orange
          - brown
          - pink
          - cyan
        apex_config:
          chart:
            height: 175%
        span:
          end: minute
        header:
          show: true
          title: Power 24 hours
        series:
          - entity: sensor.solar_power_corrected_1m
            name: Generation
            type: line
            invert: false
            group_by:
              func: raw
          - entity: sensor.envoy_current_power_consumption
            name: Consumption
            type: line
            group_by:
              func: raw
          - entity: sensor.grid_net_power_1m
            name: Grid Net
            type: line
            group_by:
              func: raw
          - entity: sensor.EV_charger_load_w
            name: EV Charger
          - entity: sensor.hot_water_system_supply_switch_0_power
            name: Hot Water
          - entity: sensor.arlec_sw_washer_power
            name: Washer
          - entity: sensor.arlec_sw_dryer_power
            name: Dryer
          - entity: sensor.sw2_tvmedia_power
            name: TV & Media
          - entity: sensor.eko_sw_dishwasher_power
            name: Dishwashwer
          - entity: sensor.eko_sw_study_power
            name: Study
        yaxis:
          - id: first
            decimals: 0
            show: true
            apex_config:
              forceNiceScale: true
              title:
                text: kW
      - type: custom:apexcharts-card
        graph_span: 20h
        stacked: true
        all_series_config:
          stroke_width: 1
          unit: kW
          curve: smooth
          opacity: 1
          group_by:
            func: avg
            duration: 20s
            fill: zero
          type: area
          invert: true
          fill_raw: zero
          extend_to: now
          transform: return x / 1000;
          show:
            legend_value: false
        color_list:
          - '#7bc043'
          - '#ee4035'
          - '#0392cf'
          - '#1a936f'
          - '#c6dabf'
          - purple
          - orange
          - brown
          - pink
          - cyan
        apex_config:
          chart:
            height: 175%
        span:
          end: minute
        header:
          show: true
          title: Power 20 hours test
        series:
          - entity: sensor.solar_power_corrected_1m
            name: Generation
            type: line
            invert: false
            group_by:
              func: raw
          - entity: sensor.envoy_current_power_consumption
            name: Consumption
            type: line
            group_by:
              func: raw
          - entity: sensor.grid_net_power_1m
            name: Grid Net
            type: line
            group_by:
              func: raw
          - entity: sensor.EV_charger_load_w
            name: EV Charger
          - entity: sensor.hot_water_system_supply_switch_0_power
            name: Hot Water
          - entity: sensor.arlec_sw_washer_power
            name: Washer
          - entity: sensor.arlec_sw_dryer_power
            name: Dryer
          - entity: sensor.sw2_tvmedia_power
            name: TV & Media
          - entity: sensor.eko_sw_dishwasher_power
            name: Dishwashwer
          - entity: sensor.eko_sw_study_power
            name: Study
        yaxis:
          - id: first
            decimals: 0
            show: true
            apex_config:
              forceNiceScale: true
              title:
                text: kW
      - type: custom:apexcharts-card
        graph_span: 19h
        stacked: true
        all_series_config:
          stroke_width: 1
          unit: kW
          curve: smooth
          opacity: 1
          group_by:
            func: avg
            duration: 20s
            fill: zero
          type: area
          invert: true
          fill_raw: zero
          extend_to: now
          transform: return x / 1000;
          show:
            legend_value: false
        color_list:
          - '#7bc043'
          - '#ee4035'
          - '#0392cf'
          - '#1a936f'
          - '#c6dabf'
          - purple
          - orange
          - brown
          - pink
          - cyan
        apex_config:
          chart:
            height: 175%
        span:
          end: minute
        header:
          show: true
          title: Power 19 hours test
        series:
          - entity: sensor.solar_power_corrected_1m
            name: Generation
            type: line
            invert: false
            group_by:
              func: raw
          - entity: sensor.envoy_current_power_consumption
            name: Consumption
            type: line
            group_by:
              func: raw
          - entity: sensor.grid_net_power_1m
            name: Grid Net
            type: line
            group_by:
              func: raw
          - entity: sensor.EV_charger_load_w
            name: EV Charger
          - entity: sensor.hot_water_system_supply_switch_0_power
            name: Hot Water
          - entity: sensor.arlec_sw_washer_power
            name: Washer
          - entity: sensor.arlec_sw_dryer_power
            name: Dryer
          - entity: sensor.sw2_tvmedia_power
            name: TV & Media
          - entity: sensor.eko_sw_dishwasher_power
            name: Dishwashwer
          - entity: sensor.eko_sw_study_power
            name: Study
        yaxis:
          - id: first
            decimals: 0
            show: true
            apex_config:
              forceNiceScale: true
              title:
                text: kW

```

**Screenshots**
3 cards with bug showing on the first two:
![image](https://user-images.githubusercontent.com/77809797/184557735-cd747907-a9ac-428b-9bc5-8f731317acfb.png)
entity: sensor.envoy_current_power_consumption history shown over the same time period for comparison:
![image](https://user-images.githubusercontent.com/77809797/184558370-0f65c6d7-2869-4aaf-9bca-db860caa63d4.png)

**Expected behavior**
Expected no noise on 'consumption' and 'grid net' series, regardless of span length.

**Desktop (please complete the following information):**
 - Chrome Windows 104.0.5112.81 (Official Build) (64-bit)
 - Also on HA companion app Android.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - HA Companion App

**Comment by RomRider** [comment]
This is because you use average as a `group_by` function and fill missing values with 0s
Try removing it, or try changing the fill parameter.

This is the part which you should modify
```yaml
          group_by:
            func: avg
            duration: 20s
            fill: zero
```
