### ISSUE TITLE
header: colorize_states: true does not seem to reflect latest value

### ISSUE THREAD

**Issue by jchhenderson** [RomRider/apexcharts-card#382]
**Checklist**
- [.] I updated the card to the latest version available
- [.] I cleared the cache of my browser
- [.] I verified that I'm really running the lastest version in my browser console
- [.] I checked if there is another issue opened with the same problem

**Describe the bug**
The color of the state in the header is always the same (looks orange to me) regardless of the last value of the line

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
- type: custom:apexcharts-card
  update_interval: 5m
  graph_span: 48h
  header:
    title: Outside
    show: true
    show_states: true
    colorize_states: true
  show:
    last_updated: true
  all_series_config:
    curve: smooth
    show:
      legend_value: false
  experimental:
    color_threshold: true
  series:
    - entity: sensor.outside_temp
      fill_raw: last
      show:
        extremas: true
        legend_value: false
      color_threshold:
        - value: -10
          color: '#000fff' # Blue <------------------
        - value: 3
          color: '#002aff' # Blue (RYB)
        - value: 4
          color: '#055fff' # Blye (RYB)
        - value: 5
          color: '#0080ff' # Azure
        - value: 6
          color: '#00aaff' # Capri
        - value: 7
          color: '#00f5ff' # Capri
        - value: 8
          color: '#00ffff' # Aqua  <-----------------
        - value: 9
          color: '#00ffd5' # Bright turquoise
        - value: 10
          color: '#00ffaa' # Medium spring green
        - value: 11
          color: '#00ff80' # Guppie green
        - value: 12
          color: '#00ff55' # Malachite
        - value: 13
          color: '#00ff2a' # Electric green
        - value: 14
          color: '#00ff00' # Electric green <--------
        - value: 15
          color: '#2bff00' # Harlequin
        - value: 16
          color: '#55ff00' # bright green
        - value: 17
          color: '#80ff00' # green
        - value: 18
          color: '#aaff00' # Spring bud
        - value: 19
          color: '#d4ff00' # electric lime
        - value: 20
          color: '#ffff00' # electric yellow
        - value: 21
          color: '#ffd500' # Gold (web) (Golden)
        - value: 22
          color: '#ffaa00' # Chrome yellow
        - value: 23
          color: '#ff8000' # Orange (color wheel)
        - value: 24
          color: '#ff5500' # International Orange
        - value: 25
          color: '#ff2a00' # Ferarri red
        - value: 26
          color: '#ff0000' # red <--------
        - value: 27
          color: '#ff002b' # Ruddy
        - value: 28
          color: '#ff0055' # folly
        - value: 29
          color: '#ff0080' # Bright pink
        - value: 30
          color: '#ff00aa' # Fashion Fuchsia 
        - value: 31
          color: '#ff00d4' # Shocking pink
        - value: 32
          color: '#ff00ff' # Fuchsia  <-------------
        - value: 33
          color: '#d400ff' # Phiox
        - value: 34
          color: '#aa00ff' # Vivid violet
        - value: 35
          color: '#8000ff' # Violet (colour wheel)
        - value: 36
          color: '#5000ff' # Electric ultramarine
        - value: 37
          color: '2b00ff' # Electric ultramarine
    - entity: sensor.hottest_temp 
      name: Hottest inside
      type: area
      fill_raw: last
      opacity: 1
      color: "#444444"
      show:
        in_header: false
    - entity: sensor.coolest_temp
      name: Coolest inside
      type: area
      fill_raw: last
      opacity: 1
      color: var(--card-background-color)
      show:
        in_header: false
```

**Screenshots**
In both examples below, the last value of the line is green, but the header shows orange
![Screenshot 2022-08-17 at 14 15 50](https://user-images.githubusercontent.com/34644672/185143675-e4cea74c-e68a-4ee8-9f66-e4b4ca3fea2c.png)

**Expected behavior**
I would expect the colour of the state in the header to match the colour of the last value in the line of that sensor/entity

**Desktop (please complete the following information):**
 - Browser Safari (on MacOS)
 - Version 15.6

**Smartphone
 (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 15.6
 - Browser iOS app
 - Version latest (auto updates)

**Additional context**
Same also on iPad.  Maybe this is an Apple issue.

**Comment by jchhenderson** [comment]
anyone?

**Comment by RomRider** [comment]
You should use
```
    - entity: sensor.outside_temp
      fill_raw: last
      show:
        extremas: true
        legend_value: false
        header_color_threshold: true  # <--- I've added this
```
