### ISSUE TITLE
color_threshold not adapted for locale settings

### ISSUE THREAD

**Issue by gigatexel** [RomRider/apexcharts-card#396]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
!! experimental feature

My PV-system outputs a sensor that uses the locale setting for decimal (point).
The experimental color_threshold feature does not take this point into account

![image](https://user-images.githubusercontent.com/65073191/190636544-1cd10ff4-2f86-49a7-9322-34cfc81373e9.png)

**Version of the card**
Version:

**To Reproduce**
This is the configuration does not work:
```yaml
        color_threshold:
          - value: 250
            color: '#FF8E15'
          - value: 500
            color: '#FAB733'
          - value: 1250
            color: '#ACB334'
          - value: 1750
            color: '#69B34C'
```
This is the configuration does not work:
```yaml
        color_threshold:
          - value: 0.250
            color: '#FF8E15'
          - value: 0.500
            color: '#FAB733'
          - value: 1.250
            color: '#ACB334'
          - value: 1.750
            color: '#69B34C'
```

**Comment by RomRider** [comment]
The point is just a display feature on the chart. A number should be expressed without any formatting in the configuration as it is the case for any other piece of configuration in Home Assistant.

**Comment by gigatexel** [comment]
You are right, I was on the wrong path,but still it does not work as expected.

```
type: custom:stack-in-card
cards:
  - type: custom:apexcharts-card
    experimental:
      color_threshold: true
    chart_type: radialBar
    series:
      - entity: sensor.pv_power_numeric
        color_threshold:
          - value: 0
            color: blue
          - value: 1500
            color: cyan
          - value: 1700
            color: green
          - value: 2000
            color: orange
        max: 2610
        show:
          legend_value: false
    apex_config:
      plotOptions:
        radialBar:
          offsetY: 0
          startAngle: -108
          endAngle: 108
          hollow:
            size: 70%
          dataLabels:
            name:
              show: false
            value:
              show: false
          track:
            strokeWidth: 80%
            margin: 0
      fill:
        type: solid
      legend:
        show: false
      chart:
        height: 240
  - type: custom:mushroom-entity-card
    entity: sensor.pv_power_numeric
    primary_info: state
    secondary_info: name
    name: Vermogen
    icon: mdi:lightning-bolt
    icon_color: green
    layout: vertical
    card_mod:
      style: |
        ha-card {
          margin-top: -90px;
          width: 140px;
          margin-left: auto;
          margin-right: auto;
        }

```

Always colors blue
