### ISSUE TITLE
color_threshold gives incorrect coloring when fill_raw is 'null' (or unspecified) and data is missing,

### ISSUE THREAD

**Issue by jpettitt** [RomRider/apexcharts-card#397]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the latest version in my browser console
- [x] I checked if there is another issue opened with the same problem. possible dupe of #202 and #305

**Describe the bug**
If there is a gap in the data and `fill_raw` is missing or set to `null` color_threshold paints incorrect colors.

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
  - type: custom:apexcharts-card
    graph_span: 24h
    update_interval: 1min
    apex_config:
      chart:
        height: 200px
      grid:
        show: false
      xaxis:
        axisBorder:
          show: false
        axisTicks:
          show: false
        spanGaps: false
    experimental:
      color_threshold: true
    header:
      show: true
      show_states: true
      colorize_states: true
    series:
      - entity: sensor.yuba_crest_temp
        color: grey
        opacity: 1
        stroke_width: 3
        name: Outside
        type: line
        show:
          legend_value: false
          in_chart: true
          header_color_threshold: true
          extremas: true
        yaxis_id: Temperature
        color_threshold:
          - value: 0
            color: rgb(224,123,222)
          - value: 20
            color: rgb(187, 116, 212)
          - value: 30
            color: rgb(116, 92, 219)
          - value: 40
            color: rgb(23, 210, 227)
          - value: 50
            color: rgb(0,215,144)
          - value: 60
            color: rgb(94,210,48)
          - value: 70
            color: rgb(255,255,101)
          - value: 80
            color: rgb(250,130,46)
          - value: 90
            color: rgb(180,35,17)
          - value: 100
            color: rgb(175,0,0)
    yaxis:
      - id: Temperature
        show: true
        align_to: 5
        decimals: 0

```

**Screenshots**
Screenshot with no `fill_raw` or `fill_raw: 'null'`
<img width="475" alt="image" src="https://user-images.githubusercontent.com/524856/190793078-0c369794-f38d-4c7d-81ec-aad19737a299.png">

Screenshot with `fill_raw: 'last'`

<img width="471" alt="image" src="https://user-images.githubusercontent.com/524856/190794724-88b28532-9508-4341-95a5-1ce38f91d44a.png">

**Expected behavior**
Expected chart to colorize correctly and leave. gap where data was `null`

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Version  105.0.5195.125

**Smartphone (please complete the following information):**
N/A - not tested

**Additional context**

Console errors:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/524856/190803567-52c999a7-6206-40e7-b811-8e745f170902.png">
