### ISSUE TITLE
mini-graph-card theme like

### ISSUE THREAD

**Issue by terminet85** [RomRider/apexcharts-card#41]
I would like share the config to get a "mini-graph-card" like graph theme.

![immagine](https://user-images.githubusercontent.com/14027613/106721250-b5be9300-6604-11eb-8bfc-33a91968f7f5.png)

```
apex_config:
  chart:
    height: 130%
  stroke:
    width: 3
  fill:
    type: solid
    opacity: 0.2
```
