### ISSUE TITLE
fill_raw: zero does not work

### ISSUE THREAD

**Issue by elektrinis** [RomRider/apexcharts-card#414]
**Describe the bug**
I have an entity without values during the night, and those values are not being filled with zeros, which messes up the graph when curve is set to "smooth". Not clear in what cases this should work.

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 72h
span:
  end: day
  offset: +1d
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: false
  float_precision: 1
  extend_to: false
  unit: kW
series:
  - entity: sensor.solcast_forecast_this_hour
    stroke_width: 1
    color: red
    fill_raw: zero
    curve: smooth
    offset: +1h
  - entity: sensor.solcast_forecast_next_hour
    stroke_width: 1
    color: orange
    type: area
    fill_raw: zero
    curve: stepline
```

**Screenshots**
https://i.imgur.com/m1QCbXs.png

**Expected behavior**
I would expect the values to be filled with zeros and "smooth" curve would be zero during the night. Because now it is growing from last value in the evening to first value in the morning, which is not zero.

**Desktop (please complete the following information):**
 - Browser Edge v106.0.1370.34 x64
