### ISSUE TITLE
Heatmap Charts

### ISSUE THREAD

**Issue by arthurbenemann** [RomRider/apexcharts-card#415]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Would like support for ApexCharts heatmaps, as shown at https://apexcharts.com/javascript-chart-demos/heatmap-charts/

**Describe the solution you'd like**
Ideally with: `chart_type:  heatmap`

**Describe alternatives you've considered**
I tried the custom configuration, and it kind of works. Y-axis and X-Axis appear correct, but the series are still plotted as lines.
```
type: custom:apexcharts-card
apex_config:
  chart:
    type: heatmap
graph_span: 14d
span:
  end: day
show:
  last_updated: true
series:
  - entity: sensor.inverter_xxxx_energy_daily
    group_by:
      func: max
      duration: 1d
  - entity: sensor.inverter_xxxx_energy_daily
    group_by:
      func: max
      duration: 1d
...
```
![image](https://user-images.githubusercontent.com/3289118/194735441-bbd539d9-56b9-4812-a2ad-c4f9fab3e670.png)

**Additional context**
Related Home-assistant thread: https://community.home-assistant.io/t/heatmap-card-in-lovelace/260595/6
