### ISSUE TITLE
Documentation for Pie and Donut chart

### ISSUE THREAD

**Issue by darox** [RomRider/apexcharts-card#42]
Thanks a lot for creating this card, I love it!

However, I'm missing some documentation for the usage of pie and donut charts. Unfortuantely my donut and pie charts are not beeing plot with config:
```
- type: custom:apexcharts-card
  chart_type: donut
  header:
    show: true
  series:
    - entity: sensor.stocks_cloudflare_total
      name: Cloudflare
    - entity: sensor.funds_technology_fidelity_total
      name: Global Fidelity
```

![image](https://user-images.githubusercontent.com/9934402/106750062-9edd6800-6627-11eb-8c2c-9aad328f6e72.png)

Thanks
