### ISSUE TITLE
Plus and minus calculations not working

### ISSUE THREAD

**Issue by ebogaard** [RomRider/apexcharts-card#425]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I try to calculate a value by using the current entity and subtract (-) or add (+) another entity. This has no effect on the value whatsoever.
Even If I just try to subtract or add a fixed number, this has no effect on the calculated value, for example:
```
...
    transform: return x + 2;
...
```
has no effect.

If I try division (/) or multiplication (*), this does work. For example:
```
...
    transform: return x * 2;
...
```

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
...
  - entity: sensor.delivery_to_grid_energy_produced
    type: line
    yaxis_id: twee
    transform: return x + 2;
    group_by:
      func: diff
...
```

**Expected behavior**
I expect that all transform-arithmetic have an effect on the calculated values.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 106
