### ISSUE TITLE
this is weird and i don't get why i happens

### ISSUE THREAD

**Issue by commentsonly** [RomRider/apexcharts-card#426]
following funny thing.
I wanted to have a temperature sensor as line and humidity as area.
Works like a charm.
Then I felt that I wanted to also see the dewpoint on the header (actual value only no diagram).
So I tried to trick apex by adding 3 dewpoint entities 1 visible the other 2 simply in background color so they get hidden. The effect is that both temperature and dewpoint values get displayed to the left side of the card, belonging to the left yaxis.
 This works ok .. even the value of the humidity gets displayed correct on the right side (opposite yaxis.
But the area drawn is way out of control.
And I don't get why this happens.
If I remove the fake entities it all works ok.
And it doesn't matter which fake sensors I use ... so it's not a matter of using the dewpoint sensor 3 times.
And defining a higher max: won't help either. transform x / 2 on the last sensor works bringing back the area curve but then values are all wrong.
first pic with the 3 fake entities .... second one without
![image](https://user-images.githubusercontent.com/35866491/198981765-912aa234-c5cf-4c75-9480-05bf52b5f102.png)
![image](https://user-images.githubusercontent.com/35866491/198981849-643222d3-e9ed-4276-9f45-288134f6dfb3.png)

```
type: custom:apexcharts-card
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  disable_actions: true
apex_config:
  grid:
    show: false
  legend:
    show: false
all_series_config:
  type: line
  stroke_width: 3
  group_by:
    func: median
    duration: 15min
  fill_raw: last
graph_span: 28h
show:
  last_updated: true
yaxis:
  - id: left
    apex_config:
      tickAmount: 4
    decimals: 0
    max: 30
    min: 10
    opposite: false
  - id: right
    apex_config:
      tickAmount: 6
    decimals: 0
    max: 90
    min: 20
    opposite: true
series:
  - entity: sensor.esp8266dach_bme280_temp
    show:
      extremas: true
    name: Temperatur
    color: '#ff0000'
    yaxis_id: left
  - entity: sensor.esp8266dach_calc_taup
    color: '#aaaaff'
    show:
      in_chart: false
    name: Taupunkt
    yaxis_id: left
  - entity: sensor.esp8266dach_calc_taup
    color: '#1c1c1c'
    show:
      in_chart: false
    unit: ' '
    name: ' '
    yaxis_id: left
  - entity: sensor.esp8266dach_calc_taup
    color: '#1c1c1c'
    show:
      in_chart: false
    unit: ' '
    name: ' '
    yaxis_id : left
  - entity: sensor.esp8266dach_bme280_humi
    name: Luftfeuchte
    color: '#00ddff'
    yaxis_id: right
    stroke_width: 0
    type: area
```

where did I do something that wrong on the left yaxis/entitied which does affect the right side that much.
I run out of ideas.
Likely not a bug but an unexpected behaviour.
