### ISSUE TITLE
Shared tooltip not working as expected

### ISSUE THREAD

**Issue by cziter15** [RomRider/apexcharts-card#428]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Shared tooltip working in edit mode, but breaks when using normal mode. Grouping is properly configured, I think.
Sometimes it work in normal mode, but value update (HA fetches new value) is breaking shared tooltip and only one series is displayed.

**Version of the card**
Version: APEXCHARTS-CARD  v2.0.2-dev.1

**To Reproduce**
This is the configuration I used:
```type: custom:apexcharts-card
header:
  title: Wykresy temperatur (24h)
  show: true
  show_states: true
graph_span: 24h
all_series_config:
  stroke_width: 2
  opacity: 0.2
  type: area
  group_by:
    func: avg
    duration: 1m
apex_config:
  xaxis:
    tooltip:
      enabled: false
series:
  - entity: sensor.pelletmon_pcb_kettle_boilertemp
    color: orange
  - entity: sensor.ook_room_temperature
    type: line
    opacity: 1
    color: green
  - entity: sensor.pelletmon_pcb_kettle_hotwatertemp
    color: steelblue

```

**Screenshots**
**Edit mode - notice that shared tooltip is working**
![image](https://user-images.githubusercontent.com/5003708/199928202-a9f7d2e4-fb44-4669-b623-9996ea37952a.png)
**Normal mode - notice that only one series value is displayed**
![image](https://user-images.githubusercontent.com/5003708/199928492-6cebc73d-0daf-4a41-9fef-5057f725c1d8.png)

**Expected behavior**
Shared tooltip is working properly (all series displayed).

**Comment by cziter15** [comment]
Looks like that by using statistics rather than raw history data I was able to bypass the problem. Used in_header: raw to achieve up-to-date header values and statistic interval of 5 minutes.

**Comment by cziter15** [comment]
> Encountering the same problem. @cziter15 can you elaborate on how to fix please?

I don't remember the details now as it is working almost untouched.  The only thing that breaks this chart is when there's no data for some time. To get this properly working, you need populated time window ( graph span).

Here's my YAML and it's still working for me:

```yaml
type: custom:apexcharts-card
header:
  title: Wykres temperatur
  show: true
  show_states: true
show:
  loading: false
graph_span: 24h
all_series_config:
  show:
    in_header: raw
    legend_value: false
  stroke_width: 2
  opacity: 0.1
  type: area
  statistics:
    type: mean
    align: end
    period: 5minute
apex_config:
  xaxis:
    tooltip:
      enabled: false
  tooltip:
    x:
      format: dd.MM.yyyy HH:mm
  chart:
    height: 255px
series:
  - entity: sensor.pelletmon_pcb_kettle_boilertemp
    color: darkorange
  - entity: sensor.pelletmon_pcb_kettle_hotwatertemp
    color: '#4488ff'
  - entity: sensor.ook_room_temperature
    opacity: 0.2
    color: '#447700'
```
