### ISSUE TITLE
fill_raw: last does not work with column type

### ISSUE THREAD

**Issue by hkapanen** [RomRider/apexcharts-card#429]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the latest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
A state having no value changes over sample size (a column width) will display as zero length columns for that period despite setting `fill_raw: last`. See the top graph in the attached screenshot.

**Version of the card**
Version: v2.0.1

**To Reproduce**
This is the configuration I used:
```
  - title: Test
    icon: mdi:leaf
    visible:
      - user: 4ecbe3cc14ab422ea128a0a7df7a491f  # Harri
    cards:
      - type: 'custom:apexcharts-card'
        span:
          start: day
        series:
          - entity: sensor.nordpool_kwh_fi_eur
            fill_raw: last
            yaxis_id: price
            stroke_width: 5
            type: column
        apex_config:
          yaxis:
            - id: price
              min: 0
              max: 0.3
              decimalsInFloat: 2

      - type: 'custom:apexcharts-card'
        span:
          start: day
        series:
          - entity: sensor.nordpool_kwh_fi_eur
            yaxis_id: price
            stroke_width: 1
            type: area
            curve: stepline
            extend_to: false
        apex_config:
          yaxis:
            - id: price
              min: 0
              max: 0.3
              decimalsInFloat: 2       
```

**Screenshots**
![Screenshot 2022-11-04 at 17 40 42](https://user-images.githubusercontent.com/12609858/200018596-31cdf03e-e0ce-4e71-9cce-f598108c093a.png)

**Expected behavior**
Columns should continue to repeat the last state value as with other graphs types (see the bottom graph in the screenshot).

**Desktop (please complete the following information):**
 - Browser [Safari]
 - Version [16.0]

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [iOS 15.6.1]
 - Browser [stock browser, safari]
 - Version [iOS 15.6.1]

**Additional context**
Data used in example hourly electricity price data from Nordpool.

A temporary workaround exists by using the following:

```
group_by:
  func: avg
  duration: 60min # sample size
```
