### ISSUE TITLE
Threshold for an Axis/Series

### ISSUE THREAD

**Issue by FrederikNS** [RomRider/apexcharts-card#430]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
With energy prices being through the roof, I'm keeping my house temperatures low. I'm plotting the temperature in an Apex chart. To avoid getting mold and rot, I want to keep my temperature above 17°C. It would be nice to be able to clearly visualize this lower threshold on the graph.

![image](https://user-images.githubusercontent.com/181295/200118778-924a71cb-b2cc-4515-adf6-8a3361b28a73.png)

**Describe the solution you'd like**
I would like to be able to draw a clear threshold line on my chart, that shades the entire area above or below it in a color. These charts in Grafana clearly shows that any temperature above 18.5°C and 20°C respectively is undesirable. In my case I would of course like to set the threshold value to 17°C, and shade the area below.

![image](https://user-images.githubusercontent.com/181295/200118906-eeddf22a-e63d-42c7-8352-8499e687287a.png)

Apex charts does seem to support this using "Y-axis range annotations": https://apexcharts.com/docs/annotations/

**Describe alternatives you've considered**
A tried using the color ranges, but those do not work very nicely with line charts.

**Comment by FrederikNS** [comment]
Oh, wait, I completely didn't understand the power of `apex_config`... I managed to create exactly what I wanted with this:
```
type: custom:apexcharts-card
series:
  - entity: sensor.bedroom_room_sensor_temperature
  - entity: sensor.upstairs_room_sensor_temperature
  - entity: sensor.entrance_room_sensor_temperature
  - entity: sensor.living_room_room_sensor_temperature
  - entity: sensor.kitchen_room_sensor_temperature
apex_config:
  annotations:
    yaxis:
      - y2: 17
        fillColor: '#880000'
```
Result:
![image](https://user-images.githubusercontent.com/181295/200119523-822922ec-d6ce-4f28-bd79-044dcd7255d1.png)
