### ISSUE TITLE
Problems with group by diff

### ISSUE THREAD

**Issue by rednasss** [RomRider/apexcharts-card#433]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [?] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When using the group_by func: diff option the bars shown don't add up to the total it should be.

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 72h
span:
  start: hour
  offset: '-71hr'
header:
  show: true
  title: Gas
  show_states: false
  colorize_states: true
yaxis:
  - id: left
    decimals: 2
    min: 0
    apex_config:
      forceNiceScale: true
  - id: right
    opposite: true
    show: false
series:
  - entity: sensor.daily_gas
    type: column
    stroke_width: 2
    curve: stepline
    float_precision: 3
    group_by:
      func: diff
      duration: 60min
    yaxis_id: left
  - entity: sensor.daily_gas
    type: line
    stroke_width: 2
    curve: stepline
    float_precision: 3
    yaxis_id: left
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3071416/200590582-154603e5-64b3-4a28-993e-e0a674b53aea.png)

**Expected behavior**
I expect that the total of the columns would be equal to the total of the sensor.
For example on Nov. 6, you can see 7 columns (0.09, 0.078, 0.019, 0.35, 0.427, 0.063, 0.007 => total 1.034), which don't add up to 1.827 which is the top of the blue line.
I can clearly see that there are columns missing at several parts where the blue line jumps up..

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 107.0.5304.88 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by vogon1** [comment]
Have you tried the option start_with_last: true  ?
It fixed my issues.

```
group_by:
  func: diff
  duration: 60min
  start_with_last: true
```
No clue what it actually does, but it made my graphs correct.
