### ISSUE TITLE
feature request: Transform takes sensor value at same point in time (not current value)

### ISSUE THREAD

**Issue by JCHH2** [RomRider/apexcharts-card#437]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I (**tried to) check** that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
I would like `transform:` (below) to have the option to take the sensor value at same point in time that it is plotted on the graph.  Currently it seems to only take the latest (current) sensor value 
```
transform: "return x === 'heating' ? hass.states['sensor.hive_heating_reported_target_temp'] : 5;"
```
The image below gives an indication of that I am trying to achieve; I want `transform:` (the white area) to plot exactly on top of the green/grey area so it shows not just what the 'Hive Target' is but when it was actually heating.
![image](https://user-images.githubusercontent.com/34644672/202687902-14019bad-535a-45e2-9285-2f19729f787b.png)

these are the two sensors in question:
```
- entity: sensor.hive_heating_reported_action
  name: "Hive action"
  type: area
  color: grey
  stroke_width: 0
  opacity: 0.5
  curve: stepline
  transform: "return x === 'heating' ? hass.states['sensor.hive_heating_reported_target_temp'].state : 5;"
  show:
    in_header: false
- entity: sensor.hive_heating_reported_target_temp
  name: "Hive Target"
  type: area
  curve: stepline
  color: DarkSlateGray 
  stroke_width: 2
  opacity: 0.5
```

**Describe alternatives you've considered**
I have tried making the sensor value the same as `yaxis: max:` but I cannot do this either - I can only set it to a specific number and set max to that same number, but this isn't great as it means manually setting the numbers (between winter and summer).**
![image](https://user-images.githubusercontent.com/34644672/202688211-5bf91022-e7ba-4859-93fa-5e7d4b4c779b.png)

**Additional context**
I wrote more about it [here](https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1962?u=jchh) in the community.home-assistant.io thread when I war trying to diagnose why I couldn't do this (and was looking for help).

Edit:** On reflection, I appreciate I could put the transform onto a different axis to achieve my 'alternative', so this is my current plan 'b'.
