### ISSUE TITLE
Span options are not templateable

### ISSUE THREAD

**Issue by Disane87** [RomRider/apexcharts-card#439]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I want to create a chart where my gas consumption is tracked and there is a fixed line for the monthly payment:

![image](https://user-images.githubusercontent.com/956158/203581044-819b7873-dfe9-429e-b341-4c7281488513.png)

Now the provider doesn't use the regular year for the yearly bills, he uses an own interval for his fiscal year.
For this date I have an `input_date` helper in HomeAssistant. 

Is there any chance to template this or use a fixed date to start?

**Expected behavior**
I would expect somethign like this:
```yaml
span:
  start: input_date.versorgerturnus
  offset: +365d
```

or

```yaml
span:
  start: "{{ states(input_date.versorgerturnus) }}"
  offset: +365d
```

**Version of the card**
Version: v2.0.1
