### ISSUE TITLE
Graph does not corelate with the data

### ISSUE THREAD

**Issue by Netesfiu** [RomRider/apexcharts-card#441]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The values shown on the graph does not corelate the actual data. The smaller value is shown above the one that is higher. (red line compared to blue)

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  brush: true
all_series_config:
  stroke_width: 2
graph_span: 36h
yaxis:
  - id: temp
    decimals: 1
  - id: power
    decimals: 1
    opposite: true
brush:
  selection_span: 6h
apex_config:
  chart:
    height: 300px
series:
  - entity: climate.aquatemp
    transform: return x/1000
    float_precision: 4
    attribute: power_usage
    color: orange
    opacity: 0.4
    type: area
    name: fogyasztás
    unit: kW
    stroke_width: 0
    show:
      in_brush: true
      in_chart: true
    yaxis_id: power
  - entity: climate.aquatemp
    attribute: temperature
    name: beállított
    unit: °C
    yaxis_id: temp
    color: '#5cad60'
  - entity: climate.aquatemp
    attribute: inlet_temperature
    name: jelenlegi
    yaxis_id: temp
    unit: °C
    color: '#3092d5'
  - entity: climate.aquatemp
    attribute: outlet_temperature
    name: Fűtő Höm.
    yaxis_id: temp
    unit: °C
    color: '#d6313e'
```

**Screenshots**
![kép](https://user-images.githubusercontent.com/68812986/204295175-923c394f-b736-4b1a-b1a6-08edfe7e6643.png)

![kép](https://user-images.githubusercontent.com/68812986/204297272-13f33910-595d-4ded-96ce-879174bdcb73.png)

The red and blue data ("Fűtő Hőm." and "Jelenlegi") are attributes for which i don't have any data how often they update.

**browser/mobile**
Changing the platform or the browser does not change the outcome

**Comment by RomRider** [comment]
Can you try and remove the `color` config from the series config and see if you have the same behavior?

**Comment by Mattie432** [comment]
seeing the same issue, I get mismatched data points to the axis when using the brush. This seems to happen when I set the `graph_span` to a value >2d. See the examples below, you can see the red line shift below the blue. Of note, changing the value of `selection_span` seem not to affect this at all.

@RomRider as per the previous suggestion, removing the colour does not seem to affect anything (not removing any other modifiers).

Example:

## 2d span
![looks good on 2d](https://i.imgur.com/m2rHSUG.png)

## >2d span
![not working with larger span](https://i.imgur.com/5ZrsTNp.png)


```
type: custom:apexcharts-card
header:
  show: true
  title: Thermostat
  show_states: true
  colorize_states: true
experimental:
  brush: true
apex_config:
  chart:
    height: 450px
graph_span: 2d
brush:
  selection_span: 1d
  apex_config:
    yaxis:
      show: false
yaxis:
  - id: first
    show: true
    decimals: 0
    min: 0
    max: 25
  - id: second
    min: 0
    max: 1
    show: false
  - id: third
    show: true
    decimals: 0
series:
  - entity: climate.hallway_thermostat
    attribute: temperature
    name: Set Temperature
    type: line
    curve: stepline
    unit: ' °C'
    stroke_width: 6
    float_precision: 0
    yaxis_id: first
    show:
      datalabels: false
  - entity: sensor.mean_temperature_upstairs
    yaxis_id: first
    opacity: 0.4
    color: red
    group_by:
      func: avg
      duration: 30min
  - entity: sensor.mean_temperature_downstairs
    yaxis_id: first
    opacity: 0.4
    color: lightblue
    group_by:
      func: avg
      duration: 30min
  - entity: sun.sun
    name: Nightime
    transform: 'return x === ''below_horizon'' ? 1 : 0;'
    color: grey
    type: area
    curve: stepline
    opacity: 0.2
    stroke_width: 0
    yaxis_id: second
    show:
      legend_value: false
      datalabels: false
      in_header: false
      extremas: false
      in_chart: true
      in_brush: true

```

**Comment by Mattie432** [comment]
Minimum repo. Does not seem to have any relation to the `graph_span` as suggested before. More like the graphs are on 'auto axis' despite being set to the same `yaxis_id`. Can see this by changing `var valMax = 5;` to be on a similar scale to the first graph.

![example](https://i.imgur.com/d174Czd.png)

```
type: custom:apexcharts-card
brush:
  selection_span: 1d
graph_span: 5d
experimental:
  brush: true
yaxis:
  - id: first
  - id: second
series:
  - entity: sun.sun
    yaxis_id: first
    name: Line1
    data_generator: |
      var interval = (2*60*60*1000); // 2hr
      var dateOffset = (24*60*60*1000) * 5; // 5days
      var valMax = 10;
      var valMin = 5;
      var now = new Date();
      var output = [];
      for (var d = new Date(now - dateOffset); d <= now; d.setTime( d.getTime() + interval)) {
          output.push( [new Date(d), Math.random() * (valMax - valMin) + valMin]);
      };
      return output;
    show:
      datalabels: true
  - entity: sun.sun
    yaxis_id: first
    name: Line2
    color: red
    data_generator: |
      var interval = (2*60*60*1000); // 2hr
      var dateOffset = (24*60*60*1000) * 5; // 5days
      var valMax = 5;
      var valMin = 0;
      var now = new Date();
      var output = [];
      for (var d = new Date(now - dateOffset); d <= now; d.setTime( d.getTime() + interval)) {
          output.push( [new Date(d), Math.random() * (valMax - valMin) + valMin]);
      };
      return output;
    show:
      datalabels: true
      in_brush: true
```

**Comment by Netesfiu** [comment]
Sorry for the radio silence. Commenting out the color attributes does not seem to solve the issue. Same probplem persists as @Mattie432 posted above. 
![kép](https://user-images.githubusercontent.com/68812986/212651389-4c091463-f930-4063-aeea-f2bf4ffb6928.png)
 the code:
```
type: custom:apexcharts-card
experimental:
  brush: true
all_series_config:
  stroke_width: 2
graph_span: 36h
yaxis:
  - id: temp
    decimals: 1
  - id: power
    decimals: 1
    opposite: true
brush:
  selection_span: 6h
apex_config:
  chart:
    height: 300px
series:
  - entity: sensor.hoszivattyu_kapcsolo_active_power
    transform: return x/1000
    float_precision: 4
    opacity: 0.4
    type: area
    name: fogyasztás
    unit: kW
    stroke_width: 0
    show:
      in_brush: true
      in_chart: true
    yaxis_id: power
  - entity: climate.aquatemp
    attribute: temperature
    name: beállított
    unit: °C
    yaxis_id: temp
  - entity: climate.aquatemp
    attribute: inlet_temperature
    name: jelenlegi
    yaxis_id: temp
    unit: °C
  - entity: climate.aquatemp
    attribute: outlet_temperature
    name: Fűtő Höm.
    yaxis_id: temp
    unit: °C

```
Also FYI: if you comment out attributes they'll be removed once you save the card. I think it's a lovelace's issue rather than the card's.
