### ISSUE TITLE
Allow styling of annotation point text

### ISSUE THREAD

**Issue by erikosvaldsson** [RomRider/apexcharts-card#444]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I'm unable to adjust the font size of annotations, ie labels from "now" and "extremas" options.

**Describe the solution you'd like**
Add a configuration options for the annotation font parameters.

**Describe alternatives you've considered**
Overwriting the value using apex_config prevents the card from loading.

```
          - type: custom:apexcharts-card  
            apex_config:  
              annotations:  
                points:  
                  label:  
                    style:  
                      fontSize: 30px
```

**Additional context**
Hardcoded value as far as I can tell: https://github.com/RomRider/apexcharts-card/blob/d8a65390789751ed0463acda1c9b83e1066b79d6/src/apexcharts-card.ts#L1122

Apexchart information: https://apexcharts.com/docs/options/annotations/
