### ISSUE TITLE
Extremas labels not changing color based on color threshold

### ISSUE THREAD

**Issue by SiriosDev** [RomRider/apexcharts-card#448]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Extremas labels not changing color based on color threshold

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
update_interval: 30min
graph_span: 24h
layout: minimal
header:
  show: true
  title: Temperatura Percepita
  show_states: true
  colorize_states: true
series:
  - entity: sensor.pirateweather_apparent_temperature
    stroke_width: 0
    color_threshold:
      - value: -10
        color: '#0033ff'
      - value: -8
        color: '#0963ff'
      - value: -6
        color: '#00a3ff'
      - value: -4
        color: '#01d6fe'
      - value: -2
        color: '#02f8eb'
      - value: 0
        color: '#06e9bd'
      - value: 2
        color: '#04db8c'
      - value: 4
        color: '#07c853'
      - value: 6
        color: '#07b923'
      - value: 8
        color: '#25bd0e'
      - value: 10
        color: '#62ce09'
      - value: 12
        color: '#92df07'
      - value: 14
        color: '#d1ef05'
      - value: 16
        color: '#fffe04'
      - value: 18
        color: '#ffea08'
      - value: 20
        color: '#ffd502'
      - value: 22
        color: '#fdc500'
      - value: 24
        color: '#feac07'
      - value: 26
        color: '#fb9300'
      - value: 28
        color: '#ff6f00'
      - value: 30
        color: '#ff4802'
      - value: 32
        color: '#ff2803'
      - value: 34
        color: '#ff0506'
      - value: 36
        color: '#d9031e'
      - value: 38
        color: '#b90135'
      - value: 40
        color: '#930058'
      - value: 42
        color: '#70016f'
    name: " "
    type: area
    show:
      header_color_threshold: true
      extremas: true

```

**Screenshots**
![image](https://user-images.githubusercontent.com/26876994/205958057-a9e09277-7678-4904-913c-730692d80caf.png)

**Desktop (please complete the following information):**
chrome 108.0.5359.95

**Smartphone (please complete the following information):**
 - Device: K20Pro
 - OS: android 13
 - chrome
