### ISSUE TITLE
After updating HA to 2022.12.0 apexcharts stopped working with statistics as source of the data

### ISSUE THREAD

**Issue by cziter15** [RomRider/apexcharts-card#449]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Description:**
After updating to latest home assistant core (from 2022.11.0 to 2022.12.0:
- Charts for long term statistics stopped working.
- Infinite loading spinner is displayed.

**Versions of the card:**
- 2.0.1
- master

**To Reproduce use this yaml (you need modify entity id)**
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Fuel usage for latest 30 days
  show_states: true
series:
  - entity: sensor.dzienne_zuzycie_pelletu
    statistics:
      type: state
      period: day
    name: Fuel usage
graph_span: 30d
span:
  end: day

```

**Screenshots**
![image](https://user-images.githubusercontent.com/5003708/206392049-02dc2c2a-7f07-4046-ab16-4ed35f5bfa4d.png)

**Expected behavior**
- Chart is properly displayed when the data is sourced from long term statistics.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 108.0.5359.98

**Additional context**
- Unknown command errors in console (see below).
