### ISSUE TITLE
Nordpool prices are doubled after midnight.

### ISSUE THREAD

**Issue by calstro** [RomRider/apexcharts-card#453]
I have a apex chart showing  prices from nordpool. The last couple of days the bars representing the prices have been doubled after midnight. See picture. 

![20221215_074100](https://user-images.githubusercontent.com/106167114/207793671-1c76433f-b237-4de6-b453-575400c2681e.jpg)

In the picture you can see that the labels showing correct max and min values. 
Even the line representing my energy consumption every hour is correct. 
The colors on the bars are correct too. 
The only issue is that the bars have double the length.

This happens on all my devices and when I restart HA, everything is back to normal. As shown below

![20221215_132714](https://user-images.githubusercontent.com/106167114/207862164-ede544f5-4622-411e-a208-648ed23f4810.jpg)

The card config looks like this

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 48h
apex_config:
  legend:
    show: false
  chart:
    height: 500px
    stacked: true
header:
  show: true
  show_states: true
  floating: false
  colorize_states: false
yaxis:
  - id: first
    min: 0
    max: 10
    apex_config:
      legend:
        fontsize: 30px
span:
  start: day
now:
  show: true
  label: Nu
series:
  - entity: sensor.nordpool_kwh_se3_sek_3_40_025
    show:
      in_chart: false
      header_color_threshold: true
    name: Pris Just nu
    float_precision: 4
  - entity: sensor.power_xxx
    show:
      in_chart: false
    name: Förbrukning Just nu
  - entity: sensor.accumulated_consumption_current_hour_xxx
    show:
      in_chart: false
    name: Förbrukning denna timme
    float_precision: 2
  - entity: sensor.accumulated_consumption_tibber_special
    show:
      in_chart: false
    name: Förbrukning Idag
    float_precision: 2
  - entity: sensor.nordpool_kwh_se3_sek_3_40_025
    show:
      in_header: false
      legend_value: false
      extremas: true
    type: column
    opacity: 1
    data_generator: |
      return entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
      });
    color_threshold:
      - value: 0
        color: green
        opacity: 0.5
      - value: 1
        color: lightgreen
        opacity: 0.5
      - value: 2
        color: yellow
        opacity: 0.5
      - value: 3
        color: orange
        opacity: 0.5
      - value: 4
        color: red
        opacity: 0.5
      - value: 5
        color: darkred
        opacity: 0.5
  - entity: sensor.nordpool_kwh_se3_sek_3_40_025
    type: column
    show:
      in_header: false
      legend_value: false
      extremas: true
    data_generator: |
      return entity.attributes.raw_tomorrow.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];
      });
    color_threshold:
      - value: 0
        color: green
        opacity: 1
      - value: 1
        color: lightgreen
      - value: 2
        color: yellow
      - value: 3
        color: orange
      - value: 4
        color: red
      - value: 5
        color: darkred
  - entity: sensor.accumulated_consumption_current_hour_xxx
    yaxis_id: usage
    type: line
    name: Forbruk
    group_by:
      func: max
    extend_to: false
    show:
      in_header: false
      legend_value: false
    color: rgb(100,0,255)
    opacity: 0.7
style: |
  ha-card {
     --ha-card-background: rgba(0, 0, 0, 0);
     box-shadow: none;
     margin: 5px;
     font-size: 25px;
     font-family: Segoe UI Light;
   }
```
I have looked though the logs but have not found anything related to apex-chart or nordpool integration. 

Apexchart-card is up to date, v2.0.2
The nordpool sensor are showing the correct RAW values when i inspect them in "developer tools" in home assistant.
