### ISSUE TITLE
more than 100k of:: Error: <path> attribute d: Expected number, "M 0 NaN".

### ISSUE THREAD

**Issue by MG-Sky** [RomRider/apexcharts-card#454]
**Checklist**
- [x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
thousands of errors in developer console:
apexcharts-card.js?hacstag=331701152201:1 Error: <path> attribute d: Expected number, "M 0 NaN".

**Version of the card**
Version:2.0.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
experimental:
  color_threshold: false
graph_span: 24h
show:
  last_updated: true
header:
  show: true
  title: Zewnątrz
  show_states: true
  colorize_states: true
  standard_format: false
series:
  - entity: sensor.czujnik_zewnatrz_humidity
    name: wilgotność
    stroke_width: 3
    show:
      legend_value: false
      header_color_threshold: false
    color_threshold:
      - value: 50
        color: green
      - value: 60
        color: orange
      - value: 70
        color: orangered
      - value: 80
        color: red
  - entity: sensor.czujnik_zewnatrz_temperature
    name: temperatura
    stroke_width: 3
    show:
      legend_value: false
      header_color_threshold: false
    color_threshold:
      - value: 18
        color: steelblue
      - value: 19
        color: midnightblue
      - value: 21
        color: darkgreen
      - value: 21.5
        color: green
      - value: 22
        color: darkorange
      - value: 24
        color: orange
      - value: 26
        color: red
  - entity: sun.sun
    transform: 'return x == ''above_horizon'' ? 89 : 0;'
    type: area
    curve: stepline
    stroke_width: 0
    color: '#474747'
    show:
      in_header: false
      legend_value: false


```

**Screenshots**

**Expected behavior**
no errors?

**Desktop (please complete the following information):**
 - Browser  Opera 
 - Version 93.0.4585.37

[1671091329401.log](https://github.com/RomRider/apexcharts-card/files/10234985/1671091329401.log)
