### ISSUE TITLE
Tooltip grouping doesn't work for multiple series types.

### ISSUE THREAD

**Issue by ZionFox** [RomRider/apexcharts-card#459]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser
- [*] I verified that I'm really running the lastest version in my browser console
- [*] I checked if there is another issue opened with the same problem

**Describe the bug**
Using a chart of different visual types (line and column) stops the tooltip grouping of entity values from working, and the tooltip now only selects the value of what the cursor is closest to.

**Version of the card**
Version: 2.0.2 release

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  brush: false
header:
  show: true
  title: Historic Gas Use
  show_states: true
  colorize_states: true
color_list:
  - '#9433A4'
  - '#D877E8'
  - '#2D6192'
  - '#6FA5D6'
layout: minimal
graph_span: 1month
span:
  start: month
brush:
  selection_span: 7d
  apex_config:
    yaxis:
      show: false
      decimalsInFloat: 0
    stroke:
      width: 2
now:
  show: true
  label: ''
show:
  loading: false
all_series_config:
  stroke_width: 4
  float_precision: 2
  show:
    in_brush: true
    extremas: false
  group_by:
    func: max
    duration: 1d
yaxis:
  - id: watt-m
    decimals: 2
    min: 0
    apex_config:
      tickAmount: 1
      labels:
        show: false
  - id: watt-d
    decimals: 3
    min: 0
    max: ~80
    apex_config:
      tickAmount: 1
      labels:
        show: false
  - id: pence-m
    decimals: 2
    opposite: true
    min: 0
    max: ~100
    apex_config:
      tickAmount: 1
      labels:
        show: false
  - id: pence-d
    decimals: 3
    min: 0
    max: ~10
    apex_config:
      tickAmount: 1
      labels:
        show: false
series:
  - entity: sensor.gas_consumption_today
    name: Day Consumption
    yaxis_id: watt-d
    type: column
  - entity: sensor.hb_gas_monthly_consumption
    name: Monthly Consumption
    yaxis_id: watt-m
  - entity: sensor.gas_consumption_today_cost
    name: Day Cost
    yaxis_id: pence-d
    type: column
  - entity: sensor.hb_gas_monthly_cost
    name: Monthly Cost
    yaxis_id: pence-m
```

**Screenshots**
![image of charts with different tooltips](https://i.imgur.com/ngfbPlL.png)

**Expected behavior**
The difference between column and line chart types to not have this split tooltip. It doesn't seem to be effected by `type: area` so it just seems to be specific to `type: column`

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 108.0.1

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 10, Oxygen OS 10.3.7
 - Browser Home Assistant Application
 - Version 2022.11.0-full

**Additional context**
The tooltips seem to break in the same way if the history of the data isn't complete for the chart, either. This doesn't matter of the type of grouping, but it would be nice to have this merged tooltip layout for when using a grouping set regardless of the historic values of the data.
