### ISSUE TITLE
the values in the header and in the bar chart are displayed wrong. Only in the edition mode or when i cleare the cache the values are right

### ISSUE THREAD

**Issue by Banis1** [RomRider/apexcharts-card#460]
**Checklist**
- [x] I updated the card to the latest version available
    Version 2.02
- [x] I cleared the cache of my browser
   if the cache is cleared the values are right, but i don't want to cleare every day the catche to get the right values
- [x] I verified that I'm really running the lastest version in my browser console
    yes
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I use bar chart with influx db an group_by function. Thr Problem ist that the values in the header and in the bar chart are displayed wrong. Only in the edition mode or when i cleare the cache the values are right. So if I use diffe**Checklist**
- [x] I updated the card to the latest version available
    Version 2.02
- [x] I cleared the cache of my browser
   if the cache is cleared the values are right, but i don't want to cleare every day the catche to get the right values
- [x] I verified that I'm really running the lastest version in my browser console
    yes
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I use bar chart with influx db an group_by function. Thr Problem ist that the values in the header and in the bar chart are displayed wrong. Only in the edition mode or when i cleare the cache the values are right. So if I use different browseres every browser shows different values.

**Version of the card**
Version:2.02

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 5d
yaxis:
  - show: false
    min: 0
apex_config:
  legend:
    show: false
  chart:
    height: 200px
show:
  last_updated: true
span:
  start: day
  offset: '-4d'
now:
  show: true
header:
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.tesla_verbrauch_tag
    type: column
    color: blue
    unit: ' '
    name: Verbrauch
    show:
      datalabels: true
      legend_value: false
    group_by:
      func: last
      duration: 1day
  - entity: sensor.Hausverbrauch_tag_save
    type: line
    unit: ' '
    stroke_width: 0.5
    color: blue
    name: avg
    float_precision: 1
    show:
      datalabels: false
      in_header: true
      legend_value: false
      in_chart: true
    group_by:
      func: median
      duration: 7day
  - entity: sensor.tesla_bezug_tag
    type: column
    unit: ' '
    color: firebrick
    name: Netzbezug
    show:
      datalabels: true
      legend_value: false
    group_by:
      func: last
      duration: 1day
  - entity: sensor.Tesla_bezug_tag_save
    type: line
    unit: ' '
    stroke_width: 0.5
    color: firebrick
    name: avg
    float_precision: 1
    show:
      datalabels: false
      in_header: true
      legend_value: false
      in_chart: true
    group_by:
      func: avg
      duration: 7day
  - entity: sensor.wp_verbrauch_tag
    type: column
    unit: ' '
    color: grey
    name: WP
    show:
      datalabels: true
      legend_value: false
    group_by:
      func: last
      duration: 1day
  - entity: sensor.delta_Zaehlerstand_WP_tag
    type: line
    unit: ' '
    stroke_width: 0.5
    color: grey
    name: avg
    float_precision: 1
    show:
      datalabels: false
      in_header: true
      legend_value: false
      in_chart: true
    group_by:
      func: avg
      duration: 7day
  - entity: sensor.verbrauch_ohne_WP
    type: column
    unit: ' '
    color: green
    name: ohne WP
    show:
      datalabels: true
      legend_value: false
    group_by:
      func: last
      duration: 1day
  - entity: sensor.delta_Verbrauch_ohne_WP_tag_save
    type: line
    unit: ' '
    stroke_width: 0.5
    color: green
    name: avg
    float_precision: 1
    show:
      datalabels: false
      in_header: true
      legend_value: false
      in_chart: true
    group_by:
      func: avg
      duration: 7day
  - entity: sensor.tesla_produktion_tag
    type: column
    unit: ' '
    color: gold
    name: Produktion
    show:
      datalabels: true
      legend_value: false
    group_by:
      func: last
      duration: 1day
  - entity: sensor.Gesamtproduktion_tag_save
    type: line
    unit: ' '
    stroke_width: 0.5
    color: gold
    name: avg
    float_precision: 1
    show:
      datalabels: false
      in_header: true
      legend_value: false
      in_chart: true
    group_by:
      func: avg
      duration: 7day

```

**Screenshots**

![1671185304589-apex_2](https://user-images.githubusercontent.com/79708016/208866949-46aeabf6-f780-46e7-b897-171023d6efaa.png)
Here you can see the behavior. The Left chart shows the correct values in the edition mode. In the right chart you can see the wrong values and bars (yellow marked)

**Expected behavior**
There should be shown always the right values without clearing the cache every day.

**Desktop (please complete the following information):**
 - Browser [ chrome, firefox, edge,...]
