### ISSUE TITLE
Dashboard through NabuCasa

### ISSUE THREAD

**Issue by rbrtwillis** [RomRider/apexcharts-card#464]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The cards work fine when viewing the dashboard locally but viewing through external NabuCasa has an issue. It works fine at first but if I navigate a way to a different tab and come back, the cards show N/A. If I then go to the local tab, they look perfect. I have an update interval set to 1m.

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used:
```yaml
type: vertical-stack
cards:
  - type: custom:apexcharts-card
    graph_span: 12h
    update_interval: 1m
    header:
      show: true
      title: Outside Weather 12h History
      show_states: true
      colorize_states: true
    series:
      - entity: sensor.weatherflow_air_temperature
        name: Temperature
        color: '#00DF00'
        stroke_width: 2
      - entity: sensor.weatherflow_relative_humidity
        name: Humidity
        color: '#FBC02D'
        stroke_width: 2
      - entity: sensor.weatherflow_wind_speed
        name: Wind Speed
        color: '#D50000'
        stroke_width: 1
  - type: custom:apexcharts-card
    graph_span: 36h
    update_interval: 1m
    header:
      show: true
      title: Outside Weather 36h History
      show_states: true
      colorize_states: true
    series:
      - entity: sensor.weatherflow_air_temperature
        name: Temperature
        color: '#00DF00'
        stroke_width: 2
      - entity: sensor.weatherflow_relative_humidity
        name: Humidity
        color: '#FBC02D'
        stroke_width: 2
      - entity: sensor.weatherflow_wind_speed
        name: Wind Speed
        color: '#D50000'
        stroke_width: 1

```

**Screenshots**
NabuCasa Screenshot: Right side has 2 cards.
![image](https://user-images.githubusercontent.com/16738717/209398322-3828ffa0-09bd-4018-93a7-d688f2203eb8.png)
Local Screenshot: Right side has 2 cards.
![image](https://user-images.githubusercontent.com/16738717/209398367-90eb0304-d80c-498b-9672-e64954ca9ba9.png)

**Expected behavior**
The cards should work regardless of NabuCasa.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 108.0.5359.124
