### ISSUE TITLE
Allow display units in yaxis 

### ISSUE THREAD

**Issue by bodawui** [RomRider/apexcharts-card#467]
The same feature as we have in series with onion unit.

and Display it on yaxis.

Atm: I have 2 columns displaying some numbers, but no values.

fx Price and KW.
![image](https://user-images.githubusercontent.com/99030435/210211219-29bdda23-e18d-4665-8aef-03f4647d2655.png)

**Comment by duncandoo** [comment]
```
yaxis:
  - apex_config:
      title:
        text: "Price"
```
does it for one axis. Admittedly the text is only static. Maybe something can be worked out from this?
