### ISSUE TITLE
Point annotations don't show

### ISSUE THREAD

**Issue by OBoudreaux** [RomRider/apexcharts-card#469]
**Checklist**
- [x] |  updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Point annotations don't show up. Axis annotations and extrema work fine.

**Version of the card**
Version:2.0.2

**To Reproduce**
The relevant bits:
```
apex_config:
  annotations:
    points:
        - x: ${ new Date(states["sensor.myradar_daily_mintime"].state).getTime()}
          y: ${ states['sensor.myradar_daily_min'].state }
          marker:
            size: 8
            radius: 2
            fillColor: blue
            shape: circle
          label:
            offsetY: 0
            text: LOW
     xaxis:
        - x: ${ new Date(states["sensor.myradar_daily_mintime"].state).getTime()}
          label:
            text: ${ states['sensor.myradar_daily_min'].state+" °F"}
            borderWidth: 0
            offsetY: -8
            style:
              fontSize: 15
              color: '#fff'
              background: '#00f'
```
xaxis produces the expected result, 'points' produces nothing.

**Expected behavior**
Point annotations to appear.

**Desktop (please complete the following information):**
 - Chrome
 - 108.0.5359.125

**Smartphone (please complete the following information):**
 - One plus 7 pro
 - OS: Oneplus Frankenstein os
 - Browser chrome
 - Version ¯\_(ツ)_/¯
 - Fire HD 10
 - Fully Kiosk v. latest
**Additional context**
