### ISSUE TITLE
Feature Request : Cumulative bar

### ISSUE THREAD

**Issue by saniho** [RomRider/apexcharts-card#47]
Thanks for this very good extension, one feature could be insterested
In case, we have a value that is calculate by the adding of two, have the detail could be interessed like this
![image](https://user-images.githubusercontent.com/52693545/106806604-775abf80-6668-11eb-8359-7ee9a386cb28.png)

**Comment by RomRider** [comment]
Stacking is already possible with `stacking: true`. You have to provide 2 entities or more obviously.
There is no selective stacking possible so it's everything is stacked or nothing.

**Comment by saniho** [comment]
thanks @RomRider , I have tried, but don"t see an exemple for this integration, can you provide a card configuration sample ?

**Comment by RomRider** [comment]
Something like this:
```yaml
type: custom:apexcharts-card
stacked: true
series:
  - entity: sensor.sensor1
    type: column
  - entity: sensor.sensor2
    type: column
```

Please head over to the forum for help.
