### ISSUE TITLE
Wrong statistics values on montly totals.

### ISSUE THREAD

**Issue by marcelhoogantink** [RomRider/apexcharts-card#470]
**Checklist**
- [X] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Using ApexChats for montly totals of used gas. the displayed totals differ from the totals of the energy-card in HA.
If differs also from the values form the database (which confirms the data of the energy card:

Picture of the Energy Card, value is 217,37 (the correct value)
![afbeelding](https://user-images.githubusercontent.com/51886888/210633701-e5151d8b-5b32-4172-a638-8613ccd7a453.png)

Picture of the Apex Chart, value= 211,978 (the wrong value)
![afbeelding](https://user-images.githubusercontent.com/51886888/210634017-b4a87d5c-e6cf-4d98-b504-efc9c1648e5b.png)

Detail of database with first and last value of december (5273,82 -5056,446 = 217,37, correct value)
```
# id, start, state
'305646', '2023-01-01 01:00:00.000000', '5273.829'
'305546', '2023-01-01 00:00:00.000000', '5273.82'
'305446', '2022-12-31 23:00:00.000000', '5273.82'
'236830', '2022-12-01 01:00:00.000000', '5056.446'
'236749', '2022-12-01 00:00:00.000000', '5056.446'
'236668', '2022-11-30 23:00:00.000000', '5056.446'

```
I also tried the different options of the statistics section and groupby section, all gave the same results

**Version of the card**
2.0.2

**To Reproduce**
This is the series part of the configuration I used:
```yaml
series:
  - entity: sensor.gas_consumption
    yaxis_id: gas
    name: gas
    statistics:
      type: sum
    type: column
    group_by:
      func: diff
      start_with_last: true
      duration: 1month
    float_precision: 3
```

**Expected behavior**
calculate and display the correct value.

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [108.0.5359.125]

**Smartphone (please complete the following information):**
  NA

**Additional context**
 NA

**Comment by marcelhoogantink** [comment]
Nice, no reply, 😥

**Comment by bamnoru** [comment]
Same issue with a weekly duration sensor. The value display in the graph is not the same as the value displayed on other cards using another card.

**Comment by haroldschmeitz** [comment]
I'm seeing similar issues; the daily average doesn't match the (correct) values in a statistics graph.
The root cause seems to be that ApexCharts is simply averaging all samples, assuming a constant interval between them.
However, for many entities the samples are actually unevenly spaced.
To calculate the correct _group_by_ statistics, sample intervals need to be taken into account. Perhaps this is doable with some javascript in _data_generator:_

**Comment by haroldschmeitz** [comment]
_group_by_ is not the right way to handle averaging. Fortunately this is implemented correctly via _statistics._
Example:
```
type: custom:apexcharts-card
graph_span: 14d
span:
  end: day
header:
  title: ApexCharts-Card
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.floor_temperature_3
    type: line
    statistics:
      type: mean
      period: day
  - entity: sensor.p1_total_gas
    type: column
    group_by:
      func: diff
      duration: 1d
```
