### ISSUE TITLE
Y axis scale min/max breaks when using stacked column and other yaxis features at same time

### ISSUE THREAD

**Issue by duncandoo** [RomRider/apexcharts-card#474]
**Checklist**
- [yes ] I updated the card to the latest version available
- [yes ] I cleared the cache of my browser
- [yes ] I verified that I'm really running the lastest version in my browser console
- [ yes] I checked if there is another issue opened with the same problem - similar issues exist

**Describe the bug**
With a stacked column, the y axis should scale to the height of the sum of the stack. If yaxis options are set this does not happen, instead the y axis scales to the height of only the bottom member of the stack. The correct behaviour occurs if yaxis options are specified within apex_config

**Version of the card**
Version:2.0.2

**To Reproduce**
This produces the correct y axis scale, but without the y axis title
```yaml
type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
stacked: true
all_series_config:
  type: column
  group_by:
    func: diff
    start_with_last: true
    duration: 1d
series:
  - entity: sensor.sensor_b1_heater_energy_spent
  - entity: sensor.sensor_b2_heater_energy_spent
  - entity: sensor.sensor_ki_heater_energy_spent
  - entity: sensor.sensor_li_heater_energy_spent
```
![image](https://user-images.githubusercontent.com/4592166/211547296-9eedf9c6-2e29-4fa7-bbd8-b768de103525.png)

Add a y axis title. The y axis scales incorrectly, from not-zero to the height of bottom member of the stack:
```yaml
type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
stacked: true
yaxis:
  - apex_config:
      title:
        text: kWh
      tickAmount: 5
all_series_config:
  type: column
  group_by:
    func: diff
    start_with_last: true
    duration: 1d
series:
  - entity: sensor.sensor_b1_heater_energy_spent
  - entity: sensor.sensor_b2_heater_energy_spent
  - entity: sensor.sensor_ki_heater_energy_spent
  - entity: sensor.sensor_li_heater_energy_spent
```
![image](https://user-images.githubusercontent.com/4592166/211547535-aa780004-5973-408a-abdc-c15c1e9884d1.png)

Specify the y axis options differently, under apex_config, and the correct behaviour occurs:
```yaml
type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
stacked: true
apex_config:
  yaxis:
    title:
      text: kWh
    tickAmount: 5
all_series_config:
  type: column
  group_by:
    func: diff
    start_with_last: true
    duration: 1d
series:
  - entity: sensor.sensor_b1_heater_energy_spent
  - entity: sensor.sensor_b2_heater_energy_spent
  - entity: sensor.sensor_ki_heater_energy_spent
  - entity: sensor.sensor_li_heater_energy_spent
```
![image](https://user-images.githubusercontent.com/4592166/211547781-bc1fe7a0-9723-4e0e-a269-14e199f611d8.png)

The yaxis scale can be partly fixed by specifying fixed values for min and max, but this removes dynamic scaling:
```yaml
type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
stacked: true
yaxis:
  - apex_config:
      title:
        text: kWh
      tickAmount: 5
    min: 0
    max: 40
all_series_config:
  type: column
  group_by:
    func: diff
    start_with_last: true
    duration: 1d
series:
  - entity: sensor.sensor_b1_heater_energy_spent
  - entity: sensor.sensor_b2_heater_energy_spent
  - entity: sensor.sensor_ki_heater_energy_spent
  - entity: sensor.sensor_li_heater_energy_spent
```
![image](https://user-images.githubusercontent.com/4592166/211548481-5ec2fe76-1bdb-44b3-9afa-42630970bd33.png)

**Expected behavior**
The yaxis scale should retain its correct autoscaling ability for a stacked column, even if other yaxis options are specified. A partial solution would be to update the docs to make it clear that min/max auto doesn't function correctly in this situation.

**Desktop (please complete the following information):**
 - Browser [firefox]
 - Version [108.0.1]
