### ISSUE TITLE
yaxis min and max are ignored if using brush

### ISSUE THREAD

**Issue by think-nice-things** [RomRider/apexcharts-card#481]
**Checklist**

- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**

yaxis min and max are ignored if using the brush feature.
Apparently if using the brush feature, autoscaling is done even if yaxis min and max are defined.
Even worse -- autoscaling with brush enabled is much less "tight" compared to regular autoscaling w/o brush. In my example sometimes it goes from 0 to 90 even though data is between 74 and 77 only.

**Version of the card**

v2.0.2 as it comes with HACS.

**To Reproduce**

This is the configuration I used:

```yaml
type: custom:apexcharts-card
graph_span: 2w
experimental:
  brush: true
yaxis:
  - min: 75
    max: 80
series:
  - entity: sensor.weight
    show:
      in_brush: true
```

**Screenshots**

![grafik](https://user-images.githubusercontent.com/4885370/212689399-979f1413-95c2-446b-9096-270f39e7f40a.png)

**Expected behavior**

I'd expect that yaxis min and max work similar to when brush is false.

**Desktop (please complete the following information):**

 - Browser -- tested with both firefox (linux) and chrome (linux and windows)
 - Version e.g. Chrome 106.0.5249.103 on linux but it doesn't really depend on the browser

**Smartphone (please complete the following information):**

 - Device: iphone 12 and xiaomi Mi A1
 - OS: iOS 16.2 and lineageos 19
 - Browser: chrome
