### ISSUE TITLE
header - state value not correct on using a data_generator

### ISSUE THREAD

**Issue by TheBrain8791** [RomRider/apexcharts-card#482]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The current state value of an entity is not displayed correctly when a data_generator is used which produces a data series which contains "future" values (e.g. values which will be valid in a timestamp in future).
My use case was creating a bar chart of a series of energy price vales. This series contains values which have been valid in the past but also values of energy costs - e.g. a day-a-head (so in future).

Using such a data series, I discovered that the state value in the header differed from the current state value of the entity. Looking at the data series I noticed, that the apexchart-card always displayed the last / newest value of my data series, thus a value which will be valid in future.

After a debugging session, I think, I also found the reason for this behaviour in the source code:

https://github.com/RomRider/apexcharts-card/blob/1449c7fab66cc65b3dc2c567184f57e0f2f67f76/src/graphEntry.ts#L113-L114

As `get lastState` always delivers the last / "youngers" value of the history of an entity and the history is generated in my case using a data_generator, this leads to the wrong state value within the header.

**Version of the card**
2.0.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 48h
span:
  start: day
apex_config:
  dataLabels:
    enabled: true
    dropShadow:
      enabled: true
  stroke:
    show: true
    width: 1
    curve: smooth
  chart:
    height: 180%
  plotOptions:
    bar:
      columnWidth: 70%
      dataLabels:
        style:
          fontSize: 12px
        background:
          enabled: true
        position: top
        enabled: true
  legend:
    show: false
    showForSingleSeries: true
    horizontalAlign: right
    position: top
  fill:
    type: gradient
    gradient:
      type: vertical
      shadeIntensity: 0...9
      opacityFrom: 0.1
      opacityTo: 0.8
      inverseColors: true
      stops:
        - 0
        - 10
        - 25
header:
  show: true
  title: Awattar Strom Preis
  show_states: true
  colorize_states: true
series:
  - entity: sensor.awattar_at_price
    type: column
    float_precision: 3
    color: '#FFB200'
    data_generator: |
      const toTimestamp = (strDate) => {
         const dt = Date.parse(strDate);
         return dt ;
      }
      const data = [];            
      for(let i = 0; i < entity.attributes.data.length; i++) {
        let tstamp = toTimestamp(entity.attributes.data[i].start_time);
        let cost = entity.attributes.data[i].price_ct_per_kwh; 
        data.push([tstamp,cost]);
      }      
      return data;
now:
  show: true
  label: current price
```

The entity `sensor.awattar_at_price` has e.g. the following data-series within it's attributes (used by the data_generator):

```yaml
Attribute
Data
- start_time: '2023-01-17T00:00:00+01:00'
end_time: '2023-01-17T01:00:00+01:00'
price_ct_per_kwh: 13.1
- start_time: '2023-01-17T01:00:00+01:00'
end_time: '2023-01-17T02:00:00+01:00'
price_ct_per_kwh: 12.956
- start_time: '2023-01-17T02:00:00+01:00'
end_time: '2023-01-17T03:00:00+01:00'
price_ct_per_kwh: 12.84
- start_time: '2023-01-17T03:00:00+01:00'
end_time: '2023-01-17T04:00:00+01:00'
price_ct_per_kwh: 12.292
- start_time: '2023-01-17T04:00:00+01:00'
end_time: '2023-01-17T05:00:00+01:00'
price_ct_per_kwh: 12.531
- start_time: '2023-01-17T05:00:00+01:00'
end_time: '2023-01-17T06:00:00+01:00'
price_ct_per_kwh: 13.581
- start_time: '2023-01-17T06:00:00+01:00'
end_time: '2023-01-17T07:00:00+01:00'
price_ct_per_kwh: 16.488
- start_time: '2023-01-17T07:00:00+01:00'
end_time: '2023-01-17T08:00:00+01:00'
price_ct_per_kwh: 19.767
- start_time: '2023-01-17T08:00:00+01:00'
end_time: '2023-01-17T09:00:00+01:00'
price_ct_per_kwh: 21.945
- start_time: '2023-01-17T09:00:00+01:00'
end_time: '2023-01-17T10:00:00+01:00'
price_ct_per_kwh: 19.905
- start_time: '2023-01-17T10:00:00+01:00'
end_time: '2023-01-17T11:00:00+01:00'
price_ct_per_kwh: 17.98
- start_time: '2023-01-17T11:00:00+01:00'
end_time: '2023-01-17T12:00:00+01:00'
price_ct_per_kwh: 16.807
- start_time: '2023-01-17T12:00:00+01:00'
end_time: '2023-01-17T13:00:00+01:00'
price_ct_per_kwh: 16.532
- start_time: '2023-01-17T13:00:00+01:00'
end_time: '2023-01-17T14:00:00+01:00'
price_ct_per_kwh: 17.131
- start_time: '2023-01-17T14:00:00+01:00'
end_time: '2023-01-17T15:00:00+01:00'
price_ct_per_kwh: 18.719
- start_time: '2023-01-17T15:00:00+01:00'
end_time: '2023-01-17T16:00:00+01:00'
price_ct_per_kwh: 20.761
- start_time: '2023-01-17T16:00:00+01:00'
end_time: '2023-01-17T17:00:00+01:00'
price_ct_per_kwh: 22.47
- start_time: '2023-01-17T17:00:00+01:00'
end_time: '2023-01-17T18:00:00+01:00'
price_ct_per_kwh: 23.496
- start_time: '2023-01-17T18:00:00+01:00'
end_time: '2023-01-17T19:00:00+01:00'
price_ct_per_kwh: 22.956
- start_time: '2023-01-17T19:00:00+01:00'
end_time: '2023-01-17T20:00:00+01:00'
price_ct_per_kwh: 22.314
- start_time: '2023-01-17T20:00:00+01:00'
end_time: '2023-01-17T21:00:00+01:00'
price_ct_per_kwh: 19.772
- start_time: '2023-01-17T21:00:00+01:00'
end_time: '2023-01-17T22:00:00+01:00'
price_ct_per_kwh: 18.419
- start_time: '2023-01-17T22:00:00+01:00'
end_time: '2023-01-17T23:00:00+01:00'
price_ct_per_kwh: 17.895
- start_time: '2023-01-17T23:00:00+01:00'
end_time: '2023-01-18T00:00:00+01:00'
price_ct_per_kwh: 15.942
```

**Expected behavior**
This sceenshot shows the intended / expected behaviour (screenshot has been taken from an already fixed version). Before instead of the correct (where also the "now - marker" is located 17,131 ct/kWh,  15.942 ct/kWh has been displayed in the header, which equals to the last values of my data - series (see above)

![Auswahl_154](https://user-images.githubusercontent.com/43881071/212897348-c78109e5-ffb6-4e5e-8837-79ff0044307b.png)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [102.0.5005.115]

**Smartphone (please complete the following information):**
 - Device: [Samsung Android]
 - OS: [10]
 - HA companion app / integrated android webview
 - Version [2022.12.0-full]

**Comment by TheBrain8791** [comment]
I've tried to prepare a fix for the issue. Pls note, I'm not a java / typescript developer, so maybe there is a better way to impl. this fix.

Also, I'm new to apexchart-card - thus maybe there is a reason, why the state value is always taken from historic data..? At least I could not discover one.

Beside this little issue - many thx for the apexchart-card and your work!! It is a really cool and useful HA UI extention!

**Comment by TheBrain8791** [comment]
reopen it - since neither any feedback nor a fix have been provided

**Comment by Olum-hack** [comment]
I have the same issue.
Please open it again.

**Comment by BobC76** [comment]
I'm seeing the same issue, with a chart drawn using data generator to produce a graph of dynamic energy rates (forwards and backwards over the day) which are in an attribute of my sensor, while the current rate is its state. 

In the image below current state is where the arrow is, but show_state is giving the final value:

![image](https://github.com/RomRider/apexcharts-card/assets/32709143/0a05adf7-e14b-4302-8822-c9cad7e6ca05)

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 1d
span:
  start: day
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.octopus_energy_electricity_XXXX_current_rate
    type: column
    color_threshold:
      - value: -10
        color: blue
      - value: 0
        color: green
      - value: 10
        color: yellow
      - value: 15
        color: orange
      - value: 25
        color: red
    data_generator: |
      return entity.attributes.rates.map((entry) => {
        return [new Date(entry.from), entry.rate]
      });
```

**Comment by RomRider** [comment]
This feature is already implemented since 1.4.0:
`in_header`:	If show_states is enabled, this would show/hide this specific serie in the header. If set to raw (introduced in v1.7.0), it would display the latest raw state of the entity in the header bypassing any grouping/transformation done by the card. If the graph spans into the future (using data_generator): before_now would display the value just before the current time and after_now would display the value just after the current time

**Comment by BobC76** [comment]
Ahh, yes thanks. I think there may still be an issue with the "legend_value" version of the same data series if you wanted it (more compact perhaps) but thanks for pointing this out.

![image](https://github.com/RomRider/apexcharts-card/assets/32709143/7209d9c4-ed10-448d-a915-13b2b2edab11)

**Comment by RezzZ** [comment]
for those who can't find out how to get this working:

under the series add:
```
    show:
      in_header: raw
```

like so:

```
series:
  - entity: sensor.some_sensor
    <data>
    show:
      in_header: raw
```
