### ISSUE TITLE
Transform binary attribute not showing in graph

### ISSUE THREAD

**Issue by nebojisa79** [RomRider/apexcharts-card#485]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Transform raw data from binary attribute not showing in the chart.

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
series:
  - entity: sensor.nordpool_kwh_tromso_nok_3_10_025
    attribute: low_price
    curve: stepline
    stroke_width: 1
    type: area
    transform: 'return x === ''true'' ? 1 : 0;'
```

**Screenshots**
![binary attribute2](https://user-images.githubusercontent.com/74430264/213780206-8d67b30e-7c8c-44a3-8536-0037302a4cef.png)

**Expected behavior**
It should transform as ordinary binary sensor.
![binary sensor](https://user-images.githubusercontent.com/74430264/213780390-0cfcf653-864d-4cfc-96b0-5732af4eb240.PNG)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 109.0.5414.75 (Official Build) (64-bit)

**Additional context**
Tried true/false and True/False, it's not showing in the chart. With binary sensor template it's working as it should.
```
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
series:
  - entity: sensor.nordpool_kwh_tromso_nok_3_10_025_low_price  ###binary sensor template from attribute "low_price"
    curve: stepline
    stroke_width: 1
    type: area
    transform: 'return x === ''True'' ? 1 : 0;'
```

This is partial state of nordpool integration, the rest is irrelevant:

state_class: measurement
average: 70.32541666666667 
off_peak_1: 66.8059375 
off_peak_2: 63.808437500000004 
peak: 74.84406249999999 
min: 62.93 
max: 90.4525 
mean: 66.570625 
unit: kWh 
currency: NOK 
country: Norway 
region: Tromsø 
**low_price: true** 
price_percent_to_average: 0.9172359448042137

**Comment by nebojisa79** [comment]
It works without quote marks around ''true''
```
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
series:
  - entity: sensor.nordpool_kwh_tromso_nok_3_10_025
    attribute: low_price
    curve: stepline
    stroke_width: 1
    type: area
    transform: 'return x === true ? 1 : 0;'
```
