### ISSUE TITLE
Vertical Markers

### ISSUE THREAD

**Issue by mutzl** [RomRider/apexcharts-card#487]
I'd like to be able to set vertical markers similar to the _now_ marker.

I faked it into one of the doc screenshots.
![image](https://user-images.githubusercontent.com/2855185/214195912-5119c505-9757-4766-bee3-a77b0c2b0d80.png)

YAML could look like this:

``` yaml
markers:
   - entity: sensor.start
     label: start
     color: green
   - entity: sensor.target
     label: target
     color: orange
```

---
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Comment by mutzl** [comment]
I realized, that this can already be achieved using apex annotations.

```yaml
  apex_config:
    annotations:
      xaxis:
        - x: ${ myValue }
           label:
            text: start
```

Only thing that can be considered as a bug (or known-issue at least):
Won't work when `now` is enabled.

So this feature request can be closed or re-labeld as `bug`.
