### ISSUE TITLE
Cannot override span in card when span is in template

### ISSUE THREAD

**Issue by Paul1865** [RomRider/apexcharts-card#489]
**Checklist**
- [ X] I updated the card to the latest version available
- [X ] I cleared the cache of my browser
- [ X] I verified that I'm really running the lastest version in my browser console
- [ X] I checked if there is another issue opened with the same problem

**Describe the bug**
I have a template with a span: start: day in it.
But on one card with that template, I wanted to use span: end: hour. But that results in an error:
/// apexcharts-card version 2.0.2 /// span: Only one of 'start' or 'end' is allowed.

**Version of the card**
Version: 2.02

**To Reproduce**
This is the configuration I used:
### TEMPLATE
```yaml
apexcharts_card_templates:
  default_bar_chart:
    apex_config:
      legend:
        show: false
      min: 0
      grid:
        lines:
          show: true
        borderColor: '#333'
        strokeDashArray: 0
      xaxis:
        axisBorder:
          show: true
          color: '#333'
          offsetX: 0
          offsetY: 0
    show:
      last_updated: true
    update_interval: 1h
    span:
      start: day
    yaxis:
      - id: both
        decimals: 2
        max: '|+0.01|'
        apex_config:
          axisBorder:
            show: true
            color: '#333'
            offsetX: 0
            offsetY: 0
```

### CARD
```yaml
type: custom:apexcharts-card
config_templates: default_bar_chart
header:
  show: true
  title: Zonneplan Gas Costs
  show_states: true
  colorize_states: true
span:
  end: hour
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17167055/214649869-850578a9-d900-4ae5-95f0-a9a376789375.png)

**Expected behavior**
I expected the span to be overridden by the card,

**Desktop (please complete the following information):**
 - Brave (chromium based)
 - Version 1.47.171  Chromium: 109.0.5414.87 (Official Build)  (64-bit)
