### ISSUE TITLE
stacking issue

### ISSUE THREAD

**Issue by JanDetrez** [RomRider/apexcharts-card#495]
Hi

Since recently I experience issues with graph stacking. I'm on v2.0.2. See below an example

Non stacked (good)
![nostacked_Screenshot 2023-02-06 143226](https://user-images.githubusercontent.com/16916740/216984805-ff896929-17c9-4b2e-93b3-191a1c8efdfd.jpg)

stacked issue with red (sensor.myenergi_my_home_power_import) and yellow one (sensor.myenergi_my_home_power_export)
![stacked 2023-02-06 143250](https://user-images.githubusercontent.com/16916740/216984893-db6d10b5-d955-4bd6-8a9e-0eaed578dc3d.jpg)

Plotting individually the  yellow one (sensor.myenergi_my_home_power_export)
![sep_Screenshot 2023-02-06 143638](https://user-images.githubusercontent.com/16916740/216985426-06df24c4-8493-4567-ba24-a2937fd98822.jpg)

```
type: custom:apexcharts-card
stacked: true
header:
  show: true
  show_states: false
  title: Today (W)
all_series_config:
  stroke_width: 0
  type: area
  opacity: 1
  curve: smooth
  extend_to: now
  show:
    legend_value: false
  group_by:
    func: max
    duration: 10min
series:
  - entity: sensor.self_consumption_w
    name: Self Consumption
    color: '#7ABD7E'
  - entity: sensor.myenergi_my_home_power_import
    name: Import
    color: '#FF6961'
  - entity: sensor.myenergi_my_home_power_export
    name: Export
    color: '#F8D66D'
    invert: true
update_interval: 10 min
graph_span: 24h
span:
  start: day

```
