### ISSUE TITLE
fill_raw not working for type: column

### ISSUE THREAD

**Issue by drschlaumeier** [RomRider/apexcharts-card#496]
I have a column graph like this
````
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
graph_span: 24h
span:
  start: day
series:
  - entity: sensor.total_dc_power
    fill_raw: last
    type: column
````

Since last HA update 2023.2, the state db seems to save storage space and not saving anymore the sensor value if the value is not changing. That happens for my sensor over night. Therefore, I added fill_raw: last to my chart but its not working for column chart but inly for line chart. See picture below - top graph is type: column and button graph is type: line :
![grafik](https://user-images.githubusercontent.com/7474396/217005060-c30d4f04-edaa-4944-94ac-6909de1283c9.png)

Side note: it gets worse if you use stacked: true and grouping by average. Thats all not working anymore since last HA update :-(
