### ISSUE TITLE
Timezone issue ?

### ISSUE THREAD

**Issue by IanAdd** [RomRider/apexcharts-card#502]
**Checklist**
- [y ] I updated the card to the latest version available
- [ y] I cleared the cache of my browser
- [ y] I verified that I'm really running the lastest version in my browser console
- [ y] I checked if there is another issue opened with the same problem

**Describe the bug**

I live in New South Wales, Australia and am hence UTC+10.
The graph only displays data up to the preceding day. 
I use a 7d barchart.
If I hold my mouse over the last bar in the barchart it shows yesterday's date and the current Australian time and the value applicable to the previous day.
If I reduce the time span to one day (ie the current day) I see no data.

I am using 'duration: 24' Does this show nothing until 24hrs have elapsed ?

**Version of the card**
Version:
v2.0.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: WaterHeater 7 day History
graph_span: 7d
stacked: true
series:
  - entity: sensor.waterheater_energy_offpeak
    color: lightgreen
    name: Offpeak
    type: column
    group_by:
      func: diff
      duration: 24h
      start_with_last: true
  - entity: sensor.waterheater_energy_shoulder
    color: orange
    name: Shoulder
    type: column
    group_by:
      func: diff
      duration: 24h
      start_with_last: true
  - entity: sensor.waterheater_energy_peak
    color: red
    name: Peak
    type: column
    group_by:
      func: diff
      duration: 24h
      start_with_last: true

```

**Screenshots**
Attached.

**Expected behavior**

I expected data for the current day as it accumulates.

**Desktop (please complete the following information):**

Chrome Version 109.0.5414.121 (Official Build) (64-bit)

**Additional context**
