### ISSUE TITLE
Hourly Statistics option don't permit use groupe_by diff

### ISSUE THREAD

**Issue by uowis** [RomRider/apexcharts-card#505]
With the option: 

```
statistics:
  type: state
  period: hour
```

With a period to hour give only one value per hour. So :

```
group_by:
  duration: hour
  func: diff
  start_with_last: true
```
  
  No graph is drawing

**Comment by uowis** [comment]
but that work : 
```
      statistics:
        type: state
        period: hour
        align: start
      group_by:
        duration: 59.99min
        func: diff
        start_with_last: true
```
