### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by exzz** [RomRider/apexcharts-card#506]
Hello,

the following code does not work and produce "Custom element doesn't exist: apexcharts-card" error:
```
resources:
  - url: /local/apexcharts-card.js?v=2.0.2
    type: module
```

The following one works (without version):
```
resources:
  - url: /local/apexcharts-card.js
    type: module
```

Also I would propose to add a more complete piece of code for beginners:
```
lovelace:
  mode: yaml
  resources:
    - url: /local/apexcharts-card.js
      type: module
```

Hope this would help and many thanks for your wonderful work.
