### ISSUE TITLE
toggleSeries as action-options

### ISSUE THREAD

**Issue by regystro** [RomRider/apexcharts-card#511]
Would it be possible to add toggleSeries capability (https://apexcharts.com/docs/methods/#toggleSeries) to [action_options](https://github.com/RomRider/apexcharts-card#_action-options)?

I like to display the current entities value in the header, therefore I hide the legend to save some space. This way I lose the option to toggle the series.

For the best of two worlds, it would be useful to have "toggleSeries" as tap_action.

```
type: custom:apexcharts-card
header:
  show: true
  title: Temperature
  show_states: true
series:
  - entity: sensor.TH1_temperature
  - entity: sensor.TH2_temperature
all_series_config:
  header_actions:
    tap_action:
      action: toggleSeries
apex_config:
  legend:
    show: false
```

I know all of the actions available are those related to the entity and standard in HA, so that would be more like a "hack," I guess. I don't know how much complexity would be required for the implementation.

Greetings.
