### ISSUE TITLE
Chart broken after HA 2023.3 update

### ISSUE THREAD

**Issue by tchristerus** [RomRider/apexcharts-card#512]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
After the Home Assistant 2023.3 update the graph does not seem to work anymore. In the screenshot you can see that after around 1 PM (after the update) new data is ignored. Maybe it has something to do with the new data precision change?

The default HA history graph still works (see screenshots)

**Version of the card**
Version: v2.0.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Diepvries (2 uur)
graph_span: 8h
series:
  - entity: sensor.tz3000_gjnozsaz_ts011f_active_power
    opacity: 1
    type: area
    stroke_width: 0
    curve: smooth
    group_by:
      duration: 2min
      func: avg
```

**Screenshots**
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/13733382/222473873-d00bc744-28fd-4019-8b69-387ca8870364.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/13733382/222474633-9602b839-a13e-4128-968a-f12d6474f29f.png">

<img width="188" alt="image" src="https://user-images.githubusercontent.com/13733382/222474201-5ca4bb41-697f-4ff5-ba37-3e3a7795abe5.png">

**Expected behavior**
A working graph :)

**Desktop / Phone**
Happens on all my devices/browsers, (Chrome, Firefox, IOS and Android)
