### ISSUE TITLE
Incorrect Y position for max extrema label for a stacked graph

### ISSUE THREAD

**Issue by markcocker** [RomRider/apexcharts-card#514]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the latest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Incorrect Y position for max extrema label for a stacked graph.

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used. The `extremas: max` adds a label for the max value in the third series in the stack - ie. the blue area in the screenshot.

```yaml
type: custom:apexcharts-card
stacked: true
config_templates: default
header:
  title: Solar generation today by panels
span:
  start: day
graph_span: 24h
all_series_config:
  type: area
series:
  - entity: sensor.solar_panels_east_facing
    name: East panels
  - entity: sensor.solar_panels_south_facing
    name: South panels
  - entity: sensor.solar_panels_west_facing
    name: West panels
    show:
      extremas: max
apex_config:
  yaxis:
    min: 0
    max: 4000
    forceNiceScale: true
    decimalsInFloat: false
  chart:
    height: 200
```

**Screenshots**

<img width="958" alt="60f387a91a0f7d2659671b1d1d96c83896a77cc7" src="https://user-images.githubusercontent.com/15351000/222897731-523193b2-a9ca-4785-85f1-f9b7ab273daa.png">

**Expected behavior**
The max extrema label should be positioned near the top of the third blue series, not at the bottom.

**Desktop (please complete the following information):**
 - Device: Apple M1 max
 - OS: macOS 13.2.1
 - Firefox 110.1

**Additional context**
None.
