### ISSUE TITLE
Offset -1year not working correctly to the hour (long term stats)

### ISSUE THREAD

**Issue by JoryHogeveen** [RomRider/apexcharts-card#515]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I've made a comparison of hourly gas consumption of today vs one year ago (within the span of a week).
This chart displays hourly usage bars.

When I input `offset: -1year` the offset is missed by 6 hours. So my morning usage (7AM) is reported as afternoon (1PM).

When I use `offset: -365days` it works correctly and the stats are put on the correct hour in the chart.

The same thing happens with temperature sensors and basically all data once pulled by the hour.
When getting data by day it works fine, only hourly data renders with a 6 hour offset.

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 350px
graph_span: 8days
update_delay: 30s
experimental:
  color_threshold: true
  brush: false
span:
  start: day
  offset: '-1week'
brush:
  selection_span: 1week
header:
  show: true
  title: Hourly consumption - 1week - Previous year
  show_states: true
  colorize_states: true
now:
  show: true
yaxis:
  - id: first
    decimals: 1
    min: 0
    max: '|+0.1|'
    apex_config:
      tickAmount: 10
      tooltip:
        enabled: true
  - id: second
    opposite: true
    decimals: 0
    min: '|-2|'
    max: '|+2|'
    apex_config:
      tickAmount: 10
      tooltip:
        enabled: true
series:
  - entity: YOUR TOTAL GAS CONSUMPTION SENSOR
    name: Gas Consumption
    type: column
    stroke_width: 2
    yaxis_id: first
    offset: '-365days'
    statistics:
      type: sum
      period: hour
    group_by:
      func: diff
      start_with_last: true
      duration: 1hour
    show:
      in_brush: true
    color_threshold:
      - value: 0
        color: '#2ecc71'
      - value: 0.5
        color: '#f1c40f'
      - value: 0.8
        color: '#e74c3c'
  - entity: YOUR TEMPERATURE SENSOR
    name: Garden
    color: '#9cb4c4'
    yaxis_id: second
    extend_to: false
    offset: '-365days'
    statistics:
      type: mean
      period: hour
    group_by:
      func: avg
      duration: 1hour
```

**Screenshots**

**-1year offset:**
![image](https://user-images.githubusercontent.com/826148/222906813-74fa09b2-179d-4887-b5b5-dbc457fcde4d.png)

**-365days offset:**
![image](https://user-images.githubusercontent.com/826148/222906827-7dc06db6-4b33-41dc-bc2f-ab73cc5d3677.png)

**Expected behavior**
The offset to be exactly -1year and not -1year and 6 hours.

**Desktop (please complete the following information):**
N.A. (all)

**Smartphone (please complete the following information):**
N.A. (all)
