### ISSUE TITLE
Tooltip serie issue with stats from today

### ISSUE THREAD

**Issue by JoryHogeveen** [RomRider/apexcharts-card#516]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When using multiple series that show stats per hour the tooltip should display all serie data.
However, when the chart is showing current data as well, which is still pending since the last hour isn't recorded in the long term statistics yet the whole chart won't combine the tooltips anymore.
This makes it difficult to pinpoint serie data (see screenshot).

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used:
**NOTE: If you change the span>offset to -61 days it will work as it doesn't include todays data anymore!**

```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 350px
graph_span: 60days
update_delay: 30s
experimental:
  color_threshold: true
span:
  start: day
  offset: '-59days'
header:
  show: true
  title: Daily consumption - 2months compare
  show_states: true
  colorize_states: true
yaxis:
  - id: first
    decimals: 0
    min: 0
    max: '|+2|'
    apex_config:
      tickAmount: 10
      tooltip:
        enabled: true
  - id: second
    opposite: true
    decimals: 0
    min: '|-2|'
    max: '|+2|'
    apex_config:
      tickAmount: 10
      tooltip:
        enabled: true
series:
  - entity:  GAS CONSUMED SENSOR
    name: Gas Consumption
    type: column
    color: '#e74c3c'
    yaxis_id: first
    statistics:
      type: sum
      period: day
    group_by:
      func: diff
      start_with_last: true
      duration: 1day
  - entity:  TEMPERATURE SENSOR
    name: Temperature
    color: '#76bceb'
    yaxis_id: second
    extend_to: false
    statistics:
      type: mean
      period: day
    group_by:
      func: avg
      duration: 1day
```

**Screenshots**

Here a working example, it's because there is no hourly data to be calculated so all serie points are exactly matching in time.
![image](https://user-images.githubusercontent.com/826148/222907322-66017a45-2175-4b12-857f-f10bc0515c3f.png)

And here an example of a chart where the last bar is "live" and not properly calculated yet since that hour isn't over yet.
![image](https://user-images.githubusercontent.com/826148/222907469-63dc1047-6c17-4572-b74e-5b2bf891d33c.png)

**Expected behavior**
I would expect that even though the last hour isn't over yet it the serie points would still be linked to each other. The span>start is based on the hour to all starting points should be the same.

**Desktop (please complete the following information):**
N.A. (all)

**Smartphone (please complete the following information):**
N.A. (all)
