### ISSUE TITLE
color_threshold with RadialBar colors bars with percentage, header with absolute values

### ISSUE THREAD

**Issue by jbaumann** [RomRider/apexcharts-card#518]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Using the experimental color_threshold with a Radialbar colors the radial bars with percentage values, but the headers with absolute values. This means if I have a color threshold at 26, the radial bar will be colored accordingly if it exceeds 26%, and the header will be colored accordingly if it exceeds an absolute value of 26.

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Temperatur
  show_states: true
  colorize_states: true
chart_type: radialBar
experimental:
  color_threshold: true
all_series_config:
  show:
    legend_value: false
    header_color_threshold: true
  color_threshold:
    - value: 90
      color: darkred
    - value: 80
      color: orangered
    - value: 70
      color: orange
    - value: 57
      color: goldenrod
    - value: 39
      color: darkcyan
    - value: 26
      color: dodgerblue
    - value: 20
      color: blue
  min: 12
  max: 35
series:
  - entity: sensor.thp_wz_temperature
    name: Wohnzimmer
  - entity: sensor.thp_az_temperature
    name: Arbeitszimmer
  - entity: sensor.thp_sz_temperature
    name: Schlafzimmer
  - entity: sensor.xiron_5f03_temp
    name: Balkon
apex_config:
  plotOptions:
    radialBar:
      offsetY: -10
      startAngle: 0
      endAngle: 270
      hollow:
        size: 35%
      dataLabels:
        name:
          fontSize: 12px
          show: true
        value:
          fontSize: 12px
          offsetY: 0
          show: true
          formatter: |
            EVAL:function (val) {
              orig = (12 + parseFloat(val) * (35-12)/100).toFixed(1);
              return orig + '°C'
            }
  legend:
    show: true
    floating: true
    position: left
    fontSize: 14px
    offsetX: 30
    offsetY: -6
    markers:
      width: 0
    itemMargin:
      vertical: -1
```

**Screenshots**

**Expected behavior**
Both radial bar and absolute value in the header should preferrably be colored using the same values. Alternatively, an additional threshold for the header could be introduced (with the disadvantage, that setting both to the same thresholds could be cumbersome).

Browser:
Safari, Chrome on iOS (iPad, iPhone) and OSX.
