### ISSUE TITLE
Apexcharts question: scale y axis based on brush selection

### ISSUE THREAD

**Issue by xelabug** [RomRider/apexcharts-card#522]
**Checklist**
- [ v] I updated the card to the latest version available
- [ v] I cleared the cache of my browser
- [ v] I verified that I'm really running the lastest version in my browser console
- [ v] I checked if there is another issue opened with the same problem

**Describe the bug**
The Brush experimental function does not autoscale the selection or the area selected with "selection_span", if "graph_span" includes very high values the y-axis scales to those values and therefore the brush selection remains invisible if includes very small values.

The problem is clearly stated here:
https://community.home-assistant.io/t/apexcharts-question-scale-y-axis-based-on-brush-selection/532041

**Version of the card**
v2.0.2 

**To Reproduce**
This is the configuration I used:

```
type: custom:apexcharts-card
graph_span: 7d
experimental:
  brush: true
brush:
  selection_span: 2d
span:
  end: day
apex_config:
  chart:
    height: 400px
    zoom:
      enabled: true
    brush:
      autoScaleYaxis: true
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: true
        zoomout: true
        pan: true
        reset: true
        download: false
  plotOptions:
    bar:
      dataLabels:
        position: center
  xaxis:
    labels:
      format: dd/MM
  legend:
    show: false
  stroke:
    show: true
    width: 2
    curve: smooth
  fill:
    type: gradient
    gradient:
      type: horizontal
      shadeIntensity: 0.1
      opacityFrom: 0.3
      opacityTo: 0.9
show:
  last_updated: true
header:
  show: false
  show_states: true
  colorize_states: true
  title: Aggregato
series:
  - entity: sensor.generale_energy_daily
    name: Totale
    type: area
    unit: ' kWh'
    color: Grey
    group_by:
      func: max
      duration: 1d
    show:
      in_brush: true
      in_chart: true
  - entity: sensor.other_energy_daily
    name: Altri Servizi
    type: column
    unit: ' kWh'
    color: HotPink
    group_by:
      func: max
      duration: 1d
  - entity: sensor.condizionatori_energy_daily
    name: Condizionatori
    type: column
    unit: ' kWh'
    color: Orange
    group_by:
      func: max
      duration: 1d
  - entity: sensor.tvsala_plug_energy_daily
    name: Sala TV
    type: column
    unit: ' kWh'
    color: Yellow
    group_by:
      func: max
      duration: 1d
  - entity: sensor.box_energy_daily
    name: Asciugatrice
    type: column
    unit: ' kWh'
    color: GreenYellow
    group_by:
      func: max
      duration: 1d
  - entity: sensor.lavatrice_energy_daily
    name: Lavatrice
    type: column
    unit: ' kWh'
    color: DodgerBlue
    group_by:
      func: max
      duration: 1d
```

Specifying these options in the code has no effect and the scaling remains inappropriate:
`  yaxis:
    min: 0
    max: 12
`
or 
`forceNiceScale: true`

**Screenshots**
https://user-images.githubusercontent.com/54978767/225587003-2b1bf01b-2b28-442e-9dc1-c4dcda95f0e6.png

**Expected behavior**

The original Apexcharts js work fine!
https://apexcharts.com/javascript-chart-demos/line-charts/brush-chart/
https://codepen.io/apexcharts/pen/rqWeBX

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Chrome + Edge 
 - Version : 111.0.5563.65

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] : Android
 - OS: [e.g. iOS8.1]: 12
 - Browser [e.g. stock browser, safari] Chrome + App Companion

**Additional context**
