### ISSUE TITLE
Login attempt or request with invalid authentication from aws

### ISSUE THREAD

**Issue by anders3408** [RomRider/apexcharts-card#525]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
At random times, i get "Login attempt or request with invalid authentication from ...compute.amazonaws.com and it seems to be related to ApexCharts.
In the log console i get these exceptions:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:82
Integration: HTTP (documentation, issues)
First occurred: 04.24.48 (16 occurrences)
Last logged: 15.36.50

Login attempt or request with invalid authentication from ec2-34-223-253-64.us-west-2.compute.amazonaws.com (34.223.253.64). Requested URL: '/api/history/period/2023-03-20T10%3A39%3A13.081Z?filter_entity_id=sensor.house_power_consumption&end_time=2023-03-20T11:39:13.081Z&significant_changes_only=0'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from ec2-34-219-234-42.us-west-2.compute.amazonaws.com (34.219.234.42). Requested URL: '/api/history/period/2023-03-20T10%3A39%3A13.081Z?filter_entity_id=sensor.daily_power_consumption_today_min&end_time=2023-03-20T11:39:13.081Z&significant_changes_only=0'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from ec2-52-90-216-77.compute-1.amazonaws.com (52.90.216.77). Requested URL: '/api/history/period/2023-03-20T13%3A32%3A15.140Z?filter_entity_id=sensor.house_daily_energy&end_time=2023-03-20T14:32:15.140Z&significant_changes_only=0'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from ec2-54-83-133-63.compute-1.amazonaws.com (54.83.133.63). Requested URL: '/api/history/period/2023-03-20T14%3A29%3A15.243Z?filter_entity_id=sensor.house_power_consumption&end_time=2023-03-20T14:33:18.893Z&skip_initial_state&significant_changes_only=0'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from ec2-3-81-136-156.compute-1.amazonaws.com (3.81.136.156). Requested URL: '/api/history/period/2023-03-20T13%3A34%3A39.899Z?filter_entity_id=sensor.daily_power_consumption_today_max&end_time=2023-03-20T14:34:39.899Z&significant_changes_only=0'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)

**Version of the card**
Version: 2.0.2

**To Reproduce**
Unknown since it happens randomly

This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
  brush: false
brush:
  selection_span: 1h
graph_span: 1h
show:
  last_updated: true
  loading: false
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
now:
  show: false
  color: red
  label: Now
series:
  - entity: sensor.house_power_consumption
    name: Lige nu
    extend_to: now
    stroke_width: 2
    float_precision: 2
    show:
      extremas: true
      in_brush: true
  - entity: sensor.daily_power_consumption_today_min
    name: Lavest i dag
    float_precision: 2
    show:
      in_chart: false
  - entity: sensor.daily_power_consumption_today_max
    name: Højest i dag
    float_precision: 2
    show:
      in_chart: false
  - entity: sensor.house_daily_energy
    name: Forbrug i dag
    float_precision: 2
    show:
      in_chart: false
  - entity: sensor.house_total_energy
    name: Totalt
    float_precision: 0
    show:
      in_chart: false

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] :  111.0.5563.65 

**Additional context**
