### ISSUE TITLE
bar chart does not display correct values?

### ISSUE THREAD

**Issue by jboesh** [RomRider/apexcharts-card#526]
my setup:

- HA in docker: the latest version
- Apex charts: the latest version.

Hi
I'm struggling with a bar chart and it looks like it doesn't display the correct values. for instance on 24 march it shows data (blue color) but there is no data for that day... so where does Apex get the data from? I don t get it.

My code:
```
type: custom:apexcharts-card
graph_span: 10d
span:
  end: day
stacked: true
apex_config:
  legend:
    show: true
header:
  show: true
  colorize_states: true
  title: Locatie ratio (10d)
all_series_config:
  type: column
  group_by:
    func: avg
    duration: 1d
series:
  - entity: sensor.zone_basicfit_ratio
  - entity: sensor.zone_werk_ratio
  - entity: sensor.zone_thuis_ratio
  - entity: sensor.android_auto_ratio
yaxis:
  - min: 0
    max: 100
    decimals: 0
```
How the chart looks like:
![image](https://user-images.githubusercontent.com/71582854/227960480-83d74f68-d1ba-44ed-a868-2d2a4144ead5.png)

so it shows data for the 24 of march that's not correct, because when I lookup the entity in Home Assistant:
it only shows data on 23 march... 
![image](https://user-images.githubusercontent.com/71582854/227961451-43db3437-a1f6-4694-8975-94d3f0462ae3.png)

but what is strange is that a day displays data untill 23:00. has this something to do with it?
![image](https://user-images.githubusercontent.com/71582854/227962377-3deb37cf-8304-4013-8e82-fd06205d3156.png)
