### ISSUE TITLE
Add bar graph type

### ISSUE THREAD

**Issue by MayeulC** [RomRider/apexcharts-card#533]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I would like to compare values for different sensors at a glance. Namely, temperature sensors.
The `radialBar` could work, but it is relatively complex to judge the interval between values due to its curvature. For instance, if a sensor is just at the begining of the bar, and another at the end with a few more bars in between, it becomes hard to read.

**Describe the solution you'd like**
Simply add Apex's `bar` chart type, that display one value on each bar, with the same scale. I believe semantics could be kept similar to other graphs.

Bar charts are generally understood to be superior to other charts for readability, I'd very much like to see them included in this card.

**Describe alternatives you've considered**

Feel free to expand both sections for screenshot and code.

<details><summary>I tried making an equivalent with columns, but they are really narrow, which wastes a lot of space. I also believe this is slower than just taking the last sensor value from HA.</summary>

![image](https://user-images.githubusercontent.com/3952726/229750160-f8426f01-9d60-450b-be73-855a6e211158.png)

```yaml
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
all_series_config:
  type: column
  show:
    datalabels: true
graph_span: 3m
update_delay: 3m
show:
  loading: false
span:
  start: minute
entities:
  - entity: sensor.tempsensor3_temperature
    name: Outside
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.thermometer_i9g_temperature
    name: Living room
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.tze200_yvx5lh6k_ts0601_temperature
    name: bedroom
    group_by:
      func: last
      start_with_last: true
      duration: 3m
apex_config:
  legend:
    show: false
  xaxis:
    labels:
      show: false
    axisBorder:
      show: false
    axisTicks:
      show: false
    crosshairs:
      show: false
    tooltip:
      enabled: false

```

</details>

<details> <summary>I also used mini-graph-card to create a similar card, but I like headers and tags from Apex.</summary>

![image](https://user-images.githubusercontent.com/3952726/229749545-e0da0606-2c53-4ce3-8dc3-a32fdc6d6f4f.png)

```yaml
type: custom:mini-graph-card
name: Temperatures
hours_to_show: 2
aggregate_func: last
smoothing: false
entities:
  - entity: sensor.tempsensor3_temperature
    name: outside
  - entity: sensor.thermometer_i9g_temperature
    name: living room
  - entity: sensor.tze200_yvx5lh6k_ts0601_temperature
    name: bedroom
show:
  graph: bar
  labels: true

```

</details>

I also tried overriding Apex's `chart: type: bar`, but it didn't seem to work, as it gave me an empty graph.

**Comment by MayeulC** [comment]
Oh no, not this bot...

**Comment by MayeulC** [comment]
I guess I'll just comment here every 30 days. Thank you, bot.

**Comment by MayeulC** [comment]
As a workaround, the column width can be increased manually above 100%:

```yaml
apex_config:
  plotOptions:
    bar:
      columnWidth: 500%
```

<details><summary>Example 1 (300% for 3 bars)</summary>

![image](https://github.com/RomRider/apexcharts-card/assets/3952726/13c4ad0d-f814-4b36-843f-7f7b0173af9d)


```yaml
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
all_series_config:
  type: column
  show:
    datalabels: true
graph_span: 3m
update_delay: 3m
show:
  loading: false
span:
  start: minute
entities:
  - entity: sensor.tempsensor3_temperature
    name: Outside
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.thermometer_i9g_temperature
    name: Living room
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.tze200_yvx5lh6k_ts0601_b5a8b0fe_temperature
    name: bedroom
    group_by:
      func: last
      start_with_last: true
      duration: 3m
apex_config:
  legend:
    show: false
  xaxis:
    labels:
      show: false
    axisBorder:
      show: false
    axisTicks:
      show: false
    crosshairs:
      show: false
    tooltip:
      enabled: false
  plotOptions:
    bar:
      columnWidth: 300%
```

</details>

<details><summary>Example 2 (500% for 6 bars)</summary>

![image](https://github.com/RomRider/apexcharts-card/assets/3952726/7f07f9e7-6530-4497-ab2b-310dc5d32139)


```yaml
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
apex_config:
  legend:
    show: false
  xaxis:
    labels:
      show: false
    axisBorder:
      show: false
    axisTicks:
      show: false
    crosshairs:
      show: false
    tooltip:
      enabled: false
  plotOptions:
    bar:
      columnWidth: 500%
all_series_config:
  type: column
  show:
    datalabels: true
graph_span: 3m
update_delay: 3m
show:
  loading: false
span:
  start: minute
entities:
  - entity: sensor.tempsensor3_temperature
    name: Outside
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.tempsensor3_temperature
    name: Outside
    offset: '-1d'
    opacity: 0.3
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.thermometer_i9g_temperature
    name: Living room
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.thermometer_i9g_temperature
    name: Living room
    opacity: 0.3
    offset: '-1d'
    group_by:
      func: last
      start_with_last: true
      duration: 40m
  - entity: sensor.tze200_yvx5lh6k_ts0601_b5a8b0fe_temperature
    name: bedroom
    group_by:
      func: last
      start_with_last: true
      duration: 3m
  - entity: sensor.tze200_yvx5lh6k_ts0601_b5a8b0fe_temperature
    name: bedroom
    opacity: 0.3
    offset: '-1d'
    group_by:
      func: last
      start_with_last: true
      duration: 3m
```

</details>

Documentation for the relevant properties is [here](https://apexcharts.com/docs/options/plotoptions/bar/).
