### ISSUE TITLE
config_templates appear broken with core 2023.4.0

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#536]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Apexcharts with config_templates have broken after upgrading to core 2023.4.0

**Version of the card**
Version: v2.0.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
config_templates:
  - 250px_chart
graph_span: 1d
series:
  - entity: sensor.kitchen_feels_like
    name: Kitchen
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54566217/230219950-f1099e27-a86a-4389-923d-7b3433fd073a.png)

**Expected behavior**
This is how it should look
![image](https://user-images.githubusercontent.com/54566217/230220057-1998ac9c-f5a5-4359-8ec6-ab999e579842.png)
(I am able to generate the card by removing the config_templates from the config for now)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 111.0.5563.147

**Smartphone (please complete the following information):**

**Additional context**
