### ISSUE TITLE
Add support for "nested attribute"

### ISSUE THREAD

**Issue by Luth1ng** [RomRider/apexcharts-card#539]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add the possibility to base the input data of the graph on a nested attribute of an entity.

**Describe alternatives you've considered**
There isn't any.

**Additional context**
For example, I have this entity which has a lot of attributes :
```
state: 1
desc: 下次出粮时间: 19:30
status: 
wifi:
  ssid: myWifi
  bssid: 1f19b8c8a220
  rsq: -44
pim: 1
ota: 0
overall: 1
errorPriority: 0
desiccantLeftDays: 0
feeding: 0
food: 0
batteryStatus: 0
runtime: 129393
batteryPower: 4
desiccantTime: 0

shared: null
icon: mdi:information
```
Well, if you look closely, you notice there is only 3 attributes : state, desc and status.
The status attribute has many other attributes : wifi (which has also "nested" attributes), pim, etc...

I would like to create a graph based on the status.overall data.
