### ISSUE TITLE
Donut card displays incorrectly on safari for mac

### ISSUE THREAD

**Issue by cooltings** [RomRider/apexcharts-card#541]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
The graph legend is partially cut off and not aligned properly

**Version of the card**
Version: 2.0.4

**To Reproduce**

On safari for mac

This is the configuration I used:
```yaml
type: custom:apexcharts-card
chart_type: donut
series:
  - entity: sensor.boiler_supply_3_1d
    name: Boiler Supply
  - entity: sensor.downstairs_lights_8_1d
    name: Downstairs Lights
  - entity: sensor.downstairs_sockets_2_1d
    name: Downstairs Sockets
  - entity: sensor.fridge_and_garage_7_1d
    name: Fridge & Garage
  - entity: sensor.kitchen_1_1d
    name: Kitchen
  - entity: sensor.kitchen_lighting_and_understair_lighting_5_1d
    name: Kitchen + Understair Lighting
  - entity: sensor.ring_kitchen_and_dining_9_1d
    name: Ring Kitchen
  - entity: sensor.upstairs_lights_4_1d
    name: Upstairs Lights
  - entity: sensor.upstairs_sockets_6_1d
    name: Upstairs Sockets
  - entity: sensor.washer_dryer_10_1d
    name: Washer Dryer

```

**Screenshots**
<img width="534" alt="Screenshot 2023-04-17 at 19 17 08" src="https://user-images.githubusercontent.com/104278596/232574816-51f4ab00-2b3c-4de6-8b22-39173dd39e95.png">
**Expected behavior**

Graph should display with no cutoff sections just like it does on other platforms

**Desktop (please complete the following information):**
 - Browser: safari for mac (safari for iphone and ipad works fine)
 - Version 16.3
 
**Smartphone (please complete the following information):**
   - Device: Works fine on mobile
 - OS: [n/a]
 - Browser [n/a]
 - Version [n/a]

**Additional context**

This problem only occurs on safari for mac
