### ISSUE TITLE
Daily average energy price using statistics...

### ISSUE THREAD

**Issue by salzrat** [RomRider/apexcharts-card#542]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I use an integration that adds hourly power consumption from my smartmeter to a statistics entity. Since the data comes 1 day late, the entity has only statistics, no state. I can display this nicely with apexcharts. However, I cannot (or do not know) how to do any calculations with it.

Since apexcharts knows how to access the statistics, maybe there is some way how to add some functionality to access statistical data to calculate averages.

**Describe the solution you'd like**
Concretely, I would like to calculate my daily average energy price based on an hourly tariff (from Epex), i.e.: hour1_consumption*hour1_price + hour2_consumption*hour2_price + ... /total_daily_consumption. I'd like to plot the result in a chart and compare with the average energy price.

**Describe alternatives you've considered**
I can't think of any.

**Additional context**
The smartmeter integration is described here: https://github.com/DarwinsBuddy/WienerNetzeSmartmeter
and the spot energy prices here: https://github.com/mampfes/ha_epex_spot

Currently, I'm plotting the energy price and consumption over one day like this:

```
type: custom:apexcharts-card
header:
  show: true
  title: Spot vs Energy
graph_span: 1day
span:
  start: day
  offset: '-2day'
yaxis:
  - id: kw
    min: 0
    opposite: true
  - id: price
    min: auto
all_series_config:
  show:
    legend_value: false
  curve: stepline
  stroke_width: 2
series:
  - entity: sensor.epex_spot_at_price
    yaxis_id: price
    unit: ct/kWh
    type: line
    transform: return x * 1.2 * 1.03 / 10
    show:
      extremas: true
  - entity: sensor.atxxx_statistics
    yaxis_id: kw
    type: line
    statistics:
      type: state
```

![image](https://user-images.githubusercontent.com/9115325/233144077-951348c8-58a0-455f-b2b8-98aa4a85c1ea.png)
