### ISSUE TITLE
Min value of yaxis neglected when using experimental brush feature

### ISSUE THREAD

**Issue by philippe-tc** [RomRider/apexcharts-card#548]
When using the experimental brush feature, the min value of the yaxis function is neglected. I want to set the yaxis (temperature) from min: 16 to max: 18, but the graph shows me an axis from 0 to 18 degrees.

When I remove the experimental: brush: true from the code, the y axis shows correct from 16 to 18 degrees. So it must be a bug directly related to the brush feature.

I use apexcharts-card V2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Provisiekast temperatuur en vocht
  show_states: false
  colorize_states: true
graph_span: 7d
yaxis:
  - id: temp
    decimals: 0
    apex_config:
      tickAmount: 2
    min: 16
    max: 18
  - id: rh
    opposite: true
    decimals: 0
    apex_config:
      tickAmount: 2
    min: 50
    max: 60
all_series_config:
  stroke_width: 1
  opacity: 1
experimental:
  brush: true
brush:
  selection_span: 1d
  apex_config:
    chart:
      height: 250px
series:
  - entity: sensor.shelly_plus_temp_rh_temperature
    yaxis_id: temp
    type: line
    name: Temperatuur
    show:
      extremas: true
      in_brush: true
  - entity: sensor.shelly_plus_temp_rh_humidity
    yaxis_id: rh
    type: line
    name: Vochtigheid
    show:
      extremas: true
      in_brush: true
```

**Screenshots**
See my screenshot without (top) and with (bottom) the brush feature.
The rest of these two charts is EXACTLY the same.

**Desktop:**
 - Browser: safari
 - Version 16.3 (18614.4.6.1.6)

**Smartphone:**
 - Device: iPhone12promax
exactly the same here

** Home Assistant information**
Runs on  Raspberry Pi 4; rpi4-64
Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend-versie: 20230411.1 - latest

<img width="984" alt="Screenshot­ yaxis problem with brush feature" src="https://user-images.githubusercontent.com/1871862/235673796-ad20be93-eb81-4064-93ca-36c97617ab5f.png">

**Comment by chertvl** [comment]
Solved it with this configuration:
```
    experimental:
      brush: true
    brush:
      apex_config:
        yaxis:
          show: false
          min: |
            EVAL:function(min) { return min }
          max: |
            EVAL:function(max) { return max }
```
