### ISSUE TITLE
 Add change type for statistics

### ISSUE THREAD

**Issue by testuser7** [RomRider/apexcharts-card#552]
**Checklist**
- [ x] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Describe the solution you'd like**
Is there a plan to add a `change` type for `statistics`?

**Comment by tomlut** [comment]
Is this actually working?

ApexCharts 2.1.1

```
series:
  - entity: sensor.upstairs_hp_energy
    type: column
    float_precision: 0
    statistics:
      type: change
      period: day
      align: middle
```
![Screenshot 2024-07-10 at 10-07-17 Administration – Home Assistant](https://github.com/RomRider/apexcharts-card/assets/10679300/cfb0f79d-f968-444c-88ce-33d8faa29724)
