### ISSUE TITLE
Doesn't show a few points at the beginning of the series

### ISSUE THREAD

**Issue by ibocharov** [RomRider/apexcharts-card#553]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Doesn't show a few points at the beginning of the series.
It happens randomly and only in the finalized card view mode. In edit card mode it can't be reproduced (look at the screenshots below).
I've even tried to use fill & fill_raw config options but no luck.

**Version of the card**
Version: v2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 12h
header:
  show: false
layout: minimal
all_series_config:
  type: area
  opacity: 0.15
  stroke_width: 0.5
  extend_to: now
  fill_raw: zero
  group_by:
    func: avg
    duration: 10m
    fill: last
series:
  - entity: sensor.bedroom_ths_temperature
    name: Bedroom
  - entity: sensor.bedroom_ir_temperature
    name: IR
```

**Screenshots**
card view mode
<img width="580" alt="Screenshot 2023-05-07 at 14 59 35" src="https://user-images.githubusercontent.com/6703786/236676724-3231ac86-bd2f-4f31-9133-e3929679f5bd.png">
<img width="832" alt="Screenshot 2023-05-07 at 15 48 52" src="https://user-images.githubusercontent.com/6703786/236678633-1c642ca4-72b5-4cf7-9f45-a1226eccad9b.png">

edit card mode
<img width="578" alt="Screenshot 2023-05-07 at 14 59 51" src="https://user-images.githubusercontent.com/6703786/236676728-d939309d-ac65-4f22-9afa-0b41cd15d45c.png">
<img width="827" alt="Screenshot 2023-05-07 at 15 48 38" src="https://user-images.githubusercontent.com/6703786/236678628-80d9c511-4550-4763-b5ee-8e2fb3938d43.png">

**Expected behavior**
Series with points from the beginning to the end of the view as on screenshot in edit card mode

**Desktop & Smartphone (please complete the following information):**
- Chrome, Safari browsers and HA app on MacOS 13.3
- Chrome browser and HA app on iOS 16.4 
- Chrome browser and HA app on Android 10
