### ISSUE TITLE
Experimental Brush: Values Misplaced on Graph

### ISSUE THREAD

**Issue by melvanderwal** [RomRider/apexcharts-card#556]
**Checklist**
- [ x ] I updated the card to the latest version available
- [ x ] I cleared the cache of my browser
- [ x ] I verified that I'm really running the lastest version in my browser console
- [ x ] I checked if there is another issue opened with the same problem

Card content is two series which generally parallel each other when viewed as lines.

When the brush feature is used, the Y values in the *second series* are mis-plotted on the main graph. The values are correct in the brush graph.  

The issue does not occur when the brush feature is not used.

In the screenshots, `brush: selection_span` is set to the full width of the graph to enable visual comparison between the main graph and the brush graph.  The issue still exists when a smaller selection span is used, or if no selection span is specified.

An error is raised in the console stating that `value.experimental.brush is not a boolean`, however setting the value results in the correct behaviour:  when `true`, the brush graph is visible, and when `false` it is hidden. I am doubtful that this error is related to this bug, but thought I'd bring it forward just in case.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
update_delay: 3s
update_interval: 1min
graph_span: 24h
experimental:
  brush: true
brush:
  selection_span: 24h
span:
  start: hour
  offset: '-23h'
apex_config:
  chart:
    height: 335px
yaxis:
  - id: left
    decimals: 2
    apex_config:
      title:
        text: $
        rotate: 0
all_series_config:
  float_precision: 2
  show:
    in_brush: true
series:
  - entity: input_number.amber_closing_export_price
    name: Sold Price
  - entity: input_number.amber_closing_import_price
    name: Bought Price
```

**Screenshots**
Console error
![image](https://github.com/RomRider/apexcharts-card/assets/25993713/7b5298fb-1e81-45d4-ad3d-1bcca03f7b05)

With `experimental: brush` set to true, the Bought Price value of $0.42 is at the incorrect vertical location.
![image](https://github.com/RomRider/apexcharts-card/assets/25993713/25d6a56e-3b18-4224-bcdf-bd74235113ed)

With `experimental: brush` set to false, the Bought Price value of $0.42 is at the correct vertical location.
![image](https://github.com/RomRider/apexcharts-card/assets/25993713/bf373380-aa67-45c8-b463-2c6e669469b7)

Exact same configuration, but with series order reversed results in values from the other series (Sold Price is now the second series) being in the incorrect location, confirming that the issue affects the second series but not the first.
![image](https://github.com/RomRider/apexcharts-card/assets/25993713/18a94608-603c-4909-a31f-bcadffd5dcc4)

**Expected behavior**
Lines should be plotted with values matching the Y axis.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 113.0.5672.93 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Browser: Chrome 
 - Version: 113.0.5672.76
 - Running Android Companion app
