### ISSUE TITLE
conditional card - not displaying apex chart

### ISSUE THREAD

**Issue by raghu-ranganathan** [RomRider/apexcharts-card#559]
When using a conditional card to display the custom apex chart, e.g., condition is a binary sensor state is ‘off’, the chart is not displayed. 

However, the chart is displayed fine as a normal custom apex chart card.

Shown below is the first few lines:

```
type: conditional
conditions:
  - entity: binary_sensor.8pm_to_5am
    state: 'Off'
card:
  type: custom:apexcharts-card
  apex_config:
    chart:
      height: 150px
```

——-[snip]

Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

Apexcharts 2.0.4
