### ISSUE TITLE
Wrong value on y-axis

### ISSUE THREAD

**Issue by Diavolezza** [RomRider/apexcharts-card#560]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The minimum value displayed for the y-axis is wrong. In this example it should display 0.06 and not 0.07 twice:
<img width="327" alt="Bildschirmfoto 2023-05-22 um 13 51 38" src="https://github.com/RomRider/apexcharts-card/assets/8983765/7daf61a3-0fff-4679-b721-f9f08a9618e3">

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  title: Strompreis (€/kwh)
yaxis:
  - decimals: 2
series:
  - entity: sensor.average_electricity_price_today
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 1
    color: ''
    data_generator: |
      return entity.attributes.prices.map((entry) => { 
      return [new Date(entry.time), entry.price];
      });

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: most recent

**Additional context**
