### ISSUE TITLE
Help? - graph is rendering very strangely

### ISSUE THREAD

**Issue by lenwar** [RomRider/apexcharts-card#562]
Hi,
I have a graph that is rendering really strangely. Any suggestions are welcome
![afbeelding](https://github.com/RomRider/apexcharts-card/assets/3773186/64c5a264-e416-4df2-a86e-e6d46d96b4bb)

It seems to jump from 21:02 to 13:02 and back to 22:02

The current data is:
```
{{ states('sensor.zonneplan_current_electricity_tariff') }}   ##### -->  0.1507167
```

This is how it looks in the 'history'
![afbeelding](https://github.com/RomRider/apexcharts-card/assets/3773186/8ecded3e-2f17-4142-b306-798c49c5262b)

configuration:

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
apex_config:
  legend:
    show: false
header:
  show: true
  show_states: true
  colorize_states: true
span:
  end: hour
graph_span: 24h
yaxis:
  - id: kosten
    opposite: true
    decimals: 2
    apex_config:
      decimalsInFloat: 3
series:
  - entity: sensor.zonneplan_current_electricity_tariff
    name: Elektriciteitsprijs
    yaxis_id: kosten
    unit: €/kWh
    stroke_width: 2
    float_precision: 3
    show:
      header_color_threshold: true
    extend_to: false
```
