### ISSUE TITLE
Change position of unit on y-axis

### ISSUE THREAD

**Issue by dflvunoooooo** [RomRider/apexcharts-card#565]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Somewhat. The actual setting is causing the graph to be very large and somewhat ugly :D Here is a picture

![Screenshot_20230531_104728](https://github.com/RomRider/apexcharts-card/assets/32816598/ecfc0391-b2b5-4798-95db-12baf9a56ea5)

The unit is causing the graph to be very small. 

**Describe the solution you'd like**
It wolud be great to have the option to place the unit at the to of the y-axis.

**Describe alternatives you've considered**
Having no units, but this does no make sense.

**Additional context**
Here is my code:

```
type: custom:apexcharts-card
header:
  show: true
  title: Verbrauch
graph_span: 1h
update_interval: 1h
all_series_config:
  stroke_width: 1
yaxis:
  - id: first
    decimals: 0
    apex_config:
      forceNiceScale: true
      title:
        text: W
  - id: second
    opposite: true
    decimals: 0
    apex_config:
      forceNiceScale: true
      title:
        text: '%'
  - id: third
    opposite: true
    decimals: 0
    apex_config:
      forceNiceScale: true
      title:
        text: °C
series:
  - entity: sensor.wohnzimmer_server_stecker_aubess_tuya_power
    name: Leistung
    yaxis_id: first
    fill_raw: last
  - entity: sensor.proxfuji_cpu_load_1_min_avg
    name: CPU Last
    yaxis_id: second
    offset: '-1min'
    fill_raw: last
  - entity: sensor.proxfuji_temperature_x86_pkg
    name: CPU Temp.
    yaxis_id: third
    fill_raw: last
```

Would be great to look something like this:

![S222creenshot_20230531_104728](https://github.com/RomRider/apexcharts-card/assets/32816598/1e781d23-c84e-4a76-971b-2b3943b4b391)

**Comment by dflvunoooooo** [comment]
I got a bit further here. The apex_chart options for the title helped me on. Here is my code:

```
type: custom:apexcharts-card
header:
  show: true
  title: Verbrauch
graph_span: 1h
update_interval: 1min
all_series_config:
  stroke_width: 1
apex_config:
  legend:
    show: false
yaxis:
  - id: first
    decimals: 0
    apex_config:
      forceNiceScale: true
      title:
        text: '[W]'
        rotate: 0
        offsetX: 15
        offsetY: -140
      'labels:':
        show: false
        offsetX: 50
      axisTicks:
        show: false
  - id: second
    opposite: true
    decimals: 0
    apex_config:
      forceNiceScale: true
      title:
        text: '[%]'
        rotate: 0
        offsetX: -15
        offsetY: -140
  - id: third
    opposite: true
    decimals: 0
    apex_config:
      forceNiceScale: true
      title:
        text: '[°C]'
        rotate: 0
        offsetX: -15
        offsetY: -140
series:
  - entity: sensor.wohnzimmer_server_stecker_aubess_tuya_power
    name: Leistung
    yaxis_id: first
    fill_raw: last
    show:
      in_header: false
  - entity: sensor.proxfuji_cpu_load_1_min_avg
    name: CPU Last
    yaxis_id: second
    offset: +1min
    fill_raw: last
  - entity: sensor.proxfuji_temperature_x86_pkg
    name: CPU Temp.
    yaxis_id: third
    fill_raw: last
```

This is the resulting graph:

![Screenshot_20230605_092702](https://github.com/RomRider/apexcharts-card/assets/32816598/10b006fe-043b-4e3d-aa41-0d262d014b5d)

But sadly the options to move the actual axis does nothing.
