### ISSUE TITLE
color_threshold seems not to be working

### ISSUE THREAD

**Issue by ronschokker** [RomRider/apexcharts-card#568]
Good day,

I fancy a graph for a temperature sensor, which displays a line or area whose color depends on the value. (e.g. Low values blue, turning to green for 'medium' and turning to red for high values)
I copied the exact example for how to use the color_threshold, only changing the colors and starting values, but do not get the result I wanted. 
In the screenshot you can see that the area is red also for the low value times. Seems like it distributes all colors over the area, no matter what the values are.

**Version of the card**
V2.0.4

**Configuration**
```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: ApexCharts-Card
  show_states: true
series:
  - entity: sensor.0xa4c138853544701c_temperature
    type: area
    stroke_width: 1
    color_threshold:
      - value: 15
        color: blue
      - value: 20
        color: green
      - value: 25
        color: red
```

**Screenshot**
![image](https://github.com/RomRider/apexcharts-card/assets/128402124/1ef86981-caee-4296-878f-5f278410a514)

**Expectation**
I expect the area to be red only when values are above 25, but it seems to act like a percentage or something.
It shows both in the iOS app and Chrome.

What am I doing wrong here :)
