### ISSUE TITLE
chart broken with yaxis label align left and two entities

### ISSUE THREAD

**Issue by dflvunoooooo** [RomRider/apexcharts-card#571]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
If I create a chart with two entities and set the yaxis label to align left, the chart gets broken.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 24h
update_interval: 1min
yaxis:
  - apex_config:
      labels:
        align: left
series:
  - entity: sensor.schlafzimmer_aqara_bewegungsmelder_illuminance_lux
    name: Aqara
  - entity: sensor.schlafzimmer_tuya_temperatur_feuchtigkeit_humidity
    name: ESP32 mmwave
```

**Screenshots**
![Screenshot_20230613_014731](https://github.com/RomRider/apexcharts-card/assets/32816598/0335a22c-47cb-45fe-9ab6-782e75553f75)

**Expected behavior**
I expect the chart to render normally. I initially noticed this in a more complex chart, where my tooltip vanished.

**Desktop (please complete the following information):**
 - Browser firefox, google chrome
 - Version 114.0, 114.0.5735.90

**Smartphone (please complete the following information):**
 - Device: ASUS Zenfone 8
 - OS: stock
 - Browser home assistant companion app
 - Version 2023.3.0-full
