### ISSUE TITLE
Access bucket size to correct calculation / riemann sum / integrate / integral / area under graph

### ISSUE THREAD

**Issue by dflvunoooooo** [RomRider/apexcharts-card#572]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
It is related to #205. I would be great to access the number of states in a bucket so that one can transform the grouped value to display the correct data. For example if monitor the power consumption of a device and group it by 30 minutes, the result will not display the actual consumption over 30 min, but the sum of all occurred states. If there was just one state in 30 minutes, the sum will consist of one state. If there where 300 states  in 30 minutes, the sum will be far higher. This does not represent the reality. 

**Describe the solution you'd like**
If it would be possible to access the number of states in a bucket, one could transform the grouped result. For example: `transform: return x / $BUCKET_SIZE;`

Or far better, add function to calculate the riemann sum / area under the graph. That would be perfect. 

**Describe alternatives you've considered**
I have tried all different combination of statistics and group_by, but was unable to fix this.

**Additional context**
Here is the sum per 20 minutes of the power consumption of my server. The server uses between 27 and 50 watts. The graph shows values around 2000 watts. That is ridiculous. 

![Screenshot_20230613_111220](https://github.com/RomRider/apexcharts-card/assets/32816598/2253159c-c815-4367-92b1-eb0a0bf6eafc)

```
type: custom:apexcharts-card
graph_span: 24h
update_interval: 20min
header:
  show: true
  title: Falsch, da bucket size unbekannt
all_series_config:
  stroke_width: 2
  group_by:
    func: sum
    duration: 20min
    start_with_last: true
  float_precision: 0
series:
  - entity: sensor.wohnzimmer_server_stecker_aubess_tuya_power
```
