### ISSUE TITLE
Apexcharts-card causing entire web browser to hand due to high resource utilization

### ISSUE THREAD

**Issue by mkanet** [RomRider/apexcharts-card#577]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem
       https://github.com/RomRider/apexcharts-card/issues/210  **<---[Closed with no solution]**

**Describe the bug**
When I make apexcharts-cards using my HA sensors, it causes the entire web browser to become unresponsive; even on a relatively fast PC with lots of free resources.  

**NOTE:  This issue doesn't happen with other graph cards such as history-graph, etc.**  

**Things I already tried**
-Disabled web browser extensions/addons; including ad-blocking
-Changed `update_interval` to >1 minute
-Tried different web browsers on PC

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 1d
update_delay: 5s
update_interval: 1min
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
all_series_config:
  stroke_width: 2
series:
  - entity: sensor.total_cpu_usage
  - entity: sensor.cpu_package_temperature
    type: column
```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/811008/96d44392-4e7b-464f-b0d9-49aa62ff433e)
**NOTE:**  Screenshot has a couple of extensions enabled.  However, disabling all of them still has the same result.

**Expected behavior**
Resource utilization should be comparable to other graph cards like history-graph, etc using the same sensors.

**Desktop (please complete the following information):**
 - Browser [Chrome, MS Edge]
 - Version [latest]
