### ISSUE TITLE
Support new time zone (local/server time) feature released in 2023.7

### ISSUE THREAD

**Issue by jrb80** [RomRider/apexcharts-card#579]
HA have just released an awesome new feature in [2023.7 ](https://www.home-assistant.io/blog/2023/07/05/release-20237/) which provides the option to select how you display time on the UI, either using the local time (default) or the server time (new). This is incredibly useful if the HA instance is in another country/time zone or if you are travelling abroad.

However, my initial testing suggests this feature isn't supported by this custom card. I show an example below showing the Apex Chart and HA History card using the server time option. The HA History (bottom) card is correctly displaying the server time, whereas the Apex Chart is still using the local client time.

![image](https://github.com/RomRider/apexcharts-card/assets/1820167/7a683043-212b-4e9a-9dfc-916c316fbdce)

**Comment by jpettitt** [comment]
This particularly annoying if you have charts that use end of day / week / month as it currently uses the browser local time and yields confusing results.

**Comment by GitHubGoody** [comment]
+1

**Comment by Lenbok** [comment]
I am guessing that https://github.com/RomRider/apexcharts-card/blob/1b63c0f53fadde489179f7c9e08d700daeb4215e/src/apexcharts-card.ts#L1444-L1463 needs to be updated, either with an explicit property like the clock weather card guys do in https://github.com/pkissling/clock-weather-card/blob/2e536aecefabf6096a4bc048b5d61736a55c348d/src/clock-weather-card.ts#L511 or by checking the 2023.7 hass preference. I don't know any typescript/javascript so am not up for it myself.

**Comment by Lenbok** [comment]
bump to keep alive

**Comment by Lenbok** [comment]
Still an issue.

**Comment by martin3000** [comment]
Discovered this today while I am in Asia and my home is in Europe.

**Comment by markcocker** [comment]
Under my HA user profile I have `Time Zone` set to `Use server time zone (Europe/London)`.
When I am travelling my machine + browser changes to another time zone, eg. GMT-5. The following keeps the ApexChart card xaxis showing GMT. For details see datetimeUTC - https://apexcharts.com/docs/options/xaxis/

```yaml
apex_config:
  xaxis:
    labels:
      datetimeUTC: true
```

**Comment by martin3000** [comment]
Since I do not live in the UTC (GMT+0) time zone, this does not make sense for me.

**Comment by budisek** [comment]
I've set `Server time zone` and add `datetimeUTC: true ` but i need to set UTC+8 because my iOS HA app shows wrong values on apexchart. I can only change time zone on my iPhone but it is not an solution.

**Comment by jrb80** [comment]
Here is an example of the problem using the Sun2 integration. This apexchart is viewed locally, in the same timezone as the Home Assistant server. The sunrise is show correctly
![Local_View](https://github.com/RomRider/apexcharts-card/assets/1820167/f420bcb0-888e-4a0d-9b7b-1d34896b3fa4)

Here is the same apexchart, viewed at the same time but from a different timezone from the Home Assistant server. You will not the sunrise is not shown correctly as the client time is used, rather than the server time
![Remote_View](https://github.com/RomRider/apexcharts-card/assets/1820167/28795aab-0b4a-45ff-af12-c1e74a3b15ee)

**Comment by Lenbok** [comment]
+1 still an issue.

**Comment by NikolajChristensen** [comment]
+1 still an issue.

**Comment by RomRider** [comment]
Working on it, but it's quite painful as the apexcharts library only supports displaying in browser's localtime or UTC. But I'll get there eventually.

**Comment by RomRider** [comment]
Please test this extensively with your setup as I might have missed edge cases !

**Comment by Lenbok** [comment]
This is working well for me so far, thanks!

**Comment by NikolajChristensen** [comment]
Works well here too. Much much better experience. Thanks!

**Comment by jrb80** [comment]
@RomRider it works great, I've been waiting so long for this update, many thanks! Here is the same graph comparison from the original issue report, the Apex chart correctly displays the server time, brilliant! 

![After](https://github.com/RomRider/apexcharts-card/assets/1820167/30ce811e-602c-4c82-b456-a2cba2079ee5)

**Comment by Sammy990** [comment]
Not sure if this is my "homemade" issue, or a general one. I have a apex card for Tibber prices forecast. Since the update it now correctly uses the server time in the card, but the chart is placed wrong. It should starting the graph from midnight, but it does start much later...


```

type: custom:apexcharts-card
experimental:
  color_threshold: true
all_series_config:
  unit: Cent/kWh
apex_config:
  grid:
    show: true
    borderColor: '#E0E0E0'
  chart:
    height: 250px
  tooltip:
    enabled: true
    followCursor: false
    x:
      show: false
    fixed:
      enabled: true
header:
  show: true
  title: Strompreis
  show_states: true
  colorize_states: true
  standard_format: false
graph_span: 48h
now:
  show: true
  color: 9E9E9E
span:
  start: day
series:
  - entity: sensor.tibber_prices
    show:
      in_header: before_now
      name_in_header: false
    color_threshold:
      - value: 0
        color: 4DD0E1
      - value: 10
        color: 26A69A
      - value: 15
        color: 4CAF50
      - value: 20
        color: 7CB342
      - value: 25
        color: FBC02D
      - value: 30
        color: EF6C00
      - value: 40
        color: B71C1C
    type: line
    curve: stepline
    extend_to: false
    stroke_width: 4
    float_precision: 2
    data_generator: |
      const noon = new Date()
      noon.setHours(0, 0, 0, 0)
      const prices = entity.attributes.today.concat(entity.attributes.tomorrow);
      const data = [];
      for(let i = 0; i < prices.length; i++) {
        data.push([noon.getTime() + i * 1000 * 3600, prices[i].total * 100])
      }
      return data;

```
![image](https://github.com/user-attachments/assets/45ac3e06-4fa6-49c3-98be-1e25f454091c)
