### ISSUE TITLE
error when trying to integrate the card in the prototype lovelace drag and drop 

### ISSUE THREAD

**Issue by scooper1** [RomRider/apexcharts-card#58]
**Checklist**
- [X ] I am running the latest version of the card
- [ X] I checked if there isn't another feature request opened with the same request
- [ X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
the new prototype drag and drop Lovelace editor stops the card from working 
because it appends another value pair to the card that your syntax checker does not like

**Describe the solution you'd like**
ignore extra value pairs that other custom integration may add

**Describe alternatives you've considered**
not checking extra value pairs at the base level 

**Additional context**
sorry bit long  - relevant  code lines

```
    type: 'custom:grid-dnd
        type: 'custom:apexcharts-card'
        layout:
          key: b99d9004-f09e-4299-bb37-137c53ca0c97

```
```
  - title: test2
    path: test2
    type: 'custom:grid-dnd
    cards:
      - entities:
          - entity: climate.wiser_back_room
          - entity: climate.wiser_front_room
          - entity: climate.wiser_hall
          - entity: climate.wiser_old_kitchen
          - entity: climate.wiser_mum_bedroom
          - entity: climate.wiser_mums_bath_room
          - entity: climate.wiser_middle_toilet
          - entity: climate.wiser_back_bedroom
          - entity: climate.wiser_top_bath_room
          - entity: climate.wiser_top_floor
        show_header_toggle: false
        title: Room Heating Temperatures
        type: entities
        state_color: true
        layout:
          key: 25a9ed14-9875-47b8-a75d-9168d7dd3df4
      - header:
          show: true
          title: .
          floating: false
          show_states: true
          colorize_states: true
        now:
          show: true
        graph_span: 7d
        span:
          start: minute
          offset: '-7d'
        series:
          - entity: sensor.wiser_itrv_back_room_2
            attribute: device_reception_RSSI
            color: 'rgb(128, 0, 128)'
            group_by:
              duration: 5min
              func: avg
            name: Device RSSI
            curve: stepline
            show:
              in_header: false
          - entity: sensor.wiser_itrv_back_room_2
            attribute: controller_reception_RSSI
            color: 'rgb(0, 128, 128)'
            group_by:
              duration: 5min
              func: avg
            name: Controller RSSI
            curve: stepline
            show:
              in_header: false
          - entity: climate.wiser_back_room
            attribute: percentage_demand
            color: 'rgb(0, 0, 255)'
            group_by:
              duration: 5min
              func: max
            name: Demand
            fill_raw: zero
            unit: '%'
          - entity: climate.wiser_back_room
            attribute: temperature
            color: 'rgb(0, 255, 0)'
            name: Target
            group_by:
              duration: 5min
              func: max
            curve: stepline
            unit: ℃
          - entity: climate.wiser_back_room
            attribute: current_temperature
            color: 'rgb(255, 0, 0)'
            group_by:
              duration: 5min
              func: max
            name: Current
            unit: ℃
          - entity: sensor.outdoor_temperature
            color: 'rgb(128, 128, 128)'
            group_by:
              duration: 10min
              func: avg
            name: Outdoor
        y_axis_precision: 0
        apex_config:
          stroke:
            width:
              - 2
              - 2
              - 3
              - 3
              - 3
              - 3
          yaxis:
            - show: false
              decimalsInFloat: 0
              min: -125
              max: 0
            - show: false
              decimalsInFloat: 0
              min: -125
              max: 0
            - show: true
              opposite: true
              min: -25
              max: 100
              decimalsInFloat: 0
            - show: true
              decimalsInFloat: 0
              min: -7
              max: 30
            - show: false
              decimalsInFloat: 0
              min: -7
              max: 30
            - show: false
              decimalsInFloat: 0
              min: -7
              max: 30
          xaxis:
            type: datetime
            zoom:
              type: x
              enabled: true
              autoScaleYaxis: true
          chart:
            type: line
            stacked: false
            height: 350
            zoom:
              type: x
              enabled: true
              autoScaleYaxis: true
            toolbar:
              show: true
              offsetX: -40
              offsetY: 0
              tools:
                download: true
                selection: true
                zoom: true
                zoomin: false
                zoomout: false
                pan: true
                reset: true
              autoSelected: zoom
          grid:
            borderColor: 'rgb(40, 40, 40)'
            strokeDashArray: 0
            position: back
            row:
              colors:
                - 'rgb(60, 60, 60)'
                - transparent
              opacity: 0.1
            column:
              colors:
                - 'rgb(60, 60, 60)'
                - transparent
              opacity: 0.1
            xaxis:
              lines:
                show: true
            padding:
              top: 5
              right: 4
              bottom: 10
              left: 4
          title:
            text: Back Room Heating
            align: centre
            margin: 0
            offsetX: 5
            offsetY: -75
            floating: true
            style:
              fontSize: 22px
              fontWeight: normal
              fontFamily: undefined
              color: 'rgb(255, 255, 255)'
        show:
          loading: false
        type: 'custom:apexcharts-card'
        layout:
          key: b99d9004-f09e-4299-bb37-137c53ca0c97

```
<img width="947" alt="Screenshot 2021-02-05 003037" src="https://user-images.githubusercontent.com/14822945/106974187-2ae8b000-674c-11eb-98a0-9537207d185c.png">

the red part should look like 

<img width="407" alt="Screenshot 2021-02-05 010032" src="https://user-images.githubusercontent.com/14822945/106975011-a1d27880-674d-11eb-980d-0c2cd3c7d575.png">
