### ISSUE TITLE
Wrong drawing when negative?

### ISSUE THREAD

**Issue by CrazyHenk44** [RomRider/apexcharts-card#580]
**Describe the bug**

Blue line is drawn wrongly when negative. See how the blue **label** does not match the position of the blue **line**? As long as it is positive, it's correct, but when negative it is wrong.

**To Reproduce**
This is the configuration I used:
```yaml

type: custom:apexcharts-card
update_interval: 30s
graph_span: 3h
experimental:
  brush: true
brush:
  selection_span: 3h
all_series_config:
  stroke_width: 2
yaxis:
  - id: first
    decimals: 0
  - id: second
    opposite: true
    decimals: 0
    min: 0
    max: 100
header:
  show: true
  title: Sessy Efficiency
  show_states: true
  colorize_states: true
series:
  - entity: sensor.sessy_dwhn_power
    yaxis_id: first
    name: Sessy Power
    group_by:
      func: avg
      duration: 2min
  - entity: sensor.sessy_active_power_flip
    yaxis_id: first
    name: Real Power
    group_by:
      func: avg
      duration: 2min
  - entity: sensor.sessy_dwhn_state_of_charge
    name: Sessy SoC
    yaxis_id: second
    stroke_width: 4
  - entity: sensor.sessy_active_power_lost
    name: Power Lost
    type: column
    yaxis_id: first
    group_by:
      func: avg
      duration: 2min
    show:
      in_brush: true
      in_chart: false
      in_header: true

```

**Expected behavior**
The blue line should be below the yellow line when negative. And I expect the blue  line to be drawn at -1500 (according to the label) and not at -1200 (as seen in the graph).

**Desktop (please complete the following information):**
 - Browser : safari
![Safari My Energy – Home Assistant 11 11 37@2x](https://github.com/RomRider/apexcharts-card/assets/5298235/af7e5e64-2226-4bdd-97da-0abe75f0d74c)
