### ISSUE TITLE
Cannot use state_attr inside yaml for custom attribute

### ISSUE THREAD

**Issue by zanac** [RomRider/apexcharts-card#588]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
I have sensors with custom attribute for colors... i need to use the hex from that attribute in yaml of card:
color: '{{ state_attr("sensor.en_solar", "en_icon_color") }}'

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 24h
update_interval: 10min
span:
  start: day
apex_config:
  chart:
    stacked: true
    height: 700px
  legend:
    show: true
  tooltip:
    enabled: false
now:
  show: true
header:
  show: false
  title: ' '
  show_states: false
all_series_config:
  type: area
  group_by:
    func: avg
    fill: zero
    duration: 30min
series:
  - entity: sensor.en_asciugatrice
    attribute: en_value_w
    name: Asciugatrice
    stroke_width: 0
    extend_to: false
    color: '#00ff9d'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_aspirazione
    attribute: en_value_w
    name: Aspirazione
    stroke_width: 0
    extend_to: false
    color: '#18ab24'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_deumidificatore
    attribute: en_value_w
    name: Deumidificatore
    stroke_width: 0
    extend_to: false
    color: '#188eab'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_forno
    attribute: en_value_w
    name: Forno
    stroke_width: 0
    extend_to: false
    color: '#e00b39'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_frigorifero
    attribute: en_value_w
    name: Frigorifero
    stroke_width: 0
    extend_to: false
    color: '#6ba5c7'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_lavastoviglie
    attribute: en_value_w
    name: Lavastoviglie
    stroke_width: 0
    extend_to: false
    color: green
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_lavatrice
    attribute: en_value_w
    name: Lavatrice
    stroke_width: 0
    extend_to: false
    color: '#4563d9'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_lavatrice_garage
    attribute: en_value_w
    name: Lavatrice Garage
    stroke_width: 0
    extend_to: false
    color: '#4563d9'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_luci_esterne
    attribute: en_value_w
    name: Luci Esterne
    stroke_width: 0
    extend_to: false
    color: '#a9b31d'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_luci_mansarda
    attribute: en_value_w
    name: Luci Mansarda
    stroke_width: 0
    extend_to: false
    color: '#a9b31d'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_luci_piano_terra
    attribute: en_value_w
    name: Luci Terra
    stroke_width: 0
    extend_to: false
    color: '#a9b31d'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_induzione
    attribute: en_value_w
    name: Induzione
    stroke_width: 0
    extend_to: false
    color: black
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_pdc
    attribute: en_value_w
    name: Pompa Di Calore
    stroke_width: 0
    extend_to: false
    color: '#9529ab'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_pdc_ehs
    attribute: en_value_w
    name: Pompa EHS
    stroke_width: 0
    extend_to: false
    color: '#9529ab'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_scaldasalviette
    attribute: en_value_w
    name: Scaldasalviette
    stroke_width: 0
    extend_to: false
    color: '#8a1327'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_split
    attribute: en_value_w
    name: Split
    stroke_width: 0
    extend_to: false
    color: '#4f65a8'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_vmc
    attribute: en_value_w
    stroke_width: 0
    extend_to: false
    name: VMC
    color: '#4f65a8'
    float_precision: 0
    show:
      legend_value: false
  - entity: sensor.en_solar
    attribute: en_value_w
    name: Fotovoltaico
    stroke_width: 5
    extend_to: false
    color: '{{ state_attr("sensor.en_solar", "en_icon_color") }}'
    float_precision: 0
    type: line
    curve: smooth
    show:
      legend_value: false
  - entity: sensor.en_missing
    attribute: en_value_w
    stroke_width: 0
    extend_to: false
    name: Mancante
    color: gray
    float_precision: 0
    show:
      legend_value: false
yaxis:
  - min: 0
    decimals: 0
```
