### ISSUE TITLE
iOS not graphing/showing entities made with 'data_generator'?

### ISSUE THREAD

**Issue by hapklaar** [RomRider/apexcharts-card#596]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Created a graph showing electricity prices. Graph shows fine on Windows (Edge) and Android (HA app), but not on iOS in the HA app

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  title: Electriciteitsprijzen Vandaag (€/kwh)
yaxis:
  - decimals: 2
series:
  - entity: sensor.average_electricity_price_today
    name: Current all-in energy price
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 10
    color: green
    data_generator: |
      return entity.attributes.prices.map((entry) => { 
      return [new Date(entry.time), entry.price];
      });

```

**Screenshots**
Expected, shown correctly on Edge and Android HA app:
![image](https://github.com/RomRider/apexcharts-card/assets/7703320/e3f8ae1b-7d18-4e12-aa72-72f16f8208ae)

Issue on iPad:
![20230823_154525](https://github.com/RomRider/apexcharts-card/assets/7703320/2016c33f-9372-43bc-8268-491b2daff350)

**Desktop (please complete the following information):**
 - Browser Edge
 - Version 115.0.1901.203

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 15.7.7
 - Browser Home Assistant app
 - Version 2023.4

**Additional context**
It seems like any entity created with 'data_generator' is not being graphed on my iPad. 
Already removed and reinstalled the app, also rebooted, to no avail. Issue remains.

**Comment by arpiecodes** [comment]
I have the exact same issue on my iPad.

**Comment by jelmerwouters** [comment]
Very similar, but I'm having this issues on desktop as well (both in Chrome and Firefox; MacOS Sonoma)

![image](https://github.com/RomRider/apexcharts-card/assets/78026082/64005a47-00e9-4f5f-9e6f-303169c00508)

```yaml
type: custom:apexcharts-card
graph_span: 10d
header:
  show: true
  title: Rainfall
  show_states: true
now:
  show: true
span:
  start: day
  offset: '-5d'
apex_config:
  chart:
    height: 175px
  legend:
    show: false
  tooltip:
    enabled: false
  xaxis:
    tickAmount: 10
    labels:
      formatter: |
        EVAL:function(value) {
          weekday = new Date(value).toLocaleDateString("nl-NL", { weekday: 'short' }).substr(0,2);      
          return weekday.charAt(0).toUpperCase() + weekday.slice(1);
        }
series:
  - entity: sensor.rainfall_today
    name: Today
    type: area
    color: 488fc2
    stroke_width: 3
    extend_to: false
    fill_raw: zero
    show:
      datalabels: true
    group_by:
      func: max
      duration: 1d
      fill: zero
  - entity: weather.buienradar
    type: area
    color: ffa602
    stroke_width: 2
    show:
      in_header: false
      datalabels: true
    data_generator: |
      return entity.attributes.forecast.map((entry) => {
        return [new Date(entry.datetime).getTime(), entry.precipitation];
      });
  - entity: sensor.buienradar_precipitation_forecast_total
    type: line
    name: Forecast (2hr)
    show:
      in_chart: false
```
