### ISSUE TITLE
Visibility of Y axis values depends only on visibility of fist series

### ISSUE THREAD

**Issue by diggit** [RomRider/apexcharts-card#599]
**Checklist**
- [x] I updated the card to the latest version available (2.0.4)
- [x] I cleared the cache of my browser (checked in anonymous window)
- [x] I verified that I'm really running the latest version in my browser console (`APEXCHARTS-CARD  v2.0.4`)
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
If chart has multiple series bound to one Y axis, hiding first one (by clicking it's name) hides Y axis values even though there are other series using it.

**Version of the card**
Version: 2.0.4

**To Reproduce**
Use multiple series bound to one Y axis and disable first one. Observe missing Y axis values.

This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 24h
yaxis:
  - id: first
    decimals: 1
    apex_config:
      tickAmount: 5
series:
  - entity: sensor.tz3000_dowj6gyi_ts0201_temperature
    name: Temperature 1
    yaxis_id: first
    color: red
  - entity: sensor.ths_02_temperature
    name: Temperature 2
    yaxis_id: first
    color: green
```

**Screenshots**
## All series enabled
![image](https://github.com/RomRider/apexcharts-card/assets/512025/fa2542ff-966b-406f-8c7a-c829073cc92b)

## First series disabled
![image](https://github.com/RomRider/apexcharts-card/assets/512025/e8c08d9b-2cdf-4393-a23d-5cf8951ea53c)

## Second series disabled
![image](https://github.com/RomRider/apexcharts-card/assets/512025/3a36879f-13a6-42dd-a1f3-042d734bf750)

**Expected behavior**
Y axis values visible as long as there are displayed series using this axis.

**Desktop:**
 - Firefox developer edition 117
 - Chromium 116

**Smartphone**
 - Device: Samsung Galaxy S10e
 - OS: Lineage OS 20
 - Browser Fennec (Firefox) 116.3
 - HA app 2023.8.4, uses webview (not sure how to get version)
