### ISSUE TITLE
Concrete colouring for stepline line graph

### ISSUE THREAD

**Issue by jtagcat** [RomRider/apexcharts-card#604]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Using colours for decision-making, all four bottom slices should be fully green, but they are on a gradient instead.

![image](https://github.com/RomRider/apexcharts-card/assets/38327267/e10978cc-9b08-4906-bd30-adf71494da0a)

```
 type: line
 curve: stepline
```

**Describe the solution you'd like**
Horizontal lines should be single-coloured based on the value. Vertical lines may be gradients.

Looking to fully replace the 'current' gauge:
![image](https://github.com/RomRider/apexcharts-card/assets/38327267/9e211707-427f-4714-adee-e86878bb1457)

Dotted horizontal reference lines would help as well.

**Comment by jtagcat** [comment]
unstale

**Comment by RomRider** [comment]
If you want hard transitions you can do it this way :
```yaml
- value: 0
  color: green
- value: 3
  color: green
- value: 3
  color: orange
- value: 6
  color: orange
- value: 6
  color: red
```
