### ISSUE TITLE
Brush experimental: y_axis assignment breaks scaling in main chart

### ISSUE THREAD

**Issue by AleXSR700** [RomRider/apexcharts-card#605]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When the brush experimental feature is enabled and a chart displays >=2 entities, the y_axis of the main chart will stay fixed in scale for the first entity and the second entity will not be scaled to match it IF both entities are assigned to a y_axis
As you can see below, the scaling of the brush chart at the bottom is correct. But the main chart at the top shows the wrong scaling between y_axis and second (green) entity.

**Version of the card**
Version: v2.0.4

**To Reproduce**
Wrong scaling:
```yaml
type: custom:apexcharts-card
series:
  - entity: sensor.sony_kd_75xf9005_naim_audio_av_energy_power_0
    yaxis_id: first
    color: orange
    show:
      in_chart: true
      in_brush: true
  - entity: sensor.sony_kd_75xf9005_naim_audio_av_energy_power_1
    yaxis_id: first
    color: green
    show:
      in_chart: true
      in_brush: true
yaxis:
  - id: first
    show: true
    max: ~5
  - id: second
    opposite: true
    show: true
    decimals: 2
    min: 0
    max: 100
apex_config:
  legend:
    show: false
experimental:
  brush: true
brush:
  selection_span: 24.0h
```

Correct scaling after removing y_axis assignment
```yaml
type: custom:apexcharts-card
series:
  - entity: sensor.sony_kd_75xf9005_naim_audio_av_energy_power_0
    color: orange
    show:
      in_chart: true
      in_brush: true
  - entity: sensor.sony_kd_75xf9005_naim_audio_av_energy_power_1
    color: green
    show:
      in_chart: true
      in_brush: true
apex_config:
  legend:
    show: false
experimental:
  brush: true
brush:
  selection_span: 24.0h
```

**Screenshots**
<img width="377" alt="image" src="https://github.com/RomRider/apexcharts-card/assets/57034871/8e1ef2bf-0666-415e-8aa5-a6adf5c5ecb9">

**Expected behavior**
All entities should be displayed in relation to the scale of the y_axis.

**Desktop (please complete the following information):**
Google Chrome Version 117.0.5938.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
