### ISSUE TITLE
 float_precision not working

### ISSUE THREAD

**Issue by Zarox666** [RomRider/apexcharts-card#607]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
When a series is configured with for example `float_precision: 1` it does not show a decimal value when the value is i.e. 24
Same applies to any number of decimals.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used (simplified):
```yaml
          - type: custom:apexcharts-card
            series:
              - entity: sensor.sensor_wohnzimmer_temperature
                name: Wohnz. Temp.
                yaxis_id: Celsius
                float_precision: 1
                color: orange
                show:
                  extremas: true
                group_by:
                  func: avg
                  duration: 600sec
            all_series_config:
              stroke_width: 1
              show:
                legend_value: false
            graph_span: 24h
            hours_12: false
            locale: de
            update_interval: 30sec
            header:
              show: true
              show_states: true
            show:
              last_updated: true
            yaxis:
              - id: Celsius
                opposite: false
                decimals: 0
                apex_config:
                  forceNiceScale: true
```

**Screenshots**

**Expected behavior**
Configuring a Series to show 1 or <n> decimal position should result in exactly that.
Having 0 decimal positions for some values while usually having <n> decimal positions just makes no sense and distorts the way data is displayed.

**Desktop (please complete the following information):**
MS Edge Version 117.0.2045.36 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Galaxy S21+ 5G
 - OS: Android V13
 - Browser: Home Assistant companion App
 - Version 2023.9.2-full

**Additional context**
