### ISSUE TITLE
Sidebar Layout w/ Brush causes chart to overflow and be cut off

### ISSUE THREAD

**Issue by Thecat8413** [RomRider/apexcharts-card#609]
**Checklist**
- [Y] I updated the card to the latest version available
- [Y] I cleared the cache of my browser
- [Y] I verified that I'm really running the lastest version in my browser console
- [Y] I checked if there is another issue opened with the same problem

**Describe the bug**
When using the brush, if the dashboard layout is set to sidebar, and the chart is in the large section, the chart overflows, but the card boundary is maintained, so the overflowing section is just not rendered. Bug only effects desktop, mobile works correctly. 

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:

Faulty Card (with brush):
```
 type: custom:apexcharts-card
experimental:
  color_threshold: true
  brush: true
header:
  show: true
  title: Tempature
  show_states: true
  colorize_states: true
brush:
  selection_span: 2h
series:
  - entity: sensor.temperature_sensor
    name: Server Room
    show:
      in_brush: true
  - entity: sensor.temperature_sensor_2
    name: Foyer
    show:
      in_brush: true
  - entity: sensor.my_ecobee_temperature
    name: Kitchen
    show:
      in_brush: true
  - entity: sensor.temperature_sensor_4
    name: Bed Room
    show:
      in_brush: true
view_layout:
  position: sidebar
```

This card works as expected (no brush):
```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: Tempature
  show_states: true
  colorize_states: true
brush:
  selection_span: 2h
series:
  - entity: sensor.temperature_sensor
    name: Server Room
  - entity: sensor.temperature_sensor_2
    name: Foyer
  - entity: sensor.my_ecobee_temperature
    name: Kitchen
  - entity: sensor.temperature_sensor_4
    name: Bed Room
view_layout:
  position: main
```

**Screenshots**
Brush in Sidebar:
![image](https://github.com/RomRider/apexcharts-card/assets/47541088/b466d3ec-2d84-4946-9aed-3626b9229217)
Brush in Main panel:
![image](https://github.com/RomRider/apexcharts-card/assets/47541088/b1ae6417-5f2e-4f95-8b37-94e829db0f8d)
No brush in Sidebar:
![image](https://github.com/RomRider/apexcharts-card/assets/47541088/7ebc4e9c-7549-4122-b2ff-a22886c81516)
No brush in Main panel:
![image](https://github.com/RomRider/apexcharts-card/assets/47541088/a88f4bf1-9dbb-492e-b185-4442f313524e)

**Expected behavior**
Card should maintain the same rendering behavior as the non-brush version

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: Version 117.0.5938.92 (Official Build) (32-bit emulated) (running on SQ2, but confirmed bug is present on mac/safari as well)
