### ISSUE TITLE
Weird hover behaviour with empty tooltip

### ISSUE THREAD

**Issue by JRascagneres** [RomRider/apexcharts-card#618]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**

**Version of the card**
Version: 2.0.4

**To Reproduce**
Note this uses my National Grid integration. This can be added without an api_key from my repo if you want to fully repro it. Probably not neccessary though.
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: 70 Hour Wind Generation
  show_states: true
  colorize_states: true
graph_span: 70h
now:
  show: true
  color: red
  label: now
span:
  start: day
series:
  - entity: sensor.national_grid_grid_generation_national_wind_mwh
    name: National Generation
    color: cyan
    opacity: 0.8
    stroke_width: 2
    type: line
    extend_to: false
    group_by:
      func: first
      duration: 1h
    show:
      legend_value: false
      in_header: raw
  - entity: sensor.national_grid_wind_forecast
    color: green
    opacity: 0.8
    name: Latest Forecast
    data_generator: |
      var now = new Date().getTime();
      var forecastData = entity.attributes.forecast.filter(entry => {
        var startTime = new Date(entry.start_time).getTime();
        if (startTime > (now - 60*60000)){
          return true
        }
        return true
      });

      return forecastData.map(entry => {
        return [entry.start_time, entry.generation] 
      });
    type: column
    show:
      legend_value: false
      in_header: raw
  - entity: sensor.national_grid_wind_forecast_earliest
    color: red
    opacity: 0.8
    stroke_width: 2
    name: Earliest Forecast
    data_generator: |
      var now = new Date().getTime();
      var forecastData = entity.attributes.forecast.filter(entry => {
        var startTime = new Date(entry.start_time).getTime();
        if (startTime > (now - 60*60000)){
          return true
        }
        return true
      });

      return forecastData.map(entry => {
        return [entry.start_time, entry.generation] 
      });
    type: line
    show:
      legend_value: false
      in_header: raw
yaxis:
  - min: 0
    max: ~20000

```

**Screenshots**
Can see this 'random' extra item with the date / time at the bottom. I suspect its because the cyan line has results every minute whereas the others have results every hour but thought the avg might've solved that.
![image](https://github.com/RomRider/apexcharts-card/assets/3264971/d977aff9-38df-4157-9070-ac4f559577f1)

Additonally if I hover at the end of the graph at the zero mark it pops up with the cyan line:
![image](https://github.com/RomRider/apexcharts-card/assets/3264971/553ba052-00e1-4443-a50a-311aee9825a1)

I assume its an issue with extend_to

**Expected behavior**
Expect the additional date / time point to not be shown

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 117.0.5938.132
