### ISSUE TITLE
date error in timeline

### ISSUE THREAD

**Issue by peca2345** [RomRider/apexcharts-card#619]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
for a longer period of time, one date is displayed that does not belong to the numeric series

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 140px
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        day: dd.MM
    tickPlacement: 'on'
graph_span: 40d
span:
  end: day
header:
  show: true
  show_states: true
  colorize_states: true
  title: Koupeno
yaxis:
  - min: 0
    max: ~11
    decimals: 0
    apex_config:
      tickAmount: 5
series:
  - entity: sensor.daily_import_gw002_price_apexcharts
    type: column
    name: ' '
    color: orange
    show:
      header_color_threshold: true
      extremas: true
    group_by:
      func: last
      duration: 1d
```

**Screenshots**
![obrazek](https://github.com/RomRider/apexcharts-card/assets/58307338/8c26eaaf-1771-4a18-8734-76ccce3faa9a)

**Expected behavior**
in the timeline should go one day at a time from the lowest to the highest

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [pc,phone]
 - OS: [win10,android]
 - Browser [firefox,chrome]
 - Version []

**Additional context**
when displaying a longer timeline, there is one entry that does not belong to the timeline
