### ISSUE TITLE
Incorrect column width when only one day of data of a whole week

### ISSUE THREAD

**Issue by wawyed** [RomRider/apexcharts-card#621]
**Describe the bug**
Incorrect width of columns when there's only one column

**Version of the card**
Version: Latest

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
cache: false
header:
  show: true
  title: Generation this week
  show_states: true
  colorize_states: true
series:
  - entity: sensor.solis_inverter_power_generation_today
    name: Generation today
    offset: '-1hour'
    group_by:
      func: last
      duration: 1d
  - entity: sensor.smart_meter_electricity_import
    name: Import today
    offset: +1hour
    group_by:
      func: diff
      duration: 1d
  - entity: sensor.smart_meter_electricity_export
    name: Export today
    group_by:
      func: diff
      duration: 1d
      start_with_last: false
  - entity: sensor.solis_inverter_house_load_today
    name: Consumption today
    offset: '-1hour'
    group_by:
      func: last
      duration: 1d
graph_span: 7d
span:
  start: isoWeek
stacked: false
all_series_config:
  type: column
  extend_to: false
  show:
    datalabels: false
    legend_value: false
apex_config:
  legend:
    formatter: |
      EVAL:function(label, opts) {
        return `${label.split(' ').slice(0, -1)} ${opts.w.globals.series[opts.seriesIndex].reduce((a, b) => {return a + b}, 0).toFixed(1)} kWh`;
      }

```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/4390806/157ce8da-f1be-4353-b150-dfd312d0db1e)

I'd expect something like this but with one day of columns:

![image](https://github.com/RomRider/apexcharts-card/assets/4390806/52f0f086-6963-4732-8104-23a01f07d244)

**Expected behavior**
It should calculate the column width correctly
