### ISSUE TITLE
Low performance showing info for more than 3 days

### ISSUE THREAD

**Issue by L0bit0** [RomRider/apexcharts-card#623]
Hi

Actually not sure if it is a bug or the expected behavior. Basically I am tring to add some power consume graphs and as soon i show more than 2 or 3 days performance of the card goes too slow. I can not even edit on most of the cases. 

I am not having this performance issue showing same data (entity and days) with standard history card and a mini-graph-card

I tried to group by hour, but i have same result

I am on the last version of HA and card...

this is an example of my yaml
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 300px
header:
  show: true
  title: Frigorifico Trastero (3d)
  show_states: false
  colorize_states: false
graph_span: 3d
chart_type: line
series:
  - entity: sensor.frigorifico_trastero_avg_dia
    name: Avg 24h
    stroke_width: 2
    color: '#FF4F00'
```

 is this normal? 

Thanks in advance
