### ISSUE TITLE
wrong y-max calculation in stacked area chart

### ISSUE THREAD

**Issue by moedi21** [RomRider/apexcharts-card#624]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I use a stacked area chart to display the energy consumption in my home. The scaling of the y-axis is incorrect, leading to clipping of the graph.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Verbrauch (wie App)
  show_states: false
  colorize_states: true
stacked: true
graph_span: 24h
span:
  start: day
yaxis:
  - decimals: 0
    min: 0
    apex_config:
      forceNiceScale: true
all_series_config:
  type: area
  stroke_width: 1
  extend_to: now
  statistics:
    period: 5minute
  show:
    legend_value: true
series:
  - entity: sensor.consumption_from_pv
    name: aus PV
  - entity: sensor.consumption_from_battery
    name: aus Speicher
  - entity: sensor.consumption_from_grid
    name: aus Netz
```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/97403595/12ad831e-1f9f-4863-8a60-db8bee28d895)

**Expected behavior**
y-max should be chosen based on the sum of all values which are stacked. In this case, the sum of all values would be 4228, so cutting the axis at 4000 is definitely wrong.

**Desktop (please complete the following information):**
 - Browser Brave 
 - Version V1.60.110 Chromium 119.0.6045.105

**Smartphone (please complete the following information):**
 - Device: Samsung A33
 - OS: Android 13

**Additional context**
