### ISSUE TITLE
[Bug] tap_action for header_actions with floating header broken

### ISSUE THREAD

**Issue by guevara777** [RomRider/apexcharts-card#625]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
If i use the card with the following yaml-code the tap_action for the states in the header is broken. The tap_action is working again if i set "floating" == "false" in header options.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
layout: minimal
header:
  show: true
  show_states: true
  colorize_states: true
  floating: true
all_series_config:
  stroke_width: 2
  float_precision: 1
  show:
    in_header: raw
    legend_value: false
  type: area
  opacity: 0.2
  statistics:
    type: mean
    period: 5minute
span:
  end: minute
graph_span: 24h
apex_config:
  chart:
    height: 200px
  legend:
    show: false
  tooltip:
    items:
      display: flex
series:
  - entity: sensor.eg_temperatur
    stroke_width: 1
    color: red
    type: area
    opacity: 0.2
    header_actions:
      tap_action:
        action: more-info
```

**Screenshots**
- https://github.com/RomRider/apexcharts-card/assets/29648553/37993f63-7908-4957-ace4-f0a6262b2ca9

**Expected behavior**
- https://github.com/RomRider/apexcharts-card/assets/29648553/3455dc56-1b05-4b3d-8044-1a1ac9b9fba9
The tap_action should behave like the tap_action if floating is set to "false"

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 118.0.5993.120
 
**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14
 - Browser: Chrome
 - Version: 118.0.5993.112

**Additional context**
-
