### ISSUE TITLE
Question/Bug label

### ISSUE THREAD

**Issue by 03397** [RomRider/apexcharts-card#626]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the latest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Is there a way when I hover the mouse over the graph to make the date in the black backround not to be shown, since at the edges it is cropped?

```
type: custom:apexcharts-card
header:
  show: true
  title: Outdoor Temperature
  show_states: true
  colorize_states: true
series:
  - entity: sensor.outside_temperature
    stroke_width: 2
    show:
      in_header: true
      name_in_header: false
```

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/6150853/01e4ec48-4b14-4fc4-9b8e-940de0437082)

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 03397** [comment]
An answer on this will be much appreciated

**Comment by 03397** [comment]
Is this fork still supported or not?

**Comment by 03397** [comment]
Anyone?

**Comment by RomRider** [comment]
You can disable the tooltip with
```yaml
apex_config:
  xaxis:
    tooltip:
       enabled: false
```
