### ISSUE TITLE
hovering popup disapear on graph refresh

### ISSUE THREAD

**Issue by michalk-k** [RomRider/apexcharts-card#63]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
When hovering cursor over graph, values valid for point under cursor are displayed in popup.
However when card refreshes the data (manifested by reload indicator), the popup disappears.

See animation in screenshot section

**Version of the card**
Version: 1.5.0

**To Reproduce**
This is the configuration I used:
```
type: 'custom:apexcharts-card'
graph_span: 1h
span:
  end: minute
apex_config:
  stroke:
    width: 2
series:
  - entity: sensor.isp1_ping
    name: google (max)
    curve: smooth
    type: line
    color: 'rgb(200, 60, 60)'
    group_by:
      duration: 1m
      func: max
  - entity: sensor.isp1_ping
    name: google (avg)
    curve: smooth
    type: area
    color: 'rgb(255, 160, 160)'
    group_by:
      duration: 1m
      func: avg
  - entity: sensor.isp2_ping
    name: 39-1 (max)
    curve: smooth
    type: line
    color: 'rgb(60, 60, 150)'
    group_by:
      duration: 1m
      func: max
  - entity: sensor.isp2_ping
    name: 39-1 (avg)
    curve: smooth
    type: area
    color: 'rgb(160, 160, 250)'
    group_by:
      duration: 1m
      func: avg
  - entity: sensor.isp3_ping
    group_by:
      duration: 1m
      func: max
    name: 192.168.100.1
```

**Screenshots**
![graph3](https://user-images.githubusercontent.com/7868445/107156099-92854200-697c-11eb-9cce-e36d9ad94596.gif)

**Expected behavior**
The popup should remain until mouse cursor is moved out from the graph. Graph data refresh shouldn't affect it's appearance

**Desktop (please complete the following information):**
 - Firefox
 - 85.0.1

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
N/A
