### ISSUE TITLE
Chart series out of sync

### ISSUE THREAD

**Issue by GGSSDD** [RomRider/apexcharts-card#635]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I'm trying to build an area chart that displays the value of 3 temperature sensors in a serie but i must be doing something wrong cause it's behaving erratic. I want their values to be shared in the tooltip, but it doesn't happen because of the way of each serie is rendered. When the card updates, at a specified interval or by an entity's change in state, it doesn't matter how, the render gets messed up, and i have to wait until the series get aligned again on the x axis, to have their values shared in the tooltip once again.

Also in editor mode it's displayed as it should, always.

PS. The chart's inside a custom: stack-in-card, but I'm pretty sure that's not the issue, because i took it out and it behaves the same.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
card_mod:
  style: |
    ha-card {
      background: none !important;
    }
    #header__title {
      font-size: 12px !important;
      font-weight: regular !important;
      margin-bottom: -20px !important;
      color: rgb(160, 160, 160) !important;
    }
header:
  show: true
  title: Temperature [°C]
graph_span: 30min
update_interval: 5sec
chart_type: line
cache: true
apex_config:
  yaxis:
    labels:
      style:
        colors: rgb(230, 230, 230)
  xaxis:
    tooltip:
      enabled: false
    labels:
      style:
        colors: rgb(160, 160, 160)
    axisBorder:
      height: 1
      color: rgb(230, 230, 230)
    axisTicks:
      color: rgb(230, 230, 230)
  stroke:
    show: true
    width: 1.5
    curve: straight
  chart:
    type: area
  fill:
    type: gradient
    gradient:
      shadeIntensity: 0.5
      opacityFrom: 0.45
      opacityTo: 0.25
      inverseColors: false
      stops:
        - 0
        - 90
        - 100
  grid:
    borderColor: rgb(169, 160, 160)
    strokeDashArray: 3
    xaxis:
      lines:
        show: true
all_series_config:
  fill_raw: 'null'
  group_by:
    func: last
    duration: 5sec
series:
  - entity: sensor.cr_10s_extruder_temperature
    name: Extruder
    color: rgb(255, 51, 51)
    show:
      legend_value: false
  - entity: sensor.cr_10s_bed_temperature
    name: Heater bed
    color: rgb(51, 153, 255)
    show:
      legend_value: false
  - entity: sensor.cr_10s_rpi
    name: Rpi
    color: rgb(255, 51, 255)
    show:
      legend_value: false

```

**Screenshots**
![286359361-e624bceb-8e0d-466f-aa4a-7441b0823892](https://github.com/RomRider/apexcharts-card/assets/121240474/13657f14-871f-420b-840b-fe513b0b2276)
![Untitled-1](https://github.com/RomRider/apexcharts-card/assets/121240474/a6267516-aa05-4e4a-9f5f-44c2db1c2164)

**Expected behavior**
Would expect all the series to be rendered properly all the way throughout the graph, from one margin to another of the x axis.
