### ISSUE TITLE
"min:" and "max:" in apex_config are not working as expected?

### ISSUE THREAD

**Issue by redlefloh** [RomRider/apexcharts-card#642]
**Checklist**
- [ X] I updated the card to the latest version available
- [ X] I cleared the cache of my browser
- [ X] I verified that I'm really running the lastest version in my browser console
- [ X] I checked if there is another issue opened with the same problem

**Describe the bug**
"min:" and "max:" in apex_config are not working as expected. If I specify a "min:" or a "max:", I shortly see the correct chart representation drawing while the chart is loading, but then it falls back to the settings that one would expect in "auto" mode?

**Version of the card**
Version: Running 2.0.4 via HACS

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Tibber Electricity Price / SOC
  show_states: true
  colorize_states: true
yaxis:
  - id: price
    apex_config:
      min: 0
      max: 0.2
      forceNiceScale: true
      decimalsInFloat: 2
      labels:
        show: true
series:
  - entity: sensor.electricity_price
    name: ‘ ’ 
    stroke_width: 3
    float_precision: 3
    color: cornflowerblue
    yaxis_id: price
    curve: straight
```

**Screenshots**
The default yaxis max value i=s 0.15, if I enter a value for max ...
<img width="993" alt="apex_config 1" src="https://github.com/RomRider/apexcharts-card/assets/24863182/0e880e85-87c3-4739-928e-804075dfa0a3">

... for example 0.2, you very briefly see the correct yaxis drawing while the chart is loading:
<img width="987" alt="apex_config 2" src="https://github.com/RomRider/apexcharts-card/assets/24863182/cd372550-752d-4fa5-9984-068fdcd101d8">

but then it falls back again to max 0.15. 
<img width="997" alt="apex_config 3" src="https://github.com/RomRider/apexcharts-card/assets/24863182/611c6c7e-a7a2-4108-b197-7f10aed5c87c">

Same again when I change max to 0.3, you very briefly see the correct yaxis drawing at 0.3 while loading:
<img width="992" alt="apex_config 4" src="https://github.com/RomRider/apexcharts-card/assets/24863182/7f1380a7-eb71-4dd8-8e5e-f975988895db">

and then it falls back again to max 0.15.
<img width="994" alt="apex_config 5" src="https://github.com/RomRider/apexcharts-card/assets/24863182/f6204554-6f12-4818-9203-6cf665450278">

**Expected behavior**
The yaxis always shows what I specify in "min:" and "max:" 

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version:120.0.6099.129 (Official Build) (x86_64) 

Note: in 2020 there was a bug in apexcharts.js that caused a similar behaviour: https://github.com/apexcharts/apexcharts.js/issues/1578. Not sure if this here is somehow related? Can anyone replicate this behaviour?
