### ISSUE TITLE
Missing space between value and unit in header

### ISSUE THREAD

**Issue by bigboban** [RomRider/apexcharts-card#645]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
There is missing space between number value and unit in header. See pic. 

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml

type: custom:apexcharts-card
header:
  show: true
  title: ''
  show_states: true
  colorize_states: true
series:
  - entity: sensor.senseair_co2_value
    show:
      legend_value: false
    stroke_width: 2
  - entity: sensor.netatmo_bobo_netatmo_indoor_co2
    stroke_width: 2
    show:
      legend_value: false


```

**Screenshots**

![image](https://github.com/RomRider/apexcharts-card/assets/7159224/19819087-eede-48ec-93ff-d4a0cd15d24e)

**Expected behavior**
I expect space between number and unit.

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Version 120.0.6099.130
