### ISSUE TITLE
`Markers: colors:` value breaks cards when number of entity increases

### ISSUE THREAD

**Issue by AleXSR700** [RomRider/apexcharts-card#646]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
When the number of displayed entities increases above a certain number, the setting
```
markers:
  colors: xxx
```
can lead to an empty chart, depending on what is selected as color.

In my tests, the value `colors: "####"` works for around 4-5 entities. Afterwards, `colors: rgba(0,0,0,0)` works for around 10 entities. After that, only deleting the entire `colors` option seemed to work.
Note, that stating the color as `rgb(0,0,0)` did not work. It had to be as rgba.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:

Note, that I repeated the humidity filter simply to create many entities fast and allow anybody to reproduce the problem with any kind of entity they have e.g. 10+ sensors of (usually temperature or humidity or similar).
```yaml
type: custom:auto-entities
filter:
  include:
    - entity_id: '*humidity*'
      options:
        show:
          in_brush: true
    - entity_id: '*humidity*'
      options:
        show:
          in_brush: true          
  exclude: []
card:
  type: custom:apexcharts-card
  header:
    show: true
    title: ApexCharts-Card
    show_states: true
    colorize_states: true
  experimental:
    brush: true
  brush:
    selection_span: 60min
  apex_config:
    markers:
      size: MARKER_SIZE
      strokeWidth: 1
      fillOpacity: 1
      colors: rgba(0,0,0,1)
```

**Screenshots**
As can be seen, the brush is always populated, i.e. data is available. Graph shows all data if `colors` parameter is deleted.
<img width="765" alt="image" src="https://github.com/RomRider/apexcharts-card/assets/57034871/5100f403-5b48-421b-840c-8779c720069c">

**Expected behavior**
Marker color should always work, no matter which value you specify and whether you use hex, rgb or plain html color name.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 120.0.6099.130 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
