### ISSUE TITLE
Extremas value and extremas box draw on differnt positions

### ISSUE THREAD

**Issue by SteffenM-DE** [RomRider/apexcharts-card#647]
**Describe the bug**
The value of the extrams and the boxes (underneath background for the extreams) not drawed on same position (the extrame value is drawed black on the line points but the underneath blue box is on the left)?

![image](https://github.com/RomRider/apexcharts-card/assets/10560225/09828eae-ecf5-4505-8752-89ba686bec17)

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
- type: custom:apexcharts-card
        update_interval: 1h
        cache: true
        graph_span: 8d1s
        span:
          end: day
        header:
          show: false
          show_states: true
          colorize_states: true
        show:
          loading: true
          last_updated: false
        apex_config:
          tooltip:
            enabled: false
          grid:
            show: false
          legend:
            show: false
          chart:
            type: bar
            stacked: true
            height: 280
            offsetY: -10
            offsetX: 10
            width: 95%
          plotOptions:
            bar:
              borderRadius: 5
              dataLabels:
                position: center
          dataLabels:
            enabled: true
            offsetY: 0
            style:
              fontSize: 10px
              fontWeight: lighter
              colors:
                - '#1f1f1f'
          xaxis:
            show: false
            border: false
            forceNiceScale: true
            labels:
              show: true
              format: ddd.
              style:
                fontSize: 12px
                fontWeight: lighter
                colors: '#9B9B9B'
          yaxis:
            show: false
            border: false
            forceNiceScale: true
        all_series_config:
          curve: smooth
          float_precision: 0
          fill_raw: last
          opacity: 0.75
        series:
          - entity: sensor.hst_heizzeit_bad_protag
            name: Bad
            type: column
            group_by:
              func: max
              duration: 1day
            color: '#a8e6cf'
            stroke_width: 2
            show:
              datalabels: true
          - entity: sensor.hst_heizzeit_wohnen_protag
            name: Wohnen
            type: column
            group_by:
              func: max
              duration: 1day
            color: '#ffd3b6'
            stroke_width: 2
            show:
              datalabels: true
          - entity: sensor.hst_heizzeit_keller_protag
            name: Keller
            type: column
            group_by:
              func: max
              duration: 1day
            color: '#ff8b94'
            stroke_width: 2
            show:
              datalabels: true
          - entity: sensor.mmx_hausoutdoor_temp_mean
            name: Außentemperatur
            type: line
            color: '#b6e2ff '
            stroke_width: 5
            group_by:
              func: avg
              duration: 1day
            show:
              datalabels: false
              extremas: true
```

**Screenshots**

**Expected behavior**
The extremas background boxes should on the position of the value.

**Desktop (please complete the following information):**
 - Browser chrome, vivaldi
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - OS: iOS17.2.1
