### ISSUE TITLE
Double Numbers on Y-Axis when min to max range is little

### ISSUE THREAD

**Issue by qryhub** [RomRider/apexcharts-card#649]
**Checklist**
- [ x ] I updated the card to the latest version available
- [ x ] I cleared the cache of my browser
- [ x ] I verified that I'm really running the lastest version in my browser console
- [ x ] I checked if there is another issue opened with the same problem

**Describe the bug**
When using a min and max on a yaxis on the card with a small range, some numbers appear twice.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 5h
yaxis:
  - id: MinecraftSpielerOnlineAchse
    max: 6
    decimals: 0
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
now:
  show: true
  label: Jetzt
series:
  - entity: sensor.cornerdogs_spieler_online
    curve: stepline
```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/37242302/c96aa54d-5d8a-4e61-8af6-507c9c18cf40)

**Expected behavior**
A Y-Axis Scale with range from 1-6 [0,1,2,3,4,5,6] and NOT [0,1,1,2,2,3,4,4,5,5,6]

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 120.0.6099.131

**Smartphone (please complete the following information):**
- not tested

**Additional context**
-
