### ISSUE TITLE
Problem with 'offset: -1month' plot, incorrect chart x-axis origin v1.5.0

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#65]
I'm not sure if this a February related issue or what, trying to chart current day starting at midnight, -1 month starting at midnight, -2 months starting at midnight.

In the attached picture, the graph for -1 month is appears to be using the time the chart was executed as the x-axis origin, the current day and -2 months charts appear to correctly start x-axis at midnight.

1st picture: problem as generated by yaml below
2nd picture: correct plot for -1 month data in matplotlib
3rd picture: chrome javascript console

attached zip file, full data set for 3 months, more than you need ;-)

Thanks for your help and great work!

```
# test 13
title: T13 Multiple Bar History
panel: true
cards:
- type: vertical-stack
  cards:



  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.backyard_atc_mi_temperature
      color: blue
      # offset: -1month
      type: line
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
    cache: true
    apex_config:
      chart:
        height: 400
      title:
        text: 'Backyard Temperature Current'

  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.backyard_atc_mi_temperature
      color: blue
      offset: -1month
      type: line
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
    cache: true
    apex_config:
      chart:
        height: 400
      title:
        text: 'Backyard Temperature -1month'

  - type: custom:apexcharts-card
    header:
      show: false
    series: 
    - entity: sensor.backyard_atc_mi_temperature
      color: blue
      offset: -2month
      type: line
    update_interval: 5m
    graph_span: 24h
    span:
      start: day
    cache: true
    apex_config:
      chart:
        height: 400
      title:
        text: 'Backyard Temperature -2month'

```

apexcharts version:

```
user@ubuntu-macmini2012:~/homeassistant/www/custom-lovelace/apexcharts$ grep -o -P '.{0,20}1\.5\..{0,20}' apexcharts-card.js
-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5V11h1V5.5c
-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5z"/>\n</sv
ate,i.card_version="1.5.0",0!==i.data.length
hSpan,card_version:"1.5.0",last_fetched:new
pan:0,card_version:"1.5.0",last_fetched:new
APEXCHARTS-CARD %c v1.5.0 ","color: orange;
th("-raw")?t:ae(t);"1.5.0"!==i.card_version&
```

<img width="1498" alt="minus-one-problem-00" src="https://user-images.githubusercontent.com/1409547/107160573-f8a5a100-694b-11eb-838e-54c24303db24.png">

<img width="815" alt="minus-one-problem-02" src="https://user-images.githubusercontent.com/1409547/107160582-0824ea00-694c-11eb-9319-59948abc73a6.png">

<img width="1508" alt="minus-one-problem-01" src="https://user-images.githubusercontent.com/1409547/107160593-1115bb80-694c-11eb-91f3-5884ac5595a3.png">

[atc-mi-backyard.csv.zip](https://github.com/RomRider/apexcharts-card/files/5940101/atc-mi-backyard.csv.zip)
