### ISSUE TITLE
group_by historical values are volatile/fluctuate (show different historical values - affected by time the chart is rendered)

### ISSUE THREAD

**Issue by d123456temp** [RomRider/apexcharts-card#652]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
Depending on the time (during the day) when I run/display the chart card, the historical chart entries are different. See the attached screenshot of the same bar chart top left of the screenshot - every time the values shown are different. What I noticed is that the popup shows date and time and the time part equals to the time of the rendering. Yes, I'm sure the data are not altered, the only thing that fluctuate is the rendered bar chart.

See chart definition below.

**Version of the card**
Version: latest release

**To Reproduce**
This is the configuration I used:
```yaml
- type: custom:apexcharts-card
        graph_span: 10d
        update_interval: 1d
        header:
          show: true
          title: Person count
        series:
          - entity: sensor.zoom_person_count
            type: column
            name: zoom
            group_by:
              func: sum
              duration: 1day
          - entity: sensor.second_person_count
            type: column
            name: fixed
            group_by:
              func: sum
              duration: 1day
```

**Screenshots**
![charts_20240111_133601](https://github.com/RomRider/apexcharts-card/assets/20557315/d73e3355-5881-49d6-9f91-1c2b5d49c64a)
![chart_20240111_215619](https://github.com/RomRider/apexcharts-card/assets/20557315/bb78477e-c774-4789-a56e-3b5f3927c2ff)
![2024-01-10](https://github.com/RomRider/apexcharts-card/assets/20557315/a8e452d4-8327-4b58-9db5-d2ea4aaa3bfe)

**Expected behavior**
Historical data presentation should be stable and exactly the same no matter when chart is rendered.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 120.0
