### ISSUE TITLE
Grid lines for x-axis don't work

### ISSUE THREAD

**Issue by OZ1SEJ** [RomRider/apexcharts-card#654]
**Checklist**
- [✅] I updated the card to the latest version available
- [✅] I cleared the cache of my browser
- [❌] I verified that I'm really running the lastest version in my browser console (how?)
- [✅] I checked if there is another issue opened with the same problem (doesn't seem like it.)

**Describe the bug**
It is not possible to get vertical grid lines.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Batteriniveau seneste 48 timer
  show_states: false
  colorize_states: false
series:
  - entity: sensor.vw_id_3_battery_level
    unit: '%'
apex_config:
  legend:
    show: false
  grid:
    show: true
    strokeDashArray: 0
    borderColor: rgb(80,80,80)
  yaxis:
    min: 0
    max: 100
    tickAmount: 5
  xaxis:
    tickAmount: 4
    lines:
      show: true
graph_span: 48h

```

**Screenshots**

![billede](https://github.com/RomRider/apexcharts-card/assets/2393164/9224d343-c032-49ee-8596-92fe4fc65430)

**Expected behavior**
I expected there to be vertical grid lines.

**Desktop (please complete the following information):**
 - Only tested in Firefox
 - 121.0 on Ubuntu

**Smartphone (please complete the following information):**

**Additional context**
There seems to be a similar, known issue in Apex Charts v3.36.x, which seems to have been fixed i v3.37:
[ Grid lines for x-axis don't work after update from 3.35.0 to 3.36.3 #3580](https://github.com/apexcharts/apexcharts.js/issues/3580)
