### ISSUE TITLE
Brush [experimental]: yaxis max is not working

### ISSUE THREAD

**Issue by typxxi** [RomRider/apexcharts-card#656]
I have a graph with a spike of 350W and I use the the brush version above the usual graphic so that I can recognice any differences easily.

Even though both have the same limitations for the yaxis the results are quite different and after investigating that it seems to be that the yaxis max of 350 is simply ignored no matter what I do with these parameters in the experimental version while the usual one is behaving like described in the documentation. 

But WHY ? 

latest apex charts card installed yesterday = 23rd of january 2024

yaml
```
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
          brush: true
        graph_span: 48h
        brush:
          selection_span: 4 h
          apex_config: null
        all_series_config:
          stroke_width: 1
        header:
          show: true
          title: 4 h LUPE AUF 48 h (graue Box schieben / vergrößern)
          show_states: true
          colorize_states: true
        apex_config:
          grid:
            show: true
            borderColor: '#E0E0E0'
          chart:
            height: 250px
          tooltip:
            enabled: true
            followCursor: false
            x:
              show: false
            fixed:
              enabled: true
        yaxis:
          - min: 0
            max: 350
            decimals: 0
            apex_config:
              tickAmount: 5
        series:
          - entity: sensor.sonoff_1000471cf4_power
            name: BRENNER LEISTUNG
            color: red
            stroke_width: 3
          - entity: sensor.sonoff_1000471cf4_power
            color: darkred
            stroke_width: 1
            float_precision: 0
            show:
              in_brush: true
              in_chart: false
      - type: custom:apexcharts-card
        experimental:
          color_threshold: true
          brush: true
        graph_span: 24h
        brush:
          selection_span: 60m
          apex_config: null
        all_series_config:
          stroke_width: 1
        header:
          show: true
          title: BRENNERLEISTUNG DER LETZTEN 18 h
          show_states: true
          colorize_states: true
        apex_config:
          grid:
            show: true
            borderColor: '#E0E0E0'
          chart:
            height: 250px
          tooltip:
            enabled: true
            followCursor: false
            x:
              show: false
            fixed:
              enabled: true
        yaxis:
          - min: 0
            max: 350
            decimals: 0
            apex_config:
              tickAmount: 5
        series:
          - entity: sensor.sonoff_1000471cf4_power
            name: BRENNER LEISTUNG
            color: red
            stroke_width: 1
    title: 'BRENNER: LAUFZEITEN & LEISTUNG'
```
```yaml

```

Screenshot with the experimental brush graphic on top of the usual one but with different yaxis results
![image](https://github.com/RomRider/apexcharts-card/assets/20662430/d8a211f8-f434-40d0-bc2b-18bc6e496fe4)

**Expected behavior**
should work a the usual one regarding y axis

**Desktop (please complete the following information):**
 - WINDOWS & CHROME latest 120.0.6099.225 

Just a reminder that something is not working properly in the experimental part but I have to say that I love this brush experimental feature. Yes, I know it is experimental and I could live with that, but just wanna let you know.

And I would love to see an option for that to move the grey box of 1h or so to a certain position on the x axis where it is now fixed to the right edge which I can understand cause the most recend data are there. But for some use cases where during night nothing is happening like solar power that right position is not optimal. I would suggest a position from 0 to 100 meaning 0 is left edge and 100 is on the right edge.

Just rather an idea than a feature request and that is why I only want to mention this as my thoughts in general about the brush experimental idea which I find really usefull in a lot of cases.

**Comment by typxxi** [comment]
It still would be nice to find a solution or workaround

**Comment by wiedsee** [comment]
same issue with it not listening to yaxis max or minimum in config

```
type: custom:apexcharts-card
experimental:
  brush: true
brush:
  selection_span: 30m
graph_span: 24h
apex_config:
  legend:
    show: false
yaxis:
  - id: temp
    decimals: 1
    min: 17
    max: auto
    apex_config:
      tickAmount: 8
  - id: gas
    opposite: true
    decimals: 2
    min: 0
    max: 0.04
    apex_config:
      tickAmount: 8
header:
  show: true
  title: Gas / Temperature
  show_states: true
  colorize_states: true
series:
  - entity: sensor.active_gas_usage
    color: rgb(255, 153, 0)
    curve: stepline
    yaxis_id: gas
    show:
      name_in_header: false
  - entity: sensor.thermostat_target
    color: rgb(255, 150, 150)
    curve: stepline
    yaxis_id: temp
    show:
      name_in_header: false
      in_brush: true
  - entity: sensor.tstat_27fc62_current_temperature
    color: rgb(255, 0, 0)
    curve: stepline
    yaxis_id: temp
    show:
      name_in_header: false
      in_brush: true
```

with brush enabled
![image](https://github.com/RomRider/apexcharts-card/assets/110336704/69e704e3-8a01-40a8-ab6b-29f6c89c590c)

expected
![image](https://github.com/RomRider/apexcharts-card/assets/110336704/3904af71-d099-468a-a5dd-61da7f415328)

**Comment by escoand** [comment]
The min/max of the brush overrides min/max of every other y-axis, so my workaround is to transform every value into the same range. But this "breaks" the second y-axis somehow. You're only able to see the amount of the data, not the real value.
```yaml
series:
  - entity: sensor.entity_1
    yaxis_id: y1
  - entity: sensor.entity_2
    yaxis_id: y2
    # transform the y-value into min/max of the brush => val / max_y2 * max_y1
    transform: return x/10000*0.5
yaxis:
  - id: y1
  - id: y2
    opposite: true
    apex_config:
      title:
        text: W
    show: false
brush:
  selection_span: 3d
  apex_config:
    yaxis:
      show: false
      # set a fixed scale, which is faulty used for every y-axis
      min: 0
      max: 0.5
```

In my case I can live with just seeing the amount of the second y-axis (blue area), but not have the real value.
![image](https://github.com/RomRider/apexcharts-card/assets/428567/0f5ba892-caf1-44ca-ad91-ec11cb85a428)
