### ISSUE TITLE
x-axis timezone seems to be wrong

### ISSUE THREAD

**Issue by saxn-paule** [RomRider/apexcharts-card#677]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console

**Describe the bug**
The x-axis values are shown with a wrong timezone (GMT+2). Should be the same timezone as the values are.
The values have the right timezone. (GMT+1)

**Version of the card**
Version: v2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
  standard_format: true
  title: Netzbezug
graph_span: 12h
update_interval: 60sec
all_series_config:
  stroke_width: 2
apex_config:
  legend:
    show: false
series:
  - entity: sensor.powerfox_meter_power
    name: Realverbrauch
    color: '#FC6F03'
  - entity: sensor.hoymiles_hms_xxxxw_t2_power
    name: Erzeugung
    color: '#00FF00'
```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/8352690/a50348f3-ffa6-4223-9248-a5df81b03113)

![image](https://github.com/RomRider/apexcharts-card/assets/8352690/61310068-dd2c-49ff-82ab-7ec76445225f)

**Expected behavior**
Timezone of axis and values should match.

**Desktop**
 - Browser Chrome
 - Version 122.0.6261.69 + 122.0.6261.112

![image](https://github.com/RomRider/apexcharts-card/assets/8352690/d4bb26aa-a714-4783-97a8-738fb32d9618)

**Smartphone**
 - Device: Huawei P20
 - OS: Android 9
 - Browser Chrome
 - Version 122.0.6261.91
