### ISSUE TITLE
Way to load additional locales

### ISSUE THREAD

**Issue by cadavre** [RomRider/apexcharts-card#68]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

No way to define custom locales for dashboards that are not in english.

**Describe the solution you'd like**

Way to import and load locales for Apexcharts.js.

**Describe alternatives you've considered**

Currently using everywhere custom labels that do no use "February" like strings. ;)

**Additional context**

None.

**Comment by RomRider** [comment]
Do you mean for all the timestamps displayed in the chart (tooltip and x-axis)?

Can you show me what you are doing right now also?

**Comment by cadavre** [comment]
This may be a tough one as it depends on external resources (.js from Apexcharts.js). :/

---

Take a look at this example (this is actually default of Apexcharts.js):
```
apex_config:
  xaxis:
     datetimeFormatter:
        year: 'yyyy'
        month: "MMM 'yy"
        day: 'dd MMM'
        hour: 'HH:mm'
```

`MMM` gives actually "Jan", "Feb", "Mar"...

For my (polish) dashboard I'd like better to see "Sty", "Lut", "Mar". For this I need to set:

```
apex_config:
  chart:
   locales: [pl]
   defaultLocale: 'pl'
```

But with "regular" Apex I'd need to import this locale via:

```js
var pl = require("apexcharts/dist/locales/pl.json")
```

So I can use it in `locales: []`.
