### ISSUE TITLE
Wrong color in header value when using header_color_threshold and radialBar

### ISSUE THREAD

**Issue by regystro** [RomRider/apexcharts-card#683]
**Describe the bug**
The header value is using gradient when `chart_type: radialBar`, and should use absolute color, to match the radialBar

**Version of the card**
Version: v2.0.4

**To Reproduce**
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  show_states: true
  colorize_states: true
chart_type: radialBar
series:
  - entity: sensor.memory_use_percent
all_series_config:
  show:
    header_color_threshold: true
  color_threshold:
    - value: 66
      color: green
    - value: 69
      color: red

```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/5755481/e7b58d0f-5be9-4123-9029-cffc43a90364)

**Expected behavior**
The header value 68.6% should be rendered green, with absolute threshold value color instead of the reddish coming from applying the linear gradient green -> red of the defined `color_threshold`

**Comment by brynyneuadd** [comment]
Yes, I've encountered the same bug - color thresholds don't appear to work with radialbar charts at the moment

**Comment by regystro** [comment]
Still an issue.

**Comment by RomRider** [comment]
If you want a "hard grandiant transitions", the way to do it is by repeating the entry:
```yaml
  color_threshold:
    - value: 66
      color: green
    - value: 69
      color: green
    - value: 69
      color: red
```

**Comment by regystro** [comment]
Workaround seems to work. Thanks, @RomRider

**Comment by bennysweb** [comment]
Workaround doesn't work for me. What am I doing wrong?

```
- entity: sensor.einspeisevergutung_jahr
    name: Aktuelles Jahr
    unit: ' €'
    float_precision: 2
    show:
      header_color_threshold: true
    min: 0
    max: 600
    color_threshold:
      - value: 0
        color: B71C1C
      - value: 25
        color: B71C1C
      - value: 25
        color: EF6C00
      - value: 75
        color: EF6C00
      - value: 75
        color: FBC02D
      - value: 300
        color: FBC02D
      - value: 300
        color: 7CB342
      - value: 500
        color: 7CB342
      - value: 500
        color: 4CAF50
      - value: 600
        color: 4CAF50        
header:
  show: true
  title: Einspeisevergütung
  show_states: true
  colorize_states: true
  standard_format: true
show:
  loading: false
apex_config:
  plotOptions:
    radialBar:
      offsetY: -20
      startAngle: -90
      endAngle: 90
      hollow:
        margin: 3,
        size: 40%
        background: transparent
      dataLabels:
        name:
          show: true
        value:
          show: false
  tooltip:
    enabled: false
    followCursor: false
    x:
      show: false
    fixed:
      enabled: true
  legend:
    show: false
    floating: true
    fontSize: 10px
    position: right
    offsetX: 0
    offsetY: 10
    labels:
      useSeriesColors: true
    markers:
      size: 2
    itemMargin:
      vertical: 5
```
<img width="493" alt="Bildschirmfoto 2024-07-19 um 18 43 36" src="https://github.com/user-attachments/assets/78d10bbc-50b6-4b28-9ba9-60c044a5f452">
