### ISSUE TITLE
[Bug] Wrong area fill color when using group_by option

### ISSUE THREAD

**Issue by HeuristicPerson** [RomRider/apexcharts-card#684]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When using the group_by option the area is not filled with the proper gradient colors.

**Version of the card**
Version: v2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: Temperature
  show_states: true
  colorize_states: true
graph_span: 7d
yaxis:
  - min: 15
    max: 25
series:
  - entity: sensor.ht_sensor_3_xiaomi_lywsd03mmc_temperature
    type: area
    name: 6h avg
    color_threshold:
      - value: 23
        color: '#ff4b00'
      - value: 0
        color: '#4040ff'
      - value: 18
        color: '#4040ff'
      - value: 19
        color: '#bc8bbc'
      - value: 20
        color: '#ffbf00'
      - value: 21
        color: '#ffbf00'
      - value: 22
        color: '#ff9400'
    fill_raw: last
    group_by:
      duration: 6h
      func: avg
    stroke_width: 3
  - entity: sensor.ht_sensor_3_xiaomi_lywsd03mmc_temperature
    color: '#606060'
    name: instant
    fill_raw: last
    stroke_width: 1
    show:
      extremas: max
```

**Screenshots**
Wrong colors
![image](https://github.com/RomRider/apexcharts-card/assets/5576896/c3f17715-5bed-4a3d-8ec6-4eb335113a2e)

Good colors
![image](https://github.com/RomRider/apexcharts-card/assets/5576896/33f8f22f-1a48-4402-8828-4981825d4a14)

**Expected behavior**
When group_by option is used to time average the results, the gradient colors should adjust to the ones defined.

**Desktop (please complete the following information):**
 - Browser Firefox / Chromium
 - Version 124.0.1 /  123.0.6312.58

**Additional context**
