### ISSUE TITLE
Unable to see data from previous month

### ISSUE THREAD

**Issue by cooltings** [RomRider/apexcharts-card#689]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser
- [X ] I verified that I'm really running the lastest version in my browser console
- [X ] I checked if there is another issue opened with the same problem

**Describe the bug**

Using the offset option within span I seem to be unable to go back over month boundaries. I can't see data from 31st of March in April.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
stacked: true
span:
  end: day
  offset: '-10days'
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.vue_2_0_123_1min
    type: column
    group_by:
      func: avg
      duration: 120min
    color: lightblue

```

**Screenshots**
Can't go to 31st March despite it being viewable in history integration:
![](https://community-assets.home-assistant.io/original/4X/5/7/2/572afa95f98b10f703ecaa7b8fe1e507da156093.png)

![](https://community-assets.home-assistant.io/original/4X/2/9/3/2936990f4bf4fc4a7b3552a59a3e957db22a5046.png)

**Expected behavior**

**Desktop (please complete the following information):**
Chrome 123
**Smartphone (please complete the following information):**

**Additional context**
