### ISSUE TITLE
Extremas not showing in column graph

### ISSUE THREAD

**Issue by jorritdb** [RomRider/apexcharts-card#692]
**Describe the bug**
Extremas not showing in column graph

**Version of the card**
Version: v2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 180px
experimental:
  color_threshold: true
graph_span: 23h
span:
  start: day
  offset: +1h
update_interval: +1h
header:
  show: true
  standard_format: true
  show_states: true
now:
  show: true
  label: NU
series:
  - entity: sensor.current_electricity_price_all_in
    name: Nu
    color_threshold:
      - value: 0
        color: green
      - value: 0.2
        color: orange
      - value: 0.3
        color: red
    show:
      extremas: true
      in_header: raw
    stroke_width: 3
    type: column
    float_precision: 2
    data_generator: |
      return entity.attributes.prices.map((record, index) => {
        return [record.from, record.price];
      });
  - entity: sensor.lowest_energy_price_today
    float_precision: 2
    show:
      in_chart: false
      in_header: raw
  - entity: sensor.highest_energy_price_today
    float_precision: 2
    show:
      in_chart: false
      in_header: raw
yaxis:
  - decimals: 2
    min: 0
    max: '|+0.10|'

```

**Screenshots**
![Chart](https://github.com/RomRider/apexcharts-card/assets/114165418/abe3cefb-8456-4a5f-aa0b-7984c879c6b6)

**Expected behavior**
Show extremas
