### ISSUE TITLE
Negative values of "diff" only showing up in edit-mode

### ISSUE THREAD

**Issue by FlorianWilk** [RomRider/apexcharts-card#694]
**Describe the bug**

I have an apex-card which shows the differences in waterlevel of my cistern. Negative Bars when the water-level goes negative and positive bars when water comes in (when it rains). 
In EditMode everything looks perfect, but when i leave and finish editing the chart only shows the positive bars.
I have cleaned my cache multiple times and also on other devices (companion App) i experience the same behaviour.

**Version of the card**
2.0.4

**To Reproduce**
This is the configuration I used:
```
  - type: custom:apexcharts-card
    apex_config:
      chart:
        height: 200px
    graph_span: 1d
    experimental:
      color_threshold: true
    header:
      show: true
      title: Differenz
      show_states: false
    series:
      - entity: sensor.liquid_check_inhalt
        type: column
        name: Inhalt
        group_by:
          func: diff
          start_with_last: true
        color_threshold:
          - value: 0
            color: '#00af00'
            opacity: 1
          - value: 15
            color: '#00afff'

```

**Screenshots**
Editmode:
![image](https://github.com/RomRider/apexcharts-card/assets/3532286/32efe6d7-f21e-4386-b405-c09dbd6c1f86)

clicking "Done":
![image](https://github.com/RomRider/apexcharts-card/assets/3532286/5a0caf44-6dc5-47ff-a8ba-7384ae8d2b3e)

Including the chart with the "raw water level" to show that there really is a decrease in water level at 4:37
![image](https://github.com/RomRider/apexcharts-card/assets/3532286/ad49ae28-f022-4385-9435-8ed122e92eed)

**Expected behavior**
It should also show the negative bar in "non editing mode"

**Desktop (please complete the following information):**
 - Browser Chrome on Linux and Companion APP
