### ISSUE TITLE
Can't retrieve long-term statistics data

### ISSUE THREAD

**Issue by cooltings** [RomRider/apexcharts-card#697]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser
- [X ] I verified that I'm really running the lastest version in my browser console
- [X ] I checked if there is another issue opened with the same problem

**Describe the bug**

I have some long term statistics energy data that apexcgarts-card cannot seem to access. 
It just displays nothing after data switches to long term statistics: 
<img width="475" alt="Screenshot 2024-05-05 at 14 47 27" src="https://github.com/RomRider/apexcharts-card/assets/104278596/0944e7d9-9d98-4732-adc0-76be5c9c712b">
<img width="1026" alt="Screenshot 2024-05-05 at 14 53 04" src="https://github.com/RomRider/apexcharts-card/assets/104278596/59ba3638-96ca-43f9-bd09-1ba915a7f7b5">

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
stacked: true
span:
  end: day
  offset: '-10day'
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.vue_2_0_123_1min
    type: column
    group_by:
      func: avg
      duration: 120min
    color: lightblue
    statistics:
      period: 5minute

```

**Screenshots**

**Expected behavior**
Another bar would appear to the left of the arrow drawn above 
**Desktop (please complete the following information):**

Safari - Latest

**Smartphone (please complete the following information):**

**Additional context**
