### ISSUE TITLE
unsure if issue or feature request  .... strange states vs. graphs (-x days) in combination with "now"

### ISSUE THREAD

**Issue by commentsonly** [RomRider/apexcharts-card#701]
See snappy. Values mismatch the graphs.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
series:
  - entity: sensor.byd_battery_box_premium_hv_state_of_charge
    name: heute
    extend_to: now
  - entity: sensor.byd_battery_box_premium_hv_state_of_charge
    name: gestern
    offset: '-1d'
  - entity: sensor.byd_battery_box_premium_hv_state_of_charge
    name: vorgestern
    offset: '-2d'
```

**Screenshots**

**Expected behavior**
If having added a "now" I would have expected to get the values of now -1d and now -2d besides the actual today value presented in the states since this is what's of interest.
Any idea about how / if this is possible somehow?
I failed in adding a "now" below of the entities itself, looking for something such as "show: states: now or such like.
But perhaps I still missed the documentation on how to get this solved.

![rr](https://github.com/RomRider/apexcharts-card/assets/35866491/34d40e30-b824-4257-8ea0-99b9320937dd)

**Comment by RomRider** [comment]
try with `in_header: before_now` for eg.

**Comment by commentsonly** [comment]
sorry I don't get that, since I can't find an example on how to make us of that. I do understand the description and it likely would do what I expected but a quick try did lead to nothing.

**Comment by RomRider** [comment]
```yaml
series:
  - entity: sensor.byd_battery_box_premium_hv_state_of_charge
    name: heute
    extend_to: now
  - entity: sensor.byd_battery_box_premium_hv_state_of_charge
    name: gestern
    offset: '-1d'
    show:
      in_header: before_now
  - entity: sensor.byd_battery_box_premium_hv_state_of_charge
    name: vorgestern
    offset: '-2d'
    show:
      in_header: before_now
```
