### ISSUE TITLE
float_precision is not manipulating decimals palces of yaxis-values

### ISSUE THREAD

**Issue by Manuel1948** [RomRider/apexcharts-card#708]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
If I enter a value for float_precision, the 5 values on the y-axis has the precision of the entity and not of the wanted floaat_precision.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```type: custom:apexcharts-card
header:
  show: true
  title: Klimaanlage Stromverbrauch
  show_states: true
  colorize_states: true
series:
  - entity: sensor.klimaanlage_current_power
    type: line
    color: '#3b719c'
    float_precision: 0
    stroke_width: 2
    curve: stepline
    show:
      name_in_header: false
```

**Screenshots**
![image](https://github.com/RomRider/apexcharts-card/assets/17245982/4b7302ca-b354-41bb-8624-5fef488a893e)

**Expected behavior**
The amount of decimal places of the y-axis should be the float_precision-value.

**Comment by RomRider** [comment]
That is expected as if you have multiple series, they might not all have the same float precision.
However, there's a config option to do so https://github.com/RomRider/apexcharts-card?tab=readme-ov-file#yaxis-options-multi-y-axis

```yaml
header:
  show: true
  title: Klimaanlage Stromverbrauch
  show_states: true
  colorize_states: true
yaxis:
  - decimals: 0
series:
  - entity: sensor.klimaanlage_current_power
    type: line
    color: '#3b719c'
    float_precision: 0
    stroke_width: 2
    curve: stepline
    show:
      name_in_header: false
```
