### ISSUE TITLE
Extend_to: end changing the end of another series

### ISSUE THREAD

**Issue by i00** [RomRider/apexcharts-card#712]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When I extend a series to the end it "closes" another series:
In this the series that is the horizontal line in the following graph (Backup) it is extended to end - as can be seen it also affects Charge:
![image](https://github.com/RomRider/apexcharts-card/assets/1435262/ed14f61c-5d8f-4951-b788-15cee5999fa8)
This is without the extend_to:
![image](https://github.com/RomRider/apexcharts-card/assets/1435262/4bfb65cf-d305-450b-b45f-88b653ea1519)

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
span:
  start: day
graph_span: 24h
all_series_config:
  extend_to: false
  group_by:
    func: avg
    duration: 15m
  yaxis_id: Power
series:
  - entity: sensor.my_home_charge
    yaxis_id: Battery
    name: Charge
    color: var(--energy-battery-in-color)
    opacity: 1
    type: line
    stroke_width: 4
    show:
      in_header: true
  - entity: sensor.my_home_backup_reserve
    yaxis_id: Battery
    name: Backup
    type: line
    stroke_width: 2
    color: var(--energy-battery-in-color)
    opacity: 0.5
    extend_to: end
  - entity: sensor.myenergi_bowler_power_charging
    name: EV Load
    color: var(--energy-battery-out-color)
    invert: true
yaxis:
  - max: 100
    min: 0
    id: Battery
    decimals: 0
  - id: Power
    opposite: true
```

**Expected behavior**
The Charge should not be affected.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 125.0.6422.141/142

**Smartphone (please complete the following information):**
N/A
