### ISSUE TITLE
Option time_delta in combination with extremas

### ISSUE THREAD

**Issue by michull** [RomRider/apexcharts-card#713]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [ ] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
The combination of the series option "time_delta: +30min" and "show->extremas: true" results in an wrong position of the extrema points and labels.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 2h
series:
  - entity: sensor.switchbot_temperature
    time_delta: +30min
    show:
      extremas: true
```

**Screenshots**
<img width="371" alt="apex1" src="https://github.com/RomRider/apexcharts-card/assets/41358006/ec7e66f7-a1b9-457d-a7cc-d44160cc9646">

**Expected behavior**
The x position of the two extrema points should be also shifted by time_delta.

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 126

**Additional context**
If I use the series option "show->datalabels: true", the time_delta is considered.
<img width="371" alt="apex2" src="https://github.com/RomRider/apexcharts-card/assets/41358006/af8d3305-663b-4d49-8e7b-56c999ba249d">
