### ISSUE TITLE
Repeated values on Y-axis column chart type

### ISSUE THREAD

**Issue by Tamadite** [RomRider/apexcharts-card#715]
**Checklist**
- [ X ] I updated the card to the latest version available
- [ X ] I cleared the cache of my browser
- [ X ] I verified that I'm really running the lastest version in my browser console
- [ X ] I checked if there is another issue opened with the same problem

**Describe the bug**
When using the bars chart type, the Y-axis shows repeated piled values and so bars with same values show different sizes.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
update_interval: 12h
graph_span: 7d
header:
  show: true
  show_states: true
  title: 7-day consumption
series:
  - entity: sensor.esp_p1reader_momentary_active_import
    type: column
    group_by:
      func: avg
      duration: 24h
    show:
      datalabels: true
```

**Screenshots**
<img width="483" alt="image" src="https://github.com/RomRider/apexcharts-card/assets/30261982/f9a88d3b-bc9c-4f1f-ab58-bc9ac426c0ee">

**Expected behavior**
To show increasing consecutive values on the Y-axis and bars with equal value having same size.

**Desktop (please complete the following information):**
 - Browser: firefox, safari, chrome
 - Version: 126.0.1, 16.4 (18615.1.26.11.23), 125.0.6422.142 

**Smartphone (please complete the following information):**
 - Device: N.A.
 - OS: N.A.
 - Browser: N.A.
 - Version: N.A.

**Additional context**
