### ISSUE TITLE
Mouse hover tooltip does not correspond with position of mouse

### ISSUE THREAD

**Issue by obiphi** [RomRider/apexcharts-card#717]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The hover tooltip of the graph does not correspond with the position of the mouse. Here's a demonstration:

![apexcharts-card-hover-issues](https://github.com/RomRider/apexcharts-card/assets/32672400/59473442-3f26-4755-aa7d-94468990e084)

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Motion Last 12 hours
update_delay: 3s
update_interval: 1min
graph_span: 12h
yaxis:
  - show: false
    apex_config:
      tickAmount: 1
apex_config:
  chart:
    height: 150px
all_series_config:
  transform: 'return x === ''on'' ? 1 : 0;'
  type: column
  stroke_width: 1
  show:
    legend_value: false
series:
  - entity: binary_sensor.visonic_z01
    name: Front door
  - entity: binary_sensor.visonic_z02
    name: Kitchen
  - entity: binary_sensor.visonic_z03
    name: Lounge
  - entity: binary_sensor.visonic_z04
    name: Kitchen back door
  - entity: binary_sensor.visonic_z05
    name: Playroom
  - entity: binary_sensor.front_camera_person
    name: Drive
  - entity: binary_sensor.back_camera_person
    name: Garden

```

**Screenshots**
As above

**Expected behavior**
The position of the tooltip should line up with the position of the mouse, and describe what is under the mouse pointer

**Desktop (please complete the following information):**
 - Browser: Tried:
   - Google chrome 126.0.6478.127 (Official Build) (64-bit) On Windows 10
   - Microsoft Edge  126.0.2592.68 on Windows 10
   - Firefox 127.0.2 on Oracle Enterprise Linux 9

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21+
 - OS: Android 14
 - Browser: 
   - Official Home Assistant App 2024.6.1-full
   - Google Chrome 126.0.6478.122

**Additional context**
None

**Comment by RomRider** [comment]
That's an issue with the apexcharts library. There's not much I can do about it, but you can try the latest beta as I've updated it to the latest version.

**Comment by cupertinomiranda** [comment]
Where exactly can I get that latest beta. I don't seem to find a branch or a release for a beta. Thanks

**Comment by pfiorentino** [comment]
@cupertinomiranda did you try with a higher chart height?

I face a very similar issue.
My chart is:
```yaml
apex_config:
  chart:
    height: 150px
```

and as soon as I change to:

```yaml
apex_config:
  chart:
    height: 205px
```

the tooltip is rendered with the correct data.


https://github.com/user-attachments/assets/323ed1c3-5612-4d51-8d0e-475aada27b0b
