### ISSUE TITLE
Some bugs Apexcharts with Fullykiosk since last update

### ISSUE THREAD

**Issue by LioBoul** [RomRider/apexcharts-card#725]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
Since the last Apexcharts update, I have a few small bugs:
- extrema shifts
- the chart is not displayed if one of the values ​​is show: in_chart: false (I got around this problem with full opacity)

Bugs only with Fullykiosk browser, not Chrome.
Cache cleared.

**Screenshots**
![Capture d’écran 2024-07-10 114038](https://github.com/RomRider/apexcharts-card/assets/162896032/e9f4f6d6-4245-4817-a6eb-316aeb38c41b)

**Version of the card**
Version: last

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
apex_config:
  legend:
    show: false
  chart:
    height: 140px
experimental:
  color_threshold: true
graph_span: 7d
span:
  end: day
show:
  last_updated: false
header:
  show: true
  show_states: true
  colorize_states: true
  title: Appareils électriques / Éclairages
yaxis:
  - min: 0
    max: ~9
    decimals: 0
    apex_config:
      tickAmount: 3
series:
  - entity: sensor.consommation_totale_des_appareils
    name: Conso aujourd'hui
    float_precision: 2
    show:
      header_color_threshold: true
      extremas: true
    header_actions:
      tap_action:
        action: navigate
        navigation_path: /lio-cindy-essential/conso
    type: column
    color: grey
    group_by:
      func: diff
      fill: last
      duration: 1d
    color_threshold:
      - value: 0
        color: limegreen
      - value: 6
        color: orange
      - value: 9
        color: red
  - entity: sensor.consommation_totale_des_appareils
    transform: return x * 0.363636
    name: Coût
    unit: €
    float_precision: 2
    opacity: 0
    color_threshold:
      - value: 0
        color: white
      - value: 10
        color: white
    group_by:
      func: diff
      fill: last
      duration: 1d
    show:
      header_color_threshold: true
      extremas: false
    header_actions:
      tap_action:
        action: navigate
        navigation_path: /lio-cindy-essential/conso
  - entity: sensor.conso_appareils_7_derniers_jours
    transform: return x / 7
    name: Conso moyenne
    float_precision: 2
    stroke_width: 0
    color: grey
    opacity: 0.3
    show:
      in_header: false
      header_color_threshold: false
      in_chart: true
      extremas: true
    type: area
    group_by:
      func: last
      fill: last
      duration: 8d
    color_threshold:
      - value: 6
        color: limegreen
      - value: 7.5
        color: orange
      - value: 9
        color: red

```

**Expected behavior**
Reload...

**Desktop (please complete the following information):**
 - Browser Fullykiosk
 - Version 1.55.3-play

**Smartphone (please complete the following information):**
 - no bug
