### ISSUE TITLE
Stacked line charts broken in 2.1.2

### ISSUE THREAD

**Issue by marcelhoogantink** [RomRider/apexcharts-card#730]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
option ```stacked: true``` does not work anymore in 2.1.2, it's OK in 2.0.4

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 10d
show:
  last_updated: true
stacked: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: test apex graph
all_series_config:
  stroke_width: 1
  type: area
  curve: stepline
  opacity: 1
  statistics:
    type: mean
series:
  - entity: sensor.hass_db_states
  - entity: sensor.hass_db_attributes
  - entity: sensor.hass_db_events
  - entity: sensor.hass_db_statistics
  - entity: sensor.hass_db_size
    type: line
    stroke_width: 2
yaxis:
  - min: 0
    max: 1500

```

**Screenshots**
Version 2.0.4 is OK:
![ApexChart_2_0_4_stacked_line_graph](https://github.com/user-attachments/assets/338fa22b-87c5-4c13-ba85-007978260606)

Version 2.1.2 is wrong:
![ApexChart_2_1_2_stacked_line_graph](https://github.com/user-attachments/assets/72e215fb-f666-45de-ad88-a13adf11cf3e)

**Expected behavior**
Graph should be stacked also in 2.1.2

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Any
 - Version [e.g. 22] ANy

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Any
 - OS: [e.g. iOS8.1] Any
 - Browser [e.g. stock browser, safari] Any
 - Version [e.g. 22] Any

**Additional context**
----

**Comment by paulius2k** [comment]
Same for `type: column` chart:
![image](https://github.com/user-attachments/assets/e3e1ba65-fc1a-4eb7-9ceb-147e32dfa35c)

**Comment by jarube** [comment]
> Same for `type: column` chart: <img alt="" width="70%" src="https://private-user-images.githubusercontent.com/24705262/348457474-e3e1ba65-fc1a-4eb7-9ceb-147e32dfa35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjgyOTcsIm5iZiI6MTcyMDg2Nzk5NywicGF0aCI6Ii8yNDcwNTI2Mi8zNDg0NTc0NzQtZTNlMWJhNjUtZmMxYS00ZWI3LTljZWItMTQ3ZTMyZGZhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEwNTMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YmI2OGNiN2ZlNGMxMzUxZTlkMzVmYTZmNWNjMDZmMTRlYTViNDBmNWIwMWVkOTMzYjM0NzExZDEzYTQzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DdvYyUbNyURELpc3iJppinsSNJCPFWAIXj64dOytoEE">

Same here!

**Comment by RomRider** [comment]
Until I fix it in the code, you can fix it with:
```yaml
apex_config:
  chart:
    stackOnlyBar: false
```

**Comment by marcelhoogantink** [comment]
> Until I fix it in the code, you can fix it with:
> 
> ```yaml
> apex_config:
>   chart:
>     stackOnlyBar: false
> ```
Thanks for your reply, I tried it, but it did not work:

![image](https://github.com/user-attachments/assets/4b4186f2-35c1-4170-b328-701e5fefd237)

**Comment by jarube** [comment]
> Until I fix it in the code, you can fix it with:
> 
> ```yaml
> apex_config:
>   chart:
>     stackOnlyBar: false
> ```

sorry, this doesn't work me either

**Comment by del13r** [comment]
Same issue here

2.0.4
![image](https://github.com/user-attachments/assets/9e4051af-2a5a-4de7-9f7c-41a17fda0eaa)

2.1.0
![image](https://github.com/user-attachments/assets/c2dd41e7-b04d-4205-88e4-83f2015a9d58)

Code
`card:
  type: custom:apexcharts-card
  stacked: true`

**Comment by paulius2k** [comment]
The strange thing for me is that I can't even make it work again by rolling back to v2.0.4.

**Comment by wejto** [comment]
As I replied in https://github.com/RomRider/apexcharts-card/issues/728#issuecomment-2222610262, it works in a newer version when you delete the y-axis block in yaml but this workaround is not possible to use every time. At least rolling back to 2.0.4 worked for me well.

**Comment by del13r** [comment]
> The strange thing for me is that I can't even make it work again by rolling back to v2.0.4.

I found that I was being impatient with the download button and had to wait a few seconds before pressing the download button.
You can confirm what version you have by doing this in the terminal

`cat /homeassistant/www/community/apexcharts-card/apexcharts-card.js | grep -o v2.0.4`
v2.0.4

**Comment by paulius2k** [comment]
I do have 2.0.4 now:

```
➜  ~ cat /homeassistant/www/community/apexcharts-card/apexcharts-card.js | grep -o v2.0.4
v2.0.4
```

**Comment by del13r** [comment]
I found that removing the yaxis: block made the stacking work again with the newer versions 2.1.0 onwards.

Originally posted by @wejto in https://github.com/RomRider/apexcharts-card/issues/728#issuecomment-2222610262

**Comment by RichardRamshaw** [comment]
> Until I fix it in the code, you can fix it with:
> 
> ```yaml
> apex_config:
>   chart:
>     stackOnlyBar: false
> ```

This did work for me, added near the top, not sure if it's not working for others as it was added at the bottom?

**Comment by alexeiw123** [comment]
Ah - I spent ages figuring out the `brush` feature and was thinking "gee, I've really nailed this view!" - then I saw that my stacked area graph had broken. First up, I thought it must have been some change I'd made when implementing `brush`.

![image](https://github.com/user-attachments/assets/288469f1-c264-421a-9d0b-f03ebdb2b198)

So after finding this issue, I see that there's a bug using stacked. So this is where it gets interesting for me. With the same code, if I roll back to `v2.0.4`, this is what I get:

![image](https://github.com/user-attachments/assets/41eed236-917f-4c8b-b706-c2a150fd3c9e)

This actually does seem related to using `brush` because if I make this change:
```
  experimental:
    brush: true
```
Then my stacked graph shows correctly - just no interactivity. (I've also changed the span just to help show detail int he screenshot)

![image](https://github.com/user-attachments/assets/b1b98941-5995-4af0-bc3b-7157ef43c33c)

So i don't know if these bugs are related. Does `brush` clash with `[stacked](stacked: true)`? Will fixing this `stacked` issue also solve the display issues when `brush` is enabled?

**Comment by man010** [comment]
Removing the yaxis block works as a workaround… but this is not a viable solution in the end

**Comment by Cellivar** [comment]
I was able to work around this by moving the y-axis config into the `apex_charts` [section.](https://apexcharts.com/docs/options/yaxis/).

![image](https://github.com/user-attachments/assets/664a4108-c589-456d-a5bc-6bc754fe30f3)


<details>
  <summary>Click here to expand the config</summary>

```yaml
type: custom:apexcharts-card
apex_config:
  yaxis:
  - show: true
    decimalsInFloat: false
    opposite: true
    min: 0
    stepSize: 100
    seriesName: '🏠'
  - seriesName: '🏠'
    show: false
  chart:
    stackOnlyBar: false
    height: 600px
    type: area
  legend:
    width: 100%
    inverseOrder: true
    position: bottom
    itemMargin:
      horizontal: 15
      vertical: 5
    markers:
      radius: 1
      height: 14
      width: 6
      offsetY: 4
stacked: true
cache: false
graph_span: 30m
update_interval: 30s
header:
  floating: true
  show: true
  show_states: true
all_series_config:
  stroke_width: 1
  opacity: 1
  type: area
  float_precision: 0
  show:
    in_header: false
  fill_raw: last
  group_by:
    func: max
    duration: 1m
series:
  - entity: sensor.eagle_200_meter_power_demand
    type: line
    stroke_width: 2
    color: '#A55'
    name: '🏠'
    yaxis_id: '1'
    show:
      legend_value: false
      in_header: raw
      extremas: true
  - entity: sensor.all_standby_power
    name: '💤'
  - entity: sensor.nelson_energy_power
    name: 🐁⚡
  - entity: sensor.fraser_energy_power
    name: 🦊⚡
  - entity: sensor.rhine_energy_power
    name: 🌿🐱⚡
  - entity: sensor.thelon_energy_power
    name: 🛜
  - entity: sensor.shelly_rubicon_power
    name: 📺
  - entity: sensor.shelly_orinoco_power
    name: 🛠️
  - entity: sensor.all_lights_power
    name: 💡
  - entity: sensor.yangtzeekiang_energy_power
    name: 🍔❄
  - entity: sensor.colorado_energy_power
    name: 💦👕
  - entity: sensor.riogrande_energy_power
    name: 💦🍽️
  - entity: sensor.evse_dryer_total_power
    name: 🚓
  - entity: sensor.fan_power
    name: ✇❄
```

</details>
