### ISSUE TITLE
color_threshold showing historical series with color changes at different values.

### ISSUE THREAD

**Issue by DrJohnM61** [RomRider/apexcharts-card#731]
**Checklist**
- [ yes] I updated the card to the latest version available
- [ yes] I cleared the cache of my browser
- [ yes] I verified that I'm really running the latest version in my browser console
- [ yes] I checked if there is another issue opened with the same problem

**Describe the bug**
color_threshold line chart is showing historical data with a different threshold than one set or more recent data.

Viz: I set the threshold to 253 and plot a history for a series for 24hrs for the prior day. Items shown for the earlier part of the day show the cutoff at about 252.4 wheres the later data shows the cutoff as expected at 253.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: false
  title: Grid Voltage
  show_states: true
apex_config:
  stroke:
    width: 1
graph_span: 1d
span:
  start: day
  offset: '-1d'
series:
  - entity: sensor.givtcp_ch2330g417_grid_voltage
    type: line
    extend_to: now
    stroke_width: 1
    color_threshold:
      - value: 0
        color: blue
        opacity: 1
      - value: 216.2
        color: cyan
      - value: 253
        color: green
      - value: 253
        color: red
```

**Screenshots**
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/684e6f14-6110-4253-b851-398539eeff2a">

Please note that I have added the line to show that the colour change is not consistent through the graph and that historical data items seem to be being marked as red at 252.5 rather than the 253 as per the yaml. Later data items are being shown correctly.

Also note that I have to put the two values for green and red the same otherwise the graph does not show as expected.

Here is another example where the latest values are showing incorrectly:

<img width="954" alt="image" src="https://github.com/user-attachments/assets/6f6b8ed3-57f1-4b9b-aedb-e97552857681">

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: Grid Voltage
  show_states: true
apex_config:
  stroke:
    width: 1
graph_span: 1d
span:
  start: day
series:
  - entity: sensor.givtcp_ch2330g417_grid_voltage
    type: line
    extend_to: now
    stroke_width: 1
    color_threshold:
      - value: -10
        color: blue
        opacity: 1
      - value: 0
        color: cyan
      - value: 253
        color: red
      - value: 253
        color: green
```

**Expected behaviour**
 I would expect that the coloured cutoff to be consistent across the graph to highlight where the measured voltage is in violation.

**Desktop (please complete the following information):**
 - Browser safari and also tested on Firefox
 - Version Safari Version 17.5 (19618.2.12.11.6)
 - Firefox 128.0 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
I fully appreciate that this is an experimental feature and provide this as a feedback bug in that context.

The ambition is to produce a report to my electricity supplier that shows that our grid electricity is exceeding the legal threshold.
