### ISSUE TITLE
max: auto  no longer works, all charts stuck at 10

### ISSUE THREAD

**Issue by LordLinhey** [RomRider/apexcharts-card#733]
max: auto - no longer works, all charts stuck at 10
```
    yaxis:
      - id: Power
        seriesName: Power
        show: true
        min: 0
        **max: auto**
        opposite: false
        reversed: false
```
![image](https://github.com/user-attachments/assets/1a8be5cf-82c2-43d1-a345-4b6ff78b804a)

Restored to V2.04 now max: auto works
