### ISSUE TITLE
Entities with unchanging statistics stops the page from loading on Firefox

### ISSUE THREAD

**Issue by tomlut** [RomRider/apexcharts-card#734]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
If you attempt to graph an entity using the statistics option and the entity has not changed for the period of time displayed then Firefox browser hangs. Google chrome fares a little better, it slows but eventually loads an empty graph. 

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 100%
  dataLabels:
    background:
      enabled: false
    style:
      colors:
        - var(--primary-text-color)
graph_span: 24h
header:
  show: true
  show_states: true
  title: 12V DC Bus
yaxis:
  - id: left
    decimals: 3
    apex_config:
      forceNiceScale: true
series:
  - entity: sensor.12v_bus_voltage
    stroke_width: 2
    type: line
    curve: stepline
    color: rgb(192,192,192)
    statistics:
      type: mean
      period: 5minute
      align: middle
    yaxis_id: left
    float_precision: 2
    show:
      datalabels: false
      extremas: false
      name_in_header: false
    header_actions:
      tap_action:
        action: more-info
```

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/d9d2d90d-b0e1-48ba-8981-c379ea0d2105)

**Expected behavior**
The statistics to be displayed 

**Desktop (please complete the following information):**
 - Firefox 128.0
- Chrome 126.0.6478.127

**Additional context**
