### ISSUE TITLE
Graph_span dynamic or template-able? 

### ISSUE THREAD

**Issue by Hellis81** [RomRider/apexcharts-card#735]
**Checklist**
- [YES] I am running the latest version of the card
- [ YES, did not find anything] I checked if there isn't another feature request opened with the same request
- [ Don't know how to...] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I want there to be an auto option for graph span or being able to template the span. 
Example: 
```
graph_span: "{{ '48h' if state_attr('sensor.nordpool_kwh_se4_sek_3_10_025', 'tomorrow') != [] else '24h' }}"
```
So if tomorrows values are in the sensor, include them in the graph, else fill the graph with todays values.

**Describe the solution you'd like**
It would be nice if it could include templates, or if the graph could scale to the data size.

**Describe alternatives you've considered**
I guess I could create two cards and use the conditional card to hide one of them depending on if the sensor includes tomorrow or not.

**Additional context**
![image](https://github.com/user-attachments/assets/b3ee1241-6be9-471b-829b-aeb1c86ca564)
![image](https://github.com/user-attachments/assets/f4f89a72-a80d-478d-9e7a-698b207005b8)

**Comment by mattmeiser** [comment]
I would love to see this feature as well.   Use case is to display a graph of temps from my Fireboard BBQ controller.   Span would be dynamic, calculated as from the time I last powered on my pellet grill's smart outlet.

**Comment by Toretto5060** [comment]
I would love to see this feature as well.

**Comment by Toretto5060** [comment]
What I need is the span from the 1st of each month to the current date, and this is feasible for me to do.
![WX20240829-213509@2x](https://github.com/user-attachments/assets/ebabdbfa-e25e-4357-b3eb-d0bd77349ee3)
![WX20240829-213523@2x](https://github.com/user-attachments/assets/40cf32a9-9f98-406c-a798-2f41222503f2)

**Comment by Hellis81** [comment]
> What I need is the span from the 1st of each month to the current date, and this is feasible for me to do. ![WX20240829-213509@2x](https://private-user-images.githubusercontent.com/27842190/362709911-ebabdbfa-e25e-4357-b3eb-d0bd77349ee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTg2MDcsIm5iZiI6MTcyNDk1ODMwNywicGF0aCI6Ii8yNzg0MjE5MC8zNjI3MDk5MTEtZWJhYmRiZmEtZTI1ZS00MzU3LWIzZWItZDBiZDc3MzQ5ZWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE5MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMTJjOWI2NGJjNGQ3YzQzNGQxOWI5NDM1MWI2MmNiNGRjY2Q0NjcwODViNTg5YWU0Nzg4YzBlNmUyMDQ4NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2eYaHTcMK22Vs1_FKF8TjsezwtmwdX3c9KbZaKQ_B3A) ![WX20240829-213523@2x](https://private-user-images.githubusercontent.com/27842190/362709946-40cf32a9-9f98-406c-a798-2f41222503f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTg2MDcsIm5iZiI6MTcyNDk1ODMwNywicGF0aCI6Ii8yNzg0MjE5MC8zNjI3MDk5NDYtNDBjZjMyYTktOWY5OC00MDZjLWE3OTgtMmY0MTIyMjUwM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE5MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYzBhNWM1MGUxM2FkYTI4OGMyNWJkMGFhOWQzNjQ2YmNiNmFjZTUwMmFmNmRiMjZmNDU3NTc2MWI5MmNhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQsdlaUY-tLyTcCdaBBbnrCFgvhBA52EKJneC4AFW5g)

You wouldn't need the sensor if templates was possible 😜

**Comment by cokecan72** [comment]
I've also just stumbled on a use case where being able to set a dynamic graph_span would be ideal. I've tried all sorts with no success. I have a custom template sensor that increments the number of days from a specific date which I'd like to use as the value for graph_span. Right now it seems like graph_span just will not accept anything but a hand typed value which is disappointing given how flexible everything else is with Apex Charts.

I want to create a line graph that displays the max value of a statistics sensor for each day for up to 1 year from a specific start date where the graph only shows the collected data to date and "extends" and shows more day by day as the year goes on. At the end of the year I'd reset the date sensor back to 1 and let graph_span "shrink" the graph back down to just the collected data to date. It would mean that I can start to see trends and points of interest at a glance on a graph that shows only data collected up to that day on a graph that looks sharp without needing to manually update or modify it.

**Comment by cokecan72** [comment]
Just commenting to stop this from being closed. I'd still really like this feature

**Comment by mad-sysadmin** [comment]
+1

**Comment by mattmeiser** [comment]
Any action on this?

**Comment by jakeycrx** [comment]
It's possible I worked it out from cherry picking the parts I needed from this post:

https://community.home-assistant.io/t/statistics-explorer-with-apex-chart/428421

**Comment by suurt8ll** [comment]
Awesome! `custom:config-template-card` seems to be just perfect for this. It needs to be added to HA, [link](https://github.com/iantrich/config-template-card), in order to get this working, I got stuck at this point for a bit. I modified @jakeycrx solution and this is my crude working config for Nordpool prices:

```yaml
type: custom:config-template-card
variables:
  getGraphSpan: |
    tomorrowData => {
      if (tomorrowData && tomorrowData.length > 0) {
        return '48h';
      } else {
        return '24h';
      }
    }
  tomorrowData: states['sensor.nordpool_mwh_ee_eur_0_10_022'].attributes.raw_tomorrow
entities:
  - sensor.nordpool_mwh_ee_eur_0_10_022
card:
  type: custom:apexcharts-card
  graph_span: ${getGraphSpan(tomorrowData)}
  span:
    start: day
  now:
    show: true
    label: Now
  series:
    - entity: sensor.nordpool_mwh_ee_eur_0_10_022
      type: column
      name: Prices
      data_generator: |
        const todayData = entity.attributes.raw_today;
        const tomorrowData = entity.attributes.raw_tomorrow || [];

        const combinedData = [...todayData, ...tomorrowData];

        return combinedData.map((item) => {
          const date = new Date(item.start.slice(0, -6));

          return {
            // Adding 30 min moves the bars to the right for better alignment.
            x: date.getTime() + (30 * 60 * 1000),
            y: item.value,
          };
        });
```

**Comment by jakeycrx** [comment]
Apologies I should have mentioned you need to download template card from HACS

**Comment by cokecan72** [comment]
This is awesome, thank you guys!

Here's my tweak on the above to return the number of days between a specific date and today. I wanted to display data on a graph from a point in time and watch it grow over the year automatically:

```yaml
type: custom:config-template-card
variables:
  span: |
    (() => {
      const currentDate = "01-01-2025";
      const parts = currentDate.split("-");
      const targetDate = new Date(parts[2], parts[1] - 1, parts[0]);
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      targetDate.setHours(0, 0, 0, 0);
      const diffTime = targetDate - today;
      return `"${Math.ceil(diffTime / (1000 * 60 * 60 * 24))}d"`; // Return as "Xd" string
    })()
entities: []
card:
  type: custom:apexcharts-card
  chart_type: line
  graph_span: ${span}
  span:
    end: day
  series:
    - entity: sensor.energy_consumption
      statistics:
        type: mean
        period: day
        align: start
```
