### ISSUE TITLE
Doesn't support layout_options option in sections panel (Home Assistant v2024.7)

### ISSUE THREAD

**Issue by xiaodong-lx** [RomRider/apexcharts-card#736]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
In [sections view(Home Assistant v2024.7)](https://www.home-assistant.io/dashboards/sections/), cards could be resized [_link_](https://www.home-assistant.io/dashboards/cards/#resizing-a-card), even custom cards(such as `custom:webrtc-camera`). But `apexcharts-card` show error if i wrote any other options.

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
update_interval: 1min
header:
  ....
yaxis:
  ....
series:
  - entity: sensor.xxx
layout_options:
  grid_columns: 4
  grid_rows: 4
```

**Screenshots**
![image](https://github.com/user-attachments/assets/f8493f05-6f7e-4eb8-9bdb-58ac31a14212)

**Expected behavior**
Support `layout_option` option

**Desktop (please complete the following information):**
 - Browser [Microsoft Edge]
 - Version [125.0.2535.85]

**Smartphone (please complete the following information):**
no

**Additional context**
no

**Comment by RomRider** [comment]
You can disable the config validation:
```yaml
experimental:
  disable_config_validation: true
```

**Comment by xiaodong-lx** [comment]
`layout_options.grid_columns` works, but `layout_options.grid_rows` not works, maybe the card has a fixed height?

````yaml
layout_options:
  grid_columns: 3
  grid_rows: 3
experimental:
  disable_config_validation: true
````

![IMG_0306](https://github.com/user-attachments/assets/9b4951d0-b33b-4af6-86de-e9b6e665c3aa)
![IMG_0305](https://github.com/user-attachments/assets/16391dc5-baf8-47c0-b8cd-598dd757aba1)

**Comment by kthofmann** [comment]
@xiaodong-lx I can confirm "grid_columns:" works for me, "grid_columns: " I have the same issues, even without fixed height.

**Comment by TylonHH** [comment]
![image](https://github.com/user-attachments/assets/cd574183-0a62-4cad-b9f1-92eaf8d8fc6a)

'''
type: custom:apexcharts-card
experimental:
  color_threshold: true
all_series_config:
  unit: Cent/kWh
apex_config:
  grid:
    show: true
    borderColor: "#E0E0E0"
  chart:
    height: 250px
  tooltip:
    enabled: true
    followCursor: false
    x:
      show: false
    fixed:
      enabled: true
header:
  show: true
  title: Strompreis
  show_states: true
  colorize_states: true
  standard_format: false
graph_span: 48h
now:
  show: true
  color: 9E9E9E
span:
  start: day
series:
  - entity: sensor.tibberpreisrest
    name: Preis
    show:
      in_header: before_now
      name_in_header: false
    color_threshold:
      - value: 0
        color: 4DD0E1
      - value: 10
        color: 26A69A
      - value: 15
        color: 4CAF50
      - value: 20
        color: 7CB342
      - value: 25
        color: FBC02D
      - value: 30
        color: EF6C00
      - value: 40
        color: B71C1C
    type: line
    curve: stepline
    extend_to: false
    stroke_width: 2
    float_precision: 2
    data_generator: |
      const noon = new Date()
      noon.setHours(0, 0, 0, 0)
      const prices = entity.attributes.today.concat(entity.attributes.tomorrow);
      const data = [];
      for(let i = 0; i < prices.length; i++) {
        data.push([noon.getTime() + i * 1000 * 3600, prices[i].total * 100])
      }
      return data;
'''

So how to handle this with the new section view in HA?

**Comment by matthewhadley** [comment]
The new sections configuration is out of experimental - https://www.home-assistant.io/blog/2024/11/06/release-202411/#sections-dashboard-no-longer-experimental

There is a new top level `grid_options` key that apexcharts-card currently does not support, for example:
```
grid_options:
  columns: full
```

For now, setting config validation off allows it to be set.

```
experimental:
  disable_config_validation: true
```

**Comment by rhpijnacker** [comment]
When I use the layout options, the card seems to always want to keep the aspect ratio. I.e. when it make the card wider, it also becomes higher. 
What is the right way to fix that?

**Comment by KernSani** [comment]
For me it seems to work with a fixed height:
```
grid_options:
  columns: full
experimental:
  disable_config_validation: true
apex_config:
  chart:
    height: 200px
  legend:
    show: false
```

**Comment by metaathron** [comment]
Hi, are you planning for fix, so we don't need to use "disable_config_validation: true"?

**Comment by rhpijnacker** [comment]
Bump

**Comment by ShelbyJenkins** [comment]
I figured out a solution that works for me.

You wrap it in a horizontal stack.

```
  - type: horizontal-stack
    cards:
      - type: custom:apexcharts-card
        grid_options:
          columns: full
        apex_config:
          chart:
            height: 300px
        experimental:
          disable_config_validation: true
        graph_span: 24h
        series:
           .....
    grid_options:
      columns: full
```
