### ISSUE TITLE
Data missing from charts

### ISSUE THREAD

**Issue by 03397** [RomRider/apexcharts-card#742]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
Randomly the graph has discontinued dara even when the data is there

**Version of the card**
Version:
2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Indoor Humidity
  show_states: true
  colorize_states: true
update_interval: 5min
series:
  - entity: sensor.kitchen_sensor_humidity
    stroke_width: 2
  - entity: sensor.master_bedroom_sensor_humidity
    stroke_width: 2
  - entity: sensor.bedroom_1_sensor_humidity
    stroke_width: 2
  - entity: sensor.bedroom_2_sensor_humidity
    stroke_width: 2
apex_config:
  xaxis:
    tooltip:
      enabled: false



```

**Screenshots**
![image](https://github.com/user-attachments/assets/d19b2a96-c6d2-4e5a-abc8-dd09c053a842)

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
