### ISSUE TITLE
Firefox renders 1st line in graph black, where as other browsers use orange

### ISSUE THREAD

**Issue by gijs007** [RomRider/apexcharts-card#744]
When looking at the graphs on iOS, or Microsoft Edge, the first line has nice orange lines. 
The orange lines are easier to read on the dark background, and look better.

However on Firefox (128.0, but also older releases) they are rendered black.

Here is a side by side comparison of Firefox (left) and Edge (right).
![black is the new orange](https://github.com/user-attachments/assets/bb6d00a8-6467-4c59-b3ba-c81433f5029e)

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 1h
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: Usage per phase last hour
series:
  - entity: sensor.dsmr_reading_phase_currently_delivered_l1
    type: line
    group_by:
      func: last
      duration: 10s
    stroke_width: 2
    unit: Watt
  - entity: sensor.dsmr_reading_phase_currently_delivered_l2
    type: line
    group_by:
      func: last
      duration: 10s
    stroke_width: 2
    unit: Watt
  - entity: sensor.dsmr_reading_phase_currently_delivered_l3
    type: line
    group_by:
      func: last
      duration: 10s
    stroke_width: 2
    unit: Watt
```
