### ISSUE TITLE
`stacked: true` not working anymore

### ISSUE THREAD

**Issue by mathieucarbou** [RomRider/apexcharts-card#746]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**

Stacking bar charts is not working anymore

**Version of the card**
Version: [v2.1.2](https://github.com/RomRider/apexcharts-card/releases/tag/v2.1.2)
(i've switched to it yesterday through HACS)

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 12months
span:
  end: month
cache: true
update_interval: 24h
stacked: true
header:
  show: true
  title: Suivi énergétique H&T (kWh/month)
  standard_format: true
apex_config:
  chart:
    height: 400px
yaxis:
  - decimals: 0
    min: -900
    max: 400
    apex_config:
      tickAmount: 13
      forceNiceScale: true
      axisTicks:
        show: false
all_series_config:
  type: column
  unit: kWh
  float_precision: 2
  show:
    legend_value: false
  statistics:
    type: sum
    period: month
    align: middle
  group_by:
    func: diff
    duration: 1month
    start_with_last: true
    fill: last
series:
  - entity: sensor.circuit_climatisation_energy
    name: PAC
  - entity: sensor.chauffage_energy
    name: Chauffage
  - entity: sensor.deshumidificateur_salon_energy
    name: Déshumidificateur Salon
  - entity: sensor.deshumidificateur_chambre_energy
    name: Déshumidificateur Chambre
  - entity: sensor.deshumidificateur_etage_energy
    name: Déshumidificateur Étage
  - entity: sensor.home_consumed_energy
    name: Consommation totale
    color: lightgrey
    invert: true
```

**Screenshots**

![image](https://github.com/user-attachments/assets/2b9c3fa3-46a1-4b21-a8fa-d7820da4ba89)
![image](https://github.com/user-attachments/assets/21dbec00-41c3-430b-b548-ac3a24ac3082)

**Expected behavior**
These bars were stacked before

**Comment by mathieucarbou** [comment]
Duplicate of #730 .

The workaround:

```yaml
apex_config:
  chart:
    stackOnlyBar: false
```

is not working
