### ISSUE TITLE
Sensor history and data_generator output not displayed together

### ISSUE THREAD

**Issue by FireFury0** [RomRider/apexcharts-card#751]
**Describe the bug**
I am building a chart which plots both the historical carbon intensity of the electricity grid, and the forecast carbon intensity on the same chart.  The historical intensity comes from a sensor which updates its state every half hour, whereas the forecast intensity comes from the attributes of a pair of entities (one for today, another for tomorrow).  I'm using a data_generator to extract the forecasts from the entity attributes.

The card only shows a legend for all of the series, but only plots a graph for the historical data.  If you click the legend to hide the historical series, the forecast graphs suddenly become visible.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Carbon Intensity
  show_states: false
  colorize_states: true
  standard_format: true
apex_config:
  fill:
    type: gradient
    gradient:
      type: vertical
  stroke:
    curve: smooth
    dashArray:
      - 1
      - 1
  xaxis:
    labels:
      show: true
  yaxis:
    title:
      text: gCO2eq/kWh
    min: 0
    max: 500
  legend:
    show: true
  annotations:
    yaxis:
      - 'y': 100
        strokeDashArray: 0
        borderColor: '#00E396'
        label:
          borderColor: '#00E396'
          style:
            color: '#fff'
            background: '#00E396'
          text: Low
      - 'y': 150
        strokeDashArray: 0
        borderColor: '#FEB019'
        label:
          borderColor: '#FEB019'
          style:
            color: '#fff'
            background: '#FEB019'
          text: Moderate
      - 'y': 200
        strokeDashArray: 0
        borderColor: '#FF4560'
        label:
          borderColor: '#FF4560'
          style:
            color: '#fff'
            background: '#FF4560'
          text: High
graph_span: 72h
span:
  start: day
  offset: '-24h'
series:
  - entity: sensor.carbon_intensity_south_wales_current_rating
    name: Actual Intensity
    type: line
    stroke_width: 2
    extend_to: false
    show:
      extremas: true
      legend_value: false
  - entity: event.carbon_intensity_south_wales_current_day_rates
    name: Forecast Intensity
    type: area
    color: blue
    stroke_width: 2
    extend_to: false
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.rates.map(entry => {
        return {
          x: new Date(entry.from),
          y: entry.intensity_forecast
        };
      });
    unit: gCO2/kWh
  - entity: event.carbon_intensity_south_wales_next_day_rates
    name: Forecast Intensity
    type: area
    color: blue
    stroke_width: 2
    extend_to: false
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.rates.map(entry => {
        return {
          x: new Date(entry.from),
          y: entry.intensity_forecast
        };
      });
    unit: gCO2/kWh
```

**Expected behavior**
All of the series should be displayed at the same time

**Desktop (please complete the following information):**
Firefox and Home Assistant Android app

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android
 - Browser: Home assistant app
