### ISSUE TITLE
`color_threshold` colors are incorrect when also configuring the y-axis.

### ISSUE THREAD

**Issue by jftanner** [RomRider/apexcharts-card#763]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The gradient applied by `color_threshold` appears to be calculated over the range of sensor values, rather than the actual y-axis values. So they are correct if the y-axis is auto-generated, but incorrect if the y-axis scale is configured with a specific minimum, or if another series is also displayed. The screenshots below demonstrate this best.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: Humidity
  show_states: true
  colorize_states: true
graph_span: 24h
yaxis:
  - min: 0
    max: ~50
    decimals: 0
    align_to: 10
series:
  - entity: sensor.ams_humidity
    color: lightblue
    type: area
    stroke_width: 1
    color_threshold:
      - value: 0
        color: white
      - value: 15
        color: cyan
      - value: 30
        color: green
      - value: 30
        color: red
      - value: 40
        color: black
        opacity: 1
```

**Screenshots**
This screenshot shows it working correctly.
Note that `color_threshold` is set with overlapping values at 30, to create a hard division between green and red at 30.
The resulting gradient goes from a light green, through the hard transition to red, and up to a little bit of black.
![image](https://github.com/user-attachments/assets/bde70ce5-52ad-438d-b26e-d987dbd5ed8f)

This screenshot is the exact same data and configuration, except the a y-axis set for 0 to ~50.
You can see that it gets the exact same gradient applied. The hard division happens around 14 instead of 30, and the low-end colors don't appear.
![image](https://github.com/user-attachments/assets/0fb6dbaf-17af-4c11-acac-7a2b930ca405)

This screenshot adds another series which extends the axis, instead of configuring it manually.
Again the same gradient is applied. Notice that the hard division happens around 27.5.
![image](https://github.com/user-attachments/assets/e13c3801-08a7-4efb-8c6e-87d779f4b104)

**Expected behavior**
I expect the color gradient to match the configured values, regardless of y-axis scale.

**Desktop:**
 - Browser: Chrome
 - Version: 128.0.6613.84

**Smartphone:**
 - Device: Samsung Galaxy S21 Ultra
 - OS: Android 14
 - Browser: Home Assistant App
 - Version 2024.07.3-full

**Additional context**
_N/A_
