### ISSUE TITLE
brush experimental selection_span does not work

### ISSUE THREAD

**Issue by argoon38** [RomRider/apexcharts-card#764]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser
- [X ] I verified that I'm really running the lastest version in my browser console
- [ X] I checked if there is another issue opened with the same problem : ther was one, but is stale for 2 years

**Describe the bug**
The `selection_span` does not working when the lovelace is loaded. It is impossible to select any range.
Surprisingly, it works if the lovelace is loaded before the graph is shown. It is a workaround : I encapsulated the graph inside a conditional card and the graph is not shown initially. Then it is correct when he condition becomes true.

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Précipitations (heure)
  show_states: false
series:
  - entity: sensor.pluviometre_precipitation
    type: column
    group_by:
      func: diff
      duration: 1h
      fill: zero
    show:
      in_brush: true
span:
  end: hour
experimental:
  brush: true
brush:
  selection_span: 1day
graph_span: 7day
apex_config:
  plotOptions:
    bar:
      columnWidth: 95%
update_interval: 5s
```

**Screenshots**
If the graph is visible when page loads :
<img width="447" alt="Capture d’écran 2024-08-26 à 22 09 31" src="https://github.com/user-attachments/assets/ec3f43c1-ed7a-4c26-b48b-901d4eda6258">

Instead of:
<img width="446" alt="Capture d’écran 2024-08-26 à 22 09 54" src="https://github.com/user-attachments/assets/40f0870c-5712-406a-af69-7042c9739b1b">

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser chrome (mac or android), iphone
