### ISSUE TITLE
Y axis not scaling correctly

### ISSUE THREAD

**Issue by PalleRaa** [RomRider/apexcharts-card#773]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
In some of my charts the data goes out-of-bounds because the y-axis is not scaling to the lowest point in the data series.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
Example #1
```
type: custom:apexcharts-card
graph_span: 48h
header:
  show: true
  title: Kælder
  show_states: true
series:
  - entity: sensor.basement_wall_sensor_humidity
    type: line
    unit: '%'
    show:
      name_in_header: false
```

Example #2
```
type: custom:apexcharts-card
graph_span: 48h
header:
  show: true
  title: Toilet
  show_states: true
series:
  - entity: sensor.toilet_wall_sensor_temperature
    type: line
    unit: °C
    show:
      name_in_header: false
```

**Screenshots**
Example #1
![image](https://github.com/user-attachments/assets/ead6a1c1-ec08-46b0-a869-84375097cb18)
![image](https://github.com/user-attachments/assets/6afea9c0-f010-449a-b335-c3164aeea7d4)

Example #2
![image](https://github.com/user-attachments/assets/2a016688-81d7-4cdd-910c-88412754c39b)
![image](https://github.com/user-attachments/assets/ea922d5b-2bb3-4044-a349-ffd04f41d283)

**Expected behavior**
I expect the y-axis to scale correctly according to highest and lowest value of data

**Desktop (please complete the following information):**
Version 128.0.6613.85 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone12]
 - OS: iOS 17.6.1
 - Browser Stock Safari

**Additional context**
