### ISSUE TITLE
Series option stroke_dash is unknown

### ISSUE THREAD

**Issue by passuff** [RomRider/apexcharts-card#775]
I would like to use dashed lines and added "stroke_dash" as a series option. Unfortunately I receive the following error message:

`/// apexcharts-card version 2.0.4 /// value.series[5] is not a ChartCardSeriesExternalConfig value.series[5].stroke_dash is extraneous value.series[5].stroke_dash is extraneous`

My Code is as following:

```
type: custom:apexcharts-card
header:
  show: true
  title: Temperatur Anbau
  show_states: true
  colorize_states: false
series:
  - entity: sensor.INT0000006_1_ACTUAL_TEMPERATURE
    name: SZ OG
    color: orange
  - entity: sensor.INT0000005_1_ACTUAL_TEMPERATURE
    name: Wohnzimmer
    color: blue
  - entity: sensor.INT0000016_1_ACTUAL_TEMPERATURE
    name: Essküche
    color: red
  - entity: sensor.INT0000017_1_ACTUAL_TEMPERATURE
    name: SZ EG
    color: purple
  - entity: sensor.INT0000018_1_ACTUAL_TEMPERATURE
    name: Bad
    color: black
  - entity: sensor.INT0000006_1_SET_POINT_TEMPERATURE
    name: SZ OG
    color: orange
    stroke_width: 2
    curve: stepline
    stroke_dash: 0
  - entity: sensor.INT0000005_1_SET_POINT_TEMPERATURE
    name: Wohnzimmer
    color: blue
    stroke_width: 2
    curve: stepline
  - entity: sensor.INT0000016_1_SET_POINT_TEMPERATURE
    name: Essküche
    color: red
    stroke_width: 2
  - entity: sensor.INT0000017_1_SET_POINT_TEMPERATURE
    name: SZ EG
    color: purple
    stroke_width: 2
  - entity: sensor.INT0000018_1_SET_POINT_TEMPERATURE
    name: Bad
    color: black
    stroke_width: 2
```
