### ISSUE TITLE
chart type: column causes front end to freeze (becoming unresponsive wait or close page prompt appears)

### ISSUE THREAD

**Issue by Ben-oo7** [RomRider/apexcharts-card#776]
**Describe the bug**
using type: line no errors
using   type: column  becomes unresponsive. wait or close page prompt appears
This only happens once a sensor entity is selected
Data generator does no cause the issue

chart cause front end to freeze (becoming unresponsive wait or close page prompt appears) loop if wait

same on Brave , Chrome , Edge , Firefox Browsers

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used:

type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.shed_temp_temperature
    type: column
  - entity: sensor.shed_temp_humidity
    type: line

```


**Desktop (please complete the following information):**
 - Browser  Brave
 - Version  Chromium  128.0.6613.138

**Comment by catshapednoodles** [comment]
I also have this issue, but only after updating to HA 2024.10.0 (from 2024.9.3). Two of my Apex charts cards with column graphs freeze my tab or make it very slow. Other graph types I'm using are not affected.
This happens on Firefox and Chrome. On the mobile Home Assistant app (Android) I notice a slowdown when opening the dashboard with the column graph, but it doesn't freeze.

**Comment by Ferrox85** [comment]
Apexcharts is freezing the front end. I got a lot of this type of errors:

Error: Invalid value for <foreignObject> attribute height="NaN"
Error: Invalid value for <svg> attribute height="NaN"
Error: Problem parsing d="M 0 NaN"

It keeps on going.

running core 2024.10.1
frontend 20241002.2

**Comment by neuroboogie** [comment]
Same issue and it prevents Apex charts to be rendered correctly the first time. Graphs don't get scaled correctly and get cropped out. Happens in Safari, both on Mac and iPad at least. Have not seen it happen on mobile phone.

**Comment by neuroboogie** [comment]
Any insights on this? 

The bug practically prevents using apexchart-cards on any wall displays, since it occurs consistently with given browsers.

**Comment by scirocco-berlin** [comment]
Encountering same issue. Apexcharts is freezing upon any attempt to change series' type from _line_ to _column_. Adding data generator config doesn't resolve the bug.

`series:
  - entity: sensor.current_consumption_cost_adjusted
    type: column 
    data_generator: |
      return entity.map(e => [new Date(e.x).getTime(), e.y]);`
      
Entity states are working and generating numeric values.

Core         2025.1.2
Frontend  20250109.0

**Comment by lloydbayley** [comment]
I have a very similar problem where I can't use columns at all. If I do, every time it refreshes, everything freezes until it finishes. This is even whilst editing the page. It makes it completely unusable.
As I work-around, I changed from ```type: column``` to ```type: area```
No freezing/speed issues from then-on.

I also added
```
all_series_config:
  stroke_width: 1
```
at the top just before the header statement to reduce the width of the lines.

It's not quite as tidy/pretty as column view but it's a passable compromise and I hope this may be of use to someone...

**Comment by catshapednoodles** [comment]
I found out what the issue on my end was. I'm using a `data_generator` to transform the data of a sensor attribute. The attribute is a list of 24 items (usually), but sometimes it bugs out and puts it there 23 times so I end up with a big list of 552 items with a lot of duplication. When that happens, my apex chart freezes up.

The list also has multiple of the same entries, so my guess would be that the freeze has something to do with that those items are getting stacked on the same column. I haven't experimented with that, so I'm not sure.

My fix was to make a separate sensor that filters out all of the duplicate items, so I always end up with 24 items. Now I don't experience any freezes.

<details><summary>For reference, this is my configuration</summary>
<p>

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 24h
header:
  title: Today
  show: true
span:
  start: day
now:
  show: true
  label: Now
series:
  - entity: sensor.day_ahead_price
    type: column
    show:
      extremas: true
    float_precision: 3
    data_generator: |
      return entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["start"]).getTime() + 1500000, entity.attributes.raw_today[index]["value"]];
      });
    color_threshold:
      - value: 0.11
        color: "#0c6b9e"
      - value: 0.1429
        color: "#12A141"
      - value: 0.2
        color: "#79B92C"
      - value: 0.26
        color: "#C4D81D"
      - value: 0.32
        color: "#F3DC0C"
      - value: 0.38
        color: "#EFA51E"
      - value: 0.44
        color: "#E76821"
      - value: 0.5
        color: "#DC182F"
yaxis:
  - id: "1"
    min: ~0
    align_to: 0.1
    decimals: 2
    apex_config:
      title:
        text: €/kWh
      tickAmount: 4
      forceNiceScale: true
apex_config:
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        hour: HH:mm
    tooltip:
      enabled: false
  tooltip:
    x:
      format: HH:00
  plotOptions:
    bar:
      columnWidth: 80%

``` 
</p>
</details>
