### ISSUE TITLE
Add more-info action for slices of pie chart 

### ISSUE THREAD

**Issue by lucasimons** [RomRider/apexcharts-card#778]
**Checklist**
- [ x] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

I would like it to be possible to have tap_action and hold_action for the slices of the cake in order to then have the history via HA, now the slice is simply highlighted but it is not possible to perform any action.

![image](https://github.com/user-attachments/assets/f7f9233b-05dc-4d34-abf2-611231310ecf)

**Describe the solution you'd like**

```
type: custom:apexcharts-card
experimental:
  disable_config_validation: true
chart_type: donut
update_interval: 3s
header:
  show: false
  show_states: false
all_series_config:
  slice_actions:
    tap_action:
      action: more-info
```

**Additional context**
This card is amazing because i can make a small pie graph with several entities and i is also readable, i use it for daily and monthly energy and some time i need to view the HA history for that entity so it might be easier if you could click on the slice of the graph.
