### ISSUE TITLE
in_chart:false breaks yaxis scaling 

### ISSUE THREAD

**Issue by aredon** [RomRider/apexcharts-card#780]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
Setting in_chart: false in **any** series breaks y-axis scaling.
Normal:
![image](https://github.com/user-attachments/assets/142e2ea0-ee78-46d1-9858-3727af519ba5)
Broken:
![image](https://github.com/user-attachments/assets/ae784547-b457-4960-b15b-386d06ddf541)

**Version of the card**
Version: v2.1.2

**To Reproduce**
Change in_chart from true to false and remove the unneeded code on house_average_humidity. 
This is the configuration I used:
```yaml
type: custom:apexcharts-card
update_interval: 1min
apex_config:
  chart:
    height: 120px
  legend:
    show: false
  xaxis:
    tooltip:
      enabled: false
    labels:
      show: false
    axisBorder:
      show: false
    axisTicks:
      show: false
  grid:
    borderColor: rgba(0,0,0,0)
layout: minimal
experimental:
  color_threshold: true
show:
  last_updated: false
graph_span: 3weeks
span:
  end: day
header:
  show: true
  title: ' '
  show_states: true
  colorize_states: true
series:
  - entity: sensor.upstairs_humidity
    type: area
    stroke_width: 1
    show:
      extremas: false
      in_header: false
    color: dodgerblue
    opacity: 0.05
    yaxis_id: first
    statistics:
      type: max
      period: hour
    group_by:
      func: max
      duration: 1day
  - entity: sensor.basement_humidity
    type: area
    stroke_width: 1
    show:
      extremas: false
      in_header: false
    color: purple
    opacity: 0.05
    yaxis_id: first
    statistics:
      type: max
      period: hour
    group_by:
      func: max
      duration: 1day
  - entity: sensor.house_average_humidity
    type: line
    stroke_width: 0
    show:
      extremas: false
      in_chart: true
    color: skyblue
    opacity: 0.05
    yaxis_id: first
    group_by:
      func: last
      duration: 1day
  - entity: sensor.upstairs_average_temperature
    type: line
    show:
      extremas: true
    color: lightgreen
    opacity: 1
    yaxis_id: second
    statistics:
      type: max
      period: hour
    group_by:
      func: max
      duration: 1day
  - entity: sensor.basement_average_temperature
    type: line
    show:
      extremas: false
      in_header: false
    color: darkgreen
    opacity: 1
    yaxis_id: second
    statistics:
      type: max
      period: hour
    group_by:
      func: max
      duration: 1day
  - entity: sensor.outdoor_temperature
    type: line
    show:
      extremas: true
      header_color_threshold: true
      in_header: false
    color: orange
    opacity: 0.75
    yaxis_id: second
    group_by:
      func: max
      duration: 1day
    color_threshold:
      - value: 20
        color: dodgerblue
      - value: 40
        color: darkcyan
      - value: 60
        color: limegreen
      - value: 80
        color: orangered
      - value: 100
        color: darkred
yaxis:
  - id: first
    show: false
  - id: second
    opposite: true
    show: false

```

**Expected behavior**
For something that isn't displayed on the chart to have no impact on said chart. 

**Desktop (please complete the following information):**
 - Firefox and Chrome

**Additional context**
Issue persists across devices.
