### ISSUE TITLE
Stacked Chards doesn't work if any modifiers applied

### ISSUE THREAD

**Issue by phoniclynx** [RomRider/apexcharts-card#790]
**Checklist**
- [* ] I updated the card to the latest version available
- [ *] I cleared the cache of my browser
- [ *] I verified that I'm really running the lastest version in my browser console
- [* ] I checked if there is another issue opened with the same problem - reporting differently, but same, but different

**Describe the bug**
Whenever you modify the graph and ask for stacking to be implemented it breaks the stacking of the graphs.

ie if you modify the yaxis command to remove the values on the side, or ask it to remove the values in the legend or apply a min or max value it fails to render the stack at all. 

When producing a stacked graph the memory that is being used in Chrome and Firefox skyrockets so much that it often causes the tab to crash. Over 1.5GB up to 2.5GB per tab.

**Version of the card**
Version:2.12

Makes it impossible to edit the page by the GUI editor as it simply hangs the page whilst it reloads, uses bup the memory and crashes.

**Comment by Elgaker** [comment]
I think that I have the same issue. 

Updated from version 2.0.4 to 2.1.2 - this breaks stacked charts that have been working for a long time. 

Tried to roll back:
- 2.1.1 Still broken
- 2.1.0 Still broken
- 2.0.4 Works again!

2.0.4
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/e74dd8bd-d786-427f-b13f-5d68c6b9b5c7">

2.1.2
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/a5a81b5e-cd9f-4856-9ea7-ee6533e3389e">

**Comment by phoniclynx** [comment]
When is this going to get fixed? It looks like it's been a bug that's been around for some time now and no updates in sight!

**Comment by phoniclynx** [comment]
Still not been fixed

18 Dec 2024 10:41:24 github-actions[bot] ***@***.***>:

**Comment by phoniclynx** [comment]
Why are we waiting, we are suffocating

18 Feb 2025 13:02:09 github-actions[bot] ***@***.***>:

**Comment by vingerha** [comment]
Have you checked v 2.2.3 and if still the case ... please provide well-formatted (!) and preferable small piece of code for allowing reproduction

**Comment by Elgaker** [comment]
@vingerha, I'll check this weekend 👍

**Comment by Elgaker** [comment]
@vingerha, I think that I have isolated the problem. 

First:
* Upgraded from 2.0.4 to 2.2.3 and cleared cache. 
* Problem remains. 
* No console errors

Tried to simplify the configuration as much as possible and then removed elements from the configuration one at a time. It is the yaxis-block that creates the problem. 

Non-working code:
```
type: custom:apexcharts-card
stacked: true
all_series_config:
  stroke_width: 1
apex_config:
  chart:
    height: 250px
span:
  start: day
yaxis:
  - id: first
    min: 0
series:
  - entity: sensor.kulladal_energiforbrukning_ovrigt_energy_per_hour
    name: One
    type: column
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_varmepump_energy_per_hour
    name: Two
    type: column
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_energiforbrukning_lagprio_energy_per_hour
    name: Three
    type: column
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_batterilager_consumption_energy_per_hour
    name: Four
    type: column
    group_by:
      func: max
      duration: 60min

```

Generates this incorrect graph

![Image](https://github.com/user-attachments/assets/ba78c04d-2a28-43d2-a0f0-d7e0cd7bb4e1)

Then removed the yaxis-block and **now it works**. 

Working code:
```
type: custom:apexcharts-card
stacked: true
all_series_config:
  stroke_width: 1
apex_config:
  chart:
    height: 250px
span:
  start: day
series:
  - entity: sensor.kulladal_energiforbrukning_ovrigt_energy_per_hour
    name: One
    type: column
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_varmepump_energy_per_hour
    name: Two
    type: column
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_energiforbrukning_lagprio_energy_per_hour
    name: Three
    type: column
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_batterilager_consumption_energy_per_hour
    name: Four
    type: column
    group_by:
      func: max
      duration: 60min
```
Generates a correct looking graph:

<img width="1421" height="278" alt="Image" src="https://github.com/user-attachments/assets/139ef51c-ee51-45b9-b284-7e7d7b77088f" />

Hopes this helps for isolating the problem!

**Comment by vingerha** [comment]
I could reproduce it and yaxis is indeed a tricky thing. If you only have 1 then best to place it in the apex_config. 
Reminiscing: the root-level yaxis has (I believe) the goal to serve multi-yaxis and for stacked graphs this will not work at all.

**Comment by Elgaker** [comment]
Great! In the original graph (before simplifying it for testing and posting reasons) I have 2 y-axis and that is why I have to use the root-level y-axis.

**Comment by vingerha** [comment]
not sure if 'great' :)
When using multi-yaxis from root, try adding ``stack_group: something``` to the entities... tweaking

**Comment by Elgaker** [comment]
Thanks @vingerha, adding stack_group seems to fix the problem. I missed that this was added in 2.1.0. From my point of view we can close this issue. 

Here is an update to my code that works. 
```
type: custom:apexcharts-card
stacked: true
all_series_config:
  stroke_width: 1
apex_config:
  chart:
    height: 250px
span:
  start: day
yaxis:
  - id: first
    min: 0
series:
  - entity: sensor.kulladal_energiforbrukning_ovrigt_energy_per_hour
    name: One
    type: column
    stack_group: A
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_varmepump_energy_per_hour
    name: Two
    type: column
    stack_group: A
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_energiforbrukning_lagprio_energy_per_hour
    name: Three
    type: column
    stack_group: A
    group_by:
      func: max
      duration: 60min
  - entity: sensor.kulladal_batterilager_consumption_energy_per_hour
    name: Four
    type: column
    stack_group: A
    group_by:
      func: max
      duration: 60min
```
 Also, applied it to my more complex graph and that works now as well.

<img width="1390" height="256" alt="Image" src="https://github.com/user-attachments/assets/00afa8ff-4e8f-4891-92c2-20b06439f10a" />
