### ISSUE TITLE
vision impaired need the same y axis label formating as for the x axis (which is already available) - or I have made a mistake

### ISSUE THREAD

**Issue by typxxi** [RomRider/apexcharts-card#795]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
maybe, maybe I had mad a typo in the yaxis trials but I checked that multiple times and had gotten no error, but it did not work due to missing support I guess
This did not work, but also showed no error in the card
```
apex_config:
  yaxis:
    labels:
      style:
        colors: black
        fontSize: 16px
        fontWeight: bold
```

**Describe the solution you'd like**
let us format the y-axis label especially for **`fontsize`** and **`fontweight`** the same way as it works for the x-axis already
with 
```
apex_config:
  xaxis:
    labels:
      style:
        colors: black
        fontSize: 16px
        fontWeight: bold
```

**Describe alternatives you've considered**
if your vision / sight is limited as for my family members there are no other options than using a magnifying lense / glass on a monitor.
But that is horrible. apex chart itself supports already these features.

**Additional context**
Here you can see the big difference for an impaired at least.
the key figure is the price shown on the y axis scale and the figures from 10 to 50 are tiny and I can not change those.
![image](https://github.com/user-attachments/assets/f3343f74-0fd2-4ab0-8daa-b561eb72dc56)

Just compare the readability of 16 versus 10 / 20 & 30 and you can see the importance of the request. I had learned from someone else how to check the genuine apex chart side and try it out . 
That way I had found the solution for the labels on the x-axis, but of same importance is the y axis now. 
![image](https://github.com/user-attachments/assets/c3a0303f-0635-47d3-8ecc-6647061bf1dd)

**Comment by typxxi** [comment]
HERE is the solution for all those searching for the same topic y-axis font formating

it is a kind of easy fix and only slightly different than my first try mentioned above.


```
yaxis:
  - id: first
    min: 0
    max: 25000
    decimals: 0
    apex_config:
      tickAmount: 5
      labels:
        style:
          colors: black
          fontSize: 16px
          fontWeight: normal
```

this did not work cause it is part of the basic settings of the yaxis and then within that there is the apex_config with the amount of ticks and labels 

```
apex_config:
  yaxis:
    labels:
      style:
        colors: black
        fontSize: 16px
        fontWeight: bold
```

So it has been fully solved, the y axis figures have the same (and increased) fontsize the x-axis figures had before.

![Image](https://github.com/user-attachments/assets/182975c7-6dd7-49f9-89f9-b3a5b6b9c2b2)
