### ISSUE TITLE
Chart header history becomes white. 

### ISSUE THREAD

**Issue by Krolik1988** [RomRider/apexcharts-card#801]
**Describe the bug**
If I use HTML color code, then header color become white and chart color applies.

**Version of the card**
Version: 2.1.2

**To Reproduce**
Try to use HTML color code in series block instead of name "yellow" . As Example:
color: cb7425

This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: XMR
  show_states: true
  colorize_states: true
update_interval: 2s
graph_span: 3d
experimental:
  brush: true
apex_config:
  tooltip:
    enabled: true
  yaxis:
    - shown: true
      labels:
        style:
          colors: white
          fontSize: 14px
      forceNiceScale: true
    - show: true
      opposite: true
      decimalsInFloat: 0
  xaxis:
    axisBorder:
      show: true
    labels:
      style:
        fontSize: 12px
    chart:
      height: auto
    gird:
      show: false
    legend:
      show: true
    dataLabels:
      enabled: true
    stroke:
      width: 1
series:
  - entity: sensor.xmr_balance
    type: line
    fill_raw: last
    float_precision: 6
    color: cb7425
    data_generator: ""
    group_by:
      duration: 10min
      func: avg
    show:
      in_brush: true
      in_chart: true
  - entity: sensor.xmr_hashrate
    type: line
    fill_raw: last
    data_generator: ""
    show:
      in_brush: false
      in_chart: false
  - entity: sensor.xmr_hashes
    type: line
    fill_raw: last
    data_generator: ""

```

**Screenshots**
![Screenshot from 2024-10-22 03-56-36](https://github.com/user-attachments/assets/68d6a6d2-6749-4dd8-8951-7580cc48c6c8)
![Screenshot from 2024-10-22 03-59-59](https://github.com/user-attachments/assets/8386249a-f7c1-4bf2-acf9-5ae2873f043b)

**Expected behavior**
Header legend color changes color to chosen.

**Desktop (please complete the following information):**
 - Firefox
 - 131.0.3 (64-bit)

Thanks you, and have a good day.
