### ISSUE TITLE
 Y_axis are hidden when the series are hidden, even if muliple series map to the same yaxis_id and only one series gets hidden.

### ISSUE THREAD

**Issue by flrnwrzl** [RomRider/apexcharts-card#805]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

Hello, I am using Apexchart all over my dashboards but now i got to a limit.
I have 5 entities in one graph. 4 in kW and 1 in %. i took a very carefull look on it and every unit is correct.
But on the display side i have following bug:
Is soon i disable entity one, the axis on the left goes away and the other 3 entities with also kW are there without the y axis.

Hope its clear what i mean. please take a look. thanks! :grinning:s.

**To Reproduce**
This is the configuration I used:

```
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
stacked: false
show:
  last_updated: true
now:
  show: true
  color: "#87ceeb"
  label: Jetzt
header:
  standard_format: true
  show: false
  show_states: false
  colorize_states: false
apex_config:
  legend:
    show: true
  yaxis:
    - id: one
      decimalsInFloat: 0
      show: true
      title:
        text: kW
    - id: two
      decimalsInFloat: 0
      show: false
      title:
        text: kW
    - id: three
      decimalsInFloat: 0
      show: false
      title:
        text: kW
    - id: four
      decimalsInFloat: 0
      show: false
      title:
        text: kW
    - id: five
      decimalsInFloat: 0
      show: true
      opposite: true
      min: 0
      max: 100
      title:
        text: "%"
  xaxis:
    tooltip:
      enabled: false
  grid:
    borderColor: rgba(112, 135, 164, 0.1)
  labels:
    style:
      fontSize: 15px
      fontWeight: 500
      fontColor: black
  tooltip:
    enabled: true
    shared: false
    fillSeriesColor: false
  fill:
    type: gradient
    gradient:
      type: vertical
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.6
      opacityTo: 0.1
      stops:
        - 0
        - 100
all_series_config:
  type: area
  extend_to: false
  stroke_width: 2
  opacity: 1
  group_by:
    func: avg
    duration: 1h
series:
  - entity: sensor.inverter_1_mppt_total_input_power
    name: PV Prod
    yaxis_id: one
    color: "#f4d043"
  - entity: sensor.batterychargevalue
    name: Ladeleistung
    yaxis_id: two
    color: "#98abed"
  - entity: sensor.batterydischagevalue
    name: Entladeleistung
    yaxis_id: three
    color: "#2062d2"
  - entity: sensor.inverter_1_active_power
    name: Leistungsaufnahme
    yaxis_id: four
    color: "#fe5800"
  - entity: sensor.battery_1_battery_state_of_charge_soc
    name: Batterie
    yaxis_id: five
    color: "#49A47D"
card_mod:
  style: |
    ha-card {
    background: none;

    border: solid grey 1px;
    border-radius: 25px;
    margin-top: 10px;
    margin-bottom: 10px;
    }
```

![image](https://github.com/user-attachments/assets/e4862c94-c5a3-4eb5-8a90-9d475561cd5a)

**Expected behavior**
They Y axis should be visible on every entity, when a other is hidden.
