### ISSUE TITLE
Question: Select the top three values from a statistics sensor.

### ISSUE THREAD

**Issue by robinostlund** [RomRider/apexcharts-card#809]
Hi,
I have been googling alot and is stuck so i am trying here to see if someone has an idea on how i can do this :) 
I would like to be able to only show the top three values from this entity :
```
 - entity: sensor.ellevio_effect_fee_import_power
    name: Average Hourly Usage
    unit: kW
    type: column
    yaxis_id: kw
    show:
      datalabels: true
      extremas: false
      legend_value: false
    color: cyan
    color_threshold:
      - value: 0
        color: Lime
      - value: 2
        color: Green
      - value: 4
        color: Yellow
      - value: 8
        color: Red
    statistics:
      type: mean
      period: hour
      align: start
```

So currently it shows every hour, but i would like to only show the top three values from it. Is it someone that have done that in the past? guess it should be possible with the data_generator somehow? What is important is that it must be possible to get the values from statistics as i will change the period to days and graph span to month later on.

Thanks
