### ISSUE TITLE
extremas does not seem to be working

### ISSUE THREAD

**Issue by jm-cook** [RomRider/apexcharts-card#819]
**Checklist**
- [x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
I use the `extremas: time` setting and get completely unexpected results:

![image](https://github.com/user-attachments/assets/07dcc2ae-4368-48b3-93ce-f3e2a725a96c)

In the figure the extremas have been plotted as values that are clearly not max/min values

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 36h
span:
  offset: +24h
now:
  show: true
  label: Now
header:
  show: true
  title: Tide
  show_states: true
series:
  - entity: sensor.home_tide_main
    name: Prediction
    show:
      extremas: time
      in_header: before_now
      legend_value: false
    data_generator: |
      return entity.attributes.data.map((entry) => {
        return [new Date(entry.datetime).getTime(), entry.prediction];
      });
  - entity: sensor.home_tide_main
    name: Forecast
    show:
      in_header: before_now
      legend_value: false
    data_generator: |
      return entity.attributes.data.map((entry) => {
        return [new Date(entry.datetime).getTime(), entry.forecast];
      });
  - entity: sensor.home_tide_main
    name: Observation
    show:
      in_header: before_now
      legend_value: false
    data_generator: |
      return entity.attributes.data.map((entry) => {
        return [new Date(entry.datetime).getTime(), entry.observation];
      });

```

**Screenshots**

**Expected behavior**
I would expect the max/min values  for the orange curve to be the top and bottom of the curve.
 
**Desktop (please complete the following information):**
 - Browser chrome
 - VersionVersion 122.0.6261.95 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

This is the sensor value in home assistant (obtained from the norwegiantide  custom integration)

```yaml
integration: norwegiantide
attribution: Data from ©Kartverket (www.kartverket.no)
place: Home
latitude: "59.943852"
longitude: "5.483648"
location_details:
  name: Vistvikevågen
  code: VIS
  delay: "5"
  factor: "0.99"
  obsname: Bergen
  obscode: BGO
  descr: >-
    Tidevann justert med 5 minutter og høydefaktor på 0,99 fra Vistvikevågen og
    observert værbidrag fra Bergen
ebb_flow: flow
ebbing: false
flowing: true
tide_state: flow
next_tide:
  value: "111.1"
  time: "2024-11-25T18:48:00+01:00"
  flag: high
  timefromlast: "5:49:00"
time_to_next_tide: 3.7
next_tide_low:
  value: "59.0"
  time: "2024-11-26T01:29:00+01:00"
  flag: low
  timefromlast: "6:41:00"
time_to_next_low: 10.4
next_tide_high:
  value: "111.1"
  time: "2024-11-25T18:48:00+01:00"
  flag: high
  timefromlast: "5:49:00"
time_to_next_high: 3.7
currentdata_prediction: "85.9"
currentdata_forecast: "128.9"
currentdata_observation: null
currentobservation_weathereffect: "39.3"
data:
  - datetime: "2024-11-25T03:10:00+01:00"
    prediction: "80.9"
    forecast: null
    observation: "118.8"
  - datetime: "2024-11-25T03:20:00+01:00"
    prediction: "82.9"
    forecast: null
    observation: "121.5"
  - datetime: "2024-11-25T03:30:00+01:00"
    prediction: "84.9"
    forecast: null
    observation: "124.0"
  - datetime: "2024-11-25T03:40:00+01:00"
    prediction: "86.9"
    forecast: null
    observation: "126.4"
  - datetime: "2024-11-25T03:50:00+01:00"
    prediction: "88.9"
    forecast: null
    observation: "129.0"
  - datetime: "2024-11-25T04:00:00+01:00"
    prediction: "90.9"
    forecast: "132.9"
    observation: "131.5"
  - datetime: "2024-11-25T04:10:00+01:00"
    prediction: "92.8"
    forecast: "135.8"
    observation: "134.1"
  - datetime: "2024-11-25T04:20:00+01:00"
    prediction: "94.7"
    forecast: "137.7"
    observation: "136.6"
  - datetime: "2024-11-25T04:30:00+01:00"
    prediction: "96.5"
    forecast: "139.5"
    observation: "139.3"
  - datetime: "2024-11-25T04:40:00+01:00"
    prediction: "98.2"
    forecast: "141.2"
    observation: "141.7"
  - datetime: "2024-11-25T04:50:00+01:00"
    prediction: "99.8"
    forecast: "141.8"
    observation: "143.6"
  - datetime: "2024-11-25T05:00:00+01:00"
    prediction: "101.3"
    forecast: "144.3"
    observation: "145.2"
  - datetime: "2024-11-25T05:10:00+01:00"
    prediction: "102.7"
    forecast: "146.7"
    observation: "147.0"
  - datetime: "2024-11-25T05:20:00+01:00"
    prediction: "104.0"
    forecast: "148.0"
    observation: "148.8"
  - datetime: "2024-11-25T05:30:00+01:00"
    prediction: "105.2"
    forecast: "149.2"
    observation: "149.9"
  - datetime: "2024-11-25T05:40:00+01:00"
    prediction: "106.2"
    forecast: "150.2"
    observation: "150.3"
  - datetime: "2024-11-25T05:50:00+01:00"
    prediction: "107.0"
    forecast: "151.0"
    observation: "150.3"
  - datetime: "2024-11-25T06:00:00+01:00"
    prediction: "107.7"
    forecast: "151.7"
    observation: "150.3"
  - datetime: "2024-11-25T06:10:00+01:00"
    prediction: "108.3"
    forecast: "152.3"
    observation: "150.9"
  - datetime: "2024-11-25T06:20:00+01:00"
    prediction: "108.7"
    forecast: "152.7"
    observation: "151.7"
  - datetime: "2024-11-25T06:30:00+01:00"
    prediction: "108.9"
    forecast: "153.9"
    observation: "152.2"
  - datetime: "2024-11-25T06:40:00+01:00"
    prediction: "109.0"
    forecast: "153.0"
    observation: "152.2"
  - datetime: "2024-11-25T06:50:00+01:00"
    prediction: "108.9"
    forecast: "153.9"
    observation: "152.1"
  - datetime: "2024-11-25T07:00:00+01:00"
    prediction: "108.6"
    forecast: "153.6"
    observation: "152.4"
  - datetime: "2024-11-25T07:10:00+01:00"
    prediction: "108.2"
    forecast: "153.2"
    observation: "152.8"
  - datetime: "2024-11-25T07:20:00+01:00"
    prediction: "107.7"
    forecast: "152.7"
    observation: "153.2"
  - datetime: "2024-11-25T07:30:00+01:00"
    prediction: "107.0"
    forecast: "152.0"
    observation: "153.5"
  - datetime: "2024-11-25T07:40:00+01:00"
    prediction: "106.2"
    forecast: "151.2"
    observation: "153.5"
  - datetime: "2024-11-25T07:50:00+01:00"
    prediction: "105.2"
    forecast: "151.2"
    observation: "152.6"
  - datetime: "2024-11-25T08:00:00+01:00"
    prediction: "104.2"
    forecast: "150.2"
    observation: "151.5"
  - datetime: "2024-11-25T08:10:00+01:00"
    prediction: "103.0"
    forecast: "148.0"
    observation: "150.4"
  - datetime: "2024-11-25T08:20:00+01:00"
    prediction: "101.8"
    forecast: "146.8"
    observation: "149.8"
  - datetime: "2024-11-25T08:30:00+01:00"
    prediction: "100.6"
    forecast: "145.6"
    observation: "148.9"
  - datetime: "2024-11-25T08:40:00+01:00"
    prediction: "99.2"
    forecast: "144.2"
    observation: "147.9"
  - datetime: "2024-11-25T08:50:00+01:00"
    prediction: "97.9"
    forecast: "143.9"
    observation: "146.5"
  - datetime: "2024-11-25T09:00:00+01:00"
    prediction: "96.5"
    forecast: "142.5"
    observation: "145.2"
  - datetime: "2024-11-25T09:10:00+01:00"
    prediction: "95.2"
    forecast: "142.2"
    observation: "144.0"
  - datetime: "2024-11-25T09:20:00+01:00"
    prediction: "93.8"
    forecast: "141.8"
    observation: "143.1"
  - datetime: "2024-11-25T09:30:00+01:00"
    prediction: "92.5"
    forecast: "140.5"
    observation: "142.3"
  - datetime: "2024-11-25T09:40:00+01:00"
    prediction: "91.2"
    forecast: "140.2"
    observation: "141.4"
  - datetime: "2024-11-25T09:50:00+01:00"
    prediction: "90.0"
    forecast: "138.0"
    observation: "140.3"
  - datetime: "2024-11-25T10:00:00+01:00"
    prediction: "88.8"
    forecast: "136.8"
    observation: "139.2"
  - datetime: "2024-11-25T10:10:00+01:00"
    prediction: "87.7"
    forecast: "136.7"
    observation: "138.7"
  - datetime: "2024-11-25T10:20:00+01:00"
    prediction: "86.6"
    forecast: "135.6"
    observation: "137.7"
  - datetime: "2024-11-25T10:30:00+01:00"
    prediction: "85.5"
    forecast: "134.5"
    observation: "137.1"
  - datetime: "2024-11-25T10:40:00+01:00"
    prediction: "84.5"
    forecast: "133.5"
    observation: "135.9"
  - datetime: "2024-11-25T10:50:00+01:00"
    prediction: "83.6"
    forecast: "133.6"
    observation: "134.7"
  - datetime: "2024-11-25T11:00:00+01:00"
    prediction: "82.7"
    forecast: "132.7"
    observation: "133.4"
  - datetime: "2024-11-25T11:10:00+01:00"
    prediction: "81.9"
    forecast: "131.9"
    observation: "132.3"
  - datetime: "2024-11-25T11:20:00+01:00"
    prediction: "81.1"
    forecast: "130.1"
    observation: "131.1"
  - datetime: "2024-11-25T11:30:00+01:00"
    prediction: "80.3"
    forecast: "130.3"
    observation: "129.9"
  - datetime: "2024-11-25T11:40:00+01:00"
    prediction: "79.7"
    forecast: "128.7"
    observation: "128.5"
  - datetime: "2024-11-25T11:50:00+01:00"
    prediction: "79.0"
    forecast: "128.0"
    observation: "127.1"
  - datetime: "2024-11-25T12:00:00+01:00"
    prediction: "78.5"
    forecast: "125.5"
    observation: "125.7"
  - datetime: "2024-11-25T12:10:00+01:00"
    prediction: "78.0"
    forecast: "125.0"
    observation: "124.3"
  - datetime: "2024-11-25T12:20:00+01:00"
    prediction: "77.5"
    forecast: "124.5"
    observation: "123.0"
  - datetime: "2024-11-25T12:30:00+01:00"
    prediction: "77.2"
    forecast: "123.2"
    observation: "121.7"
  - datetime: "2024-11-25T12:40:00+01:00"
    prediction: "76.9"
    forecast: "121.9"
    observation: "120.5"
  - datetime: "2024-11-25T12:50:00+01:00"
    prediction: "76.8"
    forecast: "121.8"
    observation: "119.2"
  - datetime: "2024-11-25T13:00:00+01:00"
    prediction: "76.7"
    forecast: "121.7"
    observation: "117.7"
  - datetime: "2024-11-25T13:10:00+01:00"
    prediction: "76.8"
    forecast: "121.8"
    observation: "117.0"
  - datetime: "2024-11-25T13:20:00+01:00"
    prediction: "77.0"
    forecast: "121.0"
    observation: "116.6"
  - datetime: "2024-11-25T13:30:00+01:00"
    prediction: "77.3"
    forecast: "122.3"
    observation: "116.7"
  - datetime: "2024-11-25T13:40:00+01:00"
    prediction: "77.8"
    forecast: "121.8"
    observation: "117.1"
  - datetime: "2024-11-25T13:50:00+01:00"
    prediction: "78.4"
    forecast: "122.4"
    observation: "117.8"
  - datetime: "2024-11-25T14:00:00+01:00"
    prediction: "79.1"
    forecast: "122.1"
    observation: "118.2"
  - datetime: "2024-11-25T14:10:00+01:00"
    prediction: "80.0"
    forecast: "123.0"
    observation: "119.1"
  - datetime: "2024-11-25T14:20:00+01:00"
    prediction: "80.9"
    forecast: "123.9"
    observation: "120.4"
  - datetime: "2024-11-25T14:30:00+01:00"
    prediction: "82.0"
    forecast: "125.0"
    observation: "121.7"
  - datetime: "2024-11-25T14:40:00+01:00"
    prediction: "83.2"
    forecast: "126.2"
    observation: "122.7"
  - datetime: "2024-11-25T14:50:00+01:00"
    prediction: "84.5"
    forecast: "127.5"
    observation: "123.8"
  - datetime: "2024-11-25T15:00:00+01:00"
    prediction: "85.9"
    forecast: "128.9"
    observation: null
  - datetime: "2024-11-25T15:10:00+01:00"
    prediction: "87.3"
    forecast: "129.3"
    observation: null
  - datetime: "2024-11-25T15:20:00+01:00"
    prediction: "88.8"
    forecast: "130.8"
    observation: null
  - datetime: "2024-11-25T15:30:00+01:00"
    prediction: "90.4"
    forecast: "131.4"
    observation: null
  - datetime: "2024-11-25T15:40:00+01:00"
    prediction: "91.9"
    forecast: "133.9"
    observation: null
  - datetime: "2024-11-25T15:50:00+01:00"
    prediction: "93.5"
    forecast: "135.5"
    observation: null
  - datetime: "2024-11-25T16:00:00+01:00"
    prediction: "95.0"
    forecast: "138.0"
    observation: null
  - datetime: "2024-11-25T16:10:00+01:00"
    prediction: "96.6"
    forecast: "139.6"
    observation: null
  - datetime: "2024-11-25T16:20:00+01:00"
    prediction: "98.1"
    forecast: "141.1"
    observation: null
  - datetime: "2024-11-25T16:30:00+01:00"
    prediction: "99.5"
    forecast: "142.5"
    observation: null
  - datetime: "2024-11-25T16:40:00+01:00"
    prediction: "101.0"
    forecast: "143.0"
    observation: null
  - datetime: "2024-11-25T16:50:00+01:00"
    prediction: "102.3"
    forecast: "144.3"
    observation: null
  - datetime: "2024-11-25T17:00:00+01:00"
    prediction: "103.6"
    forecast: "145.6"
    observation: null
  - datetime: "2024-11-25T17:10:00+01:00"
    prediction: "104.8"
    forecast: "145.8"
    observation: null
  - datetime: "2024-11-25T17:20:00+01:00"
    prediction: "105.9"
    forecast: "145.9"
    observation: null
  - datetime: "2024-11-25T17:30:00+01:00"
    prediction: "106.9"
    forecast: "146.9"
    observation: null
  - datetime: "2024-11-25T17:40:00+01:00"
    prediction: "107.9"
    forecast: "147.9"
    observation: null
  - datetime: "2024-11-25T17:50:00+01:00"
    prediction: "108.7"
    forecast: "147.7"
    observation: null
  - datetime: "2024-11-25T18:00:00+01:00"
    prediction: "109.4"
    forecast: "148.4"
    observation: null
  - datetime: "2024-11-25T18:10:00+01:00"
    prediction: "110.0"
    forecast: "149.0"
    observation: null
  - datetime: "2024-11-25T18:20:00+01:00"
    prediction: "110.5"
    forecast: "148.5"
    observation: null
  - datetime: "2024-11-25T18:30:00+01:00"
    prediction: "110.8"
    forecast: "148.8"
    observation: null
  - datetime: "2024-11-25T18:40:00+01:00"
    prediction: "111.0"
    forecast: "148.0"
    observation: null
  - datetime: "2024-11-25T18:50:00+01:00"
    prediction: "111.1"
    forecast: "147.1"
    observation: null
  - datetime: "2024-11-25T19:00:00+01:00"
    prediction: "111.0"
    forecast: "146.0"
    observation: null
  - datetime: "2024-11-25T19:10:00+01:00"
    prediction: "110.7"
    forecast: "145.7"
    observation: null
  - datetime: "2024-11-25T19:20:00+01:00"
    prediction: "110.3"
    forecast: "144.3"
    observation: null
  - datetime: "2024-11-25T19:30:00+01:00"
    prediction: "109.7"
    forecast: "143.7"
    observation: null
  - datetime: "2024-11-25T19:40:00+01:00"
    prediction: "108.9"
    forecast: "142.9"
    observation: null
  - datetime: "2024-11-25T19:50:00+01:00"
    prediction: "107.9"
    forecast: "141.9"
    observation: null
  - datetime: "2024-11-25T20:00:00+01:00"
    prediction: "106.9"
    forecast: "139.9"
    observation: null
  - datetime: "2024-11-25T20:10:00+01:00"
    prediction: "105.6"
    forecast: "138.6"
    observation: null
  - datetime: "2024-11-25T20:20:00+01:00"
    prediction: "104.2"
    forecast: "137.2"
    observation: null
  - datetime: "2024-11-25T20:30:00+01:00"
    prediction: "102.7"
    forecast: "134.7"
    observation: null
  - datetime: "2024-11-25T20:40:00+01:00"
    prediction: "101.1"
    forecast: "133.1"
    observation: null
  - datetime: "2024-11-25T20:50:00+01:00"
    prediction: "99.4"
    forecast: "130.4"
    observation: null
  - datetime: "2024-11-25T21:00:00+01:00"
    prediction: "97.5"
    forecast: "127.5"
    observation: null
  - datetime: "2024-11-25T21:10:00+01:00"
    prediction: "95.7"
    forecast: "124.7"
    observation: null
  - datetime: "2024-11-25T21:20:00+01:00"
    prediction: "93.7"
    forecast: "121.7"
    observation: null
  - datetime: "2024-11-25T21:30:00+01:00"
    prediction: "91.8"
    forecast: "120.8"
    observation: null
  - datetime: "2024-11-25T21:40:00+01:00"
    prediction: "89.8"
    forecast: "117.8"
    observation: null
  - datetime: "2024-11-25T21:50:00+01:00"
    prediction: "87.8"
    forecast: "115.8"
    observation: null
  - datetime: "2024-11-25T22:00:00+01:00"
    prediction: "85.8"
    forecast: "113.8"
    observation: null
  - datetime: "2024-11-25T22:10:00+01:00"
    prediction: "83.8"
    forecast: "111.8"
    observation: null
  - datetime: "2024-11-25T22:20:00+01:00"
    prediction: "81.9"
    forecast: "109.9"
    observation: null
  - datetime: "2024-11-25T22:30:00+01:00"
    prediction: "80.0"
    forecast: "108.0"
    observation: null
  - datetime: "2024-11-25T22:40:00+01:00"
    prediction: "78.2"
    forecast: "106.2"
    observation: null
  - datetime: "2024-11-25T22:50:00+01:00"
    prediction: "76.4"
    forecast: "104.4"
    observation: null
  - datetime: "2024-11-25T23:00:00+01:00"
    prediction: "74.6"
    forecast: "103.6"
    observation: null
  - datetime: "2024-11-25T23:10:00+01:00"
    prediction: "72.9"
    forecast: "100.9"
    observation: null
  - datetime: "2024-11-25T23:20:00+01:00"
    prediction: "71.3"
    forecast: "99.3"
    observation: null
  - datetime: "2024-11-25T23:30:00+01:00"
    prediction: "69.8"
    forecast: "97.8"
    observation: null
  - datetime: "2024-11-25T23:40:00+01:00"
    prediction: "68.3"
    forecast: "96.3"
    observation: null
  - datetime: "2024-11-25T23:50:00+01:00"
    prediction: "66.9"
    forecast: "94.9"
    observation: null
  - datetime: "2024-11-26T00:00:00+01:00"
    prediction: "65.5"
    forecast: "92.5"
    observation: null
  - datetime: "2024-11-26T00:10:00+01:00"
    prediction: "64.3"
    forecast: "91.3"
    observation: null
  - datetime: "2024-11-26T00:20:00+01:00"
    prediction: "63.1"
    forecast: "90.1"
    observation: null
  - datetime: "2024-11-26T00:30:00+01:00"
    prediction: "62.1"
    forecast: "89.1"
    observation: null
  - datetime: "2024-11-26T00:40:00+01:00"
    prediction: "61.2"
    forecast: "87.2"
    observation: null
  - datetime: "2024-11-26T00:50:00+01:00"
    prediction: "60.4"
    forecast: "86.4"
    observation: null
  - datetime: "2024-11-26T01:00:00+01:00"
    prediction: "59.8"
    forecast: "85.8"
    observation: null
  - datetime: "2024-11-26T01:10:00+01:00"
    prediction: "59.4"
    forecast: "84.4"
    observation: null
  - datetime: "2024-11-26T01:20:00+01:00"
    prediction: "59.1"
    forecast: "84.1"
    observation: null
  - datetime: "2024-11-26T01:30:00+01:00"
    prediction: "59.0"
    forecast: "84.0"
    observation: null
  - datetime: "2024-11-26T01:40:00+01:00"
    prediction: "59.2"
    forecast: "83.2"
    observation: null
  - datetime: "2024-11-26T01:50:00+01:00"
    prediction: "59.5"
    forecast: "82.5"
    observation: null
  - datetime: "2024-11-26T02:00:00+01:00"
    prediction: "60.0"
    forecast: "83.0"
    observation: null
  - datetime: "2024-11-26T02:10:00+01:00"
    prediction: "60.8"
    forecast: "83.8"
    observation: null
  - datetime: "2024-11-26T02:20:00+01:00"
    prediction: "61.7"
    forecast: "83.7"
    observation: null
  - datetime: "2024-11-26T02:30:00+01:00"
    prediction: "62.9"
    forecast: "84.9"
    observation: null
  - datetime: "2024-11-26T02:40:00+01:00"
    prediction: "64.2"
    forecast: "86.2"
    observation: null
  - datetime: "2024-11-26T02:50:00+01:00"
    prediction: "65.8"
    forecast: "86.8"
    observation: null
  - datetime: "2024-11-26T03:00:00+01:00"
    prediction: "67.5"
    forecast: "88.5"
    observation: null
  - datetime: "2024-11-26T03:10:00+01:00"
    prediction: "69.3"
    forecast: "90.3"
    observation: null
  - datetime: "2024-11-26T03:20:00+01:00"
    prediction: "71.3"
    forecast: "92.3"
    observation: null
  - datetime: "2024-11-26T03:30:00+01:00"
    prediction: "73.3"
    forecast: "93.3"
    observation: null
  - datetime: "2024-11-26T03:40:00+01:00"
    prediction: "75.5"
    forecast: "95.5"
    observation: null
  - datetime: "2024-11-26T03:50:00+01:00"
    prediction: "77.7"
    forecast: "97.7"
    observation: null
  - datetime: "2024-11-26T04:00:00+01:00"
    prediction: "80.0"
    forecast: "99.0"
    observation: null
  - datetime: "2024-11-26T04:10:00+01:00"
    prediction: "82.3"
    forecast: "100.3"
    observation: null
  - datetime: "2024-11-26T04:20:00+01:00"
    prediction: "84.5"
    forecast: "102.5"
    observation: null
  - datetime: "2024-11-26T04:30:00+01:00"
    prediction: "86.8"
    forecast: "104.8"
    observation: null
  - datetime: "2024-11-26T04:40:00+01:00"
    prediction: "89.0"
    forecast: "106.0"
    observation: null
  - datetime: "2024-11-26T04:50:00+01:00"
    prediction: "91.2"
    forecast: "108.2"
    observation: null
  - datetime: "2024-11-26T05:00:00+01:00"
    prediction: "93.3"
    forecast: "109.3"
    observation: null
  - datetime: "2024-11-26T05:10:00+01:00"
    prediction: "95.4"
    forecast: "111.4"
    observation: null
  - datetime: "2024-11-26T05:20:00+01:00"
    prediction: "97.4"
    forecast: "113.4"
    observation: null
  - datetime: "2024-11-26T05:30:00+01:00"
    prediction: "99.2"
    forecast: "114.2"
    observation: null
  - datetime: "2024-11-26T05:40:00+01:00"
    prediction: "101.0"
    forecast: "115.0"
    observation: null
  - datetime: "2024-11-26T05:50:00+01:00"
    prediction: "102.7"
    forecast: "116.7"
    observation: null
  - datetime: "2024-11-26T06:00:00+01:00"
    prediction: "104.3"
    forecast: "118.3"
    observation: null
  - datetime: "2024-11-26T06:10:00+01:00"
    prediction: "105.8"
    forecast: "118.8"
    observation: null
  - datetime: "2024-11-26T06:20:00+01:00"
    prediction: "107.1"
    forecast: "120.1"
    observation: null
  - datetime: "2024-11-26T06:30:00+01:00"
    prediction: "108.3"
    forecast: "121.3"
    observation: null
  - datetime: "2024-11-26T06:40:00+01:00"
    prediction: "109.4"
    forecast: "122.4"
    observation: null
  - datetime: "2024-11-26T06:50:00+01:00"
    prediction: "110.3"
    forecast: "122.3"
    observation: null
  - datetime: "2024-11-26T07:00:00+01:00"
    prediction: "111.1"
    forecast: "123.1"
    observation: null
  - datetime: "2024-11-26T07:10:00+01:00"
    prediction: "111.7"
    forecast: "123.7"
    observation: null
  - datetime: "2024-11-26T07:20:00+01:00"
    prediction: "112.1"
    forecast: "124.1"
    observation: null
  - datetime: "2024-11-26T07:30:00+01:00"
    prediction: "112.4"
    forecast: "123.4"
    observation: null
  - datetime: "2024-11-26T07:40:00+01:00"
    prediction: "112.5"
    forecast: "123.5"
    observation: null
  - datetime: "2024-11-26T07:50:00+01:00"
    prediction: "112.4"
    forecast: "123.4"
    observation: null
  - datetime: "2024-11-26T08:00:00+01:00"
    prediction: "112.1"
    forecast: "122.1"
    observation: null
  - datetime: "2024-11-26T08:10:00+01:00"
    prediction: "111.7"
    forecast: "121.7"
    observation: null
  - datetime: "2024-11-26T08:20:00+01:00"
    prediction: "111.0"
    forecast: "121.0"
    observation: null
  - datetime: "2024-11-26T08:30:00+01:00"
    prediction: "110.2"
    forecast: "120.2"
    observation: null
  - datetime: "2024-11-26T08:40:00+01:00"
    prediction: "109.3"
    forecast: "118.3"
    observation: null
  - datetime: "2024-11-26T08:50:00+01:00"
    prediction: "108.1"
    forecast: "117.1"
    observation: null
  - datetime: "2024-11-26T09:00:00+01:00"
    prediction: "106.9"
    forecast: "116.9"
    observation: null
  - datetime: "2024-11-26T09:10:00+01:00"
    prediction: "105.6"
    forecast: "114.6"
    observation: null
  - datetime: "2024-11-26T09:20:00+01:00"
    prediction: "104.1"
    forecast: "114.1"
    observation: null
  - datetime: "2024-11-26T09:30:00+01:00"
    prediction: "102.6"
    forecast: "112.6"
    observation: null
  - datetime: "2024-11-26T09:40:00+01:00"
    prediction: "101.0"
    forecast: "111.0"
    observation: null
  - datetime: "2024-11-26T09:50:00+01:00"
    prediction: "99.4"
    forecast: "109.4"
    observation: null
  - datetime: "2024-11-26T10:00:00+01:00"
    prediction: "97.8"
    forecast: "106.8"
    observation: null
  - datetime: "2024-11-26T10:10:00+01:00"
    prediction: "96.2"
    forecast: "105.2"
    observation: null
  - datetime: "2024-11-26T10:20:00+01:00"
    prediction: "94.5"
    forecast: "103.5"
    observation: null
  - datetime: "2024-11-26T10:30:00+01:00"
    prediction: "92.9"
    forecast: "101.9"
    observation: null
  - datetime: "2024-11-26T10:40:00+01:00"
    prediction: "91.4"
    forecast: "100.4"
    observation: null
  - datetime: "2024-11-26T10:50:00+01:00"
    prediction: "89.8"
    forecast: "97.8"
    observation: null
  - datetime: "2024-11-26T11:00:00+01:00"
    prediction: "88.3"
    forecast: "96.3"
    observation: null
  - datetime: "2024-11-26T11:10:00+01:00"
    prediction: "86.8"
    forecast: "94.8"
    observation: null
  - datetime: "2024-11-26T11:20:00+01:00"
    prediction: "85.4"
    forecast: "93.4"
    observation: null
  - datetime: "2024-11-26T11:30:00+01:00"
    prediction: "84.1"
    forecast: "92.1"
    observation: null
  - datetime: "2024-11-26T11:40:00+01:00"
    prediction: "82.7"
    forecast: "90.7"
    observation: null
  - datetime: "2024-11-26T11:50:00+01:00"
    prediction: "81.5"
    forecast: "89.5"
    observation: null
  - datetime: "2024-11-26T12:00:00+01:00"
    prediction: "80.3"
    forecast: "89.3"
    observation: null
  - datetime: "2024-11-26T12:10:00+01:00"
    prediction: "79.1"
    forecast: "87.1"
    observation: null
  - datetime: "2024-11-26T12:20:00+01:00"
    prediction: "78.0"
    forecast: "86.0"
    observation: null
  - datetime: "2024-11-26T12:30:00+01:00"
    prediction: "76.9"
    forecast: "83.9"
    observation: null
  - datetime: "2024-11-26T12:40:00+01:00"
    prediction: "75.9"
    forecast: "82.9"
    observation: null
  - datetime: "2024-11-26T12:50:00+01:00"
    prediction: "75.0"
    forecast: "82.0"
    observation: null
  - datetime: "2024-11-26T13:00:00+01:00"
    prediction: "74.2"
    forecast: "80.2"
    observation: null
  - datetime: "2024-11-26T13:10:00+01:00"
    prediction: "73.5"
    forecast: "79.5"
    observation: null
  - datetime: "2024-11-26T13:20:00+01:00"
    prediction: "73.0"
    forecast: "79.0"
    observation: null
  - datetime: "2024-11-26T13:30:00+01:00"
    prediction: "72.5"
    forecast: "77.5"
    observation: null
  - datetime: "2024-11-26T13:40:00+01:00"
    prediction: "72.2"
    forecast: "77.2"
    observation: null
  - datetime: "2024-11-26T13:50:00+01:00"
    prediction: "72.0"
    forecast: "77.0"
    observation: null
  - datetime: "2024-11-26T14:00:00+01:00"
    prediction: "72.1"
    forecast: "76.1"
    observation: null
  - datetime: "2024-11-26T14:10:00+01:00"
    prediction: "72.3"
    forecast: "76.3"
    observation: null
  - datetime: "2024-11-26T14:20:00+01:00"
    prediction: "72.6"
    forecast: "76.6"
    observation: null
  - datetime: "2024-11-26T14:30:00+01:00"
    prediction: "73.2"
    forecast: "77.2"
    observation: null
  - datetime: "2024-11-26T14:40:00+01:00"
    prediction: "73.9"
    forecast: "76.9"
    observation: null
  - datetime: "2024-11-26T14:50:00+01:00"
    prediction: "74.9"
    forecast: "77.9"
    observation: null
  - datetime: "2024-11-26T15:00:00+01:00"
    prediction: "76.0"
    forecast: "79.0"
    observation: null
unit_of_measurement: cm
icon: mdi:wave
friendly_name: Home tide main

```
