### ISSUE TITLE
Shared tooltip only works until first refresh

### ISSUE THREAD

**Issue by Grizzler89** [RomRider/apexcharts-card#821]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I have some temperature sensors that I want to display on a graph. On mouseover, I want to see all the values for the selected time in the tooltip. However, this only works until the next auto-refresh. After that, only one value is shown in the tooltip.

This issue only occurs in live mode. When I switch to edit mode, everything works as expected, even after new values are loaded.

Once it breaks in live mode, it remains broken in live mode until I delete the website data. In edit mode, however, it continues to work without any issues.

**Version of the card**
Version: 2.1.2, also tested with 2.0.4, same result

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 6h
apex_config:
  chart:
    height: 200
  legend:
    show: true
    position: right
  tooltip:
    shared: true
    style:
      fontSize: 11px
    fixed:
      enabled: true
      position: Left
  xaxis:
    tooltip:
      enabled: false
header:
  show: true
  title: Temperatur
all_series_config:
  group_by:
    func: last
    fill: last
    duration: 60s
  stroke_width: 1
series:
  - entity: sensor.dg_schreibtisch_tempsensor_temperature
    name: Schreibtisch
  - entity: sensor.somneo_temperature
    name: Bett
  - entity: sensor.dg_bett_tempsensor_temperature
    name: Unter Bett
  - entity: sensor.og_tobiastreppe_tempsensor_temperature
    name: Treppe
  - entity: sensor.dg_nebenzimmer_tempsensor_temperature
    name: Nebenzimmer
```

**Screenshots**
After it breaks:
![firefox_cgCazAcs8E](https://github.com/user-attachments/assets/05b546fd-7c2b-4c7a-b88d-a6027da78a26)

In Editmode:
![firefox_SiCm67i1kY](https://github.com/user-attachments/assets/df5e01ee-4270-4481-8f80-80658dc0d922)

**Desktop**
 - Browser: Windows 11, FF, Edge, Vivaldi (latest stable versions)

**Smartphone**
 - Device: Sony Xperia 1 V | Android 14
 - APP: Home Assistant APP (latest)
 - APP: FireFox (latest)
