### ISSUE TITLE
max auto or |+x| not working correctly with stacked columns

### ISSUE THREAD

**Issue by chrismaddahl** [RomRider/apexcharts-card#822]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
I have multiple sensors displayed as stacked columns.
For example the sum of one columns is 30kWh and the bottom column is 15kWh.
the max value of the y-axis is then only at around 15kWh and the rest above is cut off.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
apex_config:
  chart:
    height: 300px
graph_span: 2d
span:
  end: day
stacked: true
header:
  show: true
  title: Hausverbrauch letzte 24h
  show_states: true
  colorize_states: true
now:
  show: true
  color: green
yaxis:
  - id: one
    min: 0
    max: 30
    decimals: 1
    apex_config:
      tickAmount: 10
series:
  - entity: sensor.hostname_wechselrichter_home_consumption_from_grid_day
    yaxis_id: one
    name: Netzbezug
    stack_group: a
    color: 3A506B
    type: column
    stroke_width: 1
    extend_to: now
    group_by:
      func: diff
      duration: 1h
  - entity: sensor.hostname_wechselrichter_home_consumption_from_pv_day
    yaxis_id: one
    name: Eigenverbrauch PV direkt
    stack_group: a
    color: FFC300
    type: column
    stroke_width: 1
    extend_to: now
    group_by:
      func: diff
      duration: 1h
  - entity: sensor.hostname_wechselrichter_home_consumption_from_battery_day
    yaxis_id: one
    name: Eigenverbrauch Batterie
    stack_group: a
    color: 39D353
    type: column
    stroke_width: 1
    extend_to: now
    group_by:
      func: diff
      duration: 1h
  - entity: sensor.hostname_wechselrichter_energy_to_grid_day
    yaxis_id: one
    name: Einspeisung
    stack_group: a
    color: D72638
    type: column
    stroke_width: 1
    extend_to: now
    group_by:
      func: diff
      duration: 1h
  - entity: sensor.hostname_wechselrichter_battery_charge_from_pv_day
    name: Batterieladung
    stack_group: a
    color: 56CCF2
    type: column
    stroke_width: 1
    extend_to: now
    group_by:
      func: diff
      duration: 1h
  - entity: sensor.enector_geladene_energie
    name: Wallbox
    stack_group: a
    color: 5555FF
    type: column
    stroke_width: 1
    extend_to: now
    group_by:
      func: diff
      duration: 1h

```

**Screenshots**
![grafik](https://github.com/user-attachments/assets/67526377-760e-4504-9d15-e04b8470325f)
![grafik](https://github.com/user-attachments/assets/fd27c8ee-9e45-4bd2-95e2-4acde486a3f7)

**Expected behavior**
I expected the max value of the y-axis to be calculated from the sum of all columns

**Desktop (please complete the following information):**
 - Browser [Firefox]
 - Version [133.0]

**Additional context**
