### ISSUE TITLE
ApexCharts card not working with `Home Assistant 2024.12.0`

### ISSUE THREAD

**Issue by raulmatei** [RomRider/apexcharts-card#823]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the latest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Not showing data points on the charts after upgrade to `Home Assistant 2024.12.0`

**Version of the card**
Version:  `APEXCHARTS-CARD  v2.1.2`

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
    apex_config:
      chart:
        height: 150px
    graph_span: 1d
    update_interval: 5m
    yaxis:
      - min: 10
        max: ~40
    header:
      show: true
      title: Ground Floor Pipe Temperature
      show_states: true
    series:
      - entity: sensor.ground_floor_pipe_temperature_sensor_temperature
        name: " "
        type: area
        color: "#E97451"
        fill_raw: last
```

**Screenshots**
![image](https://github.com/user-attachments/assets/01b8d29f-bc47-4887-8a0d-1c5ca9ca7f84)

**Expected behavior**
Charts are not showing data but are showing loading screen. It loos that there are errors in the console:
![image](https://github.com/user-attachments/assets/da452fc8-cd87-426e-b82b-a7a5b84bb2c8)
The data is available if I load it into the Home Assistant history dialog while clicking on the entity value on the chart:
![image](https://github.com/user-attachments/assets/8ef90216-23a8-4b3b-92ac-4c9f1c783589)

On the Home Assistant Companion app it showed old data and after the upgrade just a straight line (probably last data point) but when I cleared the app cache and data it behaves similarly with it loaded into the desktop browser

**Desktop (please complete the following information):**
 - Chrome 130.0.6723.117

**Smartphone (please complete the following information):**
 - Device: Samsung S24+
 - OS: Android
 - Browser Home Assistant Companion app
 - Version 2024.10.3-full

**Additional context**
I have multiple charts but none are working, I don't use any advanced configuration, just simple data that comes straight from the sensors into Home Assistant.
