### ISSUE TITLE
layout minimal and yaxis min/max visual offset

### ISSUE THREAD

**Issue by morgoth990** [RomRider/apexcharts-card#826]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The minimal layout seem broken when a yaxis min/max is specified

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
layout: minimal
graph_span: 24h
yaxis:
  - opposite: true
    min: 8
    max: 12

series:

  - entity: sensor.lavino_di_sopra_water_level
    type: line
    color: steelblue

```

**Screenshots**
![image](https://github.com/user-attachments/assets/d2cc2998-e9c8-4c1b-b7eb-2e8b10ddd63c)

**Expected behavior**
The graph should not be offsetted and cutted

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 131.0.6778.139

**Comment by morgoth990** [comment]
Adding this to the configuration seem to fix the issue:
```yaml
apex_config:
  chart:
    offsetY: -8
```
