### ISSUE TITLE
Column charts do not stack without stack_group if yaxis is set

### ISSUE THREAD

**Issue by scop** [RomRider/apexcharts-card#827]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**

Since version 2.1.0, a top level `stacked: true` is not enough to cause column series to stack _if a top level `yaxis` configuration is present_.

If no top level `yaxis` is present, stacking works. 

The workaround is to assign series manually to `stack_group`s, but I feel it's a bug or at least weird behavior that it needs to be done only if an `yaxis` config is present.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

See debugging details at https://community.home-assistant.io/t/apexcharts-card-stacked-bar-graph-doesnt-stack-when-yaxis-is-included/810829

**Comment by scop** [comment]
Found https://github.com/RomRider/apexcharts-card/issues/730 after filing this, seems related, if not duplicate.

**Comment by scop** [comment]
I would like to remove the Stale label, but it appears I don't have rights to do that.

**Comment by scop** [comment]
Not stale.

**Comment by scop** [comment]
!stale

**Comment by scop** [comment]
I have not actually checked if this issue has been addressed already, but dropping a comment here as I'm not at all sure I'll be able to look into it in detail in the next 10 days (to avoid autoclosure). I still have the workaround mentioned in the initial description in my configs.

**Comment by Sarcastible** [comment]
> I have not actually checked if this issue has been addressed already, but dropping a comment here as I'm not at all sure I'll be able to look into it in detail in the next 10 days (to avoid autoclosure). I still have the workaround mentioned in the initial description in my configs.

In your workaround, are you able to get it to stack while defining the y-axis? I have this config:
```
type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
yaxis:
  - id: first
    opposite: false
    decimals: 0
    min: 0
    max: ~10
  - id: second
    opposite: true
    decimals: 0
    min: 0
    max: ~100
  - id: temp
    opposite: true
    decimals: 0
    min: ~-20
    max: ~100
series:
  - entity: sensor.hot_tub_energy_cost_off_peak
    name: Hot Tub (Off-Peak)
    float_precision: 2
    yaxis_id: first
    type: column
    stack_group: main
  - entity: sensor.hot_tub_energy_cost_peak
    name: Hot Tub (Peak)
    float_precision: 2
    yaxis_id: first
    type: column
    stack_group: main
  - entity: sensor.hot_tub_vue_energy_today
    name: Hot Tub (Energy)
    yaxis_id: second
    type: line
    stroke_width: 1
    stack_group: none
  - entity: sensor.outdoor_temperature
    name: Avg Outdoor Temp (°F)
    yaxis_id: temp
    type: line
    stroke_width: 1
    float_precision: 0
    stack_group: none
    statistics:
      type: mean
  - entity: sensor.hot_tub_set_temperature
    name: Hot Tub Temp
    yaxis_id: temp
    type: line
    stroke_width: 1
    float_precision: 0
    stack_group: none
    statistics:
      type: mean
apex_config:
  grid:
    show: true
  chart:
    stacked: true
    height: 570px
  xaxis:
    labels:
      format: ddd
  float_precision: 2
header:
  show: true
  title: Hot Tub
  show_states: true
  colorize_states: true
all_series_config:
  statistics:
    type: state
    period: day
    align: start
  show:
    datalabels: false
    in_legend: true
    zero_in_header: true
    legend_value: false
```
But the bars do not stack (however, if I remove all yaxis definition from the top, it will stack the bars.
<img width="1283" height="1868" alt="Image" src="https://github.com/user-attachments/assets/9f9abff0-8c8a-4c85-9a2b-fb79e15d4f75" />
