### ISSUE TITLE
Overlapped rather than stacked

### ISSUE THREAD

**Issue by danielTinkiel** [RomRider/apexcharts-card#830]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I am trying to create a bar chart with daily energy forecasted solar generation versus actual solar generation. I managed to get either one bar besides the other or one in top of the other but not the two overlapped.

**Describe the solution you'd like**
I would like to see the Forecasted energy generation, let's say in yellow in the back and the actual generation in blue in the front of the yellow bar to see at a glance one versus the other. if the actual generation goes above the forecasted then the actual generation moves to to the back and the forecasted one goes to the front , in such a way that you can see at a glance the difference and the current value all in one chart. Please see it attached the two situations' preferred view.
<img width="1152" alt="apex_preferred" src="https://github.com/user-attachments/assets/480e6b78-87d0-444b-b2cf-30ad0ff5286c" />

**Describe alternatives you've considered**

**Additional context**

**Comment by danielTinkiel** [comment]
Is still pending. No responses at all received

**Comment by henriknordgren** [comment]
Same thing here. This is driving me nuts, I can't figure out why they are overlapping and not stacked:

```
  type: custom:apexcharts-card
  graph_span: '1month' 
  update_interval: 1d
  stacked: true
  header:
    show: false   
    show_states: true
    colorize_states: false
    standard_format: true
  series:
    - entity: sensor.qubino_3_phase_smart_meter_electric_consumption_kwh
      color: lightblue
      type: column     
      name: Daily Usage
      statistics:
        type: change
        period: day
    - entity: sensor.easee_lifetime_energy
      color: purple
      type: column      
      name: Daily Usage
      statistics:
        type: change
        period: day
```

The above code just add the two bars on top of each other rather than stacked... am I doing something wrong or is this a bug??
