### ISSUE TITLE
Name and states for binary sensors

### ISSUE THREAD

**Issue by javierpose** [RomRider/apexcharts-card#835]
I want to use a chart for show states of binary sensors, but I don't see a way to display a custom status, in this case open or close, instead of 0 and N/A, neither in the legends nor in the header states :
```yaml
type: custom:apexcharts-card
header:
    title: Entrada
    show: true
    show_states: true
    colorize_states: true

graph_span: 6h
all_series_config:
  stroke_width: 2
  curve: stepline
  transform: "return x === 'on' ? 1 : 0;"
  show:
    legend_value: true
apex_config:
  chart:
    height: 200px
  tooltip:
    y:
      formatter: >
        function(val) {
          return val === 1 ? 'Abierto' : 'Cerrado';
        }
yaxis:
  - min: 0
    max: 1
    decimals: 0
    apex_config:
      tickAmount: 0
      labels:
        formatter: >
          EVAL:function(val) {
            return val === 1 ? 'Abierto' : 'Cerrado';
          }
series:
  - entity: binary_sensor.entrada_contact
    name: Puerta
  - entity: binary_sensor.nuki_casa_kato_kale_locked
    name: Cerradura
```
![Captura de pantalla 2024-12-30 a las 14 21 05](https://github.com/user-attachments/assets/c6cbfbe3-3b63-452a-95a0-e930f0f3a89b)
