### ISSUE TITLE
`header.show_states` does not display current value when using `data_generator`

### ISSUE THREAD

**Issue by Richard-AAA** [RomRider/apexcharts-card#839]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The value `show_states` does not show the current state of a sensor when using the `data_generator`. 
Instead. it uses the last value in the list provided.

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
update_interval: 5min
show:
  last_updated: true
now:
  show: true
  label: Nu
header:
  show: true
  title: Stroomprijzen vandaag
  colorize_states: true
  show_states: true
  standard_format: false
series:
  - entity: sensor.electricity_price_0_days_ahead
    type: column
    offset: "-30m"
    float_precision: 4
    data_generator: >
      const now = new Date(); 

      const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0); 
      const pricePerHour = [];

      for(let i = 0; i < 24; i++) {
        pricePerHour.push([startOfDay.getTime() + i * 1000 * 60 * 60, entity.attributes[`Hour ${i}`]])
      }

      return pricePerHour;
```

**Screenshots**
![image](https://github.com/user-attachments/assets/797cb276-9183-40ca-bb4f-b0a7afa0c64f)
This screenshot was taken around 12:30, but we can see that the price in the header does not reflect the current price.
![image](https://github.com/user-attachments/assets/6cefd79b-08e7-4ce9-a9dd-f248a537d0c7)
In this image we can see that the price does equal the last value in the list.

**Expected behavior**
I expect the header value to be the current value of the sensor or the value closest to now.

**Desktop (please complete the following information):**
Irrelevant but
 - Browser Firefox
 - Version 133.0.3

**Additional context**
For now, the issue can be fixed by making sure the last entry in the list to be the value you want to be displayed in the state header.
I can add this to the README as a quick and dirty fix.
For instance, I fixed it by adding:
```javascript
const priceNow = pricePerHour[now.getHours()];
pricePerHour[now.getHours()] = pricePerHour[23]; 
pricePerHour[23] = priceNow;
```
