### ISSUE TITLE
attribute not working

### ISSUE THREAD

**Issue by wormiedk** [RomRider/apexcharts-card#84]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I am trying to get the Attribute "Dark" from a hue motion sensor. I think I have set it up according to your instructions but I am unsure if the attribute is ever saved in "recorder" hence if it should work at all? If not I think the documentation should be updated :)

**Version of the card**
Version: 1.6.0

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
header:
  show: false
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
update_delay: 3s
series:
  - entity: sensor.hue_trappe_light_level
    group_by:
      duration: 15min
      func: avg
  - entity: sensor.hue_trappe_light_level
    attribute: Dark
    type: area
    stroke_width: 0
    curve: stepline
    color: black
    opacity: 0.2
    fill_raw: last
    transform: 'return x === ''false'' ? 1 : 0;'
    show:
      in_header: false
      legend_value: false
```

**Expected behavior**
Values for the Dark attribute 0 when true and 1 when false

**Desktop (please complete the following information):**
 - Browser Chrome, Edge, Firefox
