### ISSUE TITLE
"float_precision" not displaying trailing zeroes

### ISSUE THREAD

**Issue by dewi-ny-je** [RomRider/apexcharts-card#841]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
float_precision rounds as expected, but then omits trailing zeores

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  show_states: true
series:
  - entity: sensor.fuel_prices_fuelprices_directlease_1561_devicetracker
# value: 1.899
    float_precision: 2
```

**Screenshots**
![image](https://github.com/user-attachments/assets/fd530ab9-9ce8-4e03-b968-d21abf27dd27)

If I use 
`float_precision: 3` I get:

![image](https://github.com/user-attachments/assets/d5010fc0-0e1d-4184-8a25-89bcf65034fc)

**Expected behavior**
It should show 1.90 and not 1.9 when set with `float_precision: 2`

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 131

**Comment by 888Jay** [comment]
I have the same issue.

![Image](https://github.com/user-attachments/assets/5562fcb3-f447-4f18-b136-f3b75d622b42)

**Comment by perlchamp** [comment]
same here:

![Image](https://github.com/user-attachments/assets/fd70e9bd-0ebf-4499-a6bf-5ddfe662a7da)

```
type: custom:apexcharts-card
series:
  - entity: sensor.goldpreis_yaml
    name: AKTUELL
    type: area
    curve: straight
    stroke_width: 1
    color: gold
    opacity: 0.2
    show:
      hidden_by_default: false
      legend_value: false
      in_header: true
      in_chart: true
    float_precision: 2
  - entity: sensor.goldpreis_yaml
    name: MAX
    group_by:
      func: max
      duration: 7d
    color: lightgreen
    show:
      hidden_by_default: false
      legend_value: false
      in_header: true
      in_chart: false
    float_precision: 2
  - entity: sensor.goldpreis_yaml
    name: MIN
    group_by:
      func: min
      duration: 7d
    color: tomato
    show:
      hidden_by_default: false
      legend_value: false
      in_header: true
      in_chart: false
    float_precision: 2
...
```
Hope to get an answer soon.
Many thanks in advance !
