### ISSUE TITLE
Adding width Control with section dashboards

### ISSUE THREAD

**Issue by timpetersson81** [RomRider/apexcharts-card#842]
Im missing a slider that allows me to show the card over more than 1 collumn

**Comment by makstech** [comment]
A temporary solution for now, is to have these configs:
```yaml
grid_options:
  columns: full
apex_config:
  chart:
    height: 400
experimental:
  disable_config_validation: true
```
Change height to whatever suits best in your case, and also you can replace `full` with any other number that your Section supports
