### ISSUE TITLE
 Bug in avg function when all values are the same

### ISSUE THREAD

**Issue by pat-iphone** [RomRider/apexcharts-card#845]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Hi,

I encountered an issue with the avg function in apexcharts-card. When the values to be averaged are all identical, the card crashes and fails to render properly.

Steps to reproduce:

    Configure apexcharts-card with a dataset where all values are the same.
    Use the avg function to calculate the average.
    Observe that the chart fails to display.

Expected behavior: The card should handle datasets with identical values correctly and display the average without errors.

Actual behavior: The card crashes or fails to render when the dataset contains identical values.

**Version of the card**
Version:
v2.1.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 7d
yaxis:
  - id: first
    decimals: 0
    apex_config:
      tickAmount: 4
  - id: second
    opposite: true
    decimals: 0
    apex_config:
      tickAmount: 4
span:
  start: day
  offset: "-6d"
apex_config:
  chart:
    height: 200px
header:
  show: true
  show_states: true
  colorize_states: true
color_list:
  - blue
  - green
  - black
series:
  - entity: sensor.pompes_energy
    yaxis_id: first
    group_by:
      func: diff
      duration: 1d
    type: column
    name: Consommation journalière Pompes
    show:
      datalabels: true
      legend_value: false
  - entity: sensor.blueriiot_pool_sensor_pool_temperature
    yaxis_id: second
    stroke_width: 2
    group_by:
      func: avg
      duration: 1d
    unit: ºC
    name: Temp. Moy. piscine
    show:
      datalabels: false
      in_chart: true
      legend_value: false
```
The problem is on the "blueriiot_pool_sensor_pool_temperature" value

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [Firefox]

**Smartphone (please complete the following information):**
 - Device: [iPhone15pro]
 - OS: [iOS18.2]
 - Browser [Safari]

**Additional context**

This issue seems to be related to how the avg function processes identical values. It might be a division by zero or an assumption of variability in the dataset.

Thank you for looking into this!
