### ISSUE TITLE
Height of graph is not possible to set with apex chart. Documentation misleading.

### ISSUE THREAD

**Issue by dflvunoooooo** [RomRider/apexcharts-card#851]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
The documentation sates: "Change the height of the graph". But in Apex Chart this is not possible. One can only set the height of the chart, which is in HA terms the height of the whole card. The graph, meaning the for examle line of data can not be set to a serain height, at least didn't I find anything in the documentation of Apex Chart. 

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```
type: vertical-stack
cards:
  - type: custom:apexcharts-card
    graph_span: 24h
    header:
      show: true
      title: Time
    apex_config:
      chart:
        height: 200qx
    series:
      - entity: sensor.time
        type: line
  - type: custom:apexcharts-card
    graph_span: 24h
    header:
      show: true
      title: Time
    apex_config:
      chart:
        height: 200qx
    series:
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
      - entity: sensor.time
        type: line
        color: green
```

**Screenshots**
![2025-01-13_11-24](https://github.com/user-attachments/assets/12449155-0701-4195-8007-a413d41e0037)

**Expected behavior**
I would expect the documentation here to reflect this behaviour. Or, if the height of the graph can be set and I overlooked it, to distinguish this.

**Desktop (please complete the following information):**
 - firefox, chrome
