### ISSUE TITLE
Can't get zoom to work

### ISSUE THREAD

**Issue by mooky31** [RomRider/apexcharts-card#852]
Hello,

I'm trying to setup a graph with zoom.
The zoom doesn't show up

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Production solaire
  show_states: false
  colorize_states: true
all_series_config:
  statistics:
    type: mean
    period: 5minute
  stroke_width: 2
apex_config:
  chart:
    height: 500%
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: true
        zoomout: true
        pan: true
        reset: true
  curve: smooth
  xaxis:
    type: datetime
  yaxis:
    decimalsInFloat: 0
  zoom:
    type: x
    enabled: true
    autoScaleYaxis: false
    allowMouseWheelZoom: true
series:
  - entity: sensor.solis_meter_active_power
    name: Import/export réseau
    color: purple
  - entity: sensor.puissance_totale_maison
    name: Consommation maison
    color: red
  - entity: sensor.solis_pv_total_power
    name: Production solaire
    color: orange
  - entity: sensor.battery_input_output
    name: Charge/décharge batterie
    color: lightseagreen
```

**Screenshots**
![image](https://github.com/user-attachments/assets/f013557c-77f7-40d2-a00a-8ef7cf01c7cd)

**Expected behavior**
I'd like to be able to zoom on my graph, either with the wheel or by drawing a range with the mouse

**Desktop (please complete the following information):**
 - Firefox 134
 - Edge 131
