### ISSUE TITLE
Border radius option in stacked bar chart does not work

### ISSUE THREAD

**Issue by bladecell** [RomRider/apexcharts-card#854]
**Checklist**
- [✓ ] I updated the card to the latest version available
- [✓ ] I cleared the cache of my browser
- [✓ ] I verified that I'm really running the lastest version in my browser console
- [✓ ] I checked if there is another issue opened with the same problem

**Describe the bug**
I have tried to recreate [this](https://apexcharts.com/javascript-chart-demos/column-charts/stacked/) chart, but cannot get the border radius get to work in stacked column chart in the apex config.
```yaml
borderRadius: 10,
borderRadiusApplication: 'end', // 'around', 'end'
borderRadiusWhenStacked: 'last', // 'all', 'last'
```
**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
update_interval: 10min
graph_span: 7d
stacked: true
header:
  show: true
  show_states: true
  colorize_states: true
span:
  start: day
  offset: "-7d"
cache: true
all_series_config:
  group_by:
    func: diff
    duration: 1day
  type: column
  show:
    legend_value: false
    datalabels: true
series:
  - entity: sensor.esph_wmbusmeter_bedroom_heat
    name: Bedroom Heat
    color: var(--red-color)
  - entity: sensor.esph_wmbusmeter_study_room_heat
    name: Study Room Heat
    color: var(--green-color)
  - entity: sensor.esph_wmbusmeter_living_room_heat
    name: Living Room Heat
    color: var(--light-blue-color)
  - entity: sensor.esph_wmbusmeter_kitchen_heat
    name: Kitchen Heat
    color: var(--amber-color)
apex_config:
  plotOptions:
    bar:
      borderRadius: 10
      borderRadiusApplication: end
      borderRadiusWhenStacked: last
  legend:
    show: false
  states:
    hover:
      filter:
        type: none
  dataLabels:
    enabled: true
    textAnchor: middle 
    offsetY: 1
    style:
      fontSize: 12px
      fontFamily: Nunito, sans-serif
      colors:
        - var(--contrast11)
    background:
      enabled: false
  grid:
    show: false
    strokeDashArray: 0
  xaxis:
    labels:
      offsetY: -5
      datetimeFormatter:
        day: ddd
      style:
        fontFamily: Nunito, sans-serif
    axisBorder:
      show: false
    tooltip:
      enabled: false
    axisTicks:
      show: false
    crosshairs:
      stroke:
        color: var(--light-grey-tint)
        dashArray: 0
  yaxis:
    stepSize: 5
    labels:
      show: false
    axisBorder:
      show: false
    tooltip:
      enabled: false
    axisTicks:
      show: false

```

**Expected behavior**
Rounded borders in the stacked bar chart

**Desktop (please complete the following information):**
 - ZenBrowser
 - 1.6b (Firefox 134.0)
