### ISSUE TITLE
Graph goes out of bound

### ISSUE THREAD

**Issue by SiriosDev** [RomRider/apexcharts-card#864]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem (_if it exists I can't find it after 30 minutes of searching_)

**Describe the bug**
The graph goes beyond the limits of the card

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
chart_type: radialBar
layout: minimal
series:
  - entity: sensor.ha_processor_use
    color_threshold:
      - value: 0
        color: "#43a047"
      - value: 65
        color: "#ffa600"
      - value: 85
        color: "#db4437"
    name: " "
    show:
      header_color_threshold: true
      extremas: true
header:
  show: true
  title: Utilizzo del Processore
  show_states: true
  colorize_states: true
experimental:
  color_threshold: true
apex_config:
  plotOptions:
    radialBar:
      offsetY: -20
      startAngle: -120
      endAngle: 120
      dataLabels:
        name:
          show: false
        value:
          show: false
  legend:
    show: false
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/e27c035a-553b-4a6f-bf8b-ebef556490da)

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version 132.0.6834.160
