### ISSUE TITLE
Unable to configure apexcharts_card_templates

### ISSUE THREAD

**Issue by kaizersoje** [RomRider/apexcharts-card#87]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser
- [ ] I verified that I'm really running the lastest version in my browser console
- [ ] I checked if there is another issue opened with the same problem

**Describe the bug**

I get the following error when using a card template I have defined.

```
/// apexcharts-card version 1.6.0 /// value.config_templates is not an array
type: 'custom:apexcharts-card'
config_templates: 2d_stepline_chart
y_axis_precision: 0
series:
  - entity: sensor.wind_speed_kilometre
  - entity: sensor.gust_speed_kilometre
```

I can only configure it as an array instead.

```
- type: custom:apexcharts-card
  config_templates:
    - 2d_stepline_chart
  y_axis_precision: 0
  series:
    - entity: sensor.wind_speed_kilometre
    - entity: sensor.gust_speed_kilometre
```

**Version of the card**
Version: 1.6.0

**To Reproduce**
This is the configuration I used:
```yaml

apexcharts_card_templates:
  2d_stepline_chart:
    apex_config:
      chart:
        height: 200px
    all_series_config:
      extend_to_end: false
      stroke_width: 2
      curve: stepline
      show:
        legend_value: false
    graph_span: 2d
```

Used the template to define the card below.

```
- type: custom:apexcharts-card
  config_templates: 2d_stepline_chart
  y_axis_precision: 0
  series:
    - entity: sensor.wind_speed_kilometre
    - entity: sensor.gust_speed_kilometre

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 88.0.4324.150

**Smartphone (please complete the following information):**

**Additional context**
