### ISSUE TITLE
Span "month" don´t start or ends exactly on month

### ISSUE THREAD

**Issue by Neewieedo** [RomRider/apexcharts-card#870]
Hello everyone,

I have created the following chart to show the monthly solar production.

Unfortunately, the total for the month is not calculated up to midnight on the last (end: month) or first (start:month) day of the month, 
but always one or two day(s) earlier or later (see screenshots).
This means that the following month also starts or ends earlier and the calculation is “shifted” by around 1.5 days…

But since it is not a static error, so span offset don't helps :-(

![Image](https://github.com/user-attachments/assets/997f410f-4964-4fe5-8d87-38d68c7c329d)

![Image](https://github.com/user-attachments/assets/3d72f028-eb19-4db8-be6c-e9d35085bcd9)

```
type: custom:apexcharts-card
stacked: true
card_mod:
  style: |
    #state__value > #state {
      font-size: 1.2em !important;
    }
    .apexcharts-tooltip-series-group {
      padding-top: 0px !important;
      padding-bottom: 0px !important;
      margin-top: 0px !important;
      margin-bottom: 0px !important;
      display: none;
      text-align: left;
      justify-content: left;
      align-items: center;
    }
    #header {
        padding: 1rem !important;
    }  
yaxis:
  - id: kwh
    decimals: 0
    min: 0
    max: 50
    apex_config:
      tickAmount: 5
      forceNiceScale: true
      title:
        text: " kWh"
        rotate: -90
      labels:
        style:
          colors: var(--energy-solar-color)
apex_config:
  chart:
    height: 175px
    offsetX: 0
    offsetY: -20
  legend:
    show: false
  dataLabels:
    style:
      fontSize: 0.7rem
    rotate: 90
span:
  end: month
graph_span: 1y
update_interval: 1h
header:
  show: true
  show_states: true
  colorize_states: true
  standard_format: false
all_series_config:
  type: column
  float_precision: 1
  statistics:
    type: sum
    period: day
  group_by:
    func: diff
    start_with_last: false
    duration: 1month
  show:
    in_header: false
    datalabels: true
  opacity: 0.2
  stroke_width: 2
  unit: " kWh"
series:
  - entity: sensor.solarproduktion_gesamt
    yaxis_id: kwh
    name: Solarproduktion
    color: var(--energy-solar-color)
  - entity: sensor.solarproduktion_gesamt
    yaxis_id: kwh
    name: Solarproduktion
    color: var(--energy-solar-color)
    show:
      in_header: raw
      in_chart: false
```

**Comment by henriknordgren** [comment]
Yes I noticed that too. I get one or two days extra for the previous month. I hope this gets fixed...

**Comment by RuneNyhuus** [comment]
Mine is doing the same, its even showing the wrong Month in the ToolTip, its showing March 2 times and jumps over February
And the original HA Statistics graph Card shows it right.
![Image](https://github.com/user-attachments/assets/fabf3270-d34b-4808-bef8-9e1a5e45f46a)

**Comment by Neewieedo** [comment]
I think nobody is actively working on the project anymore and therefore the issue will unfortunately not be fixed... :-(

**Comment by Neewieedo** [comment]
Is there any idea to fix the problem?

-> Please reopen issue 👍

**Comment by vingerha** [comment]
Did you try this with the newest release? I cannot replicate it myself

**Comment by Neewieedo** [comment]
Yes, I installed version 2.2.3.
Have you tried the code above and a suitable entity?
For me, the month doesn't start on the 1st at midnight, but sometimes in the middle of the day or even on the last day of the previous month.

<img width="456" height="248" alt="Image" src="https://github.com/user-attachments/assets/1de820ef-0e57-4cab-be03-48eb241d122c" />

**Comment by vingerha** [comment]
The question is what is 'suitable', I tried 2 sensors that have stats

EDIT; ah.. now I see something, some months show wtih 1st ...but other the end of month. Did you try this with the HA statisctics graph ... to indicate it is apex issue and not data?

**Comment by vingerha** [comment]
Ah... I should have noticed this earlier... pls see here: 
https://github.com/RomRider/apexcharts-card?tab=readme-ov-file#group_by-options

**Comment by Neewieedo** [comment]
> EDIT; ah.. now I see something, some months show wtih 1st ...but other the end of month. Did you try this with the HA statisctics graph ... to indicate it is apex issue and not data?

There is data in HA statistics 


> Ah... I should have noticed this earlier... pls see here:
> https://github.com/RomRider/apexcharts-card?tab=readme-ov-file#group_by-options

Can you please explain in more detail what I should do with it and how I can solve the problem?

**Comment by vingerha** [comment]
The issue is that you are grouping by month and this is not possible (atm) so you will alsways get odd results, grouping by (say) 30d may be a solution but imo a poor one

**Comment by Neewieedo** [comment]
> The issue is that you are grouping by month and this is not possible (atm) so you will alsways get odd results, grouping by (say) 30d may be a solution but imo a poor one

I think the problem is not only in the grouping, but also in the fact that the starting point is not set correctly
`span:
  start: month`

**Comment by Rav3nholm** [comment]
I do have the same issue as I stated above.
Have updated to the latest release but still the same problem.

Its only the first month that have the correct starting day/time all the following starts drifting and have 1 day extra and different time.

Below is an example of how its looks and my code.
```
type: custom:apexcharts-card
yaxis:
  - id: kwh
    decimals: 0
    min: 0
    max: 1800
    apex_config:
      tickAmount: 5
      forceNiceScale: true
apex_config:
  chart:
    height: 252px
  grid:
    show: true
    borderColor: rgba(112, 135, 164, 0.5)
  legend:
    show: false
  dataLabels:
    style:
      fontSize: 0.7rem
    rotate: 90
span:
  start: year
graph_span: 1y
header:
  show: true
  title: Solproduktion
  show_states: false
  colorize_states: false
  standard_format: false
all_series_config:
  type: column
  float_precision: 0
  statistics:
    type: sum
  group_by:
    func: diff
    start_with_last: true
    duration: 1month
  show:
    in_header: false
    datalabels: true
  opacity: 0.2
  stroke_width: 2
series:
  - entity: sensor.energy_yield_total
    yaxis_id: kwh
    name: Solarproduktion
    color: var(--energy-solar-color)
```
<img width="592" height="373" alt="Image" src="https://github.com/user-attachments/assets/23f75482-3ccb-464a-a48f-7c1f054826b0" />
