### ISSUE TITLE
color_threshold totally off when sensor data is missing

### ISSUE THREAD

**Issue by thomasheidenreich** [RomRider/apexcharts-card#878]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
See screenshot - the colors left of the gap are proportianl to the main graph but not in alignment with the threshold values

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Boot Luftfeuchtigkeit
  show_states: true
  colorize_states: false
all_series_config:
  stroke_width: 0
  show:
    extremas: true
experimental:
  color_threshold: true
  brush: true
graph_span: 24h
brush:
  selection_span: 6h
series:
  - entity: sensor.shelly_h_t_68169d_humidity
    name: Motorraum
    type: area
    show:
      in_brush: true
    color_threshold:
      - value: 20
        color: red
      - value: 30
        color: orange
      - value: 40
        color: yellow
      - value: 60
        color: green
      - value: 70
        color: yellow
      - value: 70
        color: orange
      - value: 90
        color: red
yaxis:
  - min: 0
    max: 100


```

**Screenshots**

![Image](https://github.com/user-attachments/assets/5330c8ca-5b33-432e-a563-0c147ff59262)

**Expected behavior**
The colors should be in alignmen with tthe rest of the graph, for example 20.0 should not be green. 

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: 133
