### ISSUE TITLE
Graph is cut off on the right in edit mode

### ISSUE THREAD

**Issue by thomasheidenreich** [RomRider/apexcharts-card#879]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The graph card is cut off in edit/preview mode - see screenshot

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Boot Luftfeuchtigkeit
  show_states: true
  colorize_states: false
all_series_config:
  stroke_width: 0
  show:
    extremas: true
experimental:
  color_threshold: true
  brush: true
graph_span: 24h
brush:
  selection_span: 6h
series:
  - entity: sensor.shelly_h_t_68169d_humidity
    name: Motorraum
    type: area
    show:
      in_brush: true
    color_threshold:
      - value: 20
        color: red
      - value: 30
        color: orange
      - value: 40
        color: yellow
      - value: 60
        color: green
      - value: 70
        color: yellow
      - value: 70
        color: orange
      - value: 90
        color: red
yaxis:
  - min: 0
    max: 100

```

**Screenshots**

![Image](https://github.com/user-attachments/assets/4dc21d3d-6200-497d-ac61-1c0db3d1560e)

![Image](https://github.com/user-attachments/assets/1b8c8c53-f43f-4c79-af3f-2ef2de930883)

**Expected behavior**
The graph should not be cut off on the right in edit mode - the preview should look lioke the final result.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 133
