### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by commentsonly** [RomRider/apexcharts-card#884]
just found out that
```
apex_config:
  chart:
    zoom:
      type: x
      enabled: true
      autoScaleYaxis: true
```
does work, means the chart does scale until it receives new value which then reverts the zoom factor.

What's sort of missing a 'freeze' button or in general a zoom toolbar similar to plotly?

But since zoom isn't documented in the home assistant port I bet zooming isn't supported yet?
