### ISSUE TITLE
Incorrect graph line but values are correct.

### ISSUE THREAD

**Issue by AustinSoundsOK** [RomRider/apexcharts-card#895]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
When plotting multiple temperature sensors on a shared y-axis (yaxis_id: temp) without using group_by, the apexcharts-card renders the lines incorrectly. The tooltip and header values are correct, but the lines appear much lower on the chart than they should.

This issue occurs only when multiple ungrouped sensors are plotted together over a long graph_span (e.g., 24h). The same data is rendered correctly when using group_by, or if each sensor is plotted alone.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Upstairs Temps + Power (24h)
  show_states: true
  colorize_states: true
graph_span: 24h
apex_config:
  chart:
    height: 300
  legend:
    show: false
  yaxis:
    - id: temp
      min: 32
      max: 90
      title: Temperature (°F)
      opposite: false
      tickAmount: 4
      decimalsInFloat: 0
      labels:
        style:
          colors: "#f1c40f"
    - id: power
      min: 0
      max: 650
      title: Power (W)
      opposite: true
      tickAmount: 4
      decimalsInFloat: 0
      labels:
        style:
          colors: "#e84393"
series:
  - entity: sensor.upstairs_average_temp
    name: Average
    type: line
    curve: straight
    yaxis_id: temp
    color: "#f1c40f"
    opacity: 0.8
    stroke_width: 2
    show:
      legend_value: true
  - entity: sensor.upstairs_temperature
    name: Upstairs Hall
    type: line
    yaxis_id: temp
    curve: straight
    color: "#FF5733"
    stroke_width: 2
  - entity: sensor.elliot_bedroom_temperature
    name: Elliot's Room
    type: line
    curve: straight
    yaxis_id: temp
    color: "#4287f5"
    stroke_width: 2
  - entity: sensor.nora_bedroom_temperature
    name: Nora's Room
    type: line
    curve: straight
    yaxis_id: temp
    color: "#9b59b6"
    stroke_width: 2
  - entity: sensor.austin_bedroom_temperature
    name: Austin's Room
    type: line
    curve: straight
    yaxis_id: temp
    color: "#27ae60"
    stroke_width: 2
  - entity: sensor.upstairs_hall_plug_current_consumption
    name: Hall Plug Power
    type: line
    curve: straight
    yaxis_id: power
    color: "#e84393"
    opacity: 0.5
    group_by:
      func: avg
      duration: 30m
    stroke_width: 2


```

**Screenshots**

![Image](https://github.com/user-attachments/assets/7cb74cb1-99db-4b18-9e28-6e543e44166e)

**Expected behavior**
All temperature lines using yaxis_id: temp should plot according to the axis scale (e.g., 32–90°F), and their vertical position should match the actual sensor values, even without group_by.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 137.0 (64-bit)

Home Assistant: 2024.4.x

**Additional context**
Occurs on both desktop and mobile
