### ISSUE TITLE
`in_chart: false` influences the wrong axis

### ISSUE THREAD

**Issue by HarHarLinks** [RomRider/apexcharts-card#898]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Hiding the second out of 3 series in_chart makes that series' data mess with the axis of the third series. In this case, the visible range is calculated entirely incorrectly (based on the wrong series) and therefore hides the third series' line.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Wohnzimmer
  show_states: true
  colorize_states: true
color_list:
  - orange
  - "#4caf50"
  - "#3498db"
all_series_config:
  show:
    legend_value: false
    extremas: true
yaxis:
  - id: temperature
  - id: battery
  - id: humidity
    opposite: true
series:
  - entity: sensor.indoor_outdoor_meter_4e6f
    name: Temperature
    yaxis_id: temperature
  - entity: sensor.indoor_outdoor_meter_4e6f_battery
    name: Battery
    yaxis_id: battery
    show:
      in_chart: false
  - entity: sensor.indoor_outdoor_meter_4e6f_humidity
    name: Humidity
    yaxis_id: humidity
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/94561f11-724d-41b3-a49c-905ae593810c)

**Expected behavior**
The right line and yaxis are shown, the yaxis uses an appropriate scale.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 136

**Smartphone (please complete the following information):**

**Additional context**
