### ISSUE TITLE
Adding a value in the transform does not work, other math functions seem to work

### ISSUE THREAD

**Issue by GentleGiantSoftware** [RomRider/apexcharts-card#901]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser
- [ ] I verified that I'm really running the lastest version in my browser console
- [ ] I checked if there is another issue opened with the same problem

**Describe the bug**
My pool pH sensor value is 0.2 too low, but adding the value in the transform function using 'transform: "return x + 0.2;"' does not work. 

**Version of the card**
Version: v2.1.2

**To Reproduce**
This is the configuration I used which does not add 0.2 to the values:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Zwembad pH (7.2 - 7.6)
  show_states: true
  colorize_states: true
graph_span: 48h
series:
  - entity: sensor.mijn_zwembad_ph
    transform: "return x + 0.2;"
```

The workaround is to use a negative substraction which does work:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Zwembad pH (7.2 - 7.6)
  show_states: true
  colorize_states: true
graph_span: 48h
series:
  - entity: sensor.mijn_zwembad_ph
    transform: "return x - -0.2;"
```

**Expected behavior**
Only adding seems to go wrong in the transform function, other math functions seem to work as expected..
