### ISSUE TITLE
Extremas not showing in 2.1.2

### ISSUE THREAD

**Issue by thedude911** [RomRider/apexcharts-card#905]
**Checklist**
- [x ] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [x ] I checked if there is another issue opened with the same problem

**Describe the bug**
Extremas not showing in graph.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 24h
span:
  start: day
now:
  show: true
  label: jetzt
header:
  show: true
  title: Strompreise heute
  show_states: true
  colorize_states: true
series:
  - entity: sensor.epex_spot_data_net_price
    type: line
    color: orange
    curve: stepline
    name: mit Netzentgelt
    float_precision: 2
    show:
      in_header: before_now
      extremas: true
      legend_value: false
    data_generator: |
      return entity.attributes.data.map((entry) => {
        return [new Date(entry.start_time), entry.price_per_kwh * 100 + 8.1];
      });
  - entity: sensor.epex_spot_data_net_price
    type: area
    color: lightblue
    curve: stepline
    name: ohne Netzentgelt
    float_precision: 2
    show:
      in_header: before_now
      legend_value: false
    color_threshold:
      - value: 5
        color: steelblue
      - value: 10
        color: midnightblue
      - value: 15
        color: orange
      - value: 20
        color: orangered
      - value: 25
        color: red
    data_generator: |
      return entity.attributes.data.map((entry) => {
        return [new Date(entry.start_time), entry.price_per_kwh * 100];
      });
```

**Screenshots**

<img width="281" alt="Image" src="https://github.com/user-attachments/assets/63daff6c-febf-40eb-a547-588e4c499d7f" />

**Expected behavior**
Extremas shown on graph.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 135.0.7049.115
