### ISSUE TITLE
Stacked column chart not stacking

### ISSUE THREAD

**Issue by Johanneke** [RomRider/apexcharts-card#913]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
When creating a stacked bar chart, the bars for the same time period are not stacked, but sort-of overlap. Sometimes I see them beginnen a little higher than 0, but not high enough to actually be stacked on top of other bars.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
graph_span: 1d
update_interval: 1h
all_series_config:
  type: column
  stack_group: stack
apex_config:
  chart:
    height: 250px
series:
  - entity: sensor.servers_energy
  - entity: sensor.meterkast_energy

```

**Screenshots**
Config and preview side-by-side, so you can really see that the posted config results in overlapping bars.
<img width="1025" alt="Image" src="https://github.com/user-attachments/assets/99abb64f-839c-4dae-a72d-46cbf9d3810a" />
Zoom-in of the issue, you can see the yellow overlaps with the blue, and does not reach high enough for the sum of the two bars
<img width="262" alt="Image" src="https://github.com/user-attachments/assets/5bb3e815-65e3-43c2-80f3-d81f18aeb2fb" />

**Expected behavior**
I expect the config `stacked: true` to result in bars that are, well, stacked.

**Desktop (please complete the following information):**
 - Browser: Tested on both Safari 18.4 en Firefox 138.0.4
 - OS: Mac OS 15.4.1 (although we saw the same issue on a laptop running Linux, I just don't have access to that laptop at the time of writing)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: 18.4.1
 - Browser: Home Assistant Companion App

**Additional context**
Not sure if it is related, but the page in Home Assistant where this graph is displayed is *extremely* slow and will often result in a browser popup asking if I want to kill the tab because it is not responding. 

I've check the console log but don't see any errors or warnings logged.
