### ISSUE TITLE
Y-axis Assignment Issue in ApexCharts Card (home assistant intergration)

### ISSUE THREAD

**Issue by SonicHax** [RomRider/apexcharts-card#915]
**Checklist**

[x] I updated the card to the latest version available (Confirmed 2.1.2 is the latest as of 23 May 2025)
[x] I cleared the cache of my browser
[] I verified that I'm really running the lastest version in my browser console
[ ] I checked if there is another issue opened with the same problem

**Describe the bug**
When using apexcharts-card version 2.1.2 (which is currently the latest available version), I'm encountering a persistent issue with the assignment of series to multiple Y-axes. Despite configuring two distinct Y-axes (one for voltage, one for frequency) and explicitly assigning series to them using string-based yaxis_ids, only the first voltage series (Phase A) is correctly rendered on the voltage axis. The other two voltage series (Phase B and Phase C), along with the frequency series, are incorrectly displayed on the frequency (right-hand) Y-axis.

Multiple attempts with various yaxis and series configurations, including those that typically work in other apexcharts-card versions or are standard ApexCharts.js practices, have yielded the same incorrect visual output or resulted in validation errors specific to version 2.1.2. This suggests a core issue with Y-axis handling in this particular version.

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:

YAML

```
type: custom:apexcharts-card
header:
  title: Net Lijnspanningen (A-N, B-N, C-N)
  show: true
graph_span: 24h
span:
  start: day
now:
  show: true
apex_config:
  chart:
    height: 350
  stroke:
    curve: smooth
    width: 2
  yaxis:
    - id: spanning
      min: 210
      max: 260
      title: Spanning (V)
    - id: frequentie
      opposite: true
      min: 45
      max: 55
      title: Frequentie (Hz)
  tooltip:
    shared: true
    intersect: false
    x:
      format: dd MMM HH:mm
  colors:
    - '#FF4560' # Kleur voor Phase A
    - '#008FFB' # Kleur voor Phase B
    - '#00E396' # Kleur voor Phase C
    - '#775DD0' # Kleur voor Frequentie
series:
  - entity: sensor.30ktl_m3_001_phase_a_voltage
    name: Phase A
    type: line
    stroke_width: 2
    yaxis_id: spanning
    extend_to: false
    group_by:
      duration: 1min
      func: avg
  - entity: sensor.30ktl_m3_001_phase_b_voltage
    name: Phase B
    type: line
    stroke_width: 2
    yaxis_id: spanning
    extend_to: false
    group_by:
      duration: 1min
      func: avg
  - entity: sensor.30ktl_m3_001_phase_c_voltage
    name: Phase C
    type: line
    stroke_width: 2
    yaxis_id: spanning
    extend_to: false
    group_by:
      duration: 1min
      func: avg
  - entity: sensor.30ktl_m3_001_grid_frequency
    name: Frequentie
    type: line
    stroke_width: 2
    yaxis_id: frequentie
    extend_to: false
    group_by:
      duration: 1min
      func: avg
```
**Screenshots**

![Image](https://github.com/user-attachments/assets/c14df917-0c57-4ee6-bc95-76efa209786d)

mouse over on b
![Image](https://github.com/user-attachments/assets/7bb22cdd-84c7-433e-98f1-c2ddb39e9b3c)

**Expected behavior**
I expect all three voltage series (Phase A, B, and C) to be plotted on the left-hand 'Spanning (V)' Y-axis, and the 'Frequentie' series to be plotted on the right-hand 'Frequentie (Hz)' Y-axis, as defined by their respective yaxis_id assignments.

Desktop:

Browser: chrome
Version: 136.0.7103.114
and
Browser: firefox
Version: 138.0.3 (64-bits)

**Additional context**
I have attempted several configurations based on common apexcharts-card practices and troubleshooting steps, including:

Moving yaxis definitions outside of apex_config (resulted in value.yaxis[0] is not a ChartCardYAxisExternal; value.yaxis[0].title is extraneous errors in v2.1.2).
Using numeric yaxis_id assignments (e.g., yaxis_id: 0) (resulted in value.series[0].yaxis_id is not a string errors in v2.1.2).
Defining yaxis directly within each series entry (resulted in value.series[0].yaxis is extraneous errors in v2.1.2).
Omitting yaxis_id for voltage series to rely on implicit order (no change, problem persisted).
The current configuration (as provided above) is the only one that passes validation in v2.1.2, but the visual rendering of the Y-axis assignment remains incorrect for Phase B, C, and the Frequency series. This strongly suggests a bug in how Y-axis IDs are processed in this specific, latest card version.
