### ISSUE TITLE
Y-max to high when using stacked and mixing bar and line plots

### ISSUE THREAD

**Issue by wormiedk** [RomRider/apexcharts-card#92]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I am attempting to generate a plot which show total docker memory in use and then some selected docker instances that show as percentage of the container in use e.g.
Docker uses 1000 mb in total
Of that total 
* homeassistant uses 200 mb
* mariadb uses 100 mb

I would then like to have a bar or line at 1000 mb with bars stacked to 300 mb
I have almost gotten it to work by showing docker total as a line and the rest of the entities as bars. The problem is that the extrema of the graph then becomes the sum of all three in the example the max y-axis value would be 1300 instead of 1000 mb. See also screenshot. I can come around this by manually specifiying the y-max but this value is dynamic
 
**Version of the card**
Version: 1.7.0

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
stacked: true
header:
  show: true
all_series_config:
  fill_raw: last
  type: column
  group_by:
    func: avg
    duration: 0.5h
series:
  - entity: sensor.docker_memory
    name: Docker
    type: line
    stroke_width: 2
  - entity: sensor.docker_homeassistant_memory
    name: HASS
  - entity: sensor.docker_mc_nanna_memory
    name: Nanna
  - entity: sensor.docker_mc_frida_memory
    name: Frida
  - entity: sensor.docker_mc_andreas_memory
    name: Andreas
    show:
      datalabels: true
      legend_value: false
      in_header: false
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4417857/108190114-cd703e00-7111-11eb-9fd6-703e09819c59.png)

**Expected behavior**
y-max is set from the max value of both bars and lines

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 85.0.2 (64 bit)
