### ISSUE TITLE
Chart group by diff series going into the negative and displaying wrong monthly value

### ISSUE THREAD

**Issue by evilphish** [RomRider/apexcharts-card#922]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
As can be seen on screenshot, the current (June, rightmost columns) values for distance driven and energy used are displayed negative and the values are wrong as well. The second screenshot shows the historical data for the two sensors used in the chart. They only ever increase and one shows the energy consumed by charging the car, the other is synchronized to the odometer and displays the distance travelled since the last charge. 

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
hours_12: false
graph_span: 1year
stacked: false
span:
  end: month
apex_config:
  chart:
    height: 200px
  grid:
    show: false
  xaxis:
    axisBorder:
      show: false
    tickPlacement: "on"
header:
  show: true
  title: Statistics
  show_states: true
  colorize_states: true
series:
  - entity: sensor.carport_charging_outlet_energy_meter
    yaxis_id: energy
    name: Used energy
    color: magenta
    type: column
    fill_raw: last
    group_by:
      func: diff
      duration: 1month
      fill: last
      start_with_last: true
    show:
      datalabels: true
  - entity: input_number.smart_odometer
    yaxis_id: km
    name: km driven
    color: cyan
    type: column
    fill_raw: last
    group_by:
      func: diff
      duration: 1month
      fill: last
      start_with_last: true
    show:
      datalabels: true
yaxis:
  - id: energy
    min: 0
    show: false
  - id: km
    min: 0
    show: false
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/74286562-4f55-4742-9828-0fd8790ab54d)

![Image](https://github.com/user-attachments/assets/6a52d4ed-aba2-4bb4-bdd0-c890e547458f)

**Expected behavior**
Same behavior as in previous months. Using diff to get the energy used and distance travelled for each month and display it on the chart

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 139.0.1
 - Bug also there with mobile client. Not an issue of the browser really

**Additional context**
