### ISSUE TITLE
Page with graph jumps around on update in Firefox

### ISSUE THREAD

**Issue by diminDDL** [RomRider/apexcharts-card#928]
**Checklist**
- [x] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
Whenever the graph updates the page with said graph jumps to a different location. Only happens in Firefox

**Version of the card**
Version:
v2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
experimental:
  disable_config_validation: true
grid_options:
  columns: full
graph_span: 24h
stacked: false
update_interval: 15s
all_series_config:
  stroke_width: 1
  unit: W
  curve: stepline
  opacity: 1
  group_by:
    func: avg
    duration: 30s
    fill: last
  type: area
  invert: true
  fill_raw: zero
  extend_to: now
  show:
    legend_value: false
color_list:
  - "#ffe100"
  - "#3b4eff"
  - "#00bd06"
  - "#ff6f00"
apex_config:
  xaxis:
    tooltip:
      enabled: false
  tooltip:
    shared: true
    x:
      format: HH:mm - HH:mm
      show: true
  chart:
    height: 275%
span:
  start: day
header:
  show: true
  title: Споживання Сьогодні
series:
  - entity: sensor.pv_input_power
    name: Панелі
    type: line
    invert: false
    fill_raw: "null"
    group_by:
      func: raw
  - entity: sensor.wifi_smart_meter_phase_a_power
    name: Мережа
    type: line
    invert: false
    fill_raw: "null"
    transform: return x * 1000;
    group_by:
      func: raw
  - entity: sensor.battery_discharging_power
    name: Батарея
    type: line
    invert: false
    fill_raw: "null"
    group_by:
      func: raw
  - entity: sensor.ac_output_active_power
    name: Дім
    type: line
    invert: false
    fill_raw: "null"
    group_by:
      func: raw
yaxis:
  - id: first
    decimals: 0
    show: true
    apex_config:
      forceNiceScale: true
      title:
        text: W
```

**Screenshots**
Video showing the issue:
https://youtu.be/6BdYw0KHkDU

**Expected behavior**
It should simply update the graph without moving the scroll position.

**Desktop:**
 - Browser: Firefox
 - Version: 140.0
