### ISSUE TITLE
Group_by delta not performing as expected for rain sensor

### ISSUE THREAD

**Issue by wormiedk** [RomRider/apexcharts-card#94]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I have a rain sensor that reports the total amount of rain in mm accumulated. I would have expected that the delta function would report meaning full values, however the values are not consistent with the values reported by utility meter and have zero values in periods where the total changes. I think it might have something to do with the sensor reporting values quite infrequently and only when the value changes. I attempted to get a csv file from the chart but it seems the timescale is broken in the csv 

**Version of the card**
Version: 1.7.0

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:apexcharts-card'
header:
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.regn_mgd
    name: delta 15min
    group_by:
      func: delta
      duration: 15min
  - entity: sensor.regn_mgd
    name: delta 2h
    group_by:
      func: delta
      duration: 2h      
```

**Screenshots**
Same data with delta 15min and 2h
![image](https://user-images.githubusercontent.com/4417857/108194488-fe06a680-7116-11eb-9a9d-e62266591245.png)

Raw data:
![image](https://user-images.githubusercontent.com/4417857/108194662-2db5ae80-7117-11eb-9714-9c662d8f3168.png)

**Expected behavior**
Data whenever the graph changes

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 85.0.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
I don't think this can be considered a bug.
`group_by` generates buckets of `duration` of data based on the history. If there is not entry in the history for a specific bucket (because there is no state change within the time frame of the bucket) then the bucket receives the last known state only (by default). Which means `delta` can't work because there is only 1 value in the bucket.

Irregular timeseries is always inconsistent as we can't generate any data which does not exist.

**Comment by wormiedk** [comment]
I think there is something strange going on. My utility sensor which is based on the same sensor gives this plot
![image](https://user-images.githubusercontent.com/4417857/108201918-b127cd80-7120-11eb-8b87-63e92011dfd4.png)
It is defined as an hourly utility sensor:
```yaml
utility_meter:
  regn_time:
    source: sensor.regn_mgd
    cycle: hourly
```

The equivelent apexcharts-card results in this plot:
![image](https://user-images.githubusercontent.com/4417857/108202304-314e3300-7121-11eb-9b74-f7ab92a9998f.png)
```yaml
type: 'custom:apexcharts-card'
header:
  show: true
  show_states: true
  colorize_states: true
series:
  - entity: sensor.regn_mgd
    type: column
    group_by:
      func: diff
      duration: 1h
```

**Comment by RomRider** [comment]
You should read my comment again, the result is what is expected based on how a timeseries work. Also `utility_meter` resets the data at the beginning of the hour and if there is any state change during the hour, it records the delta.

You have to think about your history in terms of points of data and not a line.
Eg:
* at 3.30pm: state change to `2`
* no state change until...
* at 5.30pm: state change to `5`
* at 5.45pm: state change to `6`

Creating buckets of 1h will generate this (if your graph is aligned with the end of the hour `end: hour` in `span`) :
* bucket 3pm -> 4pm: `2` (delta = 0, diff = 0)
* bucket 4pm -> 5pm: `2` (because there is no value in the bucket, it uses the last known value by default. delta = 0, diff = 0)
* bucket 5pm -> 6pm: `[ 5, 6 ]` (delta = 1, diff = 1)

That's it, you can't calculate a delta or a diff within each bucket because there is only one value. In your case that what is happening.

**Comment by wormiedk** [comment]
I get your comment regarding bins, but as you can see in my bottom picture, showing the raw data, there are changes in the state before 20.30 when the graph generated by the apex card begins. It would be strange if none of these changes fall within a bucket. Could it be a rounding error?

**Comment by RomRider** [comment]
Add:
```
span:
  end: hour
```
This will align all the buckets to the exact hour. It might solve your problem. group_by's buckets are constructed from the end of the chart by default, not aligned to the hour.

**Comment by wormiedk** [comment]
I know i know. Please indulge me
![image](https://user-images.githubusercontent.com/4417857/108257214-c4f22480-715e-11eb-935b-7a17c787a463.png)
These two graphs use almost the same yaml where one shows raw and another shows delta. I also tried diff

TOP
```yaml
type: 'custom:apexcharts-card'
graph_span: 36h
header:
  show: true
  show_states: true
  colorize_states: true
span:
  end: hour
series:
  - entity: sensor.regn_mgd
    type: column
    group_by:
      func: delta
      duration: 1h
```

BOTTOM
```yaml
type: 'custom:apexcharts-card'
graph_span: 36h
header:
  show: true
  show_states: true
  colorize_states: true
span:
  end: hour
series:
  - entity: sensor.regn_mgd
    curve: stepline
    group_by:
      duration: 1h
```
I understand why there is no rain after 17.00 but why no rain before 21? I guess the state changes just happen in an unfortunate way. If I change to 2h I do get some peaks before 21.00... Oh well I will stick to the utility meter :)
